### ISSUE TITLE
 CreateProcessW("cat" error on windows

### ISSUE THREAD

**Issue by baio** [bazelbuild/rules_docker#1016]
Hi I have the issue with docker rules on windows when building container

Repo to reproduce here `https://github.com/scalio/bazel-dotnetcore-starter`

`bazel build //App:docker`

```
C:\dev\scalio\bazel\bazel-dotnetcore-starter>bazel build //App:docker
INFO: Call stack for the definition of repository 'dotnet' which is a container_pull (rule definition at C:/users/maxpu/_bazel_maxpu/x72jrr46/external/io_bazel_rules_docker/container/pull.bzl:219:18):                                                                                                                                                   - C:/dev/scalio/bazel/bazel-dotnetcore-starter/WORKSPACE:122:1                                                                                                              ERROR: An error occurred during the fetch of repository 'dotnet':                                                                                                               Failed to read digest: java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("cat" C:/users/maxpu/_bazel_maxpu/x72jrr46/external/dotnet/image/digest): The system cannot find the file specified.                                                                                                                        ERROR: C:/dev/scalio/bazel/bazel-dotnetcore-starter/app/BUILD.bazel:51:1: //app:docker depends on @dotnet//image:image in repository @dotnet which failed to fetch. no such package '@dotnet//image': Failed to read digest: java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("cat" C:/users/maxpu/_bazel_maxpu/x72jrr46/external/dotnet/image/digest): The system cannot find the file specified.
ERROR: Analysis of target '//app:docker' failed; build aborted: no such package '@dotnet//image': Failed to read digest: java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("cat" C:/users/maxpu/_bazel_maxpu/x72jrr46/external/dotnet/image/digest): The system cannot find the file specified.                         INFO: Elapsed time: 31.964s                                                                                                                                                  INFO: 0 processes.                                                                                                                                                           FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured) 
```
Verified path `C:/users/maxpu/_bazel_maxpu/x72jrr46/external/dotnet/image/digest` is perfectly exists, the only ddifference which I could spot `users` folder is `Users`

Trying to google similar issue find only this https://github.com/bazelbuild/rules_jvm_external/pull/37

Rules such as `docker build //App:bin` works perfectly fine.
Also the same  `bazel build //App:docker` command run successfully under wsl.

```
bazel version
Build label: 0.28.1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 19 15:20:45 2019 (1563549645)
Build timestamp: 1563549645
Build timestamp as int: 1563549645
```
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.18362 Build 18362
```

**Comment by smukherj1** [comment]
Hi @baio,

Thanks for opening this issue. I believe the problem is [here](https://github.com/bazelbuild/rules_docker/blob/c2f7f8165d56f3067dfc0b5a7525b9393fe562e5/container/pull.bzl#L189). It's calling `cat` which doesn't exist in your shell. Now I understand `cat` is standard in Unix distributions and doesn't usually exist on Windows. Basically, our Windows support is untested and it's possible more such issues exist. Is using a linux environment a possibility for you?

Otherwise, can you try running this in a shell that has common Unix utilities available? Cygwin is a possibility. Another option is to just write a `cat.bat` file and put in your system path which simply runs the `type` command on the given argument. See [here](https://superuser.com/questions/434870/what-is-the-windows-equivalent-of-the-unix-command-cat).

**Comment by baio** [comment]
Hi @smukherj1  the way I resolve this issue is to install additional unix tool when installing git, though it could be reflected in documentation
