### ISSUE TITLE
docker/util: container_run_and_commit doesn't support docker_run_flags

### ISSUE THREAD

**Issue by xinau** [bazelbuild/rules_docker#1026]
The _container_run_and_commit_ rule doesn't provide an option for specifying custom docker run flags, while the _container_run_and_extract_ rule does. These flags are needed e.g. setting host specific networks or dns servers.

**Comment by alex1545** [comment]
Hi @xinau,
Thank you for opening this issue and taking the time to send a PR.
We've just recently added the option to specify additional docker run flags to `container_run_and_extract` as we discovered a need for it.
