### ISSUE TITLE
Include option to use a base image that includes delve in dbg compilation mode for go_image

### ISSUE THREAD

**Issue by strican** [bazelbuild/rules_docker#1038]
Now, in order to debug a go application built with `go_image`, you have to roll your own base image that includes Delve. Most likely the best way to do that is to wrap around go_image and toggle what is included based on the compilation mode. Users doing this also need to pre-compile Delve as release configuration and therefore it would need to be a two-step build process.

Instead of every implementer needing to do this, we should include an option for the base image to include delve and set it as the entrypoint running the `binary` specified in `go_image` automatically. This would allow integration into IDEs using standard tooling, too.

**Comment by strican** [comment]
Threads with context:

- https://bazelbuild.slack.com/archives/CHSV3RSR0/p1564502332007400?thread_ts=1560455705.005000&cid=CHSV3RSR0
- https://bazelbuild.slack.com/archives/CA3NW13MH/p1562775807038000

**Comment by strican** [comment]
As a solution, it seems like the simplest would be to add a https://console.cloud.google.com/gcr/images/distroless/GLOBAL/go:debug image that we can optionally use if some parameter is set (as is done with the [static images](https://github.com/bazelbuild/rules_docker/blob/31c38b0f506d8aff07487c274ed045c0017f689f/go/image.bzl#L113)).

I'd take a stab at this but I have no idea how we go about adding another image there. It doesn't seem like they're in [GoogleCloudPlatform/container-definitions](https://github.com/GoogleCloudPlatform/container-definitions), which is the only place I'd know to look.

**Comment by strican** [comment]
We'd still need to do some work to hook up the entrypoint appropriately, but that seems possible.

**Comment by strican** [comment]
For more information on why I want this, I'm basing off of [these instructions](https://blog.jetbrains.com/go/2018/04/30/debugging-containerized-go-applications/) from JetBrains.

**Comment by alex1545** [comment]
Hi @strican and thank you for opening this issue.
Unfortunately, the issue with your suggestion is that adding and maintaining a new image that includes delve wouldn't be a simple task. We, the owners of [GoogleCloudPlatform/container-definitions](https://github.com/GoogleCloudPlatform/container-definitions) currently have no plans adding and maintaining new additional images. I also suspect that the owners of [GoogleContainerTools/distroless](https://github.com/GoogleContainerTools/distroless) are also very unlikely to maintain this new type of image. That being said, it may make sense for you to maintain your own base image that has delve installed and evaluate the additional effort it will take to make the current macro work with your base image.

**Comment by strican** [comment]
> adding and maintaining a new image that includes delve wouldn't be a simple task

I'm aware of that, but right now the choice of either doing this non-simple task or not getting functionality that is available more easily without Bazel is the current choice of consumers. In my mind, if Bazel is going to be an adequate replacement for out of the box technologies, it needs to at least have parity.

**Comment by nlopezgi** [comment]
hi @strican ,
thanks again for opening this issue. Unfortunately we, as maintainers of the rules_docker repo, are not in a position to create or maintain this image. We are concerned with providing parity but cannot take on adding this feature as the toil of maintaining these containers is too high for our team and we do not have the right expertise for it. I do recommend you open up an issue in the distroless repo, as they are more likely to be able to take on such a request. Once an image is made public, we will gladly support it in these rules.

**Comment by strican** [comment]
Thanks. I've opened up the issue there.

**Comment by nlopezgi** [comment]
kk, closing the issue here for now. Please reopen if there is any updates or let me know if you want to keep open for any other reason.
