### ISSUE TITLE
Pushing to private registry throws an exception

### ISSUE THREAD

**Issue by tarekbecker** [bazelbuild/rules_docker#104]
Hey,

First of all thanks for working on bazel and docker support. I'm new to bazel. I try to figure out whether it makes sense for me to use bazel. At the moment I try building docker images and pushing them to my registry.

I have my own docker registry running, but if I try to push using `docker_push` an error is thrown:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "../pusher/file/pusher.par/__main__.py", line 129, in <module>
  File "../pusher/file/pusher.par/__main__.py", line 121, in main
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_session_.py", line 71, in __init__
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_http_.py", line 177, in __init__
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_http_.py", line 215, in _Ping
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_http_.py", line 128, in _CheckState
containerregistry.client.v2_2.docker_http_.BadStateException: Unexpected "www-authenticate" header: Basic realm="Registry Realm"
```

My docker command for running the registry is basically:
```bash
docker run -d \
  -p 5000:5000 \
  --restart=always \
  --name registry \
  -v `pwd`/auth:/auth \
  -e "REGISTRY_AUTH=htpasswd" \
  -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
  -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
  -v `pwd`/certs:/certs \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  registry:2
```

My `BUILD` file looks like this:

```python
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_build", "docker_push")

docker_build(
    name="db1",
    files=["file.txt", "//project/setup:setup"],
    base="@nginx-alpine//image",
)

docker_push(
    name="push-db1",
    image=":db1",
    registry="registry.example.com",
    repository="project/db1",
    tag="latest",
)
```

My `~/.docker/config.json`file:

```json
cat ~/.docker/config.json
{
	"auths": {
		"https://registry.gitlab.com": {},
		"registry.example.com": {},
		"registry.gitlab.com": {}
	},
	"credsStore": "osxkeychain"
}
```

Running `bazel build` works fine, but I don't know how to provide the credentials.

Can someone guide me how to provide the credentials?

Thanks!
Tarek

**Comment by mattmoor** [comment]
@tarekbecker Can you share the version of `rules_docker` you are using from `WORKSPACE`, so I can pin down the version of the library that pairs with that callstack a bit better?

[This](https://github.com/google/containerregistry/blob/master/client/v2_2/docker_http_.py#L212-L217) path was added for a registry without authentication (e.g. `registry:2`).

I'll dig through some older versions of the library to see if I can make sense of why that error is being thrown.

**Comment by mattmoor** [comment]
Ok, I know what's going on.  This is my bad.

We added support for `Basic` auth challenges to the library, but it looks like this never made it into a release that got pulled into `rules_docker`.  I'll cut a release of the `google/containerregistry` library and open a PR that should address this.

**Comment by mattmoor** [comment]
@tarekbecker You should be able to verify my fix by replacing the current entry in your `WORKSPACE` with the version in my PR.

In the `git_repository` rule, replace `bazelbuild` with `mattmoor` and the version (`tag` or `commit`) with `commit="0150d0ba5149e075a8b7b22e76885ba753678d65"`.

Sorry for the trouble, I totally thought this had been done already.

**Comment by tarekbecker** [comment]
@mattmoor Thanks for your help! It is working fine. 

I don't want to hijack this issue but I have a short question and I don't want to open another issue for that. If I use `docker_build` can I specify that a file is added to another location within the docker image than root?
