### ISSUE TITLE
Defining a jvm_flag (e.g. -javaagent) at runtime

### ISSUE THREAD

**Issue by demichej** [bazelbuild/rules_docker#1059]
I took at look at this other issue: https://github.com/bazelbuild/rules_docker/issues/548

But I am not sure that it solves this case, but maybe I'm missing it and someone can point me to how to do this.

Basically, we would like to be able to have something like `JAVA_OPTS` be used when that  entrypoint runs. In our case, we want to use a `-javaagent`, but parameters of this javaagent can change depending on certain variables (e.g. maybe a config file is different).

Did the above issue fix this? If so, could you call it out more clearly for me since I was not able to see how it fixes this. 

Thanks.

**Comment by nlopezgi** [comment]
Hi @demichej,
Could you explain in more detail how you would achieve this with a `java_binary` target and then we can see from there how difficult it would be to get to the same functionality with `java_image`?
It might be the case that what you want is not currently supported. The main source of parity issues we have between `java_binary` and `java_image` is explained in more detail [here](https://github.com/bazelbuild/rules_docker/pull/563#issuecomment-434043074). It's possible that https://github.com/bazelbuild/rules_docker/issues/548 can help for your issue, but its also possible that, if what you need depends on the script which `java_binary` generates, which, includes a way to resolve the `jvm_flags`, it will not be trivial at all to get it to work with `java_image`.

**Comment by nlopezgi** [comment]
Closing for now. Please let me know if this issue needs to be reopenend
