### ISSUE TITLE
files added from repository rule have impossible paths

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_docker#106]
If I add the following to `docker/testdata/BUILD`:
```python
docker_build(
    name = "data_path_image_external",
    files = ["@com_google_guava_guava//jar"],
    mode = "0644",
    data_path = "/",
)
```

It produces an image with:
```shell
$ tar tvf ../../bazel-bin/docker/testdata/data_path_image_external-layer.tar
drwxr-xr-x 0/0               0 1970-01-01 00:00 ./
tar: Removing leading `./..' from member names
drwxr-xr-x 0/0               0 1970-01-01 00:00 ./../
tar: Removing leading `./../' from member names
drwxr-xr-x 0/0               0 1970-01-01 00:00 ./../com_google_guava_guava/
drwxr-xr-x 0/0               0 1970-01-01 00:00 ./../com_google_guava_guava/jar/
-rw-r--r-- 0/0         2256213 1970-01-01 00:00 ./../com_google_guava_guava/jar/guava-18.0.jar
```

**Comment by mattmoor** [comment]
[Related](https://groups.google.com/forum/#!topic/bazel-discuss/1lX3aiTZX3Y)

**Comment by ulfjack** [comment]
The title is a bit confusing. What's impossible about them?

**Comment by mattmoor** [comment]
@ulfjack In the tarballs we build for Docker images, the expansion is implicitly done at `/`, so there is no `..`

**Comment by mering** [comment]
There is still a `magic_path` in https://github.com/bazelbuild/rules_docker/blob/8e70c6bcb584a15a8fd061ea489b933c0ff344ca/container/layer.bzl#L49-L68

This should probably be replaced with something like https://github.com/bazelbuild/rules_docker/blob/8e70c6bcb584a15a8fd061ea489b933c0ff344ca/lang/image.bzl#L108-L109 as done for the language images.
