### ISSUE TITLE
[Extensibility Issue] Rulesets Rely on Consumer Naming Conventions

### ISSUE THREAD

**Issue by naturalwarren** [bazelbuild/rules_docker#1064]
I'm having trouble extending the base set of rules. This simple workspace fails when the name of the `http_archive` is anything but `io_bazel_docker_rules`:

```.bzl
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_docker", # Change name to `foo`
    sha256 = "87fc6a2b128147a0a3039a2fd0b53cc1f2ed5adb8716f50756544a572999ae9a",
    strip_prefix = "rules_docker-0.8.1",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.8.1.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl", # Change name to `@foo//...`
    container_repositories = "repositories",
)

container_repositories()
```

This seems to occur since `repositories.bzl` relies on loading a label:

```.bzl
load(
    "@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
    _docker_toolchain_configure = "toolchain_configure",
)
```

Within this project could loading be performed with relative paths instead of labels? This would alleviate consumers from having to name their http_archive `io_bazel_rules_docker`. Alternatively are there known workarounds or recommended patterns for extension?

**Comment by nlopezgi** [comment]
you must use `io_bazel_docker_rules` as name for the http_archive for these rules as we need to use absolute paths to these labels, otherwise use of these rules as external repos would not know how to find the paths.
What is it exactly that you want to do when you say "extend" these rules? You should just be able to import them and always reference targets as `@io_bazel_docker_rules//...`

**Comment by naturalwarren** [comment]
I wanted to wrap a series of rules (`docker_push`, `docker_pull`, etc.) for use in a mono repo. Consumers would load my macro and use my rules which would delegate down to the rules found in this library.

I was trying to achieve two things:

1. All consumers are using the same version of `io_bazel_rules_docker`
2. All consumers have `docker_push` and `docker_pull ` pre-configured to point at our internal Artifactory instance

Since consumers have to load `io_bazel_rules_docker` symbols to use my wrapped rules this makes for a very unintuitive API.

For posterity here's my macro:

```.bzl
""" A workspace macro for loading Bazel Docker build rules. """

# Google's replacement for deprecated the now deprecated `native.http_archive`.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def warren_docker_rules():
    """ Downloads official Bazel Docker rules. """
    http_archive(
        name = "io_bazel_rules_docker",
        sha256 = "87fc6a2b128147a0a3039a2fd0b53cc1f2ed5adb8716f50756544a572999ae9a",
        strip_prefix = "rules_docker-0.8.1",
        urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.8.1.tar.gz"],
    )
```

And here's how consumers have to load it:

```.bzl
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_push")

# Would like this to be:
# load("@warren_rules_docker//docker:docker.bzl", "docker_push")

docker_push(
    name = "docker_push",
    ...
)
```

**Comment by nlopezgi** [comment]
unfortunately what you are trying to do (wrap a series of rules (`docker_push`, `docker_pull`, etc.) for use in a mono repo. ) is, afaik, not trivial to set up and definitely not a common use case. If what you want to do is provide an easy way for your users to import all dependencies that are needed for e.g., some rules that you wrote, which happen to depend or be heavily related to rules_docker, I recommend you try the `repository.bzl` pattern (Examples of repository.bzl pattern:
rules_docker: https://github.com/bazelbuild/rules_docker/blob/master/repositories/repositories.bzl
rules_go: https://github.com/bazelbuild/rules_go/blob/master/go/deps.bzl)
and perhaps even create some of your own declaration of aliases for `rules_docker` rules that redirect to the ones in this repo. Example wrapper rules that point to impl in this repo: https://github.com/GoogleContainerTools/base-images-docker/blob/master/package_managers/download_pkgs.bzl
However, there is no way you can avoid having to need users import (directly or via repositories.bzl) this repo with the name `io_bazel_rules_docker`

**Comment by naturalwarren** [comment]
Thanks @nlopezgi. Closing this issue out since there isn't any further actions we can take at this time.

Appreciate you 🙌
