### ISSUE TITLE
nodejs_image uses heavily outdated base image

### ISSUE THREAD

**Issue by siberex** [bazelbuild/rules_docker#1068]
[nodejs_image](https://github.com/bazelbuild/rules_docker#nodejs_image) uses outdated base:
> We are currently utilizing the gcr.io/google-appengine/debian9 image as our base.

We have tried recently released [vulnerability scanner for GKE](https://cloud.google.com/blog/products/identity-security/web-application-vulnerability-scans-for-gke-and-compute-engine-are-generally-available) and all of images created with nodejs_image are marked as bad apples:

<img width="1183" alt="Screenshot 2019-08-09 01 03 10" src="https://user-images.githubusercontent.com/977336/62723390-2ce08e80-ba43-11e9-9ae1-b6d8b6003f5d.png">

Does not look very good for production.

I hope it could be easily addressed by switching to another base.

**Comment by nlopezgi** [comment]
Just updated all the base images. Can you try again after PR is in and let me know if you still see the vulnerabilities?
Thanks for creating this issue!

**Comment by nlopezgi** [comment]
PR is in. Please let me know to reopen if you still see any issues.

**Comment by siberex** [comment]
@nlopezgi I have tried latest commit:
```
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "1680198f8589ebac6a5056354dbacef3a1f0b26b",
)
```

Slightly better, but still bunch of issues:

<img width="1183" alt="Screenshot 2019-08-09 03 00 31" src="https://user-images.githubusercontent.com/977336/62730348-5a810400-ba52-11e9-8d3f-28f62aa127ed.png">

**Comment by nlopezgi** [comment]
iiuc, those are the vulnerabilities that are present in the base image we are currently using for nodejs (debian9): https://pantheon.corp.google.com/gcr/images/google-appengine/GLOBAL/debian9@sha256:84bf592c8a1626f089d5540affef7d0764428303b5f2103b1b12947ac17ba2e6/details?tab=vulnz&gcrVulnzListsize=30
And the gcr page (gcr.io/google-appengine/debian9) states that there are 55 vulnerabilities and 0 fixes available (so, iiuc, there are no updates available that can fix those vulnerabilities).
You can open up an issue in https://github.com/GoogleContainerTools/base-images-docker if you want to ask them a bit more about their release process. And please do let me know if the pin in rules_docker to these images looks to old. I forget to run that update script every once in a while.
