### ISSUE TITLE
docker_push should print out what it pushes somewhere

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_docker#107]
In https://github.com/kubernetes/test-infra/pull/3962/files I am updating our `//experiment/commenter:push` rule to use `stamp = True` as well as `--workspace_status_command` to create a dynamic tag name.

However the resulting output never tells me the tag it actually pushed:
```
$ bazel run //experiment/commenter:push
INFO: Analysed target //experiment/commenter:push (1 packages loaded).
INFO: Found 1 target...
Target //experiment/commenter:push up-to-date:
  bazel-bin/experiment/commenter/push
INFO: Elapsed time: 2.796s, Critical Path: 0.07s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/experiment/commenter/push
+ ../pusher/file/pusher.par '--name={STABLE_REGISTRY}/{STABLE_REPO}/commenter:{DOCKER_TAG}' --stamp-info-file=stable-status.txt --stamp-info-file=volatile-status.txt --config=experiment/commenter/image.config --digest=../distroless-base/image/000.tar.gz.sha256 --digest=../distroless-base/image/001.tar.gz.sha256 --digest=experiment/commenter/image-layer.tar.gz.sha256 --layer=../distroless-base/image/000.tar.gz --layer=../distroless-base/image/001.tar.gz --layer=experiment/commenter/image-layer.tar.gz
```

It would be nice if something somewhere printed out that `--name={STABLE_REGISTRY}/{STABLE_REPO}/commenter:{DOCKER_TAG}` was converted into `gcr.io/k8s-testimages/commenter:v20170807-cbcd2e51`

Any chance we can do this?

**Comment by mattmoor** [comment]
Yeah, we'd add that kind of logging [here](https://github.com/google/containerregistry/blob/master/tools/fast_pusher_.py#L119), it should be pretty easy to add.

**Comment by mattmoor** [comment]
This should be fixed in the latest update to the `google/containerregistry` library.
