### ISSUE TITLE
client_config only works for full paths

### ISSUE THREAD

**Issue by raulAtNines** [bazelbuild/rules_docker#1072]
Hi,

I would like to use gcloud docker credential helper to access a private repo, and we have two use cases:
* build locally (osx or linux)
* build from docker container (linux)

Our config.json should be very simple, and would work for both cases as long as you mount `$HOME/.config`
```
	"credHelpers": { "gcr.io": "gcloud" } ...
```

I have managed to get it working with full paths for the toolchain configuration. However, I can't get `client_config` to work with a relative path that would work.

```
load("@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
    docker_toolchain_configure="toolchain_configure"
)
docker_toolchain_configure(
  name = "docker_config",
  client_config="/Users/raul/.docker", # this works for local
  #client_config="/root/.docker", # anything works for docker since it can be mounted
)
```

According to https://github.com/bazelbuild/rules_docker/pull/594
```
             doc = """"A custom directory for the docker client config.json. If left unspecified, the value of the DOCKER_CONFIG environment variable will be used. DOCKER_CONFIG is not defined, the home directory will be used.""",
```

However when empty or unspecified, I get:
```
ERROR: error loading package '': Unable to load file '@docker_config//:pull.bzl': file doesn't exist
ERROR: error loading package '': Unable to load file '@docker_config//:pull.bzl': file doesn't exist
```

**Question 1**: Don't we need to create a variant here that sets the path to the home directory?
https://github.com/bazelbuild/rules_docker/blob/master/toolchains/docker/toolchain.bzl#L97

- - -

When using a relative path, ~it seems to use it from the location of the `puller`, rather than from the workspace top.~, as pointed by a coworker, the file may not have been brought to the sandbox since it's not a dependency?

**Question 2** What's the proper way to use client_config? Are we expected to have a common place from /? Eg: `/.bazel_docker_config` that anyone building needs to have?

Thanks!

**Comment by raulAtNines** [comment]
Btw, trying now with env variable, which may be the best workaround DOCKER_CONFIG.

**Comment by nlopezgi** [comment]
Hi @raulAtNines ,
Thanks for creating this issue.
Responses inline

> 
> However when empty or unspecified, I get:
> 
> ```
> ERROR: error loading package '': Unable to load file '@docker_config//:pull.bzl': file doesn't exist
> ERROR: error loading package '': Unable to load file '@docker_config//:pull.bzl': file doesn't exist
> ```

This is actually the expected behavior:
from [here](https://github.com/bazelbuild/rules_docker#container_pull-custom-client-configuration):
If you specified a docker client directory using the "client_config" attribute to the docker toolchain configuration described here, you can use a container_pull that uses the authentication credentials.
If you dont specify a client_config you should use pull w/o auth

> 
> **Question 1**: Don't we need to create a variant here that sets the path to the home directory?
> https://github.com/bazelbuild/rules_docker/blob/master/toolchains/docker/toolchain.bzl#L97
> 

using the home directory as the location for the client_config is just the default for the docker tool. We could be clearer about that in the docs. 

> When using a relative path, it seems to use it from the location of the `puller`, rather than from the workspace top.

We don't support using client_config with a relative path, and I'm not sure its something we would want to support given these type of files probably should not be made part of a source tree. I will update docs to make this explicit.

> 
> **Question 2** What's the proper way to use client_config? Are we expected to have a common place from /? Eg: `/.bazel_docker_config` that anyone building needs to have?
> 

Yes, I do think that is the current way we expect this to be used. If you have suggestions as to how to improve it let me know. As you mention using the DOCKER_CONFIG env variable is also a good option.

> Thanks!

I'll send a doc PR to make the clarifications outlined above.

**Comment by raulAtNines** [comment]
Thanks for the quick reply, @nlopezgi!

> using the home directory as the location for the client_config is just the default for the docker tool. We could be clearer about that in the docs.

Ah! I get it now: this is only required for a custom config different than that of your local docker, but if your local docker is already authenticated with the private repo, you don't need to customize auth. 

I'm now trying to get gcloud working inside the builder container. Building work locally (outside container) without the custom auth, but can't get the builder container to work without the custom config. It keeps failing to access the private repo (custom config does work).

> We don't support using client_config with a relative path, and I'm not sure its something we would want to support given these type of files probably should not be made part of a source tree. I will update docs to make this explicit.

Originally I wanted a per-user folder, but instead of using tokens (which are encoded in config.json), I switched to gcloud, and the config.json is the same for everyone (just with the credHelpers entry). Given that it was the same for everyone, I thought adding it to the repo was not a bad idea. But now that I understand how this can work

> Yes, I do think that is the current way we expect this to be used. If you have suggestions as to how to improve it let me know. As you mention using the DOCKER_CONFIG env variable is also a good option.

I am trying `bazel build --action_env DOCKER_CONFIG=/Users/raul/.docker target`, and it doesn't seem to work. Is that not the right way to pass the env variable?

Thanks for the information!

**Comment by raulAtNines** [comment]
In fact, yeah, sharing config inside a docker container and outside may not be desired:

```
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.09.2 (darwin)"
	},
```

Our builder container is linux, but would use the underlying osx config with the non-custom auth approach.

**Comment by raulAtNines** [comment]
Ok, sharing the config I was able to get it to work finally. No need for the custom auth if your local docker is authorized already.

Outstanding question is: how can you specify DOCKER_CONFIG env?

Updating the doc to clarify that with an empty client_config the custom/authorized versions do not work, and that you are expected to use the regular ones would be nice. Thanks for that 👍

**Comment by nlopezgi** [comment]
> 
> I am trying `bazel build --action_env DOCKER_CONFIG=/Users/raul/.docker target`, and it doesn't seem to work. Is that not the right way to pass the env variable?

That should be the right way to do it. Can you run the command with `-s` or `--subcommands` (or `-v` `--verbose` if the specific action is failing) and check the action was executed with the right value for the env variable?

Use of the DOCKER_CONFIG env variable should be performed by the docker tool directly as specified in their docs (https://docs.docker.com/engine/reference/commandline/cli/)

Let me know if you have more questions.

**Comment by raulAtNines** [comment]
```
bazel build -s --action_env DOCKER_CONFIG=/Users/raul/.docker target
ERROR: error loading package '': Unable to load file '@docker_config//:pull.bzl': file doesn't exist
ERROR: error loading package '': Unable to load file '@docker_config//:pull.bzl': file doesn't exist
```

It's just not grabbing it.

**Comment by raulAtNines** [comment]
Am I missing a step in `docker_toolchain_configure` to use the env var?

**Comment by raulAtNines** [comment]
Ah, this is also to not use the custom container. I think I misunderstood in the same way I misunderstood it being empty.

**Comment by raulAtNines** [comment]
I understand better how this works, and got my two use cases working by using the local docker configuration. Good to close.
