### ISSUE TITLE
registering py3_images

### ISSUE THREAD

**Issue by cdg720** [bazelbuild/rules_docker#1087]
I just cannot figure out how to register //py3_images/image.bzl:deps. (py_images or py3_images search only shows me the README.md here.) Can someone help me out?

I want to build a docker image using bazel.

I have a very simple BUILD:
```
load("@io_bazel_rules_docker//python3:image.bzl", "py3_image")

py3_image(
    name = "hello_world",
    srcs = ["hello_world.py"],
)
```
And hello_world.py:
```
print("Hello World!")
```

If I run
```
bazel run tutorials:hello_world
```
I get "OSError: [Errno 2] No such file or directory: '/usr/bin/python3'". I can get around this with by providing "--incompatible_use_python_toolchains=false" but I like to register the python tools and not provide the flag.

(I had another image with numpy but the numpy installation was failing and it looked like I needed to control what interpreter I was passing to the py3_image.)

I am using bazel 0.27.

**Comment by smukherj1** [comment]
Hi @cdg720, Does your system have a python3 binary installed at `/usr/bin/python3`? This is what the default python toolchain assumes (see [here](https://github.com/bazelbuild/rules_docker/blob/835d20b7272e214b4449b88b6154cfea3544ec99/toolchains/python/BUILD#L29)). If not, see instructions [here](https://github.com/bazelbuild/rules_python/blob/master/proposals/2019-02-12-design-for-a-python-toolchain.md#example) on how to configure a python binary installed at a location other than what the default toolchain expects.

Note that the bazel invocation will then require the `--platforms` flag as indicated in the instructions above to use the custom toolchain.

**Comment by cdg720** [comment]
Thanks smukherj1.

No I don't have python3 at ```/usr/bin/python3```. I will use the platforms flag.

By the way, do you know what ```//py3_images/image.bzl:deps``` is? The README.md said as if it is something I can register but I couldn't find any mention of it outside the README.md.

**Comment by cdg720** [comment]
Now I am getting 
```
$ bazel run tutorials:hello_world --platforms=//platform_defs:my_platform
no matching toolchains found for types @io_bazel_rules_docker//toolchains/docker:toolchain_type
```  

Another person had a similar problem [here](https://stackoverflow.com/questions/56813476/how-to-register-the-io-bazel-rules-docker-toolchains-dockerdefault-linux-too).

I am building things on an OSX.

**Comment by nlopezgi** [comment]
See resolution to this problem in https://github.com/bazelbuild/rules_docker/issues/1093
