### ISSUE TITLE
no matching toolchains found for @io_bazel_rules_docker//toolchains/docker:toolchain_type

### ISSUE THREAD

**Issue by cdg720** [bazelbuild/rules_docker#1093]
I am trying to build a simple py3_image with bazel and get "no matching toolchains found for @io_bazel_rules_docker//toolchains/docker:toolchain_type". 

I followed the [instruction](https://github.com/bazelbuild/rules_docker/tree/master/toolchains/docker#how-to-use-the-docker-toolchain).

To reproduce you can
```bash
git clone https://github.com/cdg720/bazel_examples.git
cd bazel_examples/py3_image
bazel run -c opt //foo:hello_world --platforms=//platform_defs:my_platform
```

Does anyone know what I am missing?

I am using bazel 0.27 and OSX.

**Comment by nlopezgi** [comment]
Hi @cdg720 ,
Thanks for opening this issue. Is there any particular reason why you are registering a platform (here)[https://github.com/cdg720/bazel_examples/blob/master/py3_image/WORKSPACE#L16]? The instructions you point to indicate you should only have the call to `container_repositories()` in your WORKSPACE.
Setting up toolchains beyond that default use case is not trivial. The error you are getting is due, likely, to having constraints set up improperly, likely because you do not have constraints in your platform that match those in https://github.com/bazelbuild/rules_docker/blob/master/toolchains/docker/BUILD#L39 and or https://github.com/bazelbuild/rules_docker/blob/master/toolchains/docker/BUILD#L57.
I recommend you check out https://docs.bazel.build/versions/master/toolchains.html#debugging-toolchains and try to use --toolchain_resolution_debug to figure out why the platform you are passing (//platform_defs:my_platform) is not working well with the docker_toolchain

**Comment by cdg720** [comment]
That is my WORKSPACE, no?. The directory bazel_examples is not the root. I am writing simple examples without unnecessary stuff in their BUILD and WORKSPACE. In bazel_examples, py_binary and py3_image are completely separate.

I will try the debug flag. Thanks!

**Comment by nlopezgi** [comment]
> That is my WORKSPACE, no?. 

Yes, but I was not sure why you had the register platforms there, which I suspect is the source of the problem, but I've sync'd with @smukherj1 and he pointed me to the other issue (https://www.google.com/url?q=https://github.com/bazelbuild/rules_docker/issues/1087) which he suggested you add the python toolchain / platform.

>The directory bazel_examples is not the root. I am writing simple examples without unnecessary stuff in their BUILD and WORKSPACE. In bazel_examples, py_binary and py3_image are completely separate.

Yes I saw that

> 
> I will try the debug flag. Thanks!

Yes, please do, and try to add the constraints we have in our toolchains (https://github.com/bazelbuild/rules_docker/blob/master/toolchains/docker/BUILD#L60) to your platform, that might just do the trick.

**Comment by smukherj1** [comment]
This is a follow up to #1087. The python toolchains proposal instructions I mentioned [here](https://github.com/bazelbuild/rules_docker/issues/1087#issuecomment-521640780) were used to set this example repo up.

`--toolchain_resolution_debug` is a good flag to use to debug these issues. I think what's happening here is that the docker toolchain isn't compatible with the new platform as @nlopezgi mentioned.

Instead, can you try
`bazel run -c opt //foo:hello_world --extra_toolchains=//platform_defs:my_platform_python_toolchain --toolchain_resolution_debug`

This instructions Bazel to use the custom python toolchain without changing the platform. This way the docker toolchain won't fail to register. If this doesn't work, the toolchain resolution debug messages should provide some guidance.

**Comment by cdg720** [comment]
@nlopezgi I am confused. Are you asking why I am using platforms? I was trying to find why my image was not finding python and tried what @smukherj1 suggested. Do you have another solution to the problem where an image fails to find python?

```
toolchain(
    name = "my_platform_python_toolchain",
    # Since the Python interpreter is invoked at runtime on the target
    # platform, there's no need to specify execution platform constraints here.
    target_compatible_with = [
        # Make sure this toolchain is only selected for a target platform that
        # advertises that it has interpreters available under /usr/weirdpath.
        ":usr_weirdpath_python2",
        ":usr_weirdpath_python3",
        "@bazel_tools//platforms:linux",
        "@bazel_tools//platforms:osx",
    ],
    toolchain = ":my_platform_runtimes",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)
```
still fails with the same output I had. With --toolchain_resolution_debug I get
```
$ bazel run -c opt //foo:hello_world --platforms=//platform_defs:my_platform --toolchain_resolution_debug
Starting local Bazel server and connecting to it...
INFO: ToolchainResolution: Selected execution platform @bazel_tools//platforms:host_platform, 
INFO: ToolchainResolution: Looking for toolchain of type @io_bazel_rules_docker//toolchains/docker:toolchain_type...
INFO: ToolchainResolution:   Considering toolchain @docker_config//:toolchain...
INFO: ToolchainResolution:     Toolchain constraint @platforms//os:os has value @platforms//os:linux, which does not match value <missing> from the target platform //platform_defs:my_platform
INFO: ToolchainResolution:   Rejected toolchain @docker_config//:toolchain, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @docker_config//:toolchain...
INFO: ToolchainResolution:     Toolchain constraint @platforms//os:os has value @platforms//os:windows, which does not match value <missing> from the target platform //platform_defs:my_platform
INFO: ToolchainResolution:   Rejected toolchain @docker_config//:toolchain, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @docker_config//:toolchain...
INFO: ToolchainResolution:     Toolchain constraint @platforms//os:os has value @platforms//os:osx, which does not match value <missing> from the target platform //platform_defs:my_platform
INFO: ToolchainResolution:   Rejected toolchain @docker_config//:toolchain, because of target platform mismatch
INFO: ToolchainResolution:   No toolchains found
ERROR: While resolving toolchains for target //foo:hello_world: no matching toolchains found for types @io_bazel_rules_docker//toolchains/docker:toolchain_type
ERROR: Analysis of target '//foo:hello_world' failed; build aborted: no matching toolchains found for types @io_bazel_rules_docker//toolchains/docker:toolchain_type
```

And if I change platforms with extra_toolchains
```
$ bazel clean --expunge
$ bazel run -c opt //foo:hello_world --extra_toolchains=//platform_defs:my_platform --toolchain_resolution_debug
Starting local Bazel server and connecting to it...
INFO: ToolchainResolution: Selected execution platform @bazel_tools//platforms:host_platform, 
ERROR: While resolving toolchains for target //foo:hello_world: invalid registered toolchain '//platform_defs:my_platform': target does not provide the DeclaredToolchainInfo provider
ERROR: Analysis of target '//foo:hello_world' failed; build aborted: invalid registered toolchain '//platform_defs:my_platform': target does not provide the DeclaredToolchainInfo provider
INFO: Elapsed time: 11.720s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 165 targets configured)
FAILED: Build did NOT complete successfully (17 packages loaded, 165 targets configured)
```

Hmm. Is either error message familiar to you?

**Comment by smukherj1** [comment]
@cdg720 Hi could you please try

`bazel run -c opt //foo:hello_world --extra_toolchains=//platform_defs:my_platform_python_toolchain --toolchain_resolution_debug`?

`--extra_toolchains=//platform_defs:my_platform` is incorrect because `--extra_toolchains` expects a toolchain target, not a platform target.

**Comment by nlopezgi** [comment]
Ok, you're close, but debugging toolchains issue is a pain over chag. So I'll just avoid the back and forth and solve it for you:
https://github.com/cdg720/bazel_examples/pull/1
This worked for me on a linux host, you probably need to change if you're running from a mac host so the @bazel_tools//platforms:linux is @bazel_tools//platforms:osx.
And then run: 
`bazel run -c opt //foo:hello_world --extra_toolchains=//platform_defs:my_platform_python_toolchain --platforms=//platform_defs:my_platform`

These kind of use cases really need for you to become an expert in platforms/toolchains. I recommend you read in detail the platform/toolchains docs I linked to in my first comment above and read in very fine detail the debug info, as it did help in this case for me to fix this issue, but in general I cant really spend the time to debug these issues for customers (and this is not a rules_docker issue you were having, its a toolchain/platform issue)

**Comment by cdg720** [comment]
Thanks all!

**Comment by cdg720** [comment]
I appreciate your help. I ended up running bazel build inside the docker image using Dockerfile.

With the solution I got from @nlopezgi I still get
```
Traceback (most recent call last):
  File "bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256", line 340, in <module>
    Main()
  File "bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256", line 326, in Main
    ret_code = subprocess.call(args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/usr/bin/python3'
```

Here's what I understand:
I don't have ```/usr/bin/python3``` and the platform flag tells bazel to use the user defined python on my mac (in my case ```/usr/local/bin/python3```) to build the image. The base docker image (distroless) comes with its own ```/usr/bin/python3``` which runs the image I have built with the bazel. What I don't understand is why I need to pass extra_toolchain flag to let the image know what its interpreter path is.

No recent macs have ```/usr/bin/python3``` as you cannot create symlinks under ```/usr/bin``` anymore. That means mac users need to go through docs for platform and toolchains to use ```py3_image```. I think it would be nicer if it was just flipping ```py_binary``` to ```py3_image``` (at least for simple examples)  or there was some working example for OSX.

For someone interested in my broken example, see [my repository]( https://github.com/cdg720/bazel_examples/tree/master/py3_image).

**Comment by smukherj1** [comment]
@cdg720 I think this is now a [rules_python](https://github.com/bazelbuild/rules_python) and python toolchain for OSX specific issue. I would suggest trying to create the hello world example you first tried in #1087 but using the [py_binary](https://github.com/bazelbuild/rules_python/blob/master/docs/python.md#py_binary) rule. Note that you must specify the attribute `python_version` as `"PY3"`. I think you'll see the same toolchain related issue on OSX. If that's the case, I would suggest opening an issue in [rules_python](https://github.com/bazelbuild/rules_python) because they'll be in a better position to provide guidance on how to properly configure the python toolchain on OSX.

**Comment by cdg720** [comment]
@smukherj1 In [my repository](https://github.com/cdg720/bazel_examples/blob/master/py3_image/foo/BUILD#L3-L13) I have both py_binary and py3_image examples and py_binary runs fine.

For example,
```
bazel run -c opt //foo:hello_world_py \
  --extra_toolchains=//platform_defs:my_platform_python_toolchain \
  --platforms=//platform_defs:my_platform
```
runs fine whereas

```
bazel run -c opt //foo:hello_world_image \
  --extra_toolchains=//platform_defs:my_platform_python_toolchain \
  --platforms=//platform_defs:my_platform
```
fails.

**Comment by smukherj1** [comment]
At this point I suggest reaching out to [rules_python](https://github.com/bazelbuild/rules_python) for help on how to configure the python toolchain on OSX for python3 for rules that use the python rules.

In general we support and test the linux use case for the core `container_*` rules like `container_pull`, `container_image`, `container_push`, etc, thoroughly and don't have the bandwidth to keep up with changes in how the toolchain configuration works for the `<lang>_image` rules, especially for non Linux platforms like OSX. If you get your python3 use case working, we would welcome a pull request updating our docs on how to use the python rules on OSX.

**Comment by brandjon** [comment]
Resolved in bazelbuild/rules_python#230, turns out you need to pass `--host_platform=...` in addition to `--platforms=...` to ensure the right toolchain gets used for host-configured targets.

**Comment by nlopezgi** [comment]
just to close the loop on this, its likely this error was also in part because of the custom python toolchain we have in rules_docker for py_image and py3_image. Understanding platforms is hard. I think all of these problems should be solved with  bazelbuild/rules_docker#1105, but please let me know if you are still running into issues after that PR is in.

**Comment by abhillman** [comment]
I'm running into issues here with a very basic setup on OS X:

**WORKSPACE**
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

### io_bazel_rules_docker

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "b1e80761a8a8243d03ebca8845e9cc1ba6c82ce7c5179ce2b295cd36f7e394bf",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.25.0/rules_docker-v0.25.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

### Docker images

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "alpine",
    digest = "sha256:1304f174557314a7ed9eddb4eab12fed12cb0cd9809e4c28f29af86979a3c870",
    registry = "hub.docker.com",
    repository = "library/alpine",
)
```

**BUILD**
```
java_binary(
    name = "hello-world",
    srcs = ["src/fun/aryeh/HelloWorld.java"],
    main_class = "fun.aryeh.HelloWorld",
)
```

Just _this_ atm does not compile due to this error:

```
ahillman@MacBook-Air-3 docker-rule-sh % bazel run //:hello-world
ERROR: /Users/ahillman/Development/docker-rule-sh/BUILD:8:12: While resolving toolchains for target //:hello-world: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
ERROR: Analysis of target '//:hello-world' failed; build aborted: 
INFO: Elapsed time: 0.097s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
```

**Comment by abhillman** [comment]
FWIW, this seems to go away with bazel 6 `USE_BAZEL_VERSION=6.0.0-pre.20220922.1 bazel run //:hello-world`
