### ISSUE TITLE
Bump bazel_skylib dependency to 0.9

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/rules_docker#1102]
The version of skylib used by `rules_docker` appears to be 0.8. Blindly using 0.9 causes problems, yet this has fixes in it that would be nice to use with other projects. Could you please update the version used by these rules?

**Comment by nlopezgi** [comment]
Hi @shs96c,
Thanks for creating this issue!
Unfortunately we cant upgrade to skylib 0.9 yet (afaik) see https://github.com/bazelbuild/bazel-skylib/issues/163 for more details. Nevertheless, we would be happy to accept any PRs that fix the issues preventing us from upgrading to 0.9, yet, iiuc again, you'll probably need to send fixes to multiple repos that we depend upon to get us to a point where rules_docker can use 0.9. Keeping this issue open in case community wants to contribute for this, but we wont be investing any effort atm towards making the move to 0.9.

**Comment by shs96c** [comment]
It sounds like a fix may be forthcoming: https://github.com/bazelbuild/bazel-skylib/issues/163#issuecomment-519537245

**Comment by nlopezgi** [comment]
great! As soon as it's ready we can bump here. Please ping me if you're keeping track of that issue whenever it's resolved.
