### ISSUE TITLE
Support label variables in env field

### ISSUE THREAD

**Issue by TannerYoung** [bazelbuild/rules_docker#1116]
It looks like https://github.com/bazelbuild/rules_docker/issues/670 only added support for make variables, and not the functions as outlined at https://docs.bazel.build/versions/master/be/make-variables.html#predefined_label_variables

This makes the documentation a little confusing, as when I attempted to add a $(location ...) expansion to the env field it failed, though I expected it to succeed since it says "The values of this field support make variables" which is ambiguous what precisely that means.

**Comment by smukherj1** [comment]
It looks like support for $(location ...) can be added with [ctx.expand_location](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#expand_location). We are open to accepting a PR implementing this by calling expand_location wherever ctx.expand_make_variables is currently called for the `env` attribute. I'm not seeing functions to expand the other cases listed [here](https://docs.bazel.build/versions/master/be/make-variables.html#predefined_label_variables) so support for those might have to go to the Bazel repo.

**Comment by Ayindemade** [comment]
Hello..please can you teach me how to be an expert on GitHub
