### ISSUE TITLE
UnicodeEncodeError when attempting to pull docker.io/atlassian/pipelines-awscli

### ISSUE THREAD

**Issue by thundergolfer** [bazelbuild/rules_docker#1119]
🐛🐛

### Description

The latest (`0.9.0`) `docker_rules` is unable to pull the [`docker.io/atlassian/pipelines-awscli`](https://hub.docker.com/r/atlassian/pipelines-awscli) image. In some part of the process the © symbol (` u'\xa9'`) is being encountered and it's failing the Bazel target. 

----

**Note:** I can produce this issue within our Bazel+Nix monorepo at work and also here -> https://github.com/thundergolfer/the-one-true-bazel-monorepo/tree/jonathon/rules_docker-bug. Run `bazel run :test`

----

### Setup for reproducibility

**`bazel version`:** `0.24.1` 👴🏼
**`python` version:** `Python 3.7.3 (default, Mar 27 2019, 09:23:15)`
**`rules_docker` version:** `0.9.0` (latest as of issue creation time). Also present on `0.7.0`
**`bazel` flags:** `build --python_path="/usr/local/bin/python3"`

```
rules_docker_version = "0.9.0"
http_archive(
    name = "io_bazel_rules_docker",
    strip_prefix = "rules_docker-{version}".format(version = rules_docker_version),
    url = "https://github.com/bazelbuild/rules_docker/archive/v{version}.tar.gz".format(version = rules_docker_version),
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)
container_pull(
    name = "awscli",
    registry = "docker.io",
    repository = "atlassian/pipelines-awscli",
    tag = "latest",
)
```

### Expected

`container_pull` for the above image will succeed, as other images do.

### Actual

```
ERROR: Analysis of target '//:test' failed; build aborted: no such package '@awscli//image': Pull command failed: Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/private/var/tmp/_bazel_jonathonbelotti/1d31e26348def3cbe892454dd398945f/external/puller/file/downloaded/containerregistry/tools/logging_setup_.py", line 63, in format
    return super(Formatter, self).format(record)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 72178: ordinal not in range(128)
Logged from file __main__.py, line 147
 (/usr/local/bin/python2 /private/var/tmp/_bazel_jonathonbelotti/1d31e26348def3cbe892454dd398945f/external/puller/file/downloaded --directory /private/var/tmp/_bazel_jonathonbelotti/1d31e26348def3cbe892454dd398945f/external/awscli/image --os linux --os-version  --os-features  --architecture amd64 --variant  --features  --name docker.io/atlassian/pipelines-awscli:latest)
INFO: Elapsed time: 5.609s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 97 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 97 targets configured)
```

-----

Perhaps I'm missing something, but it's odd that Python `2.7` is appearing in the trace, as I'm definitely passing `python3` to Bazel.

**Comment by nlopezgi** [comment]
Hi @thundergolfer ,
thanks for opening this issue, I was able to reproduce it. I will look into it and report back findings.

**Comment by nlopezgi** [comment]
I was able to work around the issue by using new_container_pull instead of container_pull. Could you try to see if this works for you?
example:
```
load(
    "@io_bazel_rules_docker//container:new_pull.bzl",
    "new_container_pull",
)
new_container_pull(
    name = "awscli",
    registry = "docker.io",
    repository = "atlassian/pipelines-awscli",
    tag = "latest",
)
```
Its possible there's a bug with py containerregistru, but since we're about to migrate to the new go containerregistry (see #580), if using new_container_pull works for you then we can just mark this as a known issue with py containerregistry.

**Comment by thundergolfer** [comment]
Can confirm that using `new_container_pull` like above with version `0.9.0` works 👌.

Thanks for looking into this. I wish I'd tried `new_container_pull` before just making a basic image myself.

**Comment by nlopezgi** [comment]
Thanks for confirming.
