### ISSUE TITLE
mechanism to replace puller in new_container_pull expects a separate http_file repo

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_docker#1121]
I'm trying to figure out where the bug lies in `new_container_pull` with this mysql image I'm attempting to pull. Along the way, I wanted to replace the puller binary that rules_docker is using.

However, the only way to do that is by defining another repo that's called "go_puller_linux" or "go_puller_darwin" and has a target at `//file:downloaded`. This means I can't be testing a puller that I'm editing locally in the rules_docker repo without going through the work of building it and hosting it over HTTP (even locally) somewhere.

It seems there was an attempt to allow folks to override the puller by passing in a label to `new_container_pull`, but those attributes (`_puller_darwin` and `_puller_linux`) are marked as private.

It would be nice for those attributes to be made public. Or some other mechanism that is easier than creating and then hosting the binary on an HTTP server.

**Comment by nlopezgi** [comment]
Hi @jmhodges ,
The one issue we see with making this attr public is that it would make the API of these tools public, which is not something we are really prepared to maintain. 
We could make these attrs public, but docs should be very clear these values should only be changed for testing purposes. I'd be happy to review a PR to make them public if you want to send.

@smukherj1 fyi

**Comment by jmhodges** [comment]
Cool!

I'm also open to other alternatives if you have one and am willing to send a patch with that preferred change.
