### ISSUE TITLE
httplib.IncompleteRead on docker_push to eu.gcr.io

### ISSUE THREAD

**Issue by ains** [bazelbuild/rules_docker#113]
Trying out a full pull -> build -> pull cycle with rules_docker. Currently failing on the push stage (doesn't seem to be an authentication issue).

```
    docker_push(
       name = "push_thor_production_docker",
       image = ":thor_production_docker",
       registry = "eu.gcr.io",
       repository = "windy-oxide-102215/thor",
       tag = "{BUILD_TAG}",
       stamp = True,
    )
```

When i run 
`bazel run :push_thor_production_docker --workspace_status_command="~/platform-staging/go/build/workspace_status.sh"`

I get the following traceback

```
+ ../pusher/file/pusher.par '--name=eu.gcr.io/windy-oxide-102215/thor:{BUILD_TAG}' --stamp-info-file=stable-status.txt --stamp-info-file=volatile-status.txt --config=go/src/improbable.io/server/thor/thor_production_docker.config --digest=../base_tiny/image/000.tar.gz.sha256 --digest=../base_tiny/image/001.tar.gz.sha256 --digest=../base_tiny/image/002.tar.gz.sha256 --digest=../base_tiny/image/003.tar.gz.sha256 --digest=../base_tiny/image/004.tar.gz.sha256 --digest=go/src/improbable.io/server/thor/thor_production_docker-layer.tar.gz.sha256 --layer=../base_tiny/image/000.tar.gz --layer=../base_tiny/image/001.tar.gz --layer=../base_tiny/image/002.tar.gz --layer=../base_tiny/image/003.tar.gz --layer=../base_tiny/image/004.tar.gz --layer=go/src/improbable.io/server/thor/thor_production_docker-layer.tar.gz
ERROR:root:Error during upload of: eu.gcr.io/windy-oxide-102215/thor:20170810-153516-673-bazel
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "../pusher/file/pusher.par/__main__.py", line 129, in <module>
  File "../pusher/file/pusher.par/__main__.py", line 124, in main
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_session_.py", line 297, in upload
  File "../pusher/file/pusher.par/concurrent/futures/_base.py", line 398, in result
  File "../pusher/file/pusher.par/concurrent/futures/thread.py", line 55, in run
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_session_.py", line 267, in _upload_one
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_session_.py", line 203, in _put_blob
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_session_.py", line 169, in _patch_upload
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_http_.py", line 342, in Request
  File "../pusher/file/pusher.par/containerregistry/transport/transport_pool_.py", line 62, in request
  File "../pusher/file/pusher.par/httplib2/__init__.py", line 1659, in request
  File "../pusher/file/pusher.par/httplib2/__init__.py", line 1399, in _request
  File "../pusher/file/pusher.par/httplib2/__init__.py", line 1382, in _conn_request
  File "/usr/lib/python2.7/httplib.py", line 588, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 642, in _read_chunked
    raise IncompleteRead(''.join(value))
httplib.IncompleteRead: IncompleteRead(73 bytes read)
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by mattmoor** [comment]
Is the issue persistent?  Generally when I've seen this kind of exception in the past it had to do with flaky network.  We can probably make our client transport code a bit more resilient to transient failures, but that only help here if it goes away.

**Comment by ains** [comment]
It is persistent, actually turns out it is an authentication issue, trying to debug exactly what though.

When I use
`docker-credential-gcr configure-docker`

```
ains@ains-dev-box-late-2017-edition-2:~/platform-staging$ docker push eu.gcr.io/windy-oxide-102215/ains:latest
The push refers to a repository [eu.gcr.io/windy-oxide-102215/ains]
a09947e71dc0: Layer already exists
9c42c2077cde: Layer already exists
625c7a2a783b: Layer already exists
25e0901a71b8: Layer already exists
8aa4fcad5eeb: Layer already exists
denied: An error occurred uploading the manifest with digest "sha256:ee703208893fcfb218d683f5fbf295d995c8334ff3431b5e0b7546015970af54".
```
Using `gcloud docker -a`

I can push using `docker push` but obviously has no effect on bazel rules_docker push. I'm guessing docker-credentials-gcr is attempting to use the service account of the machine that i'm on and not my active account via `gcloud auth`

**Comment by ains** [comment]
and on that note after reading the documentation of `docker-credential-gcr`

Based on the ordering of credential lookup it was using the service account
Running
`docker-credential-gcr config --token-source="gcloud"` means it will use my personal account via gcloud auth.

Everything works now, would be great to have clearer error messages when access is denied on manifest upload.

**Comment by mattmoor** [comment]
Cool, glad you are unblocked.

**Comment by jonjohnsonjr** [comment]
I'm having trouble reproducing this -- I just see "Access denied."

If you don't mind, could you describe a ~minimal setup to reproduce that error?

**Comment by ains** [comment]
I'll try and come up with a repro if you still can't get a hold of anything but I believe the issue was it had credentials (service account of a google cloud VM) but they were invalid for the given repository. I also get `access denied` if I try without any credentials configured.

Forcing it to use the gcloud token source resolved the issue as my personal account could push.

**Comment by mattmoor** [comment]
@jonjohnsonjr Should we close this?

**Comment by mattmoor** [comment]
@jonjohnsonjr I'm going to close this, re-open it if you can find a repro.

**Comment by krzyzacy** [comment]
@ains @mattmoor  I'm getting the exactly same issue - what's the resolution? do I have to depend on `docker-credential-gcr`?

**Comment by mattmoor** [comment]
@krzyzacy You should certainly start using `docker-credential-gcr`

**Comment by krzyzacy** [comment]
hummm, so, even if I have `GOOGLE_APPLICATION_CREDENTIALS` set properly, it's still not enough?
