### ISSUE TITLE
Must have gcloud auth token to pull gcr.io images, even public ones

### ISSUE THREAD

**Issue by justinsb** [bazelbuild/rules_docker#1175]
With 0.10, trying to pull public gcr.io images fails if you do not have a valid gcloud auth token (`gcloud auth revoke`).  If I go back to 0.9 I get a different error but it still fails.

Example of a public image:
gcr.io/distroless/base@sha256:e37cf3289c1332c5123cbf419a1657c8dad0811f2f8572433b668e13747718f8

Example error:
```
2019/10/04 13:10:48 Image pull was unsuccessful: reading image "gcr.io/distroless/base@sha256:e37cf3289c1332c5123cbf419a1657c8dad0811f2f8572433b668e13747718f8": Get https://gcr.io/v2/token?scope=repository%3Adistroless%2Fbase%3Apull&service=gcr.io: invoking docker-credential-gcloud: exit status 1; output: 
```

Docker pull fails to get an auth token, but the pull works succeed:

```
docker pull  gcr.io/distroless/base@sha256:a4624843fb1d7d43d9e3d62f6d76b51b6e02b3d03221e29fef4e223d81ef3378
ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
sha256:a4624843fb1d7d43d9e3d62f6d76b51b6e02b3d03221e29fef4e223d81ef3378: Pulling from distroless/base
Digest: sha256:a4624843fb1d7d43d9e3d62f6d76b51b6e02b3d03221e29fef4e223d81ef3378
Status: Image is up to date for gcr.io/distroless/base@sha256:a4624843fb1d7d43d9e3d62f6d76b51b6e02b3d03221e29fef4e223d81ef3378
```

**Comment by nlopezgi** [comment]
iiuc, its required to have a valid gcloud auth token to pull many images (even public ones), and it has never been possible to pull them w/o the valid token (and its something that is configured on the side of the owners of these images). 

The differences you are seeing between errors in 0.9 and 0.10 correspond to differences in the implementation that were switched out between these versions. 

Not sure what your specific ask here is in this issue, though, as there is nothing we can do in these rules to avoid this restriction (or are you saying that this did work with 0.9 but does not work with 0.10.0, if so, please let me know to reopen, closing for now).
