### ISSUE TITLE
Upgrading to v0.9.0 breaks with @com_github_google_go_containerregistry' could not be resolved

### ISSUE THREAD

**Issue by sim4life** [bazelbuild/rules_docker#1176]
Using bazel v0.24.1 and go v1.13.1, I'm upgrading docker_rules from v0.8.1 to v0.9.0 and running on buildkite ci server but it is breaking with following error:
```
ERROR: /home/user/.cache/bazel/_bazel_user/0a34cc5f3ef19080785f32397de382e9/external/io_bazel_rules_docker/container/go/cmd/extract_config/BUILD:19:1: no such package '@com_github_google_go_containerregistry//pkg/v1/tarball': The repository '@com_github_google_go_containerregistry' could not be resolved and referenced by '@io_bazel_rules_docker//container/go/cmd/extract_config:go_default_library'
--
  | ERROR: Analysis of target '//go/src/<company_name>/server/anderson:anderson_tagged_docker_push_gcr' failed; build aborted: no such package '@com_github_google_go_containerregistry//pkg/v1/tarball': The repository '@com_github_google_go_containerregistry' could not be resolved
```
My `WORKSPACE` file looks like:

```
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "513c12397db1bc9aa46dd62f02dd94b49a9b5d17444d49b5a04c5a89f3053c1c",
    url = "https://github.com/bazelbuild/rules_go/releases/download/v0.19.5/rules_go-v0.19.5.tar.gz",
)

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

http_archive(
    name = "bazel_gazelle",
    sha256 = "7fc87f4170011201b1690326e8c16c5d802836e3a0d617d8f75c3af2b23180c4",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.18.2/bazel-gazelle-0.18.2.tar.gz"],
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "e513c0ac6534810eb7a14bf025a0f159726753f97f74ab7863c650d26e01d677",
    strip_prefix = "rules_docker-0.9.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.9.0/rules_docker-v0.9.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "base_tiny",
    digest = "sha256:59339b6629886ebb44e0fd7d406b88e9cbe77aa19678a3222c5b29772f8dd258",
    registry = "eu.gcr.io/windy-oxide-102215",
    repository = "base_tiny",
)

container_repositories()
```

I've an empty `BUILD.bazel` at the root of the project.
Any clues?

**Comment by nlopezgi** [comment]
You're missing (at least) a call to `container_deps()` and you probably should not have a call to container_pull before your call to `container_repositories` and `container_deps`. Please check in detail https://github.com/bazelbuild/rules_docker#setup to make sure you have properly set up deps for these rules. Also, better to use 0.10.1 and to switch to a more recent version of Bazel (0.29.1 is latest release). Closing but please let me know to reopen if there are any issues once you have properly done the [setup](https://github.com/bazelbuild/rules_docker#setup)

**Comment by sim4life** [comment]
Thanks a lot. I got it working with Bazel v0.24.1 and docker_rules v0.10.1.
Yes, that's the ultimate goal to get to Bazel v0.29.1 and eventually to v1.0 but we are using a lot of protobuf pubref rules that I need to replace before upgrading the Bazel version.

Would you like taking a look at my 300+ line WORKSPACE file to suggest easy an upgrade path?

**Comment by nlopezgi** [comment]
good to hear you were able to resolve the issue with rules docker.
I'm not sure I can help much with an upgrade path, upgrading Bazel is hard, and protobuf is a very common pain point. But do look at rules_k8s, we have some protobuf deps there that we have managed to keep working with newer versions of Bazel.
