### ISSUE TITLE
Gazelle recreates a go_binary that conflicts with go_image.

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_docker#119]
When I convert a project with Gazelle to use Bazel and then rewrite a generated `go_binary` to use `go_image` instead, the next time I run Gazelle it creates a new `go_binary` with a conflicting build target.

**Comment by mattmoor** [comment]
@ianthehat @jayconrad I opened this here mostly to track, what can I do to make Gazelle do the right thing here?

**Comment by ianthehat** [comment]
In this particular case I think the right thing is to actually have a go_binary and then have a go_image depend on it. There are some good reasons why wrapping binary rules is troublesome (things like whitebox tests that require the binary as a library attribute, or the ability to consume the static/msan etc versons). I am hoping to put together a proposal for doing it this way as soon as the new version of bazel lands so I can merge all the toolchains work with the updated providers.

There is the more general point though that people will probably always want to write rules that wrap the go rules. I am trying to make it as rare as possible with the way we design the rules (to the point where you can now customize how a rule operates by modifying the action emitting functions at the toolchain level), but it's never going to go away totally, so we need to have a way of indicating to gazelle that a rule is a wrapper, and that it should either manage it the same way it would an underlying rule, or at least trust it to consume the sources it lists and not put them in another rule as well.

**Comment by mattmoor** [comment]
Favoring the rules_go issue for tracking.
