### ISSUE TITLE
Support stamping build_args with dockerfile_image

### ISSUE THREAD

**Issue by asv** [bazelbuild/rules_docker#1194]
I should be able to use a variables from my workspace status as build_arg when running dockerfile_image.

Example:
```
dockerfile_image(                                                                                                                                                                              
    name = "webui-image",
    build_args = {"node_env": "{STABLE_NODE_ENV}"},
    dockerfile = "//webui:Dockerfile",
) 
```

**Comment by nlopezgi** [comment]
Hi @asv,
Thanks for creating this issue.
We're not currently actively building new features for the `dockerfile_image` rule.
We'd be happy to receive a PR to implement this feature and test it though.
Thanks!

**Comment by asv** [comment]
Hi @nlopezgi.

I tried to make a naive implementation, but it seems `repository_ctx` does not have fields `info_file` and `version_file` ... Tell me in which direction to continue? Can to move this rule to execution phase?

**Comment by nlopezgi** [comment]
Hi @asv,
moving this rule to a regular Starlark rule would be significant effort which we are not willing to take on atm. The main reason why this is complex is because we would need to figure out how to get the Docker cache and the Bazel cache to play along nicely.
