### ISSUE TITLE
create_image_config.go failed to parse env variables with multiple equals signs

### ISSUE THREAD

**Issue by kangnak** [bazelbuild/rules_docker#1199]
The docker image nvidia/cuda has an env variable like CUDA_PKG_VERSION=10-0=10.0.130-1. Note that it has three equals(=) signs. And the following line of code emits an error when parsing the variable.

https://github.com/bazelbuild/rules_docker/blob/13a4d3aeabd179a7aed88d37f296aef82823df49/container/go/pkg/compat/config.go#L133

Reference: https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/ubuntu18.04/10.1/base/Dockerfile

**Comment by nlopezgi** [comment]
https://github.com/bazelbuild/rules_docker/pull/1192 should solve this. Waiting on the contributor to add some tests.

**Comment by kangnak** [comment]
Thanks. Let me close this issue.
