### ISSUE TITLE
Document minimum version of Bazel required

### ISSUE THREAD

**Issue by mariusgrigoriu** [bazelbuild/rules_docker#1216]
The README should document what version(s) of Bazel  are required to run rules_docker.  For example v0.8.0 uses `default_mtime` which appears to have been introduced with Bazel 0.24, but there was no mention that a newer version was required.

**Comment by nlopezgi** [comment]
We don't do any backward compatibility testing with older versions of Bazel (nor do we have the time atm to set these up). Support for older versions of Bazel is not something we are doing explicitly. We always recommend you use the latest version of Bazel; at this point, if we document anything, it would be that we support 1.0.0 and anything else backwards that works is just by accident. Keeping open to consider documenting this explicitly.

**Comment by alexeagle** [comment]
I'd like to add that backwards compat testing with a new focus on bazel-integration-testing, maybe something we can pick up.
