### ISSUE TITLE
container_image full docker image tarball

### ISSUE THREAD

**Issue by emranbm** [bazelbuild/rules_docker#1219]
Hi,
As mentioned [here](https://github.com/bazelbuild/rules_docker#container_image-1), the full docker image tarball is created as implicit output **on demand**.  
But, what does it mean by on demand? how can I inform the build to produce it?  
Seems a lack of documentation here.

**Comment by smukherj1** [comment]
The documentation [here](https://github.com/bazelbuild/rules_docker#using-with-docker-locally) guides how to generate the "on-demand" outputs. So if you have
```
container_image(
  name = "image",
  ...
)
```

in package `//path/to/package`, you can generate the image tarball with `bazel build //package/to/package:image.tar`.
