### ISSUE TITLE
Parallel docker_push?

### ISSUE THREAD

**Issue by ains** [bazelbuild/rules_docker#122]
Migrated a few of our production go + docker builds to be completely managed with rules_go and rules_docker, and it's already significantly faster than our prior build process.

However, I think we could get a significant speedup by being able to execute multiple `docker_push` rules in parallel.

As the `docker_push` rule is executed using `bazel run` only one can be executed at a time (to my knowledge), so i'm currently running `bazel build` with multiple targets to build as many docker images as Bazel can schedule concurrently and then afterwards sequentially running `bazel run` with the push target to leverage the earlier cache.

Is there any way to achieve this at the moment / is it something you guys would consider supporting, happy to submit an implementation PR if we can agree on a design.

**Comment by mattmoor** [comment]
@ains There is `docker_bundle` and (under contrib) a `docker_push` that pushes an entire bundle (with the tags from the bundle).  You can see an example [here](https://github.com/bazelbuild/rules_docker/blob/master/docker/testdata/BUILD#L341-L361).

This has the right shape to achieve what you want, but IIRC it doesn't currently do the pushes in parallel.

I'd vote for a PR to parallelize those, if the shape is agreeable?

**Comment by ains** [comment]
Thanks for the quick response, looks like I can do what we want with `bundle` + `pushall`.
Also moves even more of our config a bazel rule which is awesome.

I'll also have a look at submitting a PR to make it parallel.

**Comment by ains** [comment]
Landed in https://github.com/bazelbuild/rules_docker/commit/92250a141b7a2fe80c098e3d019aa229cd56fdb2
