### ISSUE TITLE
Have individual layer output from the `install_pkgs()` rule

### ISSUE THREAD

**Issue by bajacondor** [bazelbuild/rules_docker#1231]
It would be very convenient and useful to have an output of the just the layer.tar that was created with the `install_pkgs()` rule.  Currently the rule outputs the entire image tar.  Is there a way to just get the layer that was created?  Maybe there is something I'm missing.  

Thank you!

**Comment by nlopezgi** [comment]
Perhaps the `language_tool_layer` rule is what you are looking for here? Ex: https://github.com/GoogleCloudPlatform/layer-definitions/blob/master/layers/ubuntu1604/bazel/BUILD#L93 (note it does not output a separate later, but can be composed in a `toolchain_container` rule: https://github.com/GoogleCloudPlatform/container-definitions/blob/master/ubuntu1604_rbe/BUILD#L32). If that does not work for you, happy to write with you to add the feature to the `language_tool_layer` rule (i.e. not to the `layer` rule as that one does not require docker binary)
