### ISSUE TITLE
[feature request] expose 'mode' to language rules

### ISSUE THREAD

**Issue by hempsteadz** [bazelbuild/rules_docker#1239]
The language rules are macros that consist of an appropriate binary target and an `app_layer` target. `app_layer` accepts `mode` - my request is for the language rules to accept `mode` as an attribute and to pass it along to `app_layer`.

`container_image` has many attributes that the language rules don't, but the workaround for most of them is (as suggested in the documentation) to use a `container_image` as the base for a language-specific image. I don't think that workaround works in this case.

**Comment by alex1545** [comment]
Hi @hempsteadz,
Can you please provide more details about your use case? I'm not sure I understand how exactly the data passed in the `mode` attribute to a `lang_image` macro will be used further in the `app_layer` target. Keep in mind that the goal of the `lang_image` rules is to build an image that wraps a specific `lang_binary` target.

What `mode` currently dose is it sets the mode of the files passed in the `files` attribute. So the mode of what files do you wish to set when calling the `lang_image` macro? If it is for some additional files that you want to include in your image, then you should be able to achieve this with your own `container_image` target that you will then use as your base (as suggested in the docs).

**Comment by hempsteadz** [comment]
The files whose mode I want to change are the files added to the image by the `lang_image` macro itself - essentially everything under `*.runfiles` of the `lang_binary` target. It's not currently possible to do this by creating a separate `container_image` as a base.

The context is that I want the source files of these containers to be editable on the fly without granting `root` access inside the container.

**Comment by nlopezgi** [comment]
Hi @hempsteadz,
Thanks for creating this issue. It does make sense that the only way to achieve what you need is by exposing mode in the lang image rules. We would be happy to work with you if you want to create a PR to expose this attr properly and add tests to validate the new feature.
