### ISSUE TITLE
Use puller with http_proxy

### ISSUE THREAD

**Issue by pvcnt** [bazelbuild/rules_docker#1241]
I'm working behind a proxy, with `http[s]_proxy` environment variables set. By default, rules are trying to pull images from gcr.io, and it ends up with a timeout (i.e., host cannot be reached). If I try a direct docker pull, I do not have any issue.

Is it a setup issue (my bad), a Docker pull issue, or a rules_docker issue?
Thanks!

**Comment by nlopezgi** [comment]
Hi @pvcnt 
Can you provide more info about your setup (content of your WORKSPACE file with container_pull target) and more details of the error you are getting. These rules don't pull by default from any repo/registry, but you might not be setting up the attrs of [container_pull](https://github.com/bazelbuild/rules_docker#container_pull-1) in the correct way.

**Comment by Zetten** [comment]
Hi @nlopezgi I'm also having issues using rules_docker behind an HTTP proxy.

What was previously running happily on commit 30eda16f0fc98e2d6df4c2d377fdfb3872318dc1 is now timing out with v0.12.1.

Like @pvcnt I have the `http[s]_proxy` and `HTTP[S]_PROXY` variables set in my shell, and have been passing them through to bazel with `--action_env` (although I think for some time bazel automatically injects these by default for repository_rule execution).

My effective WORKSPACE content:
```
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "14ac30773fdb393ddec90e158c9ec7ebb3f8a4fd533ec2abbfd8789ad81a284b",
    strip_prefix = "rules_docker-0.12.1",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.12.1/rules_docker-v0.12.1.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//container:container.bzl", "container_pull")

container_pull(
    name = "java_image_base",
    registry = "gcr.io",
    repository = "distroless/java",
    digest = "sha256:8311f55c69481436c04efbd69af2e00b4e4544596dc7212932af5741f0d23f4e",
)
```

When building any image which uses this as a base, the fetch simply runs up to the puller's default 600s timeout - no additional logging though:
```$ bazel fetch @java_image_base//...
Loading: 0 packages loaded
    Fetching @java_image_base; fetching 49s
```

I can replicate the behaviour by manually downloading and executing the puller tool directly, so I think the issue is not necessarily anything to do with bazel, but rather the go puller (or go-containerregistry):

```./puller-linux-amd64 -directory ~/tmp/img -name gcr.io/distroless/java@sha256:8311f55c69481436c04efbd69af2e00b4e4544596dc7212932af5741f0d23f4e --timeout=10
2019/10/29 16:35:12 Running the Image Puller to pull images from a Docker Registry...
2019/10/29 16:36:07 Image pull was unsuccessful: reading image "gcr.io/distroless/java@sha256:8311f55c69481436c04efbd69af2e00b4e4544596dc7212932af5741f0d23f4e": Get https://gcr.io/v2/: dial tcp 74.125.133.82:443: i/o timeout
```

**Comment by pvcnt** [comment]
Hi @nlopezgi, as mentioned above, it is not the rule which is pulling an image (I believe it can't) but the call to the associated repositories from WORKSPACE, which also sets up other dependencies (e.g., go_deps and toolchains). I was still expecting the container_pull to work, given https_proxy is set correctly and a plain docker pull works.

I ended up using an image from an internal Docker registry, which was a better solution. anyway Hopefully @Zetten's answer gives more information to reproduce the issue.

**Comment by Zetten** [comment]
I've finally found some time to look at this, and found a fairly simple workaround: simply add `Proxy: http.ProxyFromEnvironment,` to the `&http.Transport` creation at https://github.com/bazelbuild/rules_docker/blob/master/container/go/cmd/puller/puller.go#L138

This causes the puller tool to use the conventional proxy env vars, which bazel is already propagating to the rule context.

I'm not confident to make a PR for this, as I suspect there are other places in rules_docker which should be considered, and I'm not any kind of go expert so there could be an alternative approach.

**Comment by remycx** [comment]
I'm also meeting the same issue behind a corporate proxy, and I'm unsure how to apply that workaround to a CI context. Is someone able to look at the potential fix @Zetten found ?

I'm attempting to use Bazel in a company environment, and it'd be quite helpful ^^

Thanks much :)

**Comment by Zetten** [comment]
For what it's worth, until a fix is upstreamed I've done the following - not really sustainable but it works for now:

1. Make the change to puller.go and build the tool
2. Commit the resulting `puller` binary into my project, add it to `exports_files` in a BUILD file
3. Rewrite all `container_pull` rules to reference it: `puller_linux = "//third_party/rules_docker:puller",`

It might be possible to do the same with a patched `http_repository` but this was a quick and dirty workaround.

**Comment by nlopezgi** [comment]
Hi @Zetten ,
Sorry for the long delay in replying. Why don't you start a PR with your suggested fixes and we'll work from there?

**Comment by Zetten** [comment]
Great! I've started off in #1135 

Like I said I'm not sure if there's any other go code I should check (no other go files are importing `net/http` at least) or whether there's anything I can do to set up a test.
