### ISSUE TITLE
Use target from `container_image()` as the `base` of `language_tool_layer()` in a different build file

### ISSUE THREAD

**Issue by bajacondor** [bazelbuild/rules_docker#1242]
Hello,

I have  one BUILD  file that specifies a `container_image()` target in `//images/build/base_tool:tool_base_image` like this:

```container_image(
    name = "tool_base_image",
    base = "@debian_buster_slim//image",
    tars = [
        ":user_and_group/tmp/user_and_group.tar",
    ],
    env = {
        "HOME": "/home/nonroot"
    },
    user = "nonroot",
    workdir = "/home/nonroot",
)
```

Then a `language_tool_layer()` target in `//layers/common/curl_ssl:curl_ssl_ltl` looks like this:

```
language_tool_layer(
    name = "curl_ssl_ltl",
    base = "//images/build/base_tool:tool_base_image//image",
    installables_tar = ":download_curl_ssl_packages.tar",
)
```

But I get the error: 

```
rule: invalid target name 'tool_base_image//image': target names may not contain '//' path separators
```

When I specify the `base` like this:

```
base = "//images/build/base_tool:tool_base_image.tar",
```

I get the error:

```
Unable to extract manifest.json, make sure bazel-out/darwin-fastbuild/bin/images/build/base_tool/tool_base_image-layer.tar is a valid docker image.
 "filename 'manifest.json' not found"
```

How to I specify an image target from elsewhere in my workspace?

Thank you.

**Comment by nlopezgi** [comment]
Try
`base = "//images/build/base_tool:tool_base_image",`

**Comment by bajacondor** [comment]
Thanks, @nlopezgi.

Should have mentioned that I tried that too.  Somehow it still points to `-layer.tar`:

The error:

```
Unable to extract manifest.json, make sure bazel-out/darwin-fastbuild/bin/images/build/base_tool/tool_base_image-layer.tar is a valid docker image.
 "filename 'manifest.json' not found"
````

**Comment by nlopezgi** [comment]
This worked for me with:
 
```
language_tool_layer(
    name = "curl_ssl_ltl",
    base = "//images/build/base_tool:tool_base_image.tar",
)
``` 

I have repro code here: https://github.com/nlopezgi/rules_docker/tree/issue1242/testing/java_image (see the new images/build/base_tool and layers/common/curl_ssl directories there)

**Comment by bajacondor** [comment]
I pulled and tried to run that code and got:

```
ERROR: Skipping '//testing/java_image/layers/common/curl_ssl/*': no such package 'testing/java_image/layers/common/curl_ssl/*': Package is considered deleted due to --deleted_packages
```

**Comment by bajacondor** [comment]
But, I copied your test BUILD files and got it to work.  It appears to be the `tars = []` attr that is causing the problem.

**Comment by nlopezgi** [comment]
ugh, we probably don't have a test that exercises some path and we might have a bug. I'll have to look into it in detail later (in a few days), if you can find any other clues about what might be happening or find bugs / fixes let me know. Thanks for reporting this issue!

**Comment by bajacondor** [comment]
I'm not sure what happened, but I can't seem to reproduce the behavior anymore.  When I copied your targets it worked, then I started adding back my additional attrs and the error never returned.  Everything is working as expected now.
