### ISSUE TITLE
Pusher does not follow insecure-registries directive

### ISSUE THREAD

**Issue by kovkev** [bazelbuild/rules_docker#1245]
Hi rules_docker contributors! Thank you very much for developing this repository.

I am trying to setup a cluster where one machine would have a private docker registry running in there. It is running and listening to port 5000 right now.

After lots of digging, I found out that one of the steps to connect to the registry is to use `docker login`, because that will make sure the credentials are stored in a keystore somewhere (maybe the local keychain or whatnot. That's specified with credsStore in config.json).

I'm running Docker on OSX. In the UI, I added the IP:5000 of the machine to `Insecure Registries`, clicked `Apply & Restart`, and proceeded to run `docker login`, and that succeeded. 

```
Users-MacBook-Pro:tgkj kevin$ docker --config ~/pdev/tgkj/docker_config/ login http://IP:5000
Username: testuser
Password:
Login Succeeded
```
on a subsequent run, it doesn't ask for credentials:
```
Users-MacBook-Pro:tgkj kevin$ docker --config ~/pdev/tgkj/docker_config/ login http://IP:5000
Authenticating with existing credentials...
Login Succeeded
```

However, if I setup rules_docker with the following path, which is what Docker on OSX is using:
```
docker_toolchain_configure(
  name = "docker_config",
  client_config="/Users/kevin/.docker/",
)
```

and I run `Users-MacBook-Pro:tgkj kevin$ bazel run //human/forum:image_push`, I get:
```
2019/10/25 00:01:44 Error pushing image to IP:5000/human/forum:dev: unable to push image to IP:5000/human/forum:dev: Get https://IP:5000/v2/: x509: cannot validate certificate for IP because it doesn't contain any IP SANs
```

It seems like this line will not consider the "insecure-registries" configured in `daemon.json`:.

https://github.com/bazelbuild/rules_docker/blob/582ea1a7b57ee154aa2d4c1f558ac451516b0913/container/go/cmd/pusher/pusher.go#L167

It seems like it only looks at the Keychain. But won't ignore the certificate security.

I would like to bypass that just to see if I am doing some of my set up right. There's a lot of steps to get this thing set up and I just need to test and develop the infrastructure while nothing important is stored in this registry and machine.

**Comment by kovkev** [comment]
I think that's because the `rules_docker` is using `containerregistry` where they do not check the `insecure-registries` attribute in the configs:

https://github.com/google/containerregistry/blob/da03b395ccdc4e149e34fbb540483efce962dc64/client/docker_creds_.py#L249-L286

What would be an alternative? I guess I have to construct proper certificates then.

**Comment by nlopezgi** [comment]
Hi @kovkev,
thanks for opening this issue. Which version of `rules_docker` are you using? As of 0.12.0 rules_docker does not have any dependencies from the core rules on  https://github.com/google/containerregistry, we have migrated to using https://github.com/google/go-containerregistry. Please try your use case with a more recent version of rules_docker and let me know if the problem persists. If so (or if you are indeed now using 0.12.0), we can loop in the owners of https://github.com/google/go-containerregistry to help us out (but the reference above to https://github.com/google/containerregistry is probably not relevant atm).

**Comment by kovkev** [comment]
Hi @nlopezgi , thanks. Indeed, the reference to google/containerregistry is not relevant after all.

I tried using rule_docker 0.12.0 and run `bazel run //human/forum:image_push` and still got the same error. I looked at the code and the rules_docker's `container_push` calls go-containerregistry's remote.Write: 

https://github.com/google/go-containerregistry/blob/f9947dc9e9f8a234eb279ce02b277dca184de9be/pkg/v1/remote/write.go#L44

where it is not clear if the `DOCKER_CONFIG` environment variable nor the config directory we specify in the WORKSPACE with `rules_docker` is being used.

`google/go-containerrules` does have a way to specify the option Insecure: 

https://github.com/google/go-containerregistry/blob/e1c5762cb945605669ed5fcb3124e3f839e5cc79/pkg/name/options.go#L47

but `google/go-containerrules` does not decide to set Insecure by inspecting the `DOCKER_CONFIG` files. So, I think we should definitely loop the owners of `go-containerregistry` in on this to help us understand what happens. I don't know how to loop them in. I'll let you do that if you may!

Thanks,

Kovkev
