### ISSUE TITLE
Issue resolving @io_bazel_rules_go

### ISSUE THREAD

**Issue by ChetanBhasin** [bazelbuild/rules_docker#1246]
With `0.12.0` the resolution of `io_bazel_rules_go` doesn't work (probably) because of the wrong reference.

Here is a given stack trace:

```
ERROR: Analysis of target '//app:server' failed; build aborted: error loading package '@io_bazel_rules_docker//': in /private/var/tmp/_bazel_user/6ece328f72073a7b59747a1611298c44/external/bazel_gazelle/def.bzl: in /private/var/tmp/_bazel_user/6ece328f72073a7b59747a1611298c44/external/io_bazel_rules_go/go/def.bzl: in /private/var/tmp/_bazel_user/6ece328f72073a7b59747a1611298c44/external/io_bazel_rules_go/go/private/context.bzl: Unable to find package for @io_bazel_rules_go_compat//:compat.bzl: The repository '@io_bazel_rules_go_compat' could not be resolved.
```

It [seems like](https://github.com/bazelbuild/rules_go/issues/1976#issuecomment-516046551) in the `rules_go` the references need to be resolved from `deps.bzl` not `def.bzl`.

**Comment by nlopezgi** [comment]
If you're getting this error you have a problem in the order of your dependencies in your `WORKSPACE` or you are not doing the [setup](https://github.com/bazelbuild/rules_docker/#setup) properly. If the former, you might be pulling an earlier version of `rules_go` than the one required by these rules (i.e., the repo `@io_bazel_rules_go_compat//:compat.bzl` exists with the right version of `rules_go`). The easiest fix (typically) is to put further up in your `WORKSPACE` the declarations [in the rules_docker setup](https://github.com/bazelbuild/rules_docker/#setup). If that does not work, you can paste here the relevant contents of your `WORKSPACE` (where you have the `rules_docker` targets and the `rules_go` targets) and I can help you debug.

**Comment by jonbuffington** [comment]
I was able to workaround this issue using `v0.12.1` of `io_bazel_rules_go` by adding the following in my `WORKSPACE` before the declarations in [the rules_docker setup](https://github.com/bazelbuild/rules_docker/#setup):

```
### WORKAROUND
http_archive(
    name = "io_bazel_rules_go",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.20.2/rules_go-v0.20.2.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.20.2/rules_go-v0.20.2.tar.gz",
    ],
    sha256 = "b9aa86ec08a292b97ec4591cf578e020b35f98e12173bbd4a921f84f583aebd9",
)
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
####
```
prior
