### ISSUE TITLE
build_tar fails with --file containing '='

### ISSUE THREAD

**Issue by yitaosun** [bazelbuild/rules_docker#1254]
I'm new to bazel.  While creating a docker image with dependency for `pyspark==2.4.4`, I found a file in the Wheel archive named [`pyspark/data/mllib/images/partitioned/cls=kittens/date=2018-01/not-image.txt`](https://github.com/apache/spark/tree/v2.4.4/data/mllib/images/partitioned/cls%3Dkittens/date%3D2018-01) that broke the docker image target.  Digging around the code, I realized that `build_tar` does not handle `--file` arguments where the input file contains the `=` character.

https://github.com/bazelbuild/rules_docker/blob/7476c25fcf188dbfc4eb154ad309eda7df24652c/container/build_tar.py#L430-L432

I created a hack to fix it in our local environment.

https://github.com/yitaosun/rules_docker/blob/8848211f7d66893883d30c9a2d1c1b68a7ec9c2c/container/build_tar.py#L430-L441

I'm not sure if this is a real bug or intentional behavior, therefore I'm not sure what the proper fix should be.  Would someone like to chime in?

**Comment by alex1545** [comment]
Hi @yitaosun and thank you for trying out rules_docker.
Can you please provide more details about how you are creating the docker image (i.e., show you Bazel target in the BUILD file and your setup in your WORKSPACE file). Can you also provide details about your broken docker image target? Are you getting any specific error messages? You may also want to share details about your workaround and what exactly you were able to achieve with it.

**Comment by yitaosun** [comment]
Hi @alex1545, here's a minimized repro.  Similar to the repro, our build setup uses Bazel 0.24.1 and a fork of `rules_docker` from August, 2018.

```python
# WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz",
    sha256 = "aa96a691d3a8177f3215b14b0edc9641787abaaa30363a080165d06ab65e1161",
)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()
# Only needed if using the packaging rules.
load("@rules_python//python:pip.bzl", "pip_repositories")
pip_repositories()

# Import bazel_source ourselves, to work around checksum issues 
# https://github.com/bazelbuild/rules_docker/issues/500
http_archive(
    name = "bazel_source",
    sha256 = "46dfffac884ccd51fcb493dd86463cb8c21be949fdb17634ca37805fd544beae",
    urls = [("https://releases.bazel.build/0.17.0/rc1/bazel-0.17.0rc1-dist.zip")],
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "5d64414477ffe87b16e248986c0731aee821ea3d626121cfeeec4ef7096812ca",
    strip_prefix = "rules_docker-0.5.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.5.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
    container_repositories = "repositories",
)

# This is NOT needed when going through the language lang_image
# "repositories" function(s).
container_repositories()

load(
    "@io_bazel_rules_docker//python:image.bzl",
    _py_image_repos = "repositories",
)

_py_image_repos()
```

```python
# BUILD
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_binary(
  name = "main",
  main = "foo=bar.py",
  srcs = [
    "foo=bar.py"
  ],
)

load("@io_bazel_rules_docker//python:image.bzl", "py_image")

py_image(
  name = "main_image",
  main = "foo=bar.py",
  srcs = [
    "foo=bar.py"
  ],
) 
```

```python
# foo=bar.py
if __name__ == "__main__":                                                                                                                                                  
  print("hello world")                                                                                                                                                      
```

**Comment by yitaosun** [comment]
I believe https://github.com/bazelbuild/rules_docker/commit/904c934486de17e49cc82cbc06692254d9d457ca is the commit that addresses my exact issue.  I'll look into updating our local `rules_docker` fork.
