### ISSUE TITLE
Error running images, created using go_image, container_push on MacOS 

### ISSUE THREAD

**Issue by boseabhishek** [bazelbuild/rules_docker#1273]
Hello everybody,

I have created and pushed a Buildbarn `bb-storage` image successfully on my **MacOS (version: 10.14.6)** using:
`bazel run --host_force_python=PY2 //cmd/bb_storage:bb_storage_container_push`

But it crashes during the container creation with the below error message:
`standard_init_linux.go:211: exec user process caused "exec format error"`

I tried using 

`bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 --host_force_python=PY2 //cmd/bb_storage:bb_storage_container_push`  

when I see other errors:

```
ERROR: While resolving toolchains for target @io_bazel_rules_go//:go_context_data: no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type
ERROR: Analysis of target '//cmd/bb_storage:bb_storage_container_push' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type
INFO: Elapsed time: 3.208s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (39 packages loaded, 429 targets configured)
FAILED: Build did NOT complete successfully (39 packages loaded, 429 targets configured)
    currently loading: @io_bazel_rules_go//go/tools/builders ... (2 packages)
```

Other info:
$ bazel --version
$ bazel 0.27.1

**Comment by nlopezgi** [comment]
please see https://github.com/bazelbuild/rules_docker/issues/943

**Comment by boseabhishek** [comment]
Thanks @nlopezgi  for pointing out.. but for me I can push the image to registry and pull it BUT it keeps on failing with:
` standard_init_linux.go:211: exec user process caused "exec format error" `

**Comment by boseabhishek** [comment]
Apologies but I think it's a separate issue - I can build an image with bazel run using go_image and container_push but the image after being pulled does not run and keeps on crashing with: ` `standard_init_linux.go:211: exec user process caused "exec format error" `

**Comment by nlopezgi** [comment]
This is not a separate issue. The images can be created, pulled and pushed. But the binaries inside it are created for mac, and cant run inside a Linux container, due to the issue pointed above.

**Comment by boseabhishek** [comment]
yes - so as a workaround, would I install a VM on Mac and build the image from there? @nlopezgi if you please advise me..

**Comment by nlopezgi** [comment]
Yes, you could build this inside a VM on a Mac or alternatively (and likely easier), you could use the bazel container: https://docs.bazel.build/versions/master/bazel-container.html

**Comment by boseabhishek** [comment]
Hi @nlopezgi - with using bazel container and checking out the soucre code inside it and then running `bazel run --host_force_python=PY2 //cmd/bb_storage:bb_storage_container_push`, it works and pushes to docker registry.

However, when I use in this way: 
`
docker run \
  -e USER="$(id -u)" \
  -u="$(id -u)" \
  -v /src/workspace:/src/workspace \
  -v /tmp/build_output:/tmp/build_output \
  -w /src/workspace \
  l.gcr.io/google/bazel:0.17.1 \
  --output_user_root=/tmp/build_output \
  run --host_force_python=PY2 //cmd/bb_storage:bb_storage_container_push
`

it fails with 

`
ERROR: /tmp/build_output/5d9ce43a1ac7b5311c5e3a18e17a7284/external/go_image_base/image/BUILD:6:1: SHA256 external/go_image_base/image/000.tar.gz.sha256 failed (Exit 1) sha256 failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256 external/go_image_base/image/000.tar.gz bazel-out/k8-fastbuild/bin/external/go_image_base/image/000.tar.gz.sha256
`
 and also

`
KeyError: 'getpwuid(): uid not found: 501'
`

Is it something to do with permission on Mac with the build_output directory?
