### ISSUE TITLE
Is there an alternative to downloading dependencies?

### ISSUE THREAD

**Issue by kovkev** [bazelbuild/rules_docker#1280]
https://github.com/bazelbuild/rules_docker/blob/048ee9bbbe26f6d304d8ca4657ccef1720f4e792/repositories/repositories.bzl#L40

Hi contributors to rules_docker! Thanks tons for your contributions to the repository.

I was wondering if there's an alternative to downloading the puller binary? There is the source code for the puller within this exact WORKSPACE/repository. Why not reuse it? I know there's a limitation if we need to Build the puller by doing a call from within the WORKSPACE. 

Are there alternative solutions? Is it possible to first run `bazel build //...:puller` and then use the output.

Does there exist a tool to easily host binaries locally? I found this makes it possible to push the binaries somewhere. What tool should one use to host the binaries? https://github.com/scele/rules_docker/commit/b0f78e9c51dbeb5bc52f89339e7325fa3140424e

**Comment by nlopezgi** [comment]
Hi @kovkev ,
thanks for creating this issue.
Unfortunately, there is no alternative to downloading dependencies for repo rules. Repo rules cannot build any artifacts, and requiring users to first run `bazel build //...:puller` is an alternative that would be too error prone and would likely cause friction for users whenever they update their dependencies on rules_docker.


> Does there exist a tool to easily host binaries locally? I found this makes it possible to push the binaries somewhere. What tool should one use to host the binaries?

I do not know of any tools to host binaries locally. We usually recommend folks who need to do tests that require them to push these somewhere to host these binaries in GCS (https://cloud.google.com/storage/).

Closing as there is no action here that we are taking to improve this atm, but let me know if you have more ideas about how to make this experience better.
