### ISSUE TITLE
Bazel Container not working

### ISSUE THREAD

**Issue by boseabhishek** [bazelbuild/rules_docker#1283]
I have tried using Bazel container for **container_push** in both the ways (as mentioned here https://docs.bazel.build/versions/master/bazel-container.html)

### **Way 1**
Using Bazel container (docker run -it --entrypoint=/bin/bash l.gcr.io/google/bazel:0.17.1) and checking out the source code inside it and then running `bazel run --host_force_python=PY2 //cmd/bb_storage:bb_storage_container_push`,

**It works and pushes to docker registry.**

### **Way 2**
However, when I use in this way:

```
docker run \ 
-e USER="$(id -u)" \ 
-u="$(id -u)" \ 
-v /src/workspace:/src/workspace \ 
-v /tmp/build_output:/tmp/build_output \ 
-w /src/workspace \ l.gcr.io/google/bazel:0.17.1 \ 
--output_user_root=/tmp/build_output \ 
run --host_force_python=PY2 //cmd/bb_storage:bb_storage_container_push
```

**It fails with**

ERROR: 
```
/tmp/build_output/5d9ce43a1ac7b5311c5e3a18e17a7284/external/go_image_base/image/BUILD:6:1: SHA256 external/go_image_base/image/000.tar.gz.sha256 failed (Exit 1) sha256 failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256 external/go_image_base/image/000.tar.gz bazel-out/k8-fastbuild/bin/external/go_image_base/image/000.tar.gz.sha256
```

and also

`KeyError: 'getpwuid(): uid not found: 501`

I am using MacOS b.t.w. and hence resorted to use Bazel Container as go_image doesn't really work on Mac.

Is it something to do with permission on Mac with the build_output directory?

**Comment by nlopezgi** [comment]
Hi @boseabhishek,
We don't do support for the Bazel container in this repo, and this issue does not look like something specific to the Bazel container, more like an improper permissions setup.
It seems, however, you are also trying to use a very old version of Bazel (I know that's what's in the docs, but its a good idea to not copy blindly as these docs get out of date fast).
I should also note that documentation was written for linux and not ever tested on a mac.
It does seem like a permissions issue related to running docker con a mac. I have little experience on running docker on a mac, I'd recommend you look for forums/sites/docs about how to properly do volumes on docker on a mac. Closing as this issue does not really belong in this repo.

**Comment by boseabhishek** [comment]
Hi @nlopezgi  I am using Bazel 1.0.0 btw and it still doesn't work. (not a blind copy paste :))

Though, I used `goos` and `goarch` inside the `go_image` to make that working without Bazel container and it just does work on my Mac...

**Comment by nlopezgi** [comment]
as I mentioned, we dont really do support for the Bazel container running on Mac, so we cant really help you here. I'd recommend, again, you look for forums/sites/docs about how to properly do volumes on docker on a mac.

**Comment by nioann** [comment]
In case someone else stumbles upon this:

Updating to the 1.2.1 bazel image, removing the -u and -e params (i.e. running as the default root user in the docker image), works on a mac (with docker desktop 2.2.03) :

docker run -v <path-to-workspace-root>:/workspace   -v /tmp/build_output:/tmp/build_output   -w /workspace   l.gcr.io/google/bazel:1.2.1   --output_user_root=/tmp/build_output build <go_image_target>

If you create a new docker file and you add the user id, would probably work as well.

**Comment by davidvandebunte** [comment]
If you don't want to run as root on your local machine:
https://stackoverflow.com/a/70559256/622049
