### ISSUE TITLE
How can I specify the tag for my (nodejs) docker image?

### ISSUE THREAD

**Issue by tjarjoura** [bazelbuild/rules_docker#1296]
Hi all, I'm trying to figure out the best way to approach using these rules. I am using the "nodejs_image" rule and by default it creates the image with the tag $DIRECTORY_NAME:$TARGET_NAME but ideally I would want to version these images so would want something like $TARGET_NAME:$VERSION where $VERSION is something I can specify.

I looked through the code and documentation and I found a "tags" kwarg that is being passed to the nodejs_image rule, but it doesn't seem to do what I want. What am I missing here? Is there a way to do this, or is there another tagging approach I should be taking? It seems weird that the tag is just the target name.

**Comment by nlopezgi** [comment]
Use a container_push rule to set a custom name / tag using as base the nodejs image you currently have.
