### ISSUE TITLE
containerregistry python

### ISSUE THREAD

**Issue by cristifalcas** [bazelbuild/rules_docker#1297]
Hi,

Wanted to ask if is this still needed: https://github.com/bazelbuild/rules_docker/blob/941ac9b13a6008e730a75b56fc745ced9ee9917a/repositories/repositories.bzl#L67-L173

Currently it's putting six-1.9.0 module in the path added by rules_python, which breaks our kubernetes import, that needs six-1.10 at least.

Thank you

**Comment by smukherj1** [comment]
We use it in our tests. However, it should be possible to move this dependency from repositories.bzl to the `WORKSPACE` file so that users of the rule aren't forced to import it. Feel free to create a PR making this change and I'll be happy to review it.

**Comment by cristifalcas** [comment]
Fixed in https://github.com/bazelbuild/rules_docker/pull/1299
