### ISSUE TITLE
What's supposed to be inside go_image_base//image?

### ISSUE THREAD

**Issue by rodgarrison** [bazelbuild/rules_docker#1305]
Consider this build file (corrected include go_image command originally omitted as pointed out below):

`
load("@io_bazel_rules_docker//go:image.bzl", "go_image")
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@io_bazel_rules_docker//container:container.bzl", "container_image")

go_image(
    name = "bazel_docker_image",
    srcs = ["main.go"],
    pure = "on",
)
`
As far as I can tell the resulting go_image_base//image should include the task, libs (if pure off), some timezone, and other scaffolding. I only get a .tar with the task and nothing else. 

In addition the Bazel doc mentions:

"To address this, we publish variants of the distroless runtime images
tagged :debug, which are the exact-same images, but with additions
such as busybox to make debugging easier."

How?

**Comment by nlopezgi** [comment]
> Consider this build file:
> 
> `load("@io_bazel_rules_docker//go:image.bzl",` "go_image")
> load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
> load("@io_bazel_rules_docker//container:container.bzl", `"container_image")`
> 

Your example build file is missing an actual `go_image` target, but lets assume there is one there like this one: https://github.com/bazelbuild/rules_docker/blob/master/tests/container/go/BUILD#L20 with name `go_image`


> As far as I can tell the resulting go_image_base//image should include the task, libs (if pure off), some tinezone, and other scaffolding. I only get a .tar with the task and nothing else.
> 

I'm not really sure what your expectation is for the contents of `@go_image_base//image:image` (and if it is indeed to that target that you refer to), but that target is just the distroless base image that has very little installed and can be used as base for a `go_image` target that you declare yourself. So yes, it's contents are 'just' a tar that corresponds to the distroless base image, nothing else (everything needed to actually run a go_binary, libs, etc, gets created as a result of building concrete `go_image` target).

> In addition the Bazel doc mentions:
> 
> "To address this, we publish variants of the distroless runtime images
> tagged :debug, which are the exact-same images, but with additions
> such as busybox to make debugging easier."
> 
> How?

To use the debug image as base, all you would need to do is change the go_image target to have as base:
`    base = "@go_debug_image_base//image:image"`

I'm guessing the issue here is you are not properly declaring a go_image target anywhere, but let me know if I'm off.

**Comment by rodgarrison** [comment]
@nlopezgi thank you for responding so quickly. I confused the question by misquoting what was inside the src/BUILD.bazel file. It's missing a `go_image` command as you point out. I corrected it above and give the correct contents here:

`load("@io_bazel_rules_docker//go:image.bzl", "go_image")`
`load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")`
`load("@io_bazel_rules_docker//container:container.bzl", "container_image")`
`go_image(`
`    name = "bazel_docker_image",`
`    srcs = ["main.go"],`
`    pure = "on",`
`)`

The resulting .tar file contains just 14 files:

`Target //src:bazel_docker_image up-to-date:`
`  bazel-bin/src/bazel_docker_image-layer.tar`

*and the only non-zero sized file* is:

`r-xr-xr-x  0 0      0     1670384 Dec 31` `./app/src/bazel_docker_image.binary.runfiles/__main__/src/darwin_amd64_pure_stripped/bazel_docker_image.binary`

inside only one directory `/app/....`. This .tar file is considerably different than what Bazel made here:

`find -H bazel-bin -type f -name "*tar.gz*"`
`bazel-bin/external/go_image_static/image/000.tar.gz.nogz.sha256`
`bazel-bin/external/go_image_static/image/000.tar.gz.nogz`

This .tar file (presumably from the default base go_image) seems to contain a distroless collection of over 2000 files including /usr/share, /etc/passwd, /etc/... and so on. But it does not contain the task bazel-bin/src/bazel_docker_image-layer.tar has.

I thought bazel-bin/src/bazel_docker_image-layer.tar would contain the task (which it does) plus everything in bazel-bin/external/go_image_static/image/000.tar.gz.nogz e.g. the union. Hence my original question: what's supposed to be in there? 

Once that's in place I can use container images to layer up from that to a complete images.

One off note: no .tar file contained /usr/lib/libSystem.B.dylib ... which Darwin seems to need ... but that's an aside at this point.

**Comment by nlopezgi** [comment]
> The resulting .tar file contains just 14 files:
> 
> `Target //src:bazel_docker_image up-to-date:`
> ` bazel-bin/src/bazel_docker_image-layer.tar`
> 
> _and the only non-zero sized file_ is:
> 
> `r-xr-xr-x 0 0 0 1670384 Dec 31` `./app/src/bazel_docker_image.binary.runfiles/__main__/src/darwin_amd64_pure_stripped/bazel_docker_image.binary`
> 
> inside only one directory `/app/....`. 

So what you are asking are the implementation details of this rule.
The go_image rule defines a go_binary target here: https://github.com/bazelbuild/rules_docker/blob/master/go/image.bzl#L108

and then creates an container_image here: https://github.com/bazelbuild/rules_docker/blob/master/go/image.bzl#L123
which includes the binary produced by the go_binary rule 

> This .tar file is considerably different than what Bazel made here:
> 
> `find -H bazel-bin -type f -name "*tar.gz*"`
> `bazel-bin/external/go_image_static/image/000.tar.gz.nogz.sha256`
> `bazel-bin/external/go_image_static/image/000.tar.gz.nogz`
> 
> This .tar file (presumably from the default base go_image) seems to contain a distroless collection of over 2000 files including /usr/share, /etc/passwd, /etc/... and so on. But it does not contain the task bazel-bin/src/bazel_docker_image-layer.tar has.

I think the problem here is your assumption here that `bazel-bin/external/go_image_static` is "presumably from the default base go_image"
The contents in `bazel-bin/external/go_image_static` are the files pulled for the @go_debug_image_base//image:image, which is declared [here](https://github.com/bazelbuild/rules_docker/blob/master/go/image.bzl#L50). Which is NOT the one that is used by default by `go_image `

> 
> I thought bazel-bin/src/bazel_docker_image-layer.tar would contain the task (which it does) plus everything in bazel-bin/external/go_image_static/image/000.tar.gz.nogz e.g. the union. Hence my original question: what's supposed to be in there?

If that is what you want, then probably, as I indicated in my first message, what you need to do is set:
`base = "@go_debug_image_base//image:image"`
in your `go_image` target

> 
> Once that's in place I can use container images to layer up from that to a complete images.
> 
> One off note: no .tar file contained /usr/lib/libSystem.B.dylib ... which Darwin seems to need ... but that's an aside at this point.

iiuc, you are referring to a lib that is needed for running a go taget on Mac. It seems that you are perhaps trying to use go_image from a Mac? If so, please see https://github.com/bazelbuild/rules_docker/issues/943 

Closing for now, but please let me know if you need me to reopen for any reason.

**Comment by rodgarrison** [comment]
@nlopezgi I read through your reply. Thanks for that. I regret to inform that adding a base command simply did not work. I surmise there's a problem with the WORKSPACE file? The exact tree I am working [working on is here](https://github.com/rodgarrison/test4)

**Comment by nlopezgi** [comment]
Can you expand what you mean by "did not work"? Does your go image not have the files you expect when you do 'Bazel run'. Or what is your expectation? Are you running this target from a Mac or from a Linux env? Please post a bit more detail...

**Comment by nlopezgi** [comment]
So I think what you're seeing as being off is that you're trying to open the tar files produced by these rules directly and expecting them to have some contents according to how you would expect things to be layered. The issue with that approach is those tars are implementation details and dealing with them requires deep knowledge of how docker and these rules work. Also, that's not really a good way to understand what's in the images produced by these rules. You should really not need to ever touch or check out the contents of the tar files in bazel-bin or bazel-out. If you want to understand what's in the image, please use a `container_test` ([example](https://github.com/bazelbuild/rules_docker/blob/master/tests/container/go/BUILD#L60)) or some other mechanism to inspect images. 

Also, please let me know if you are or not using a Mac. From your repo it seems like you are, and then we do have a problem here that will be hard to resolve, please see #943 as your use case might just not be supported with these rules!

**Comment by rodgarrison** [comment]
The [README](https://github.com/rodgarrison/test4) exactly answers questions as to,

- what's in WORKSPACE, BUILD
- what appears on stdout
- fact that it is a mac
- contents of .tar file (which after all is provided by Bazel as the result of the go_image target)
- etc.

Please follow that link.

I go back to my original question: Bazel provides container base-like functionality (good!) but the doc is unclear as to what's supposed to result. To resolve this I am asked what I think is supposed to happen or want to happen, which is bringing us into a circular conversation b/c I am not sure what or how Bazel does with base images. 

The first section in the README shows what appears on stdout. Bazel makes clear it produced:

Target //src:myimage up-to-date:
  bazel-bin/src/myimage-layer.tar        <------------------- this

So I  look in that .tar file. I see my app. That part is good. But I do not see busybox, timezone etc. etc. etc. files that we can easily see bazel-bin/external.

Look, the point of a base image is to union two sets of files together. the go_image provides the app. the base image is supposed (AFAIK) the base set of files. go_image should produce the union, no?

**Comment by nlopezgi** [comment]
The issue here is you're trying to understand what's on the images by looking at the tar files in bazel-bin, that is not the right approach.
Go_image produces an image that is layered on top of the base image, not a union (which is not really a concept that makes sense in docker afaik). This is to say, You will not find a tar file like the one you're looking for, but if you run the container or use container_test to see it's contents you'll see the contents of the base image there.

Also, go_image does not work on a Mac, so you'll have to get around that first if you want to do anything useful with go_image.

**Comment by rodgarrison** [comment]
Thank you for responding so quickly. Now we're getting somewhere. I will change to RH Linux and redo this test. Now, for the record, when one runs `bazel build //src:myimage` and Bazel tells me it produced `bazel-bin/src/myimage-layer.tar` ... well, is this in fact the docker image Bazel produced for the target `//src:myimage` or not? If I don't look there ... then where/what? Where is the image produced by `bazel build //src:myimage`? TIA

**Comment by nlopezgi** [comment]
The image is made up of a manifest and several tar files, the files are spread out over multiple directories in bazel-bin depending on the does of your image. 
To run the image do "Bazel run ..." for your target. You can also do "docker load <main tar file of your target> to load the image into the registry.
If you want to explore the contents of the image, run it or load it, or use a container_test or some other tools specifically made for that purpose.
I strongly advise against trying to read/navigate the tar/manifest files yourself unless you're a docker expert.

**Comment by rodgarrison** [comment]
You make valid points about not delving into implementation details of how Bazel does its work. And I absolutely agree there. I did not bother mention this earlier, but the fact the .tar file Bazel tells me it made `bazel-bin/src/myimage-layer.tar` ... is a layer ... and is already suggestive that it's merely one layer of a yet incomplete docker image.

So we're still circling around this problem. The bottom line here is that one of these ought to be true. This is stated with the goal that Bazel makes a valid Docker image:

* `bazel build //src:myimage` produces the image --- it tells explicitly that's `bazel-bin/src/myimage-layer.tar`. If this is true I can use docker to import this .tar file as an image and I'd be done

--OR---

* `bazel build //src:myimage` does all the correct work but the .tar it tells it makes `bazel-bin/src/myimage-layer.tar` is spurious information. And in fact I should issue another Bazel command to tell Bazel to put the image into the Docker repo whereupon it'd collect all the layers as befits its internal implementation resulting in a complete, final image

We now return to the original question: what's supposed to be the correct, final image? Bazel was instructed to make:

```
go_image(
    name = "myimage",
    srcs = ["//src:main.go"],
    pure = "on",
    base = "@go_debug_image_base//image:image",
    out = "testapp",
)
```
e.g. a statically linked task unioned with "@go_debug_image_base//image:image". If, after the build completes we look at bazel-bin for .tar files we can see:

```
bazel-bin/external/go_debug_image_base/image/000.tar.gz.nogz
bazel-bin/external/go_debug_image_base/image/002.tar.gz.nogz
bazel-bin/external/go_debug_image_base/image/001.tar.gz.nogz
bazel-bin/src/image-layer.tar
```

`bazel-bin/src/image-layer.tar` contains the statically linked app. The .tar files in `bazel-bin/external` appear contain the busybox, timezone, and other files. I had hope to in the way I describe above to get an image that is the union of all those files. 

Unless this is true, I completely fail to see what the value-add of the `base` attribute in a go_image command.

And noted: none of this works fully on MacOS right now -- which is no big deal.

**Comment by nlopezgi** [comment]
man, this is getting a bit circular but, lets keep trying:

> * `bazel build //src:myimage` produces the image --- it tells explicitly that's `bazel-bin/src/myimage-layer.tar`. If this is true I can use docker to import this .tar file as an image and I'd be done

Yes this is true, you can run `docker import "tar file for your target"` and that will load the image into your registry



> * `bazel build //src:myimage` does all the correct work but the .tar it tells it makes `bazel-bin/src/myimage-layer.tar` is spurious information. And in fact I should issue another Bazel command to tell Bazel to put the image into the Docker repo whereupon it'd collect all the layers as befits its internal implementation resulting in a complete, final image

This is also true, you can do `bazel run "your target"` and that will load the image into the registry and run it.

> I had hope to in the way I describe above to get an image that is the union of all those files.

We've been struggling to get through this expectation of yours from the beginning, there is no such union of files anywhere. I recommend you read a bit more about how docker layers work (I can point you to some references, but you can probably find some good ones on your own). This will allow you to understand that the image you are producing with go_image target is just layered on top of the base image. This layering is only effectively manifested in a filesystem that contains all files when the image is loaded, and it is not reflected in the separate tar files in the way you seem to expect. Specifically, there is no single tar file that ever contains the base image plus the top layers (there is no union, please, lets get this very clear). That would be a totally wasteful implementation. In fact, the tar files in `bazel-bin/external` for your base, are the ones that get loaded when you load the image using `bazel-bin/src/image-layer.tar`. Hope this helps, but please do check a bit more about docker layers before pushing any more the idea that you don't see the union of all files anywhere.

**Comment by rodgarrison** [comment]
Thank you for all your patience. I think we're at "message received" over here. Here's my summary then of the takeaways:

* go_image functionality not fully implemented on MacOS. No big deal
* Bazel does not union .tar files, and this perspective is just wrong to start with. One should not be focused on .tar files. As such the first option I ref'd two comments above that as Bazel tells me it made `bazel-bin/src/myimage-layer.tar` is spurious. There was never going to be a single unioned .tar file now or at anytime.
* Bazel (helpfully) supports base images, however, the correct way to interact with that image is via the second option I ref'd two comments above: we issue another Bazel command to run the image as a container or container_push it into Docker whereupon the fully assembled image would result.

Now, I have worked with Docker apart from Bazel and am familiar with multi-builds, and how one can build up a final image ... Bazel will also do this which is the whole point of the `base` attributed in a `go_image` command ... however the correct way to do this is by not looking at .tar files but rather by issuing additional Bazel commands.

I will test my understanding on this on Linux.

Regards-
