### ISSUE TITLE
Custom credential helper toolchain

### ISSUE THREAD

**Issue by mariusgrigoriu** [bazelbuild/rules_docker#1323]
rules_docker allows us to configure the docker toolchain and set custom credentials. Seems it would be a nice feature to set credentials helpers too so you don't need to have docker desktop installed on the system.

**Comment by nlopezgi** [comment]
Hi @mariusgrigoriu ,
thanks for creating this feature request. We would be happy to receive contributions to implement it. Let me know if you need guidance or advice as to how to best implement/test this (I have not given it much thought, but would be happy to help).
