### ISSUE TITLE
document docker_build `debs` caveats

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_docker#133]
Just moving bazelbuild/bazel#2812 here

**Comment by mattmoor** [comment]
FTR,  I left this on the old repo when I moved everything else because this caveat is driven by `build_tar.py` in Bazel core's package archive.

**Comment by damienmg** [comment]
build_tar is just ready archive image, it could return information (e.g. --fails_if_script) but that's not it's goal. We have to decide what docker_build should do first, then maybe do change on build_tar.

**Comment by pcj** [comment]
Closing due to age/inactivity.
