### ISSUE TITLE
Can't pip_import (or pip3_import) into py_image  with modified base

### ISSUE THREAD

**Issue by jasonh-logic2020** [bazelbuild/rules_docker#1336]
Hello. 

I am trying to build a python image with python 3.7. I managed to graft the [build of python3_debian10 from distroless](https://github.com/GoogleContainerTools/distroless/blob/master/experimental/python3/BUILD) into my repo. The image builds with it, and I can verify that the container runs with it using ```print (sys.version)```, which returns ```3.7.3 (default, Apr  3 2019, 05:39:12) ```

However, I cannot figure out how to get ```@rules_python```'s pip_import (or pip3import) to install dependencies.

As you can see from the snippets below, I am versioned up on rules_docker and up all the way to the latest git on rules_python.

When I ```bazel run [app name omitted]:image```, I can see the pip libraries being fetched, but my app fails because they are not found. The command log (see link below) shows them being fetched    once per import statement across the many files in my library although my redacting might obscure it.  I have no idea why that is.

n.b.: the WORKSPACE as excerpted below is set up to use ```pip3_import``` but I've tried it with regular ```pip_import``` with no change in the outcome. 

Any help would be most welcome. I'm happy to provide any relevant resources.

###########################################################

Here is a [link to a redacted version of my command log](https://paste.centos.org/view/602ab996)

the python part of my WORKSPACE is as follows:
```
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/archive/38f86fb55b698c51e8510c807489c9f4e047480e.tar.gz",
    strip_prefix = "rules_python-38f86fb55b698c51e8510c807489c9f4e047480e",
    sha256 = "c911dc70f62f507f3a361cbc21d6e0d502b91254382255309bc60b7a0f48de28",
)

load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

load("@rules_python//python:pip.bzl", "pip_repositories")
pip_repositories()

load("@rules_python//python:pip.bzl", "pip3_import")

pip3_import(
    name = "lib_[library name omitted]",
    requirements = "//lib/[library name omitted]:requirements.txt",
)

load("@lib_[library name omitted]//:requirements.bzl", "pip_install")
pip_install()

# Download the rules_docker repository at release v0.13.0
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "df13123c44b4a4ff2c2f337b906763879d94871d16411bf82dcfeba892b58607",
    strip_prefix = "rules_docker-0.13.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.13.0/rules_docker-v0.13.0.tar.gz"],
)
```

the important part of my BUILD where I define my image is:
```
py_binary(
    name = "main",
    deps = ["//lib/[library name omitted]"],
    srcs = ["main.py"]
)

py_image(
    name = "image",
    srcs = ["main.py"],
    base = "//experimental/python3:python3_debian10",
    deps = [
        "//lib/[library name omitted]",
    ],
    main = "main.py",
)
```

the important part of the library's BUILD is as follows:
```
load("@lib_[library name omitted]//:requirements.bzl", "requirement")

py_library(
    name = "[library name omitted]",
    srcs = glob (["*.py"], exclude=["test_*"]),
    deps = [
        requirement("[requirement name omitted]"),
              .
              .
              .
[a bunch of other requirements omitted]
              .
              .
              .
    ],
)
```

**Comment by nlopezgi** [comment]
Unfortunately, afaik py_image / py3_image rules are not really compatible with using pip_import, as these import rules pull versions of the deps that are compatible with the host (where Bazel runs) and not with the exec environment (the docker container). Significant work would be needed (probably both on the import rules as well as here) to get these use cases working (again, afaik) and there is no plan to work on this afaik. Closing for now but let me know if you want me to reopen for some reason.

**Comment by jasonh-logic2020** [comment]
I accept that this angle for getting external libraries is not currently supported and is unlikely to be supported any time soon. 

Is there any workaround for getting a python 3.x container with a ```requirments.txt ``` to build with bazel? I can't be the only person who has this problem.

**Comment by nlopezgi** [comment]
The best workaround (afaik) is to run Bazel inside a container that is similar to the one you want to produce (wrt OS, runtime libraries, etc)
