### ISSUE TITLE
go_containerregistry tarball write loads whole contianer .tar into memory

### ISSUE THREAD

**Issue by DhashS** [bazelbuild/rules_docker#1349]
I've observed this error coming from rules_docker

> ERROR: /home/dhash/synced/radix/monorepo/device_drivers/tf-exactive/jvm/BUILD:15:1: 
> JoinLayers device_drivers/tf-exactive/jvm/foo-jni-cpp-img.tar failed (Exit 2) join_layers failed: error executing command bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/join_layers/linux_amd64_stripped/join_layers '--output=bazel-out/k8-fastbuild/bin/device_drivers/tf-exactive/jvm/foo-jni-cpp-img.tar' ... (remaining 6 argument(s) skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> fatal error: runtime: out of memory
> 
> runtime stack:
> runtime.throw(0x59b939, 0x16)
> 	GOROOT/src/runtime/panic.go:774 +0x72
> runtime.sysMap(0xc240000000, 0x200000000, 0x6dfd18)
> 	GOROOT/src/runtime/mem_linux.go:169 +0xc5
> runtime.(*mheap).sysAlloc(0x6c8320, 0x200000000, 0x53b39a, 0xd2a19)
> 	GOROOT/src/runtime/malloc.go:701 +0x1cd
> runtime.(*mheap).grow(0x6c8320, 0x100000, 0xffffffff)
> 	GOROOT/src/runtime/mheap.go:1255 +0xa3
> runtime.(*mheap).allocSpanLocked(0x6c8320, 0x100000, 0x6dfd28, 0x100000081)
> 	GOROOT/src/runtime/mheap.go:1170 +0x266
> runtime.(*mheap).alloc_m(0x6c8320, 0x100000, 0x400101, 0xc0004b2148)
> 	GOROOT/src/runtime/mheap.go:1022 +0xc2
> runtime.(*mheap).alloc.func1()
> 	GOROOT/src/runtime/mheap.go:1093 +0x4c
> runtime.(*mheap).alloc(0x6c8320, 0x100000, 0x7fd7d1010101, 0x436915)
> 	GOROOT/src/runtime/mheap.go:1092 +0x8a
> runtime.largeAlloc(0x1fffffe00, 0xc000010101, 0xc000000180)
> 	GOROOT/src/runtime/malloc.go:1138 +0x97
> runtime.mallocgc.func1()
> 	GOROOT/src/runtime/malloc.go:1033 +0x46
> runtime.systemstack(0xc0004bc480)
> 	GOROOT/src/runtime/asm_amd64.s:370 +0x66
> runtime.mstart()
> 	GOROOT/src/runtime/proc.go:1146
> 
> goroutine 1 [running]:
> runtime.systemstack_switch()
> 	GOROOT/src/runtime/asm_amd64.s:330 fp=0xc0000bcfe8 sp=0xc0000bcfe0 pc=0x457440
> runtime.mallocgc(0x1fffffe00, 0x5580e0, 0x1, 0x0)
> 	GOROOT/src/runtime/malloc.go:1032 +0x895 fp=0xc0000bd088 sp=0xc0000bcfe8 pc=0x40d855
> runtime.makeslice(0x5580e0, 0x1fffffe00, 0x1fffffe00, 0xc1bc469e00)
> 	GOROOT/src/runtime/slice.go:49 +0x6c fp=0xc0000bd0b8 sp=0xc0000bd088 pc=0x44275c
> bytes.makeSlice(0x1fffffe00, 0x0, 0x0, 0x0)
> 	GOROOT/src/bytes/buffer.go:229 +0x77 fp=0xc0000bd120 sp=0xc0000bd0b8 pc=0x4c0167
> bytes.(*Buffer).grow(0xc0000bd248, 0x200, 0x40000000)
> 	GOROOT/src/bytes/buffer.go:142 +0x15b fp=0xc0000bd170 sp=0xc0000bd120 pc=0x4bfb3b
> bytes.(*Buffer).ReadFrom(0xc0000bd248, 0x7fd7d853b118, 0xc00000f920, 0x40a31b, 0x6c0f60, 0x5684c0)
> 	GOROOT/src/bytes/buffer.go:202 +0x4b fp=0xc0000bd1e0 sp=0xc0000bd170 pc=0x4bff5b
> io/ioutil.readAll(0x7fd7d853b118, 0xc00000f920, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	GOROOT/src/io/ioutil/ioutil.go:36 +0x100 fp=0xc0000bd280 sp=0xc0000bd1e0 pc=0x4c1900
> io/ioutil.ReadAll(...)
> 	GOROOT/src/io/ioutil/ioutil.go:45
> github.com/google/go-containerregistry/pkg/legacy/tarball.MultiWrite(0xc0000bd7a8, 0x5c96e0, 0xc00028e038, 0x0, 0x0)
> 	external/com_github_google_go_containerregistry/pkg/legacy/tarball/write.go:260 +0xa5b fp=0xc0000bd670 sp=0xc0000bd280 pc=0x531bcb
> main.writeOutput(0x7ffe1f649ace, 0x4d, 0xc000084780, 0xc0000847b0, 0xc000014760, 0x1, 0x1, 0xc000012200, 0x2, 0x2, ...)
> 	external/io_bazel_rules_docker/container/go/cmd/join_layers/join_layers.go:111 +0x8e3 fp=0xc0000bddf0 sp=0xc0000bd670 pc=0x53ad33
> main.main()
> 	external/io_bazel_rules_docker/container/go/cmd/join_layers/join_layers.go:142 +0x5db fp=0xc0000bdf60 sp=0xc0000bddf0 pc=0x53b39b
> runtime.main()
> 	GOROOT/src/runtime/proc.go:203 +0x21e fp=0xc0000bdfe0 sp=0xc0000bdf60 pc=0x42f3ae
> runtime.goexit()
> 	GOROOT/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000bdfe8 sp=0xc0000bdfe0 pc=0x459511
> Target //device_drivers/tf-exactive/jvm:foo-msvc-runtime-container failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 126.418s, Critical Path: 126.32s

Reading the stack trace, you can narrow it down to the MultiWrite function in go_containerregistry, which contains this comment.

> 			// Reads the entire uncompressed blob into memory! Can be avoided
> 			// for some layer implementations where the uncompressed blob is
> 			// stored on disk and the layer can just stat the file.
> 			uncompressedBlob, err := ioutil.ReadAll(u)

AFAICT, the blob that i'm depending on does exist on disk, and should not have to be fully read into memory. How can I make this happen?

I'm trying to use a container_run_and_execute rule, and it's strange behavior (at least to me) that it really needs to read the whole container into memory in order to run.

**Comment by DhashS** [comment]
More info:

- I had plenty (2G RAM remaining) on my personal laptop (16G total).
- changing the bazel `--ram_utilization_factor` had no discernible effect, but the command was long-running so it's possible I missed something. 
- Moving to another machine with 32G RAM solves the issue. 
- My image totals 7.9G according to `docker images`

**Comment by smukherj1** [comment]
This is a known issue as documented in the comment [here](https://github.com/google/go-containerregistry/blob/e4d5ca269fc3b63d12f77823409b355d3344d3df/pkg/legacy/tarball/write.go#L257). Avoiding this will require changing the `v1.Layer` interface in go-containerregistry that exposes the ability to obtain the size of the uncompressed blobs. The tarball writer can implement this method efficiently by returning the blob metadata without actually loading the entire blob into memory. So if you're interested in trying to fix this, I would start with updating the `v1.Layer` interface in go-containerregistry followed by updating the tarball writer to implement the new method without actually loading the entire blob into memory.

FYI @jonjohnsonjr

**Comment by jonjohnsonjr** [comment]
Here's what I had in mind for this: https://github.com/google/go-containerregistry/pull/655

If you were to implement something similar to this: https://github.com/bazelbuild/rules_docker/blob/004b0138566ea8dd20363bb7634b25c333389b7b/container/go/pkg/compat/image.go#L78-L85

But for `os.Stat(l.uncompressedTarball)` called `UncompressedSize`, the in-memory buffering would just go away.
