### ISSUE TITLE
flip bazel flag --nolegacy_external_runfiles

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_docker#1350]
For more context see the links

https://github.com/bazelbuild/rules_docker/pull/1346#pullrequestreview-338261931
https://docs.bazel.build/versions/master/command-line-reference.html#flag--legacy_external_runfiles
https://github.com/bazelbuild/rules_nodejs/blob/master/common.bazelrc#L60

**Comment by alexeagle** [comment]
Never mind, not going to do this right now, the test breakages are too much work to understand
