### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jolarsso** [bazelbuild/rules_docker#136]
I'm working on a project where we are evaluating using bazel for building and also running some of our services in the cloud (Docker/Kubernetes). The problem is that enough of our developers are running Windows that we want that to work also before deciding on a transition. I've been tasked with trying it out on Windows 7 and possibly also Windows 10 down the road.

I have followed the installation instructions for bazel on docs.bazel.build and it's dependecies for Windows and made sure I have 64-bit versions of everything.

I initially thought my problems where related to my enviroment and how it all was installed so I have tried everything including reinstalling everything by downloading all dependencies by hand and installing (not using choclatey like I did on the first try) and the exact same problem still remains. I narrowed the problem down to the rules_docker rule and tried to run the simplest possible example I could find to use it.

When I run the example borrowed from the issue reported [here](https://github.com/bazelbuild/rules_docker/issues/116). I run just the first part of the several steps process by executing:

`bazel build //:hello.tar`

And I get this output:

____Loading

 package: @local_config_cc//
____Loading complete.  Analyzing...
____Loading package: @io_bazel_rules_docker//docker
ERROR: E:/projects/rules_docker/BUILD:4:1: no such package '@helloworld//image': Pull command failed: 
java.io.IOException: CreateProcess(): %1 is not a valid Win32 application.
 (C:/msys64/tmp/_bazel_jonas.larsson/vs4nb3vm/external/puller/file/puller.par --directory C:/msys64/tmp/_bazel_jonas.larsson/vs4nb3vm/external/helloworld/image --name index.docker.io/library/hello-world:latest) and referenced by '//:hello'.
ERROR: Analysis of target '//:hello.tar' failed; build aborted.
____Elapsed time: 22,834s

It seems to me that the rule code expects the "puller.par" file to be a Win32 executable when it is in fact a bundle of code that needs to be executed with Python? In fact when I call the "puller.par" file with the python executable manually (and with the same parameters as in the output above) it executes. Silently with no output. But it executes.

bazel installed on Ubuntu and MacOS runs this same project just fine.

Any ideas on what my problem is? I've tried it all. No Python installed. Python for 64-bit Windows in the path. pacman installed python2 or python3 in a msys2 bash shell. All with the same result. It does not matter if I run from a Windows CMD prompt or a msys2 mintty bash terminal. The problem remains the same.

I have an old Windows 7 install on my own machine so I am thinking about also trying this on a machine with a fresh install of Windows 10 Pro to see if the problem remains.

I'm still not even sure if this is a bug or if there is something seriously wrong with my environment.

Any thoughts?

**Comment by mattmoor** [comment]
Roping in some experts @damienmg (Bazel) @duggelz (Python/PAR).

TBH, I was under the impression that Bazel's Windows support was still pretty immature (perhaps that has changed, as I know a lot of work is being done here).  But I haven't spent any time yet investigating compat issues with `rules_docker` on Windows as a result.

@damienmg Is Windows support in a state that we should start looking at this?

@duggelz Are you aware of any issues invoking PAR files on Windows?

**Comment by jolarsso** [comment]
No wonder there might be potential compatibility problems if you haven't been testing on Windows yet :) The Windows version used to be experimental but is now in beta since May I think so you might have to add that to your testing. And yes, the Windows support definately still feels immature.

**Comment by damienmg** [comment]
For the record we have Windows machine on CI.bazel.io for testing, tagged
windows-x86_64. @meteorcloudy should be able to tell more about Bazel's
Python support on windows but I know that py_binary generate a zip file
ready for consumption (no symlink) and you have to use the rlocation trick
because we do not have runfiles tree there.

**Comment by jolarsso** [comment]
FYI. I have now tested compiling/running some of the official example projects (which I should have done first really) and java native/python/CC++ works fine on my install.

**Comment by mattmoor** [comment]
What happens if you just download and run [this](https://github.com/bazelbuild/rules_docker/blob/master/docker/docker.bzl#L44-L45)?

I'm wondering if it explodes on a similar error or displays usage...

I'm hoping for [this](https://github.com/google/containerregistry/blob/master/tools/docker_puller_.py#L71)

**Comment by jolarsso** [comment]
Hmm. Not sure what you mean. I'm very new to this whole bazel business. Isn't that piece of code already included in the rule I am running in my example above? Or do you mean to run just that file in isolation in some way?

**Comment by mattmoor** [comment]
We fetch that binary `puller.par` from GCS, verify it's checksum and use that to download Docker images.  I'm wondering what error it gives you if you download it and just try to run it on Windows.

If `puller.par` spits out an error, what about `python puller.par`?

**Comment by jolarsso** [comment]
Ah. Ok. 

Downloading and executing puller.par directly currently gives me this (as you where hoping for):

$ ./puller.par
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File ".\puller.par\__main__.py", line 83, in <module>
  File ".\puller.par\__main__.py", line 57, in main
Exception: --name and --directory are required arguments.

And running it with the python executable gives the exact same thing:

$ python puller.par
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "puller.par\__main__.py", line 83, in <module>
  File "puller.par\__main__.py", line 57, in main
Exception: --name and --directory are required arguments.

**Comment by mattmoor** [comment]
Ok, so the good news is that it sounds like it is a problem with how we're having Bazel invoke the binary, and not a portability problem.  I'll take a look at it with fresh eyes after lunch :)

thanks for trying this out.

**Comment by jolarsso** [comment]
No problem. Where I am it's Friday night and the work-week is over :)

**Comment by mattmoor** [comment]
Hmm, I see nothing obvious (the rule literally just invokes the PAR file, presumably as you do in your first invocation).  Hopefully some element of the error makes sense to the Bazel folks pulled in above...

**Comment by jolarsso** [comment]
I have now verified that I have no issues running the examples in https://github.com/bazelbuild/bazel/tree/master/examples

I have tried c++, python and java-native with no issues.

**Comment by meteorcloudy** [comment]
@jolarsso On Windows, you cannot run a python par file directly from native console(cmd.exe) or when creating a new process, so at https://github.com/bazelbuild/rules_docker/blob/master/docker/pull.bzl#L40, you'll need to add `python.exe` as the first argument.

```
  args = [
      "<path/to/python/binary>",
      repository_ctx.path(repository_ctx.attr._puller),
      "--directory", repository_ctx.path("image")
  ]
```

**Comment by dslomov** [comment]
What @meteorcloudy said re particular issue. 

Replying to @mattmoor @jolarsso: Windows support in Bazel is what we call a "beta" state. There are still many issues, but several projects use it so far, and we encourage you to try as well. We will try to fix any issues promptly.
A word of caution though: you cannot expect your build to "just work" on Windows. We can not - and do not - intend to paper over all the differences between Unix and Windows, and between various tools on those platforms (as you discovered here when you realized that Windows cannot run .par files directly)

**Comment by mattmoor** [comment]
@meteorcloudy @damienmg Isn't there some magic Bazel way to access the Python interpreter path?

**Comment by jolarsso** [comment]
I don't expect anything when it comes to Windows support! It usually comes a distant third when it comes to open source multi-plattform development tools so that is to be expected :)

Regarding execution of the "puller.par" file. As you see above it seems to be recognized just fine without passing it to the python interpreter **when executing it from msys2 mintty bash**. But when executed from a pure Windows cmd prompt I get the "Windows can't open this file" dialog.

Yet I get exactly the same error message regardless of where the example bazel build script using the rules_docker is run...

**Comment by dslomov** [comment]
Bazel will not execute your .par through bash, regardless of how you started Bazel

**Comment by mattmoor** [comment]
@jolarsso That makes more sense, I'll just run these through `python` explicitly in `rules_docker`.

**Comment by mattmoor** [comment]
Back to my question above...  How do I point to python in a portable way?

[context](https://github.com/bazelbuild/rules_docker/pull/137)

**Comment by meteorcloudy** [comment]
@mattmoor I don't think there is currently a way to access python binary through skylark. But can we expose it to skylark, @dslomov?
What TensorFlow did is setting a `PYTHON_BIN_PATH` environment variable by themselves. https://github.com/tensorflow/tensorflow/blob/master/configure.py#L186

**Comment by mattmoor** [comment]
I finally found the thing that led me to believe Bazel knows the version of Python the user expects us to use:
```shell
$ bazel help build
...
Version options, for selecting which version of other tools will be used:
...
  --python2_path (a string; default: "python")
  --python3_path (An option for python3 path; default: "auto")
  --python_path (a string; default: "python")
  --python_top (a build target label; default: see description)
...
```

To ask a more basic question, does the Windows Bazel CI machine have `python` installed?  Is there a reason it isn't on the path?  Is there a way in Skylark to access these flags?

**Comment by jolarsso** [comment]
Just a quick heads up. All of these options might have existed at some point but seem to be deprecated. I get this when running:

![bild](https://user-images.githubusercontent.com/26574755/30331180-5f4e6ac6-97d7-11e7-8bbc-cc0c46e08335.png)

**Comment by mattmoor** [comment]
It probably needs to be after `build`, e.g. 
```shell
$ bazel build --python2_path
ERROR: Expected value after --python2_path
```

**Comment by jolarsso** [comment]
Yet when i run:

`bazel help startup_options | grep python`

I get nothing.

Looking at the Windows install page i suddenly realize that part of the installation instructions include setting an environment variable "BAZEL_PYTHON" to point to a python executable. So at this point couldn't that be used (if set) in the rules_docker code to locate the interpreter?

**Comment by mattmoor** [comment]
I'll give that a shot when I get in.

**Comment by mattmoor** [comment]
Not sure how exactly to access `BAZEL_PYTHON` in Skylark, so suggestions would be appreciated.  It's also worth pointing out that Tensorflow is using the flags I mentioned...  See [here](https://github.com/tensorflow/tensorflow/blob/master/configure.py#L238-L242).

**Comment by mattmoor** [comment]
Based on a quick hangouts conversation I'm going to assign this to @damienmg to follow up with the proper Bazel folks on what the expectations are for folks who want to support Skylark rules on Windows.

Once the guidance from the Bazel team is clearer on how folks are expected to do this, please assign it to me and I can take another look.

**Comment by dslomov** [comment]
@jolarsso re python_path options: check out `bazel help build | grep python`. These options are build options, not startup options.

@mattmoor in your repository rules you will need to somehow discover where python.exe is.
You can access BAZEL_PYTHON variable or look in the PATH (use `repostiory_ctx.os.environ` for the former or `repository_ctx.which` for the latter). 
(We should consider unified mechanism for Python and other interpreters discovery in repository rules but that will take some time; on Unix/Linux we just assume these are in PATH)

**Comment by mattmoor** [comment]
@dslomov Neither of these yields a valid python interpreter on the Bazel CI Windows node.  [see here](http://ci.bazel.io/blue/organizations/jenkins/PR%2Frules_docker/detail/rules_docker/117/pipeline/25)

**Comment by dslomov** [comment]
@mattmoor Interesting. This is what we do https://github.com/bazelbuild/bazel/blob/d852e484d8114829ad2d7a98f075a823889f5469/tools/cpp/windows_cc_configure.bzl#L92, this works on or CI machines.

**Comment by dslomov** [comment]
Commented on your pull request. (I think if you are committed to making rules_docker work on Windows, you need to get Windows machines to test and debug changes locally)

**Comment by mattmoor** [comment]
@dslomov Ack, this was mostly a smoke test to see what it would take to get the repo to just build.  Given that the main unit testing is written in bash, I fully expect to need a Window Bazel VM to fully add Windows support.

**Comment by mattmoor** [comment]
An approach based on what @dslomov gives, and (for outside of `WORKSPACE`) what @damienmg suggested on chat (to avoid needing to pipe the environment through to `BUILD` actions) seems to work (I at least am past the `python` not found issues).

I think it would be immensely useful to have a `ctx.py_action` method to avoid the need for these hacks, I'll probably encapsulate this myself as `py_action(ctx, *args, **kwargs)`.

**Comment by duggelz** [comment]
I've done zero work to make .par files work on Windows.  But, if you have a new enough version of Python installed (Python 3.3+), and you checked the [Python Launcher for Windows](https://www.python.org/dev/peps/pep-0397/) box while installing, and if we renamed the .par file to the magic file extension `.pyz`, it might work?  I'll go home and play around on my Windows machine.

**Comment by dslomov** [comment]
On Sep 13, 2017 00:26, "Douglas Greiman" <notifications@github.com> wrote:

I've done zero work to make .par files work on Windows. But, if you have a
new enough version of Python installed (Python 3.3+), and you checked
the Python
Launcher for Windows <https://www.python.org/dev/peps/pep-0397/> box while
installing, and if we renamed the .par file to the magic file extension .pyz,
it might work? I'll go home and play around on my Windows machine.


I highly recommend making sure that rules_docker work without users needing
to go through those steps.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/rules_docker/issues/136#issuecomment-329001838>,
or mute the thread

**Comment by duggelz** [comment]
Bazel system requirements are Python 2.7.x.  Unfortunately, none of the Python 2.7.x versions include the Python Launcher for Windows.  So that's a non-starter, which is shame, because that launcher specifically exists to solve several of these problems.

**Comment by pcj** [comment]
@jolarsso Clearly your developers are facile with docker, so as a temporary workaround have you tried using a linux containerized bazel, volume mounted to your windows drive?

**Comment by damienmg** [comment]
Precising what @dslomov said regarding "We can not - and do not - intend to paper over all the differences between Unix and Windows, and between various tools on those platforms (as you discovered here when you realized that Windows cannot run .par files directly)" :

As talked offline, we are going to provide guidance on porting rules for Windows. We are providing windows slave as part of our CI. However, as Dmitry pointed out, we cannot cover all the difference between unixes and Windows so there will always be specifics to the tool each rules is using that we cannot cover.

**Comment by jolarsso** [comment]
1) msys2 is the official dependency for bazel for Windows per: https://docs.bazel.build/versions/master/windows.html so you would probably only have to support only that on Windows and not "those platforms".

2) I understand if you really can't be bothered to support the special case of Windows. Trust me, I do. But then at least be very clear about it in you readme.md. This will save a lot of time for everyone involved down the line since this is probably going to be a very popular bazel rule.

Appreciate the the quick response and effort though @mattmoor. You did what you could :)

**Comment by dslomov** [comment]
> msys2 is the official dependency for bazel for Windows per: https://docs.bazel.build/versions/master/windows.html so you would probably only have to support only that on Windows and not "those platforms".

well yes at this point of time. We would like to eventually remove that dependency.

> I understand if you really can't be bothered to support the special case of Windows. Trust me, I do. But then at least be very clear about it in you readme.md. This will save a lot of time for everyone involved down the line since this is probably going to be a very popular bazel rule.

"Can't be bothered to support the special case of Windows" is not what I said. Sorry if my response was unclear. We do support Bazel on Windows, and we will help people, like @mattmoor here, to port rules. However, for rule owners this is not going to be a simple process - builds ported from Linux will likely not work immediately and will require maintenance their authors.

**Comment by dslomov** [comment]
> An approach based on what @dslomov gives, and (for outside of WORKSPACE) what @damienmg suggested on chat (to avoid needing to pipe the environment through to BUILD actions) seems to work (I at least am past the python not found issues).

For BUILD (not WORKSPACE), if you have a tool that is declared as py_binary, it should just work out of the box (you can create an action via `ctx.actions.run` whose executable is py_binary)

> I think it would be immensely useful to have a ctx.py_action method to avoid the need for these hacks, I'll probably encapsulate this myself as py_action(ctx, *args, **kwargs).

You mean inside WORKSPACE? (so that `ctx` in `ctx.py_action` is repository_ctx).

**Comment by mattmoor** [comment]
@dslomov you beat me to it. :)

@jolarsso I think the sentiment is that the process isn't going to be easy for **rule writers**, so that we can reach a place where it is easy for folks like yourself in a shop with heterogeneous workstation environments.  I'm very keen for this to be the end state.

@dslomov re: `py_action` no, I mean `ctx`.  AIUI rules executing in the `BUILD` phase (`ctx`) won't have access to the environment, but `WORKSPACE` does.  This means that to depend on something like `BAZEL_PYTHON` I have to **write it to a file during `WORKSPACE`** (I used `repository_ctx.symlink` to create my own Python interpreter path, see my PR), which is a sad state.  Given all of the flags and environment variables Bazel has, what I'm suggesting is that it could make this easier for rule writers.



To be clear, I don't **think** I'm currently blocked (just juggling other things).  @dslomov I would be happy to spend some cycles on this, if you guys have bandwidth to field questions?

**Comment by dslomov** [comment]
> re: py_action no, I mean ctx. AIUI rules executing in the BUILD phase (ctx) won't have access to the environment, but WORKSPACE does. This means that to depend on something like BAZEL_PYTHON I have to write it to a file during WORKSPACE (I used repository_ctx.symlink to create my own Python interpreter path, see my PR), which is a sad state. Given all of the flags and environment variables Bazel has, what I'm suggesting is that it could make this easier for rule writers.

Ah, gotcha. No, it should be as easy as 
 1. Declare `py_binary(name = "my_tool", ....)
 2. Depend on my_tool in your rule
 3. use my_tool in `ctx.actions.run(.. executable = ...)`. 
In other words, as easy as on other platforms. I think we are there in 0.6.0 (just cut), you'll probably need to provide `--python_path`, although we are making it easier (https://bazel-review.googlesource.com/c/bazel/+/16631) /cc @pcloudy

> To be clear, I don't think I'm currently blocked (just juggling other things). @dslomov I would be happy to spend some cycles on this, if you guys have bandwidth to field questions

Yes! @laszlocsomor, @pcloudy and me are the Windows gang.

**Comment by mattmoor** [comment]
@dslomov I see the nuance now.
* In `WORKSPACE`, I have access to `BAZEL_PYTHON`.
* In `BUILD`, I can just use the `py_binary` target directly.

That definitely simplifies my current workaround.  I'd still love to be able to use `py_binary` for `tools=[]` dependencies in `WORKSPACE`, but that's a whole separate discussion ;-)

**Comment by jonjohnsonjr** [comment]
I suspect @dslomov meant to /cc @meteorcloudy

**Comment by dslomov** [comment]
Yes thanks, corrected.

**Comment by mattmoor** [comment]
@jolarsso I'm going to rename this issue and use it to track Window support, since that's pretty much the direction things have headed.  Thanks for forcing the issue :)

**Comment by duggelz** [comment]
It sounds like we have a way forward without needing bare .par files to run under CMD.EXE.  If that's not the case, let me know.

Personally, given Win10 support for Ubuntu, and msys2 for Win7, I'd like to see a stake driven through CMD.EXE for good, and Bazel just uses Posix shell on Mac/Win/Linux/other.

**Comment by dslomov** [comment]
> Personally, given Win10 support for Ubuntu, and msys2 for Win7, 
Do not confuse those! 

 * Win10 support for Ubuntu lets you run *unmodified Linux applications* under Windows. In theory, you can just download Bazel-fo-Linux and run it under Linux Subsystem for Windows directly (in practice it does not work for unknown reasons - we have not investigated due to lack of resources and community interest, but we'll accept patches if someone wants to make it work). It will not work well with Windows native programs (such as e.g. Microsoft C++ compiler)

 * msys2 requires us to build a special version of Bazel to run on Windows (and ships a version of Unix tools, specially compiled to run in Windows). We used to use it as a stopgap measure, but it is terrible for many reasons: 
    - it has a lot of quirks. It rewrites process command lines at exec() level and changes system behaviour in interesting and confusing ways
   - one needs to link against a very specific version of `msys-2.0.dll` or things stop working. Many apps ship various versions of `msys-2.0.dll` and users very quickly get into a DLL hell
   - it is horribly slow, mainly because process creation on Windows is slow.

>I'd like to see a stake driven through CMD.EXE for good, and Bazel just uses Posix shell on Mac/Win/Linux/other.

Make no mistake - this is not in the cards, even with the existence of Linux Subsystem for Windows. If rule authors want to serve Windows users, they need to ensure they interop with native Windows tooling.
