### ISSUE TITLE
Maven now requires HTTPS, Causing issues with javax servlet dependency

### ISSUE THREAD

**Issue by surlyengineer** [bazelbuild/rules_docker#1373]
As of today (January 15th 2020), HTTPS is required for maven. 
 https://support.sonatype.com/hc/en-us/articles/360041287334-Central-501-HTTPS-Required . This will need an update https://github.com/bazelbuild/rules_docker/blob/master/java/image.bzl#L90 so as to not fail

**Comment by nlopezgi** [comment]
Thanks for the heads up. it would be awesome if you could send a PR to update (is the update just switching from http to https?). Thanks again

**Comment by surlyengineer** [comment]
Opened here: https://github.com/bazelbuild/rules_docker/pull/1374 .  This'll be my first PR so that's fun.
