### ISSUE TITLE
Implicit dependency on skylib with Bazel 2.0.0?

### ISSUE THREAD

**Issue by surlyengineer** [bazelbuild/rules_docker#1378]
Completely willing to believe this is a problem with configuration on my end, but since updating to Bazel 2.0.0 and the newest release of rules docker, if I don't explicitly include skylib 0.8.0 at the top of my workspace I get

```
Analysis of target '<MY_TARGET>' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@io_bazel_rules_docker//toolchains/docker': Unable to load file '@bazel_skylib//:bzl_library.bzl': file doesn't exist
```

This is on MacOS, with the workspace ordering followed as set out in the setup section, though it's a fairly crowded workspace so would believe something else is messing it up, too.

**Comment by nlopezgi** [comment]
Can you copy here the contents of your workspace file so I can help you debug. There haven't been any recent changes to our service in recent versions of repositories.bzl, but debugging errors in workspace can be a hassle

**Comment by seh** [comment]
I find that if I don't load the _rules_go_ stuff first, I run into this same problem.
