### ISSUE TITLE
Error when running a docker_build cmd to cause it to tag the image in docker

### ISSUE THREAD

**Issue by macrael** [bazelbuild/rules_docker#138]
When I `bazel run` a docker_build cmd, it waits for ~20 seconds, apparently hanging, and then prints out this error message before finally loading the layer and tagging the new image:

```
Wastrel:Gyroscope macrael$ gsbazel run aservice:dev
____Loading complete.  Analyzing...
____Found 1 target...
____Building...
Target //aservice:dev up-to-date:
  bazel-bin/aservice/dev-layer.tar
____Elapsed time: 5.938s, Critical Path: 2.79s

Error response from daemon: open /mnt/sda1/var/lib/docker/tmp/docker-import-515193573/sha256:2a9a98de99130ab23dfbd3f38853acd51461dba1de430063bfce60ab0dcb02c8: no such file or directory
2a9a98de9913: Loading layer [==================================================>] 10.97 MB/10.97 MB
Tagging 2bf2e4a2930caff7e096e6a376953f31b4d558af2791d8c7b227688740dc93a8 as bazel/aservice:dev
```

What does the "Error response from daemon" line mean? I don't want to have to have a 20 second wait when re-building docker images. My janky genrule workaround is much faster.

**Comment by mattmoor** [comment]
Sorry for the delay, this somehow got through my filters and I just noticed it.

The error looks like it is unsquelched output from some existence checks we do to avoid reloading layers into the daemon that it already has.

Would it be possible for you to use a fork or local copy of `rules_docker` that passes `-x` [here](https://github.com/bazelbuild/rules_docker/blob/master/docker/incremental_load.sh.tpl#L17) so we can get a better sense for what command is taking ~20 seconds?

Once the build completes and the `run` portion starts, we're basically doing a whole bunch of shelling out to Docker to try and be smart about what layers we pay to load into the daemon.  I think the (bad) assumption is that these commands are effectively instant, but the reality is likely that you have a bunch of stuff in your daemon and something is `O(slow)`.

If you `bazel build aservice:dev.tar` and `docker load -i bazel-bin/aservice/dev.tar` how long does it take?  I'm curious what your genrule is doing?

**Comment by macrael** [comment]
Here is my genrule:

```
genrule(
    name = "docker-build",
    srcs = [
        "Dockerfile",
        "//receiver/src/receiver",
    ],
    outs = ["docker_output"],
    cmd = "rm -rf docker-rec && mkdir docker-rec && cp -L $(SRCS) docker-rec && docker build docker-rec -t gyroscope-receiver:dev > $@",
    visibility = ["//visibility:public"],
)
```

**Comment by mattmoor** [comment]
Are you able to run this with `-x` in the incremental load script?

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
