### ISSUE TITLE
`container_run_and_commit` does not support incremental loading.

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/rules_docker#1384]
`container_run_and_commit` doesn't support incremental loading as output or input. I couldn't find out if it's because it was never implemented, or if it's a fundamental limitation due to having to interact with `docker save`. Even if it was due to `docker save`, it doesn't explain why it doesn't support incremental loading as input, as incremental loading does load the image into docker, so it should be possible to run commands in it?

Can this be clarified in the readme? https://github.com/bazelbuild/rules_docker/blob/b48dddfdad7764c6164701067c6e3736b8e707d7/docker/util/README.md

Related: https://github.com/bazelbuild/rules_docker/issues/1281

**Comment by nlopezgi** [comment]
Hi @uri-canva thanks for creating this issue. I think this is just never been implemented for this rule. We would be happy to accept contributions to either implement this feature for container_run_and_commit or document better the limitation better in the readme.

**Comment by uri-canva** [comment]
I have put up a PR to support incremental loading as input: https://github.com/bazelbuild/rules_docker/pull/1439

Supporting intermediate format as output seems to be more complicated since `docker save` does not support saving specific layers: https://github.com/moby/moby/issues/3870, https://github.com/moby/moby/issues/8039. The feature was implemented twice already https://github.com/moby/moby/pull/5067, https://github.com/moby/moby/pull/9304, but has been rejected both times.

The only API that is layer aware is the registry API: https://docs.docker.com/registry/spec/api/. It is possible to run either https://github.com/docker/distribution configured to use filesystem storage, then symlink / copy the existing layers where it expects them to be, or a simple http server that implements enough of the spec to handle image pushes, that pretends to have the previous layers.

Unfortunately this might require configuring the docker daemon to list localhost as an insecure registry, and hosting a local registry on mac or indows seems to get broken now and again: https://github.com/docker/for-mac/issues/3611 https://github.com/docker/for-win/issues/624 (it's not working for me on mac right now, I tested it by running the docker daemon in a VM).

This all smells pretty bad, I'm considering avoiding `container_run_and_commit` and instead build up images that require running programs inside the container using a combination of `container_run_and_extract` and `container_image` passing the extracted files, but that's not really nice either.

**Comment by uri-canva** [comment]
Can this be reopened? I've updated my PR again: https://github.com/bazelbuild/rules_docker/pull/1439

**Comment by amir-f** [comment]
Thanks Uri for trying to fix this. `container_run_and_commit` esp. on large images is really slow.
