### ISSUE TITLE
some rules_docker tests are broken on Bazel CI

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/rules_docker#1393]
At d000a48ddfd1c36e874c4700d07463aa219ebbf4, using Bazel 2.0.0 on any platform, some tests are broken on Bazel CI.

Log: https://buildkite.com/bazel/rules-docker-docker/builds/3741#b4a24457-4fbe-47a7-a235-7da020285c89

**Comment by nlopezgi** [comment]
thanks @laszlocsomor looking into it.

**Comment by nlopezgi** [comment]
created https://github.com/bazelbuild/rules_docker/pull/1394, error is due to change in alpine image digest (likely a change in upstream alpine repo).
