### ISSUE TITLE
Read rule argument value from config file

### ISSUE THREAD

**Issue by emranbm** [bazelbuild/rules_docker#1405]
Sometimes an attribute value may be dynamic (i.e. based on some json/yaml file). Is there a way to prevent hard-coding/duplicating them in the bazel build files?  
For example, consider the following rule written in a `WORKSPACE` file. Suppose we have a config file that contains the `tag` and/or `digest` of the docker image. Is there a way to read the parameters from that file?  
```
container_pull(
    name = "release-base",
    registry = "mydockernet:9443",
    repository = "release-base",
    digest = digest_from_config,
    tag = tag_from_config,
)
```

**Comment by alex1545** [comment]
Hi @emranbm,
I don't know of an easy way to directly read variables from json/yaml file into a `WORKSPACE` file, but you can easily define your variables in a `.bzl` file and then import that file (with the variables you need) into your `WORKSPACE` or `BUILD` file. Check this [example](https://github.com/GoogleCloudPlatform/layer-definitions/blob/master/WORKSPACE#L22) where the `RULES_DOCKER` variable is imported from [this](https://github.com/GoogleCloudPlatform/layer-definitions/blob/master/revisions.bzl) `revisions.bzl` file.

Just a note that your question is a general Bazel question and not `rules_docker` related. You may find answers to such questions from Bazel docs or ask in the bazel-discuss@googlegroups.com group.
