### ISSUE TITLE
Authentication with service key

### ISSUE THREAD

**Issue by sgammon** [bazelbuild/rules_docker#1414]
Hello `rules_docker` authors,

I am having some trouble loading a service key and using it for `container_push` operations to GCR. The environment is a Github Workflow, where I have done the following:

1) Defined a secret, containing the JSON service key
2) In the workflow, I emit the key to a file from env (`echo "$SERVICE_KEY_JSON" > service-key.json`)
3) I define an env var pointing to the file (`GOOGLE_APPLICATION_CREDENTIALS=service-key.json`)

The thing is, the key seems to work for other operations (i.e. RBE and remote caching), for which it is entitled. After adding the proper build permissions (even up to *Editor* to make sure I'm not just getting denied based on policy), the key won't work to push a container.

Here is the output I get:
```
info: note: Creating bean classes for 1 type elements
Target //javatests/server:BasicTestApplication-image-push up-to-date:
  dist/bin/javatests/server/BasicTestApplication-image-push.digest
  dist/bin/javatests/server/BasicTestApplication-image-push
INFO: Elapsed time: 134.067s, Critical Path: 14.42s
INFO: 501 processes: 501 remote cache hit.
INFO: Build completed successfully, 627 total actions
INFO: Running command line: dist/bin/javatests/server/BasicTestApplication-image-push
INFO: Build completed successfully, 627 total actions
2020/02/06 19:11:54 Destination us.gcr.io/***/tests/basic/jvm:***BUILD_SCM_VERSION*** was resolved to us.gcr.io/***/tests/basic/jvm:ce65c65 after stamping.
2020/02/06 19:11:55 Error pushing image to us.gcr.io/***/tests/basic/jvm:ce65c65: unable to push image to us.gcr.io/***/tests/basic/jvm:ce65c65: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

I've taken a look at the page referenced, but it just offers directions for using a service key, which I am already doing. I don't think it's permissions on the key. Am I doing something wrong?

**Comment by smukherj1** [comment]
Suggest following the instructions [here](https://cloud.google.com/container-registry/docs/advanced-authentication#gcloud-helper) to configure docker to authenticate with GCR using the gcloud credential helper. After this doing a raw `docker push` should work to your target repository.

After this, I suggest following the instructions [here](https://github.com/bazelbuild/rules_docker#container_push-custom-client-configuration). The Docker client config it refers to is usually in `~/.docker/config.json` on Linux.

Let me know if that doesn't work.

**Comment by sgammon** [comment]
@smukherj1 thank you! that got it working. would you take a PR for a Github Workflow sample? i'm happy to share one if so.

**Comment by smukherj1** [comment]
@sgammon PR's that imrpove our docs are always welcome :)
