### ISSUE TITLE
container_push outputs full path to image

### ISSUE THREAD

**Issue by mariusgrigoriu** [bazelbuild/rules_docker#1419]
Scripting an application deployment with `container_push` running the push target, reading the `push_image.digest` and assembling a string that includes the registry and repository paths, which are arguments to the `container_push` target.

It would be much nicer if the push target would output the full image name@digest in a way that is parsable by deployment scripts, perhaps on stdout.

What do you think? Would this be a good enhancement to the usability of rules_docker?

**Comment by nlopezgi** [comment]
stdout is not a good place to put this as we dont like to make it part of the API. I do think it makes sense to output this somewhere, but it would have to be to a separate file, making it an explicit output of the rule.

**Comment by nlopezgi** [comment]
I'd be happy to review any PRs to contribute this feature!
