### ISSUE TITLE
Allow setting compression level for gzip

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_docker#1425]
When building large images for a development workflow (as opposed to a release), compressing the layers with gzip can be quite expensive. For example, in a case I just tested, compressing an image took ~50s to produce a ~250MB file. By changing `zip.bzl` to invoke `gzip -1`, this becomes ~20s to produce a ~290MB file.

What do you think about adding a parameter to `container_image` to allow setting the compression level, eg `zip_fast=True` or `gzip_flags="-1"`? Alternatively, it could select automatically based the compilation mode, using `-1` for fastbuild and the default for optimized builds. I'd be happy to send a PR.

**Comment by smukherj1** [comment]
I would avoid naming the attributes that implies a compression library, example `zip` or `gzip`. So I think something like one of the two sgtm:
1. Tying the compression level to the build mode as you suggested.
2. Adding two attributes, one for the compression algorithm which would be set to `zip`, `gzip`, etc and the other to pass custom flags to the underlying compression binary/library.

Please feel free to send a PR.
