### ISSUE TITLE
Arguments are not passed to binary when using `bazel run` and py_image

### ISSUE THREAD

**Issue by LegNeato** [bazelbuild/rules_docker#1441]
When running `bazel run -- //whatever MY_ARGUMENT`, with `whatever` being a `py_image` or `py3_image` target, the cli argument `MY_ARGUMENT` is not passed through--`len(sys.argv)` is always 1.

Switching `py[3]_image` to `py_binary` with the exact same arguments works and sees `MY_ARGUMENT`.

**Comment by alex1545** [comment]
Can you please instead try
`bazel run //whatever MY_ARGUMENT`
with `whatever` being a `py_image` or `py3_image` target.

The argument passed after the `--` is reserved for the `--norun` option described [here](https://github.com/bazelbuild/rules_docker#using-with-docker-locally), which optionally prevents the built image from running.

**Comment by LegNeato** [comment]
I will try but that runs in direct opposition to Bazel docs, right? https://docs.bazel.build/versions/master/user-manual.html#run

> Note the use of the --. This is needed so that Bazel does not interpret --arg1 and --arg2 as Bazel options, but rather as part of the command line for running the binary
