### ISSUE TITLE
local machine registry

### ISSUE THREAD

**Issue by lshamis** [bazelbuild/rules_docker#1454]
The `registry` argument is required for both `container_pull` and `container_push`. I'd like to push and pull from local machine.

So far, I've been running
`docker run -d --net=host --name registry registry:2`
and set the `registry` value to `localhost:5000`, but this requires me to copy large images between my local machine and the local registry, which is inexplicably slow. Also, generally a pain with other tools.

I've tried setting the `registry` argument of `container_pull`/`container_push` to the empty string and to `/var/run/docker.sock`, neither of which work.

Is there a way to have bazel push and pull docker images on the current machine?

**Comment by LarsAlmgren** [comment]
Is your docker perhaps running inside minikube? In that case you need to use `$(minikube ip)`.

**Comment by lshamis** [comment]
Unfortunately I'm not running inside minikube. Just a stock Ubuntu machine.

**Comment by lshamis** [comment]
I was linked to https://github.com/bazelbuild/rules_docker#using-with-docker-locally

I can use run a `container_image` rule, instead of a `container_push` rule.

Is there an equivalent for `container_pull`?

**Comment by lshamis** [comment]
ping

**Comment by smukherj1** [comment]
Apologies for the delayed response.

> Is there a way to have bazel push and pull docker images on the current machine?

I'm not sure this is actually possible. Registries running locally store their images in an implementation dependent format (e.g., the docker private registry) that rules_docker doesn't know how to interpret directly.

> I was linked to https://github.com/bazelbuild/rules_docker#using-with-docker-locally
> 
> I can use run a container_image rule, instead of a container_push rule.
> 
> Is there an equivalent for container_pull?

I'm not sure running the `container_image` target using `bazel run` avoids the file copy. It makes docker load the image built by bazel into its private registry which creates a *copy* of the image. Thus, the equivalent for `container_pull` would actually be setting `registry` to `localhost:<port>`

**Comment by lshamis** [comment]
Our current workflow involves building a set of Dockerfiles, copying them into a local `registry`, then using `container_pull` to copy them a second time into bazel cache. Saving one copy would save a lot of time for us. I'd also like to remove running a local registry from our workflow.

How does `container_image` with `bazel run` know the docker's implementation dependent format, in order to push, but not to pull?
