### ISSUE TITLE
nodejs base image exception lacks a tracking issue

### ISSUE THREAD

**Issue by gilbahat** [bazelbuild/rules_docker#1460]
README.md states:

"It is notable that unlike the other image rules, nodejs_image is not currently using the gcr.io/distroless/nodejs image for a handful of reasons. This is a switch we plan to make, when we can manage it. We are currently utilizing the gcr.io/google-appengine/debian9 image as our base."

I could not find an issue that tracks this and explains what are the reasons/blockers for not upgrading. this would be extremely useful when one would like to try contributing patches and/or manually configuring their specific builds due to their own need or using an alternate image (distroless/GAE debian10) assuming said reasons are not valid / unimportant for their scenario.

**Comment by clementnero** [comment]
Are there any plans to use gcr.io/distroless/nodejs ?
