### ISSUE TITLE
pre (and post) hook for pull and push rules (authentication).

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_docker#147]
Unless I am missing some way for a runnable target to depend on another runnable target. 

The pull and push rules could do with a hook for authentication (and other logic).

I currently have this rule  to ensure an ECR login. 

```
genrule(
    name="ecr_login",
    executable = True,
    cmd = """aws ecr get-login --no-include-email > $@ """,
    outs =["ecr_login.sh"]
)
```

**Comment by mattmoor** [comment]
The underlying client basically reads `~/.docker/config.json` directly, and it also supports Docker's "credential helpers" ([see more](https://github.com/bazelbuild/rules_docker#authorization)).

It looks like [this](https://github.com/awslabs/amazon-ecr-credential-helper) is what you want?

**Comment by mattmoor** [comment]
I'll update the docs to link there for ECR and [here](https://github.com/Azure/acr-docker-credential-helper) for AzureCR.

**Comment by hsyed** [comment]
Aah I see now that I have added credentials helpers as the credsStore on os x docker_pull works without me have to run the genrule I mentioned above. 

This approach is still less than ideal for AWS ECR It means the installation of an extra component on the build environment  -- transitively requiring the go toolchain, The build environments on both CI and developer machines should have AWS credentials setup naturally and the AWS CLI. This is all that is strictly required.

**Comment by mattmoor** [comment]
@hsyed I'm a little surprised that the AWS CLI doesn't include it TBH, we at least distribute ours through `gcloud`.

However, I'm with you 100% on this being less than ideal.  IMO Bazel needs a more first-class auth model than to have you preconfigure the N auth models of the various tools you use for fetching external dependencies (their is a dual argument here for publishing/deploying artifacts).

@ulfjack @damienmg @davidstanke FYI
