### ISSUE TITLE
args should be processed similarly in {lang}_binary and {lang}_image targets

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/rules_docker#1472]
Tested specifically with `py3_image`, but applicable to others.

Passing `args` to `py_binary` as part of `kwargs` in `py3_image` has unintended consequences in that it triggers a different set of processors, specifically it does Make variable substitution and Bourne shell tokenization, in addition to location expansion.

How `args` are handled in `py_binary`:
https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-binaries

How `args` are handled in `py3_image` and similar:
https://github.com/bazelbuild/rules_docker/blob/62a1072965e98f74662a11ba89e11df77d7e4305/lang/image.bzl#L220

However, args processed like in the first case are never actually used because the target is never run directly using `bazel run`.  The args that are actually used only go through location expansion (second case) before they are stored as the `CMD` entry in the image config.

This creates problems when the argument is an environment variable. For example, the following diff in the current repo will break the tests with the following error.
```
$ git diff -U1
diff --git a/tests/container/python3/BUILD b/tests/container/python3/BUILD
index 55509ef..48faee6 100644
--- a/tests/container/python3/BUILD
+++ b/tests/container/python3/BUILD
@@ -24,3 +24,3 @@ py3_image(
         "arg0",
-        "arg1",
+        "$USER",
         "$(location :BUILD)",
```
```
$ bazel run //tests/container/python3:py3_image
ERROR: /Users/sbagaria/Workspace/rules_docker/tests/container/python3/BUILD:20:1: in args attribute of py_binary rule //tests/container/python3:py3_image.binary: '$USER' syntax is not supported; use '$(USER)' instead for "Make" variables, or escape the '$' as '$$' if you intended this for the shell. Since this rule was created by the macro 'py3_image', the error might have been caused by the macro implementation
```

If we follow the suggestion to escape with `$$` because we do intend this for the shell, then the docker config file that's generated continues to have the escape sequence `$$`, because that string has only gone through `ctx.expand_location`, which does not deal with shell escapes. This has been reported [previously](https://github.com/bazelbuild/bazel/issues/8447).

We should have the same set of processing done for the args in `py_binary` and in `py_image`, or not pass in the args to `py_binary` at all.

**Comment by LegNeato** [comment]
Related to https://github.com/bazelbuild/rules_docker/issues/1441

**Comment by siddharthab** [comment]
This issue is still relevant. Can we assign somebody to it please?

**Comment by LegNeato** [comment]
This was closed in error, we should reopen.

**Comment by LegNeato** [comment]
Actually, I think this might be fixed.
