### ISSUE TITLE
Change image target name to something meaningful

### ISSUE THREAD

**Issue by sandrobusse** [bazelbuild/rules_docker#1476]
How could one set the bazel `docker_pull` generated docker image target name to something meaningful, e.g not just `bazel/image:image` but rather `bazel/my_custom_image_repo:my_tag`?

**Comment by smukherj1** [comment]
We currently don't have a way to specify the name of the images as they are stored locally. They are always named using the bazel package the image target was defined in and the name of the target itself. We allow specifying the name when pushing the image externally in the `container_push` rule.
