### ISSUE TITLE
nodejs_image with binary dosen't pull in data

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_docker#1479]
We have a rule which accesses volitile status. Due to this, it's uncacable since volitile status always has the build timestamp.
We use this to access the value of `git describe` as the version info for deployment.
```
def repo_status(name, srcs = [], **kwargs):
    #ref https://github.com/bazelbuild/bazel/issues/4842
    #this will only rerun (only grab the git version) when the sources change
    native.genrule(
        name = name,
        output_to_bindir = True,
        outs = ["version_file.txt"],
        stamp = True,
        srcs = srcs,
        cmd = "cat bazel-out/volatile-status.txt > $@",
        **kwargs
    )
```
We'd like to pass the `repo_status` directly to the `nodejs_image` rather than the `nodejs_binary` so that the `nodejs_binary` targets can be cached.

The result is when you use nodejs_image like as below, data does nothing, you can even pass it a non existing label and it dosen't throw an error. We'd expect it to be in the final image as apart of the application layer.
```
    nodejs_binary(
        name = "be",
        entry_point = ":main.ts",
    )

    nodejs_image(
        name = nodejs_name,
        data = [":some-non-existing-file-label"]
        binary = binary,
    )
```
We could use `layers`, but then that prevents us from caching our `node_modules`

If this isn't what the `data` attribute is intended to be used for then some guidance on how to get `git describe` into the top layer of the image would be super appreciated.

Another way to describe what we want would be to describe what we're after is that we'd like out layers to look like:
1. nodejs runtime
2. node_modules
3. application files
4. version information

**Comment by alexeagle** [comment]
Didn't read the whole thing, but one thing I learned is your rule should only include volatile status as an input if the `--stamp` config setting is on.

add an attr to your rule like
```
"node_context_data": attr.label(
        default = "@build_bazel_rules_nodejs//internal:node_context_data",
        providers = [NodeContextInfo],
        doc = "Internal use only",
    ),
```
and then you can read from `ctx.attr.node_context_data[NodeContextInfo].stamp` and only add the input if that evals to True

See how rollup_bundle does it

**Comment by Toxicable** [comment]
@alexeagle awesome, thanks heaps, that did it, not need to change how `rules_docker` works.
Below is the rule I ended up with.

Note that if anyone else wants to do this; if you run your deploy command like this:
```
bazel build :app
bazel run :deploy --config=release # run:release --stamp --workspace_status_command=./some-stamp.sh
```
It will not rerun this rule and your version file will be empty, since none of the inputs have changed. so i'd advise to use step your outtput_base to a clean dir to ensure this file is generated correctly.
```
bazel build :app
bazel run :deploy --config=release --output_base=/tmp/some-new-dir # run:release --stamp --workspace_status_command=./some-stamp.sh
```

```
load("@build_bazel_rules_nodejs//:providers.bzl", "NodeContextInfo")

# this allows us to get the git describe as our  version
def _impl(ctx):
    out_file = ctx.outputs.version_file

    # only read version if --stamp is used
    if ctx.attr.node_context_data[NodeContextInfo].stamp:
      # ctx.version_file is the volitile-status.txt file
      volitle_file = ctx.version_file
      ctx.actions.run_shell(
        inputs = [volitle_file],
        outputs = [out_file],
        arguments = [volitle_file.path, out_file.path],
        command = "cat $1 > $2",
      )
    else:
      # create an empty file so the program can still access it
      # but it's empty when --stamp isn't used
      ctx.actions.write(out_file, "")


repo_status = rule(
    implementation = _impl,
    attrs = {
      "srcs": attr.label_list(mandatory=True),
      "node_context_data": attr.label(
        default = "@build_bazel_rules_nodejs//internal:node_context_data",
        providers = [NodeContextInfo],
        doc = "Internal use only",
      ),
    },
    outputs = {"version_file": "version_file.txt"},
)
```
