### ISSUE TITLE
Pass binary flags from "bazel run" down to "docker run"?

### ISSUE THREAD

**Issue by phs** [bazelbuild/rules_docker#1486]
I'd like to build and then run my docker image (via `legacy_run_behavior = False`) passing through options on the command line.

My hope is running this:

```
bazel run //my:image -- my-command --argv
```

..turns into something like this:

```
docker run -i --rm myrepo:image my-command --argv
```

Looking [here][0] it seems this isn't currently possible.  Or is it?

[0]: https://github.com/bazelbuild/rules_docker/blob/634ff5b5678e0db01baef8fadc9bdb2493193aee/container/layer_tools.bzl#L264

**Comment by johnjameswhitman** [comment]
In your `{lang}_image` build rule, try providing `args` like this:
```python
python3_image(
    name = "whatever",
    ...
    args = [
        "--foo=bar",
    ],
)
```

**Comment by phs** [comment]
The intent is to defer choosing those arguments until `bazel run`; I'd like to use bazel to portably build and then run a CLI tool that has thick OS dependencies that are well-suited for a docker image.

**Comment by dakshas** [comment]
I have the same requirement, is this going to be supported any time soon ?
