### ISSUE TITLE
Support providing docker registry credentials via environment variables

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_docker#1492]
I find it currently lacking to only support local docker config to authenticate with a registry.  It would be useful to me to be able to specify credentials via environment variables. This would allow a lower barrier for new developers to interact with my bazel repo and only require them set env vars for authentication.

**Comment by smukherj1** [comment]
Hi @joeljeske,

Feel free to implement this in a PR. You would need to add the list of environment variables to read the credentials from [here](https://github.com/bazelbuild/rules_docker/blob/62a1072965e98f74662a11ba89e11df77d7e4305/container/pull.bzl#L215) update the puller Go binary  [here](https://github.com/bazelbuild/rules_docker/blob/62a1072965e98f74662a11ba89e11df77d7e4305/container/go/cmd/puller/puller.go) to actually implement the credentials support.

**Comment by joeljeske** [comment]
After digging deeper into the api of the docker credentials helper, i think it makes more sense to create my own credentials helper instead; something like this: 

https://gist.github.com/jasonk/480d87b49e4c8caf51932f184ff764b2

I think I would have a hard time landing a PR here due to lack of a good way to express multiple registry authentication, which would likely be expected. It's more flexible to gather authentication at the credentials helper level. 

Thanks for the guidance.
