### ISSUE TITLE
container_image does not produce expected digest

### ISSUE THREAD

**Issue by radix-aw** [bazelbuild/rules_docker#1496]
The [container_image rule](https://github.com/bazelbuild/rules_docker#container_image-1) does not seem to be producing the proper SHA256 digest. My expectation is that the digest reported by `name.digest` is equal to the digest by which I can reference the image. In other words, the output of `cat bazel-bin/.../foo.digest` does not equal the image ID reported by docker when running `bazel run :foo -- --norun`.

**Comment by smukherj1** [comment]
This is WAI. See https://stackoverflow.com/questions/56364643/whats-the-difference-between-a-docker-images-image-id-and-its-digest

Basically the digest is the sha256sum of the image manifest and the image ID is the sha256sum of the image config.
