### ISSUE TITLE
How to put a custom executable into a image?

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_docker#1497]
I'm trying to create a `container_image` that includes a target of a custom executable rule that I've created.

The custom rule calls wraps a Java binary to execute database migrations.

I've tried adding the executable target to the `files` attribute on `container_image` but then the runfiles are not included.

I then tried using `pkg_tar` with `include_runfiles=True` and added it to the `tars` attribute on `container_image. It the complains that it can't locate the Java runfiles with this error: `./src/java/com/bin: Cannot locate runfiles directory. (Set $JAVA_RUNFILES to inhibit searching.)`

Is there any way to take a executable target that wraps other executables and make it work?

**Comment by smukherj1** [comment]
Hi @purkhusid,

I would suggest looking at the implementation of the `java_image` rule [here](https://github.com/bazelbuild/rules_docker/blob/131eb110957ef46ebbcbb0e81dce99132f15334c/java/image.bzl#L168) for an example of how it includes binary runfiles and provides them as transitive dependencies to the `container_image` rule.

**Comment by purkhusid** [comment]
Is it a impossible task to to create a `executable_image` that can take any Bazel executable target as a layer and then invoke it?

**Comment by teran** [comment]
Hello @purkhusid, it could be easily done the following way (I've used it with Go, but just checked with Rust and Java - all the files are in place in resulting image):

```
pkg_tar(
    name = "binaries",
    srcs = [
        "//path/to/go/package/cmd:cmd",
        "@org_golang_x_lint//golint",
        "//path/to/rust/binary:cmd",
        "//path/to/java/binary:my_bin",
    ],
    package_dir = "/usr/local/bin",
)
```

All the targets I've specified in `srcs` are `*_binary` targets. After that this pkg_tar could be added to `container_image` in `tars` list.
