### ISSUE TITLE
Correct way to package assets with a go microservice

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_docker#1498]
I'm working on removing `go_bindata` from our monorepo and instead packaging assets into our go microservices. Providing `layers` to `go_image` does not need seem to work. Instead I have to do something this:

```
def go_microservice(name, args = [], assets = []):
    pkg_tar(
        name = "assets-tar",
        strip_prefix = ".",
        package_dir = "/app/" + native.package_name(),
        srcs = assets,
        mode = "0755",
    )

    go_image(
        name = "go-image",
        binary = name,
        args = args,
        visibility = ["//visibility:public"],
    )

    container_image(
       name = "image",
       base = ":go-image",
       tars = [":assets-tar"]
    )
```

Is this the correct way to achieve this ?

**Comment by hsyed** [comment]
It bothers me that the approach above creates a separate layer.

**Comment by smukherj1** [comment]
You might be able to use the [data](https://github.com/bazelbuild/rules_docker/blob/d8ab7998dee8f2cd1b0f0bde042360858a5e14db/go/image.bzl#L130) attribute on `go_image`. However, I'm not sure if it'll still create a separate layer.
