### ISSUE TITLE
Workspace status and Make variable support in Labels.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_docker#150]
Docker Labels should have workspace status variables and make variable support. 

Git commit hash, git commit branch, dirty status etc come from the workspace status and variables from the make variables set in bazelrc or at the command line.

This would mean  enabling stamping on docker_build.

**Comment by mattmoor** [comment]
Today we support reading these from a file, but not stamping.

I agree this would be useful, and it would roughly go [here](https://github.com/bazelbuild/rules_docker/blob/master/docker/create_image_config.py#L94-L98).  It should roughly follow [this](https://github.com/google/containerregistry/blob/master/tools/fast_pusher_.py#L67-L84) pattern from the pusher.
