### ISSUE TITLE
py3_image with data

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/rules_docker#1504]
** sorry if this is the wrong place for support **

In the following BUILD file I was expecting the target named `:image` to build a container image that would include the templates folder.

However it fails to add the templates to the container, or at least the folder is not in the working directory.

How should this be done?

```
package(default_visibility = ["//visibility:public"])

load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")
load("@io_bazel_rules_docker//python3:image.bzl", "py3_image")
load("@corp_pip_deps//:requirements.bzl", "all_requirements")

filegroup(
    name = "templates",
    srcs = [
        "templates/jobqueue.html",
        "templates/list.html",
        "templates/master.html",
        "templates/show.html",
    ],
)

py_library(
    name = "py_image_library",
    deps = all_requirements,
)

py3_image(
    name = "image",
    data = [
        ":templates",
    ],
    deps = [":py_image_library"],
    main = "server.py",
    srcs = [
        "__init__.py",
        "main.py",
        "server.py",
        "store/__init__.py",
        "store/jobqueue.py",
        "store/introducers.py",
    ],
)

```

Thanks in advance.

**Comment by bweston92** [comment]
Ok I managed to see they're actually placed into the container but following the path from the workspace root. How can I get the `templates` target in the same place as the working directory?

**Comment by chasain** [comment]
We had to include this in our container_image rule to get it to not flatten filegroup rules:

data_path = ".",

Not sure if it's the same in py_image but worth a shot

**Comment by bweston92** [comment]
Thanks @chasain will see if it works.
