### ISSUE TITLE
Upgrade from 0.14.1 to 0.14.2 - target '@rules_pkg//:archive' is not visible from target '@io_bazel_rules_docker//container:build_tar_lib'

### ISSUE THREAD

**Issue by skyl** [bazelbuild/rules_docker#1518]
Upgrading from 0.14.1 to 0.14.2 gives me the following error

```
ERROR: /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/io_bazel_rules_docker/container/BUILD:40:11: in py_library rule @io_bazel_rules_docker//container:build_tar_lib: target '@rules_pkg//:archive' is not visible from target '@io_bazel_rules_docker//container:build_tar_lib'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

I'm using some tars which smells like the source of the problem; I'm not sure if I need to change something so I can update.

I'm making a `rules_k8s` `k8s_object`:

```
load("@io_bazel_rules_docker//container:container.bzl", "container_image")
load("@io_bazel_rules_k8s//k8s:object.bzl", "k8s_object")

container_image(
    name = "worker",
    base = "@py3base//image",
    cmd = [
        "/py/dj/manage.py worker",
    ],
    directory = "/py/",
    tars = [
        "//py:djtar",
    ],
)

k8s_object(
    name = "deployment",
    kind = "Deployment",
    template = ":deployment.yaml",
    images = {
        "...worker:latest": ":worker",
    },
)
```

The filegroup/tar bit looks something like this:

```
load("@rules_pkg//:pkg.bzl", "pkg_tar")

filegroup(
    name = "djfiles",
    srcs = glob([
        "dj/*/**/*.py",
    ]),
    visibility = ["//visibility:public"],
)
pkg_tar(
    name = "djtar",
    srcs = [":djfiles"],
    strip_prefix = ".",
    visibility = ["//visibility:public"],
)
```

**Comment by ericnorris** [comment]
I believe this can be fixed by using the latest version of `rules_pkg` (https://github.com/bazelbuild/rules_pkg/releases/tag/0.2.6-1) in your WORKSPACE. It contains this commit: https://github.com/bazelbuild/rules_pkg/commit/8c6a4bd54ecf86b3481025c2ede667837066228f.

I believe the `http_archive` in the release notes is incorrect, however, so I've also filed an issue to rectify that: https://github.com/bazelbuild/rules_pkg/issues/189.

**Comment by skyl** [comment]
> I believe this can be fixed by using the latest version of `rules_pkg` (https://github.com/bazelbuild/rules_pkg/releases/tag/0.2.6-1) in your WORKSPACE. It contains this commit: [bazelbuild/rules_pkg@8c6a4bd](https://github.com/bazelbuild/rules_pkg/commit/8c6a4bd54ecf86b3481025c2ede667837066228f).
> 
> I believe the `http_archive` in the release notes is incorrect, however, so I've also filed an issue to rectify that: [bazelbuild/rules_pkg#189](https://github.com/bazelbuild/rules_pkg/issues/189).

Thanks for the tip @ericnorris! I didn't even remember that the rules_pkg version was something I had defined - I thought that was part of bazel. This works now.

**Comment by TheButlah** [comment]
I'm getting this bug without messing about with rules_pkg directly at all, but using the fix in @ericnorris 's comment, the issue goes away. Does the current version of rules_docker not use this fix?

**Comment by smukherj1** [comment]
#1556 Removed rules_pkg as a dependency of rules_docker so this should be fixed in rules_docker if you use the latest commit.
