### ISSUE TITLE
Container pull windows support

### ISSUE THREAD

**Issue by Caribosaurus** [bazelbuild/rules_docker#1524]
It is unclear if container pull can be ran on Windows. 
When I try to do it I get errors regarding the linux-puller.
 Is there a way to make it work?

**Comment by themacguffinman** [comment]
No it doesn't, the  `container_pull()` rule uses a downloaded binary to pull an image but the maintainers don't build a Windows version of that binary, only Linux & macOS have binaries available for them. Look at https://github.com/bazelbuild/rules_docker/issues/1438

Some people have managed to build the binary themselves and modify the rules to use their self-built binary, but as a Bazel newbie it's not exactly clear to me how to do it.

**Comment by luna-duclos** [comment]
Hello! Would a fix for this be welcomed in the repo ? I have working patches in our bazel monorepo I'd be happy to contribute back. The build infrastructure needed looks like it could use the existing cloudbuilders as well and just pass the correct GOOS and GOARCH to get the binaries.

**Comment by gregmagolan** [comment]
@luna-duclos I'd be very interested in helping get your fix into this repository.
cc @alexeagle
