### ISSUE TITLE
Depend on gflags from WORKSPACE rather than @bazel_tools

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_docker#1533]
https://github.com/bazelbuild/rules_docker/blob/f7e6d6f28ac9f9e92d8b875426233031c5c5257c/container/BUILD#L46
depends on   "@bazel_tools//third_party/py/gflags",

Bazel has removed gflags because it is not used any more.

**Comment by aiuto** [comment]
Or... just replace the single use of gflags with the python flag library.  It is only container/build_tar

**Comment by meteorcloudy** [comment]
@aiuto Can you help file bugs for other projects failing in downstream due to this issue to upgrade their rules_docker version?
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1531

**Comment by aiuto** [comment]
Maybe over the weekend. 
It is not sustainable for us to monitor and warn on everything. Don't the downstream projects themselves have an obligation to monitor this CI we run for the?
We should certainly be enforcing that for the rule sets. For projects (like robotics) that is less clear.

**Comment by meteorcloudy** [comment]
@aiuto 
> Don't the downstream projects themselves have an obligation to monitor this CI we run for the?

I don't think all third party projects should monitor our Downstream Pipeline, because it could be broken by Bazel bugs. It make more sense for them to monitor our "Bazel@Releasse + Incompatible flags" pipeline, but this change is not guarded by a flag. Even though, the current situation is the author of every incompatible change should drive the downstream projects migration, like filing bugs.

**Comment by meteorcloudy** [comment]
@aiuto Can you make sure there is a paragraph in the next Bazel release note that mentions the removal of gflags and the necessary to upgrade rules_docker to fix the build error?

**Comment by meteorcloudy** [comment]
@smukherj1 When is the next release of rules_docker happening? Should the projects depending on rules_docker wait for the new release or just ping rules_docker to the latest commit?

**Comment by aiuto** [comment]
Sure. I created a milestone for the next major release. That will be the place to look.

**Comment by smukherj1** [comment]
> @smukherj1 When is the next release of rules_docker happening? Should the projects depending on rules_docker wait for the new release or just ping rules_docker to the latest commit?

We don't really have a release schedule. We only create a release if specifically requested. If pinning to the latest commit is possible, downstream projects are free to do so.
