### ISSUE TITLE
Question: how to load image to the local docker

### ISSUE THREAD

**Issue by teran** [bazelbuild/rules_docker#1538]
Hello,

I have the following case:
I'm building docker images with bazel and everything around it works perfect except one trivial thing: there's no way to load into local docker instance and depend on it from tests (in my case tests are written in Go so it's about `go_test` definitions).

Currently `container_import` requires v2.2 image's json configuration which is normally should be generated automatically (which already works with `container_push` and `container_pull` definitions).

Any ideas how to achieve that (preferably without writing custom rules but simply rely on rules_docker) ?

Thanks in advance.

**Comment by smukherj1** [comment]
Hey @teran,

My suggestion would be to use `container_image` targets as a dependency to your Go tests and load the image artifacts using `go-containerregistry`.  One simple way could be to get your `container_image` to build a tarball of the image and provide load this tarball using the tarball opener library here [https://github.com/google/go-containerregistry/blob/master/pkg/v1/tarball/image.go]. This will allow you to do simple file existence checks or inspect the manifest or config JSON files of the built image.

**Comment by teran** [comment]
Hello @smukherj1,

From the first perspective it looks like attempt to move to Go part image loading which doesn't look necessary way since rules_docker can load images on predictable tag, this behaviour could be obtained by running `bazel run` on any `container_image` target. So I suppose there should be an easier way to handle this.

Anyway thanks for the idea! I'll check it out, probably it would be easier.
