### ISSUE TITLE
Latest release incompatible with the latest bazel version

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_docker#1542]
See https://github.com/bazelbuild/rules_k8s/issues/569 https://github.com/bazelbuild/rules_k8s/pull/580

> The next release of Bazel will remove @bazel_tools//third_party/py/gflags.
> That forced an update of rules_docker.
> https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1531#94f5ac34-18d0-4eac-af7a-322acde84841

/cc @aiuto @meteorcloudy

**Comment by meteorcloudy** [comment]
@smukherj1 Can we have a new release of rules_docker? It will be easier for downstream projects to migrate.

**Comment by smukherj1** [comment]
https://github.com/bazelbuild/rules_docker/releases/tag/v0.14.4 has been released.
