### ISSUE TITLE
[Puller] Wrong image digest when manifest uses tabs

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/rules_docker#1547]
It seems like when original docker registry has manifest with tabs and not spaces - the puller manifest and digest are different.

Just came across a very niche issue.
[`busybox:1.25.0`](https://hub.docker.com/layers/busybox/library/busybox/1.25.0/images/sha256-2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749?context=explore) has the following manifest in dockerhub:
```json
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/octet-stream",
		"size": 1459,
		"digest": "sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 667590,
			"digest": "sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f"
		}
	]
}
```
Using tabs, and respectfully the digest `sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749`

But when downloading this image using go puller we get different manifest:
```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 1459,
      "digest": "sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 667590,
         "digest": "sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f"
      }
   ]
}
```
(using 3 spaces)
And the digest `sha256:a59906e33509d14c036c8678d687bd4eec81ed7c4b8ce907b888c607f6a1e0e6` which does not exist in original repo.

Is it a desired behavior? internally we use the digest in order to locate the base image in the original repo, and copy / mount layers to the target repo so we need this digest to be the same as the one in the original repo.

## repro

I created this "simply repro" https://github.com/or-shachar/rules_docker/tree/wrong-digest (`wrong-digest` branch).
You can see this issue by running `bazel build @busybox_1.25.0//image` and then go to `cd $(bazel info output_base)/external/busybox_1.25.0/` and have a look around.

**Comment by smukherj1** [comment]
Not entirely sure why the manifest of an "unmodified" image downloaded by the puller would differ. Our puller references the remote image [here](https://github.com/bazelbuild/rules_docker/blob/faaa10a72fa9abde070e2a20d6046e9f9b849e9a/container/go/cmd/puller/puller.go#L95) and the manifest is written out [here](https://github.com/bazelbuild/rules_docker/blob/faaa10a72fa9abde070e2a20d6046e9f9b849e9a/container/go/pkg/compat/write.go#L57) using the `RawManifest` function on go-containerregistry's `remote` implementation of `v1.Image` [here](https://github.com/google/go-containerregistry/blob/92c877ee115a51bd6e06937bd681103f20394843/pkg/v1/remote/image.go#L67). Go container registry seems to be returning the image exactly as it got from the HTTP response from the registry URL so I'm not sure where the difference is coming in. Do you mind taking a look at this? I would be happy to review a PR that fixes the source of the problem.

**Comment by or-shachar** [comment]
I wish I could... I can help around startlark tricks but I'm a total newbie with `go` to be honest... I'll try to look around and see if I can understand what's going on there. I see that eventually we write to the file [this field](https://github.com/bazelbuild/rules_docker/blob/faaa10a72fa9abde070e2a20d6046e9f9b849e9a/container/go/pkg/compat/image.go#L132) but I'm not sure what populates it.

**Comment by or-shachar** [comment]
It's very odd... but I think it doesn't relate to rules_docker or go container registry.

I see that  the go container registry tries to download the manifest by using the API call:
```sh
curl  'https://index.docker.io/v2/library/busybox/manifests/1.25.0' \
--header 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
--header 'Authorization: Bearer xxx
```

Which returns

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 1459,
      "digest": "sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 667590,
         "digest": "sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f"
      }
   ]
}
```
But the actual manifest (that is not retrieved from API call, I guess), is different as it has tabs in it. I guess this should be reported somehow to `index.docker.io` in some way.

Alternatively we can inspect alternative ways to bring the manifest that is not from the API?

**Comment by or-shachar** [comment]
I'll close it for lack of interest now... workaround is easy - chose a different base image that is not messed up in the remote registry.
