### ISSUE TITLE
Version 0.14.4 have error

### ISSUE THREAD

**Issue by henrywong-seekers** [bazelbuild/rules_docker#1550]
Hi, I found this error when using version 0.14.4 but fine for version 0.14.3

```
every rule of type _app_layer implicitly depends upon the target '@io_bazel_rules_docker//container:build_tar', but this target could not be found because of: error loading package '@io_bazel_rules_docker//container': Unable to find package for @pip_deps//:requirements.bzl: The repository '@pip_deps' could not be resolved.
```

**Comment by whilp** [comment]
@smukherj1 FYI, I think your update over here resulted in some unexpected breakage with this release:

https://github.com/bazelbuild/rules_docker/commit/770e67f629caa8dd28388247064525cb36ae0932#diff-5135d099cb06bd6b67cf9a4f68ea2d85R16

**Comment by whilp** [comment]
oh heck, I see @smukherj1 already addressed this in the discussion on that PR:

**Comment by henrywong-seekers** [comment]
@whilp I add the lines

```
load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")    
    
container_deps()
```

and got another error

```
no such package '@pip_deps_pypi__python_gflags_3_1_2//': The repository '@pip_deps_pypi__python_gflags_3_1_2' could not be resolved and referenced by '@io_bazel_rules_docker//container:build_tar_lib'
```

**Comment by whilp** [comment]
@henrywong-seekers yeah, I get a similar error (for six) — I’ve had `container_deps` in `WORKSPACE`. I started to set up a small repo to demonstrate the issue and hope to get back to this tomorrow, something seems not quite right.

**Comment by whilp** [comment]
For now, in case it’s helpful, this repo (and the GitHub actions status checks in it) show the general issue: https://github.com/whilp/world/pull/50

**Comment by smukherj1** [comment]
I think you'll also need the following in your WORKSPACE after the `container_deps` (see [here](https://github.com/bazelbuild/rules_docker/commit/770e67f629caa8dd28388247064525cb36ae0932#diff-42862346ecb62269e4dff601de060d35))

```
load("@io_bazel_rules_docker//repositories:pip_repositories.bzl", "pip_deps")

pip_deps()
```

I'll update the README

**Comment by scorsi** [comment]
@smukherj1 thanks, it's solves this issue ! 👏
