### ISSUE TITLE
Do not depend on @rules_pkg//:archive 

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_docker#1553]
At least a few places depend on the internal library `archive` in `rules_pkg`.  E.g.
https://github.com/bazelbuild/rules_docker/blob/e680c545ee6adf1634df29eac95ac341ccad7900/testdata/extras_gen.py#L19

This library should be private to rules_pkg, so that those rules can develop as needed.
The libraries were only public to begin with because of the historical that they originated inside bazel itself.

Tracking from the rules_pkg side:  https://github.com/bazelbuild/rules_pkg/issues/200

**Comment by alex1545** [comment]
Hi @aiuto, we no longer depend on the `archive` library from `rules_pkg` after copying over what we rely on.

**Comment by aiuto** [comment]
You're the best!
