### ISSUE TITLE
Building with --stamp does not set creation_time

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/rules_docker#1554]
Hi,

I'm trying to build images with a proper creation_time set. As I understand it, this behavior should be automatically inferred when using `--stamp`. However, it seems to have no effect.

When looking at this snippet of code, I can see that it is reading the deprecated stamp attribute, but this still wasn't setting the creation_time and I was getting warnings that the stamp attribute was deprecated.

https://github.com/bazelbuild/rules_docker/blob/v0.14.4/container/image.bzl#L129-L134

So when I modify these lines of code to always set the creation time 

```starlark
    args.add("-creationTime", "{BUILD_TIMESTAMP}")
```

Then it fails to parse the date. I am guessing because BUILD_TIMESTAMP is never substituted. 

```
SUBCOMMAND: # //tools:cc_image [action 'ImageConfig tools/cc_image.0.config', configuration: 6bceea3a6a16503c54e0002f649115e014f212639f417aa9bc9de63a323389a9]
(cd /home/preston/.cache/bazel/_bazel_preston/6e220e5720b8243fd605645eb29a29ba/execroot/prysm && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/create_image_config/linux_amd64_stripped/create_image_config -outputConfig bazel-out/k8-opt/bin/tools/cc_image.0.config -outputManifest bazel-out/k8-opt/bin/tools/cc_image.0.manifest -creationTime '{BUILD_TIMESTAMP}' -user root -layerDigestFile @bazel-out/k8-opt/bin/tools/cc_image-layer.tar.sha256 -baseConfig external/cc_image_base/image/config.json -architecture amd64 -operatingSystem linux)
ERROR: /home/preston/git/prysm/tools/BUILD.bazel:61:16: ImageConfig tools/cc_image.0.config failed (Exit 1) create_image_config failed: error executing command bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/create_image_config/linux_amd64_stripped/create_image_config -outputConfig bazel-out/k8-opt/bin/tools/cc_image.0.config ... (remaining 14 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
2020/07/12 12:17:10 Failed to override values in old image config and write to dst failed to create/update image config: failed to parse creation time from config: failed to parse "{BUILD_TIMESTAMP}" as RFC3339. Assumed format to be RFC3339 as it failed to parse as a float as well: parsing time "{BUILD_TIMESTAMP}" as "2006-01-02T15:04:05Z07:00": cannot parse "{BUILD_TIMESTAMP}" as "2006": bazel-out/k8-opt/bin/tools/cc_image.0.config
```

I'm using v0.14.1 and I tried v0.14.4 as well.

FWIW, it looks like reading the value of "--stamp" is not directly supported in starlark, but is possible with a workaround `config_setting`. See: https://github.com/bazelbuild/bazel/issues/11164

Additional context: https://github.com/prysmaticlabs/prysm/issues/6561

**Comment by alex1545** [comment]
Hello,
I just tried this and it works for me. I'm specifying `stamp = True` as part of my `container_image` target and I get a proper creation time. Are you looking for a different use of `stamp`?

**Comment by prestonvanloon** [comment]
It doesn’t work with container_bundle.

I tried specifying stamp = True and got a deprecation log message, the
creation time was not set.

https://github.com/prysmaticlabs/prysm/blob/8fda48409ca9398a1d907bbc4724e73ca2152e7c/beacon-chain/BUILD.bazel#L72

**Comment by prestonvanloon** [comment]
@alex1545 Any feedback? There seems to be a real issue here.

**Comment by smukherj1** [comment]
Hi there, sorry for the delay:

The way the substitution works is by specifying the list of stamp variables in Bazel via a text file mapping the stamp variables to their values [here](https://github.com/bazelbuild/rules_docker/blob/v0.14.4/container/image.bzl#L173). So either this file isn't being passed in the `container_bundle` case or the file that's being passed doesn't have the `BUILD_TIMESTAMP` set or `stamp = True` isn't being inferred automatically. I likely won't have the bandwidth to look into this soon. Please feel free to submit a PR with a fix if you find the issue. Sorry for the inconvenience :(
