### ISSUE TITLE
rules_docker still depends on Python?

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/rules_docker#1555]
I know that recently rules_docker has been rewritten to use gocontainerregistry package instead of the python one, so I'm trying to use a docker image with bazel to build an application and this image does not have Python. I'm getting errors because rules_docker uses https://github.com/bazelbuild/bazel/tree/master/tools/build_defs/hash which uses a python script to calculate the sha256.

If this is the only dependency on Python then I think it might be beneficial to remove it and use an implementation of sha256 rule in Go (since there is a dependency on Go anyway). WDYT?

p.s. I wrote such a rule a while ago https://github.com/atlassian/bazel-tools/tree/master/file_hash.

**Comment by tommyknows** [comment]
I actually wondered the same, and it might work for the `go_image` rules at least. But the `container` rules still use python (see for example `container/build_tar.py`).

**Comment by anantdamle** [comment]
I am facing the same issue, especially since Python2 is not deprecated.

**Comment by mwysokin** [comment]
With Ubuntu 20.04 being the current "go to LTS" the issue is even more noticeable since it doesn't ship with Python2 by default.

**Comment by dragonsinth** [comment]
@ash2k do you have a way to override the python based hash with your own?  I'm running into this problem myself and would love to borrow your workaround.

**Comment by ash2k** [comment]
@dragonsinth IIRC I worked this around by using a docker image with (an old version of) Python.

**Comment by dragonsinth** [comment]
@ash2k #1993 would solve the first case, but there's still `build_tar.py` after that

**Comment by HectorB-2020** [comment]
Hello! There is one more file which directly relies on Python2 without wrapper or variable like `$PYTHON_BIN`.
[https://github.com/bazelbuild/rules_docker/blob/master/container/incremental_load.sh.tpl](https://github.com/bazelbuild/rules_docker/blob/master/container/incremental_load.sh.tpl)

```
TOTAL_DIFF_IDS=($(cat "${name}" | python -mjson.tool | \
      grep -E '^ +"sha256:' | cut -d'"' -f 2 | cut -d':' -f 2))
```
So I'm wondering if this piece of code is to be reworked as well. Wouldn't like to install Python2 specifically to workaround this line.
