### ISSUE TITLE
Symlinks point to the wrong location

### ISSUE THREAD

**Issue by andrewalker** [bazelbuild/rules_docker#1557]
It's not really clear to me how symlinks are expected to work currently, but even in the tests they point to non-existing files.

Here they are meant to point to `layer_file_path(ctx, s.target_file)`:
https://github.com/bazelbuild/rules_docker/blob/b48dddfdad7764c6164701067c6e3736b8e707d7/lang/image.bzl#L189-L193

Which is defined as:
https://github.com/bazelbuild/rules_docker/blob/b48dddfdad7764c6164701067c6e3736b8e707d7/lang/image.bzl#L108-L109

I have custom rules that use symlinks very similar to the test case:
https://github.com/bazelbuild/rules_docker/blob/b48dddfdad7764c6164701067c6e3736b8e707d7/testdata/utils.bzl#L30-L38

Which is then tested here:
https://github.com/bazelbuild/rules_docker/blob/b48dddfdad7764c6164701067c6e3736b8e707d7/container/image_test.py#L528-L552

The symlinks are tested to are be present in the layer in the right location, but the tests don't check whether they point to the right location. In the above example, IMHO, foo-symlink.txt should point to `/app/testdata/py_image_with_symlinks_in_data.binary.runfiles/io_bazel_rules_docker/testdata/foo.txt`. Instead, it points to `/app/io_bazel_rules_docker/testdata/foo.txt` which doesn't exist in any of the layers. That would be achieved by using `_final_file_path` instead of `layer_file_path`:
https://github.com/bazelbuild/rules_docker/blob/b48dddfdad7764c6164701067c6e3736b8e707d7/lang/image.bzl#L83-L84

I think that would break `py_image`, which seems to be relying on symlinks. https://github.com/bazelbuild/rules_docker/issues/161.

Ideally I'd like to add something this to the test file:
```diff
diff --git a/container/image_test.py b/container/image_test.py
index 84ac902..0fdb17f 100644
--- a/container/image_test.py
+++ b/container/image_test.py
@@ -538,6 +538,15 @@ class ImageTest(unittest.TestCase):
 
   def test_py_image_with_symlinks_in_data(self):
     with TestImage('py_image_with_symlinks_in_data') as img:
+      buf = cStringIO.StringIO(img.blob(img.fs_layers()[0]))
+      with tarfile.open(fileobj=buf, mode='r') as layer:
+        # This crashes, because the symlink points to /app/io_bazel_rules_docker/testdata/foo.txt:
+        symlink_content = layer.extractfile('/app/testdata/py_image_with_symlinks_in_data.binary.runfiles/io_bazel_rules_docker/foo-symlink.txt').read()
+        # this works fine:
+        foo_txt_content = layer.extractfile('./app/testdata/py_image_with_symlinks_in_data.binary.runfiles/io_bazel_rules_docker/testdata/foo.txt').read()
+        # ideally I'd like to do something like:
+        self.assertEqual(symlink_content, foo_txt_content)
+
       # Check the application layer, which is on top.
       self.assertTopLayerContains(img, [
         '.',
```

It currently crashes when trying to extract foo-symlink.txt, because it points to a non-existing location.

How are symlinks supposed to work? I assume they work for their intended purpose because of how `py_image` is using them, but is there a way to make them more intuitive (i.e. just point to existing files, possibly using `_final_file_path` as mentioned above). Pinging @scele who introduced most of the relevant code here.

**Comment by pvcnt** [comment]
I was just bitten by this, and the suggested fix seems to work for me so far (I'm working with a Python image). Is that the correct way to fix it?

**Comment by det** [comment]
I am also running into this.
