### ISSUE TITLE
py3_image won't run grpc target: "cannot import name 'cygrpc'"

### ISSUE THREAD

**Issue by eap** [bazelbuild/rules_docker#1561]
I have the following py3_image definition that points to a GRPC server. As defined below I'm using the distroless/python3-debian10 base image, but I get the exact same issue if I use the default base image.

It's confusing to me because it was my impression that dependencies were supposed to come from bazel; when I define this as a py_binary I do not get the same issue. I need to be able to define this as a docker image since we are deploying to k8s.

```
py3_image(
    name = "server",
    srcs = ["main.py"],
    base = "@py3_experimental_image_base//image",  # distroless/python3-debian10
    main = "main.py",
    deps = all_requirements + [
        "//proto/actuator:actuator_service_py_grpc_proto",
        "//actuator/service",
    ],
)
```

This is the error my server emits while trying to load.

```sh
[actuator-******] Traceback (most recent call last):
[actuator-******]   File "/app/actuator/server/server.binary.runfiles/__main__/actuator/server/main.py", line 1, in <module>
[actuator-******]     from actuator.service import service_impl
[actuator-******]   File "/app/actuator/server/server.binary.runfiles/__main__/actuator/service/service_impl.py", line 3, in <module>
[actuator-******]     from proto.actuator import actuator_service_pb2_grpc
[actuator-******]   File "/app/actuator/server/server.binary.runfiles/__main__/proto/actuator/actuator_service_pb2_grpc.py", line 2, in <module>
[actuator-******]     import grpc
[actuator-******]   File "/app/actuator/server/server.binary.runfiles/py_deps/pypi__grpcio/grpc/__init__.py", line 23, in <module>
[actuator-******]     from grpc._cython import cygrpc as _cygrpc
[actuator-******] ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/app/actuator/server/server.binary.runfiles/py_deps/pypi__grpcio/grpc/_cython/__init__.py)
```

**Comment by romnnn** [comment]
Same issue and cannot find a solution. Even tried many different base images :(

**Comment by bjorns** [comment]
I ran into a similar issue where the root cause seems to be that compiled cython so files are not included in the image. I don't know where or how these are supposed to be built so I'm not sure how to keep investigating but your error:

```
ImportError: cannot import name 'cygrpc' from 'grpc._cython'
```

implies that it may be the same issue.

**Comment by eap** [comment]
I'll start with TLDR:
**use a debian base image which has a glibc version matching your build environment, ensure you add a layer that creates required symlinks for a `py3_image` base image (see the bottom for an example)**

Full notes.

1) Even if you depend directly on a grpc proto, you'll need to manually add the grpc dependencies to your binary (grpcio, protobuf, etc). I don't know if this is generally true or if it was just true for me.

2) the pip package `cygrpc` is totally unrelated to  `grpc._cython.cygrpc` installing it doesn't fix the issue but it also doesn't make it worse, just avoid this rabbit hole generally.

3) The base image must have a glibc version greater than or equal to that of your build environment thanks to grpc build magic that detects glibc version. Try adding a container_pull to your WORKSPACE for either `gcr.io/distroless/python3-debian10` or if you need debian bullseye you can use the official `buildpack-deps:bullseye` image.

4) In order to use an official python image (be it buildpack-deps or other) with the `dfdsfsd` rule, you'll need to add a symlink. This can be done in bazel using the following rule build rule to create a layer ontop of the base image

```
# Inject the needed symlink
container_image(
    name = "symlinked_buildpack_deps",
    base = "@buildpack_bullseye//image",
    symlinks = {
        "/usr/bin/python": "/usr/bin/python3.8",
    },
)

py3_image(
    ... various required flags ...
   base = ":symlinked_buildpack_deps",
   ...
)
```

Alright, I'm closing this since my specific issue is fixed. Hopefully my notes help others who encounter this.

**Comment by HuanwenChen312** [comment]
I also encountered this issue, I tried to follow the note from @eap , but that does not help much.

**Comment by sbairos** [comment]
A workaround that I found to work for my use case was to stop using py3_image() at all and instead use app_layer() with a py_binary. app_layer() is what the py3_image rule [uses under the hood anyways](https://github.com/bazelbuild/rules_docker/blob/280b6e6cfbaaaedad169bd846abe9903c59b35e3/python3/image.bzl#L112).

Originally my BUILD file had something like this (which was failing with the same error):
```
load("@io_bazel_rules_docker//python3:image.bzl", "py3_image")

py3_image(
    name = "my_py3_image",
    srcs = glob(["*.py"]),
    deps = [
        "//foo:bar",
        "//third_party/python/common:grpcio",
    ],
    base = "@my_py3_base//base_image"
)
```

and I turned it into this:

```
load("@io_bazel_rules_docker//lang:image.bzl", "app_layer")

app_layer(
    name = "my_py3_image",
    base = "@my_py3_base//base_image",
    binary = ":my_py3_binary",
    create_empty_workspace_dir = True,
    entrypoint = ["/usr/bin/python3"]
)

py_binary(
    name = "my_py3_binary",
    srcs = glob(["*.py"]),
    deps = [
        "//foo:bar",
        "//third_party/python/common:grpcio",
    ],
)
```

I don't know why it worked but since making this change, I haven't seen this problem anymore.
Your mileage may vary, though.

**Comment by HuanwenChen312** [comment]
Hi @sbairos, I'm trying your workaround, may I know what python base image are you using? I'm using 
`container_pull(
    name = "py3_image_base",
    digest = "sha256:d5a717649fd93ea5b9c430d7f84e4c37ba219eb53bd73ed1d4a5a98e9edd84a7",
    registry = "gcr.io",
    repository = "distroless/python3-debian10",
    tag = "latest",
)`
but after then I got error
`Neither 'python3' nor 'python' were found on the target platform's PATH`
, also I'm wondering how did you import grpcio dependency, I'm using [pip install](https://github.com/bazelbuild/rules_python#importing-pip-dependencies) and not sure if that might be the culprit.

**Comment by sbairos** [comment]
Hi @HuanwenChen312, so I was working on this problem at work and at work we actually use a custom docker image based off of [ubuntu_docker 16.04](https://hub.docker.com/layers/ubuntu/library/ubuntu/16.04/images/sha256-fa75879dbfde012f6c5b50ac35d0d46e8c3c3d07f7383997865161baf91d6bd7?context=explore) with Python3 installed in it at the path `/usr/bin/python3`. I think using ubuntu_docker 20.xx has python3 installed at the same path by default if you want to try that.
We also install packages in a very custom way.

If you were getting the original error that @eap posted,  I think keeping the same base image and imports should work.

I've never seen that error message before, does that happen during `bzl build` or when you run the docker image? Feel free to try changing the `entrypoint` of your app_layer to whatever path python is installed in your image, that might help too

**Comment by HuanwenChen312** [comment]
Hi @sbairos , thanks for your reply, I build the image with `bazel build` command, it succeeded. The error was shown when I try to start the image with `bazel run` command.

**Comment by HuanwenChen312** [comment]
I found the python executable path for `distroless/python3-debian10`, it's `/usr/bin/python3.7`, but now I'm getting different error which is `standard_init_linux.go:211: exec user process caused "no such file or directory"`

**Comment by HuanwenChen312** [comment]
I used different image, and `standard_init_linux.go:211: exec user process caused "no such file or directory` did not show up but now I still get same error: `ImportError: cannot import name 'cygrpc' from 'grpc._cython'`

**Comment by HuanwenChen312** [comment]
Is it possible [pip_install rule](https://github.com/bazelbuild/rules_python#importing-pip-dependencies) can't work well with py3_image? Does anyone have any recommendation on other ways to bring in third party dependency? Any help would be appreciated, thanks!

**Comment by odashi** [comment]
I encountered the same issue too, and it was somehow resolved after adjusting the Python version to 3.7 in both the host and the container. As far as I checked `pip_install` is still working for me.

Also, to use `app_layer` directly, I think `py_binary` may need [`exec_compatible_with`](https://github.com/bazelbuild/rules_docker/blob/7da0de3d094aae5601c45ae0855b64fb2771cd72/python3/image.bzl#L99) attribute as well.

**Comment by ax-meyer** [comment]
FWIW, this issue still persists and is very annoying.

**Comment by jscheel** [comment]
The problem is that bazel is happily copying the host-compiled lib for grpc, instead of one compatible with your container's platform. Take a look here how to download the wheels that will work for you: https://github.com/bazelbuild/rules_python/pull/773#issuecomment-1202118678

You will probably want to use the multilinux_2_17 wheels.
