### ISSUE TITLE
broken dependencies with latest (0.14.4) and bazel 3.4

### ISSUE THREAD

**Issue by leeschumacher** [bazelbuild/rules_docker#1563]
/io_bazel_rules_docker/container/BUILD:41:11: no such package '@pip_deps_pypi__six_1_11_0//': The repository '@pip_deps_pypi__six_1_11_0' could not be resolved and referenced by '@io_bazel_rules_docker//container:build_tar_lib'

**Comment by smukherj1** [comment]
This is likely a duplicate of #1550. Please ensure you're following the setup instructions [here](https://github.com/bazelbuild/rules_docker#setup). Ignore the `docker_toolchain_autoconfigure` part which is OPTIONAL (as noted in the README as well)

**Comment by leeschumacher** [comment]
thanks - adding the pip_deps repo fixed it.

**Comment by mmlac** [comment]
As far as I can see this is a breaking change from 0.14.3 to 0.14.4. Can we have those in the release notes? (not sure if you can update those after you pushed the release, as it seems to have been a bug / missing infor that was addressed the day after the release?)
