### ISSUE TITLE
java_image rule ignores jvm_flags argument

### ISSUE THREAD

**Issue by aalexand** [bazelbuild/rules_docker#157]
java_binary in Bazel [accepts](https://docs.bazel.build/versions/master/be/java.html#java_binary.jvm_flags) that, but passing it to the java_image rule appears to ignore it. Being able to pass JVM flags is important for tuning the JVM behavior or for configuring the app to run with a JVMTI agent, such as a profiler.

**Comment by mattmoor** [comment]
@aalexand I assume you can reproduce this with `//docker/testdata:java_image`, can you include the exact command you used to run it?

**Comment by mattmoor** [comment]
I see it now.  `jvm_flags` goes into the wrapper script, and I'm invoking `java` directly and constructing the `--classpath` myself.

This should be a relatively easy fix, but I'd like to land [this](https://github.com/bazelbuild/rules_docker/pull/156) before I change this.

**Comment by mattmoor** [comment]
(famous last words) ;-)
