### ISSUE TITLE
override tag in container_image

### ISSUE THREAD

**Issue by teto** [bazelbuild/rules_docker#1570]
I would like to see the different images built via bazel appear in my local docker `docker images -a`

According to the README `bazel run` should do it but in my case the tag doesn't conform to docker representation and I can't seem to override it in container_image.

```
bazel run //testapp/result-store:result-store-service@image
Target //testapp/result-store:result-store-service@image up-to-date:
  bazel-bin/testapp/result-store/result-store-service@image-layer.tar
INFO: Build completed successfully, 1 total action
Loaded image ID: sha256:218fc2b8d2d1f972fe8fa22314110b8d1f0a8ed729efcf4c0dec70c5f6d2dd19
Tagging 218fc2b8d2d1f972fe8fa22314110b8d1f0a8ed729efcf4c0dec70c5f6d2dd19 as registry.corp.com/project/project/testapp/result-store:result-store-service@image
Error parsing reference: "registry.corp.com/project/project/testapp/result-store:result-store-service@image" is not a valid repository/tag: invalid reference format
```

I thought I could run a local registry (being new to docker, I am not sure how it would interact with the docker daemon) but it seems like a no go https://github.com/bazelbuild/rules_docker/issues/1454.

`docker tag sha256:218fc2b8d2d1f972fe8fa22314110b8d1f0a8ed729efcf4c0dec70c5f6d2dd19 registry.corp.com/project/project/testapp/result-store:local`

I would very much like to be able to override the tag in container_image so that it is used in https://github.com/bazelbuild/rules_docker/blob/master/container/layer_tools.bzl#L252

Also in my experience, even with stamp=True, repository wouldn't accept variables like "{MY_VARIABLE}" while the same variable is accounted for in container_push.

**Comment by smukherj1** [comment]
Hi there, feel free with create a PR implementing this along with tests and we'll be happy to review
