### ISSUE TITLE
How download_pkgs & install_pkgs are working with Bazel's remote caching feature?

### ISSUE THREAD

**Issue by teran** [bazelbuild/rules_docker#1572]
Hello,

I have CI configuration with remote caching for a couple of bazel workers which are testing incoming commits.
Some of images we defined with bazel are using `download_pkgs` & `install_pkgs` and it started to rebuild those targets without any change to them. Docker images obviously are cleaned after previous CI passes (if that matters) but remote cache is available and consistent.

So could you please provide some details how these rules are cacheable with Bazel's remote caching feature?

Thanks in advance.

**Comment by smukherj1** [comment]
Hi @teran,

You can find what `download_pkgs` depends on [here](https://github.com/bazelbuild/rules_docker/blob/v0.14.4/docker/package_managers/download_pkgs.bzl#L160). Possibly one of these inputs changed (maybe the image.tar?) or bazel decided to rebuild a dependency. I'm wondering if you can try the [explain](https://docs.bazel.build/versions/master/command-line-reference.html#flag--explain) flag to get Bazel to tell you which dependency caused it to rerun the action.

**Comment by teran** [comment]
Hello @smukherj1,

Thanks for the way to troubleshoot that!
I've probably got what the problem was: we have two steps in CI - `bazel build` and `bazel test`, I'm checking if that's the reason, and get back with feedback shortly.

Thanks!

**Comment by teran** [comment]
So, I've considered removing build step and it was the thing caused building the images twice (obviously).

Thanks!
