### ISSUE TITLE
The use of set() breaks docker_build under Bazel 0.6.0

### ISSUE THREAD

**Issue by hwright** [bazelbuild/rules_docker#158]
Building a trivial `docker_build` rule with the Bazel release-0.6.0 branch, I get the following:

`$ bazel build :foo-image
Extracting Bazel installation...
..........................................................
ERROR: /private/var/tmp/_bazel_hwright/0c1dcd494edf6933a7c645d083d11d41/external/python_base/image/BUILD:6:1: in docker_import_ rule @python_base//image:image: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_hwright/0c1dcd494edf6933a7c645d083d11d41/external/python_base/image/BUILD", line 6
		docker_import_(name = 'image')
	File "/private/var/tmp/_bazel_hwright/0c1dcd494edf6933a7c645d083d11d41/external/io_bazel_rules_docker/docker/import.bzl", line 98, in _docker_import_impl
		struct(runfiles = runfiles, files = set([...]), ...)
	File "/private/var/tmp/_bazel_hwright/0c1dcd494edf6933a7c645d083d11d41/external/io_bazel_rules_docker/docker/import.bzl", line 99, in struct
		set([ctx.outputs.out])
The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false.
ERROR: Analysis of target '//:foo-image' failed; build aborted.
INFO: Elapsed time: 41.006s
$`

It's pretty easy to work around this with the `--incompatible_disallow_set_constructor=false` flag to Bazel, but it'd be nice to get this fixed and avoid the error.

**Comment by mattmoor** [comment]
@hwright Are you hitting this at HEAD or just with the release from the `README.md`?

**Comment by hwright** [comment]
I'm hitting this on Bazel HEAD on both master and release-0.6.0.

I'm using v0.1.0 of the docker rules, per the README.md:

```
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    tag = "v0.1.0",
)
```

**Comment by mattmoor** [comment]
I need to cut another release, the one in the docs is relatively old.  HEAD should be in a good state, if you want to pick that up to get around the issue (and please let me know if you have any issues).

I'll TAL a look at what's in flight to see what else I'd like to land, but I'll plan to cut a release ASAP.

**Comment by hwright** [comment]
Awesome, thanks!

**Comment by mattmoor** [comment]
Ok, I cut `v0.2.0` and updated the docs.  LMK if you have any trouble.
