### ISSUE TITLE
rules_docker does not work with bazel 3.4.0

### ISSUE THREAD

**Issue by rajatvig** [bazelbuild/rules_docker#1583]
Upgrading to Bazel 3.4.0 throws errors in the logs like

```
(16:13:14) ERROR: /private/var/tmp/_bazel_rvig/6621b690da1486a6482c087733c0c0e3/external/io_bazel_rules_docker/container/BUILD:41:11: no such package '@pypi__python_gflags_3_1_2//': The repository '@pypi__python_gflags_3_1_2' could not be resolved and referenced by '@io_bazel_rules_docker//container:build_tar_lib'
(16:13:14) ERROR: /private/var/tmp/_bazel_rvig/6621b690da1486a6482c087733c0c0e3/external/io_bazel_rules_docker/container/BUILD:41:11: no such package '@pypi__six_1_11_0//': The repository '@pypi__six_1_11_0' could not be resolved and referenced by '@io_bazel_rules_docker//container:build_tar_lib'
```

**Comment by rockwotj** [comment]
Did you try upgrading to the latest version of these rules?

**Comment by subotic** [comment]
Also, when you upgrade to the new rules_docker version, don't forget to add
the few new necessary lines of configuration. I had the same error, because
I didn't see that the incantation changed.

Best,
Ivan

**Comment by rajatvig** [comment]
Yeah, missed the lines to add `pip_deps`. It works now.

**Comment by sagitiminsky** [comment]
Hi,
I have the same error. could you please specify what lines did you add?

Thanks,
Sagi

**Comment by neakor** [comment]
How come this isn't in the README?
