### ISSUE TITLE
Container pull fails due to i/o timeout

### ISSUE THREAD

**Issue by kagrawal2** [bazelbuild/rules_docker#1585]
Defined a py_image() with all defaults set on MacOS Catalina
py_image_base Container pull fails due i/o timeout.
`
Repository rule container_pull defined at:
/private/var/tmp/_bazel_kireet/6af5e6d303c12f8671f1a27b9f41a33c/external/io_bazel_rules_docker/container/pull.bzl:228:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'py_image_base':
   Pull command failed: 2020/08/08 02:11:34 Running the Image Puller to pull images from a Docker Registry...
2020/08/08 02:13:19 Image pull was unsuccessful: reading image "gcr.io/distroless/python2.7@sha256:ebe778d426d1d78a3954bf61deacc4371a430200a1f1c88b16e913bc5192aebf": Get "https://gcr.io/v2/": dial tcp: lookup gcr.io on <IP1:PORT1>: read udp <IP2:PORT2>-><IP1:PORT1>: i/o timeout
 (/private/var/tmp/_bazel_kireet/6af5e6d303c12f8671f1a27b9f41a33c/external/go_puller_darwin/file/downloaded -directory /private/var/tmp/_bazel_kireet/6af5e6d303c12f8671f1a27b9f41a33c/external/py_image_base/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/python2.7@sha256:ebe778d426d1d78a3954bf61deacc4371a430200a1f1c88b16e913bc5192aebf)
`
Any ideas?

docker pull gcr.io/distroless/python2.7@sha256:ebe778d426d1d78a3954bf61deacc4371a430200a1f1c88b16e913bc5192aebf
succeeds.

**Comment by ouceduxzk** [comment]
same problem for me, with a base image of 1.8G

**Comment by cristifalcas** [comment]
Use `PULLER_TIMEOUT` to increase the timeout: https://github.com/bazelbuild/rules_docker/blob/master/docs/container.md#container_pull

**Comment by IntepayHK** [comment]
Using Ansible to Pull Docker Image and saving as tarball failed
```
TASK [archive backend image as a tarball] **************************************
fatal: [**.**.**.**]: FAILED! => {"changed": false, "msg": "Error getting image ghcr.io/***/***/***:latest - UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)"}
```
