### ISSUE TITLE
Non-root user for `nodejs_image`

### ISSUE THREAD

**Issue by danielepolencic** [bazelbuild/rules_docker#1591]
I'm building a container that runs in a Kubernetes cluster. The container should not run as root.
I built the container with:

```bazel
container_image(
    name = "nodejs_base_image",
    base = "@nodejs_base_image//image",
    user = "node",
)

nodejs_image(
    name = "server",
    base = ":nodejs_base_image",
    data = [
        ":dependencies",
    ],
    entry_point = "entry.js",
)
```

However, when the container starts, I can see the following error:

```
[link_node_modules.js] An error has been reported: [Error: EACCES: permission denied, symlink '/app/server.binary.runfiles/npm/node_modules' -> 'node_modules'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'symlink',
  path: '/app/server.binary.runfiles/npm/node_modules',
  dest: 'node_modules'
} Error: EACCES: permission denied, symlink '/app/server.binary.runfiles/npm/node_modules' -> 'node_modules'
```

How can I fix the permissions? Should I run the container as root?

**Comment by zoidbergwill** [comment]
So it seems to be at:

```
/app/blah/image.binary.runfiles/nodejs_linux_amd64/bin/nodejs/bin/node /app/blah/image.binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js /app/blah/image.binary.runfiles/workspace/blah/_image.binary.module_mappings.json

**Comment by zoidbergwill** [comment]
So it's because of the `rules_nodejs` [linker](https://github.com/bazelbuild/rules_nodejs/tree/stable/internal/linker)

**Comment by zoidbergwill** [comment]
So adding the following to the `nodejs_image` rule seemed to work for me, but I think it'd only work in some subset of cases:

```
nodejs_image(
    # other bits...
    args = [
        "--nobazel_run_linker",
        "--nobazel_node_patches",
    ]
```

**Comment by mathieubergeron** [comment]
@zoidbergwill :
> So adding the following to the `nodejs_image` rule seemed to work for me, but I think it'd only work in some subset of cases:
> 
> ```
> nodejs_image(
>     # other bits...
>     args = [
>         "--nobazel_run_linker",
>         "--nobazel_node_patches",
>     ]
> )
> ```

Did you meant `templated_args`? The following worked for me:

```
nodejs_image(
    # other bits...
    templated_args = [
        "--nobazel_run_linker",
        "--nobazel_node_patches",
    ]
)
```

Reference:
- https://github.com/bazelbuild/rules_docker/blob/v0.15.0/nodejs/image.bzl#L128
- https://bazelbuild.github.io/rules_nodejs/Built-ins.html#nodejs_binary-templated_args

Thanks!
