### ISSUE TITLE
export as an oci-archive tar file

### ISSUE THREAD

**Issue by smijolovic** [bazelbuild/rules_docker#1603]
container_push allows the push of a tar to docker, but there is no way to support secure environments that want to use  rootless/daemonless container solutions.

To support all container runtimes, it would be ideal to push a tar or directory to an OCI compliant image archive (.tar) so that it can be loaded with non-docker based solutions.

**Comment by smukherj1** [comment]
Hi there, this would need to be implemented in github.com/google/go-containerregistry first. After that, we could look into rules_docker's `container_image` rule to accept an attribute that specifies the format of the image tarball.

FYI @jonjohnsonjr

**Comment by chanseokoh** [comment]
Let me help here:

@smijolovic I think you are confused. `container_push` is to push images to a remote registry.

@smukherj1 the context is that @smijolovic is loading images to a local container runtime (specifically podman, if that matters). And yes, I know podman by default loads tarball images in Docker format, but for some reason, @smijolovic encountered some issues, and possibly as a workaround, @smijolovic now wants have a local tarball image in OCI format. There is no remote image push involved.

**Comment by chanseokoh** [comment]
@smukherj1 unrelated to the issue to create a local OCI tarball, looks like [`container_push`](https://github.com/bazelbuild/rules_docker#container_push-1) already supports `format = 'OCI'`? (OTOH, `container_image` doesn't have `format`.)

**Comment by jonjohnsonjr** [comment]
There are two related things here that might be causing confusion.

The format of image manifests for the OCI spec is largely the same as docker images, with slight changes to the media types used. This is described [here](https://github.com/opencontainers/image-spec/blob/master/manifest.md), and I believe rules_docker already supports pushing images like this via the `format = 'OCI'` property as @chanseokoh described.

There is also an [OCI Image Layout Specification](https://github.com/opencontainers/image-spec/blob/master/image-layout.md) that defines how you can write an image (or collection of images) to disk (or a tarball). We have (poorly documented) support for this in [go-containerregistry](https://github.com/google/go-containerregistry/tree/master/pkg/v1/layout). I'm guessing that @smijolovic is asking for the ability to export images as an OCI image layout tar, similar to [`container_bundle`](https://github.com/bazelbuild/rules_docker#container_bundle-1), which exports images in the `docker save` format.

Is that correct?

I'd generally view this as a good idea, but I'm not familiar enough with rules_docker to know how hard it would be to implement. We had a lengthy discussion over in https://github.com/google/go-containerregistry/issues/651 about how you can produce an archive that functions as both a `docker save` tarball and an OCI tarball, so we might be able to do this in a backward-compatible way without introducing any additional options.

**Comment by chanseokoh** [comment]
> Is that correct?

Correct.

**Comment by smukherj1** [comment]
@chanseokoh ah apologies I wasn't clear in my initial response. I did mean to imply that rules_docker needs to generate the OCI format tarball in container_image which it currently doesn't. I wasn't aware go-containerregistry already supports but I cc'd jonjohnsonjr for exactly this reason :D

So @smijolovic, our image tarball is created in by the [join_layers](https://github.com/bazelbuild/rules_docker/blob/master/container/go/cmd/join_layers/join_layers.go) binary here. You'll need to update this to generate the OCI tarball pass in `format` attribute from [here](https://github.com/bazelbuild/rules_docker/blob/v0.14.4/container/layer_tools.bzl#L157).
