### ISSUE TITLE
architecture should default to that of the base image

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_docker#1636]
Today this defaults to `linux/amd64` unless `architecture` is passed to every layer of the chain.

**Comment by mattmoor** [comment]
cc @jonjohnsonjr @loosebazooka @chanseokoh FYI

**Comment by chanseokoh** [comment]
What if the base image is a manifest list (or `scratch`)? I think `linux/amd64` is the right default. But yeah, if the base image is a manifest, the arch/OS should be that of the base image.

**Comment by mattmoor** [comment]
@chanseokoh It is sort of moot since rules_docker doesn't have a model for multi-arch at all at the moment.

I suspect that multi-arch should treat `arch/os` as overrides to force a particular behavior,  and either:
 * error if they are unspecified, or
 * default to one of: `linux/amd64` or the current os/arch

One interesting back-compat question: What does `docker_pull` of a multi-arch tag do today when presented with this sitatuation?
