### ISSUE TITLE
Need to specify a different entrypoint

### ISSUE THREAD

**Issue by nikunjy** [bazelbuild/rules_docker#1649]
I have a which is kind of like https://github.com/hashicorp/envconsul
I want this to be the entrypoint of the language image. So let's say I make a `go_image` I want that the entry point is the `envconsul` binary and the command is the `go_image.binary` (basically the actual binary that my code produces).

The only way I have found is to copy over this part and add an argument for `entrypoint`
https://github.com/bazelbuild/rules_docker/blob/master/go/image.bzl#L123

What is the best way to achieve this?

**Comment by nikunjy** [comment]
I can do a PR to support this but not sure if someone will accept it. Any guidance @mattmoor ?

**Comment by sudoforge** [comment]
if i'm understanding your goal, you want to define a rule that is the equivalent of this docker command line:

```docker run --entrypoint=/bin/foo someimage somecommand```

there isn't a way to accomplish this with the `go_image` rule that i'm aware of, but you could accomplish this by creating your own layers with the two binaries and specify your entrypoint/command then.

**Comment by nikunjy** [comment]
There would be a way to accomplish this with `go_image` if it just took entrypoint as one of the argument. I can send a PR I just don't know if someone will actually engage me with that, looking at response on this issue. @sudoforge

**Comment by nikunjy** [comment]
@smukherj1 can you guide here ? Would such a PR be acceptable ?

**Comment by kriswuollett** [comment]
Can this be reopened? Is passing through `entrypoint` an acceptable solution? I'd expect to use this by creating a custom `go_image` with a layer that adds `dlv` for debugging, and then change the entrypoint to `dlv` launching the original binary. I assume simple string manipulation of the `binary` argument can yield the final symlinked path to form the new `entrypoint` in a macro?

**Comment by kriswuollett** [comment]
Although an easy workaround would be to change it in a deployment spec, I'd rather the wrapper script be controlled through environment variables so any deployment args apply just to the underlying binary.
