### ISSUE TITLE
"could not set sticky bit" when using Podman

### ISSUE THREAD

**Issue by SanjayVas** [bazelbuild/rules_docker#1663]
Building targets with rules that call Docker to load images, such as `container_run_and_commit_layer`, results in the following error with using Podman/libpod as a non-root user. The same succeeds with rootless Docker (passing `--action_env=DOCKER_HOST`).

> could not set sticky bit on /run/user/129944/libpod: chmod /run/user/129944/libpod: read-only file system

This is related to GoogleContainerTools/distroless/issues/572 which led to bazelbuild/rules_docker#1603, but the latter focuses on OCI vs. Docker format images. As surmised in the distroless issue, the problem seems to be a conflict between how Linux sandboxing with Bazel mounts some paths as readonly and how Podman sets the sticky bit on a file in the user runtime directory when run.

Bazel version: release 3.7.0
rules_docker commit: cc45596d140b3b8651eb7b51b561f1bf72d1eea9

**Comment by kurt-google** [comment]
It would be nice if docker rules could set XDG_RUNTIME_DIR to avoid this issue.
