### ISSUE TITLE
[puller] Feature request: support registry-mirrors global configuration

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/rules_docker#1664]
Recently I had to change a lot of my `container_pull` definitions to prepare for this:

> As of November 1, 2020, Docker Hub [rate limits](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/) apply to unauthenticated or authenticated pull requests on the Docker Free plan. To avoid disruptions and have greater control over your software supply chain, you can migrate your dependencies to Container Registry or Artifact Registry.

Basically I replaced:
```python
container_pull(
    name = "redis_latest",
    registry = "index.docker.io",
    repository = "library/redis",
    tag = "latest"
  )
```
with
```python
container_pull(
    name = "redis_latest",
    registry = "mirror.gcr.io",
    repository = "library/redis",
    tag = "latest"
  )
```

I found it a little awkward that I can't configure `registry-mirrors` globally by global bazelrc.
In non-bazel builds that use native docker client they just added this global config to their docker daemon:
```json
{
  "registry-mirrors": ["https://mirror.gcr.io"]
}
```

I know we love everything to be defined in our committed source code but in this case - I think there's a great value in allowing global definition.  

BTW: I see that `docker_toolchain_configure` has `client_config` property - but I'm pretty sure it's not used in case of the puller (am I wrong?). Maybe the best case would be to read that property directly from the client_config.

**Comment by smukherj1** [comment]
Hi @or-shachar,

Generally you're right that injecting files whose contents aren't part of the source tree is an anti-pattern. However, if the docker client supports this, it makes sense for rules_docker to support this as well.

Note that client_config is a standard docker client configuration JSON and I would make rules_docker accept arbitrary fields from this file unless docker recognizes it as well. Put another way, if docker client doesn't expect `registry-mirrors` in the client config JSON, I wouldn't update rules_docker to expect it in that file. OTOH, if the client config JSON is where docker client reads the registry mirrors from, I'm open to having rules_docker support it as well.

I'm open to PR(s) that implements this. It's possible part of the implementation needs to be in go-containerregistry.

**Comment by rmohr** [comment]
#1789 would solve our use-case. @or-shachar would it solve yours too?

**Comment by sluongng** [comment]
Just FYI we have had a lot of discussion around the approach to solve this in Bazel Build Slack

https://bazelbuild.slack.com/archives/CA3NW13MH/p1618411736057600
https://bazelbuild.slack.com/archives/CA3NW13MH/p1618501747076700

The general consensus is that the Container eco system (docker, podman, etc...) support too many versions of `registry-mirror` setting. And we are currently unsure between several choices:

A. Should we support `registry-mirrors` or `http_proxy` or `.netrc` or bazel's own `--experimental-downloader-config` any combination of those configs while pulling container images.

B. If we were to support `registry-mirrors` config, should that abstraction live in `rules_docker` or it's dependency, `google/go-containerregistry`. @gravypod, maintainer of go-containerregistry, seems to be in favor of having that supported in that repo and willing to review a PR for it.

**Comment by or-shachar** [comment]
@rmohr sorry for late response - we eventually solved it by introducing an indirection to `container_pull`:
```python
load(
  "@io_bazel_rules_docker//container:container.bzl",
  container_pull_real = "container_pull"
)
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

_MIRROR_URL="..."
def container_pull(name, registry, **kwargs):
  # rewriting docker-hub registry to our proxy in artifactory since soon they will limit anonymous requests
  actual_registry = _MIRROR_URL if registry == "index.docker.io" else registry
  kwargs['registry'] = actual_registry
  maybe(
    name = name,
    repo_rule = container_pull_real,
    **kwargs
  )
```

**Comment by gravypod** [comment]
> @gravypod, maintainer of go-containerregistry

I'm currently only a maintainer on `rules_docker` (for now :wink:). Still, thank you for the summary @sluongng! 

> we eventually solved it by introducing an indirection to container_pull

@or-shachar, that's awesome. I think for now we can recommend that as a short-term fix and in the long term correctly address it in rules_docker/go-containerregistry when we find a good cross-system solution.
