### ISSUE TITLE
sha256 print needs parens

### ISSUE THREAD

**Issue by hwright** [bazelbuild/rules_docker#168]
I'm getting a failure when using python3 with the docker build rules at version 0.2.1.  This appears to be fixed at HEAD.

```
$ cat .bazelrc
test --test_output=errors

run --force_python=py3
test --force_python=py3
build --force_python=py3

run --python_path=/usr/local/bin/python3
test --python_path=/usr/local/bin/python3
build --python_path=/usr/local/bin/python3

$ bazel build :app
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_hwright/0c1dcd494edf6933a7c645d083d11d41/external/python_base/image/BUILD:6:1: SHA256 external/python_base/image/001.tar.gz.nogz.sha256 failed (Exit 1).
  File "/private/var/tmp/_bazel_hwright/0c1dcd494edf6933a7c645d083d11d41/bazel-sandbox/1250952573107272256/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/docker/sha256.runfiles/__main__/../io_bazel_rules_docker/docker/sha256.py", line 23
    print "Usage: %s input output" % sys.argv[0]
                                 ^
SyntaxError: Missing parentheses in call to 'print'
Target //:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.296s, Critical Path: 0.24s
$
```

**Comment by mattmoor** [comment]
@hwright There definitely isn't great testing of the Python3 support in these rules, but it's come up enough times that I should definitely add testing and ensure things are compatible.

At a minimum I'll get the `print` fixed for the next release of the library / rules.

**Comment by mattmoor** [comment]
Ah, this isn't in the library I was thinking of.  You are talking about the `sha256` utility, which as of this past weekend we get from Bazel core :(

Maybe I can get a cherry-pick into Bazel 0.6.x, but that's going to be a lot slower than I originally thought.

/me returns to sipping his coffee...

**Comment by mattmoor** [comment]
Oh, I see parens in the [version in Bazel at HEAD](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/hash/sha256.py#L24), so perhaps 0.6 fixes this.

**Comment by hwright** [comment]
This works just fine with rules_docker HEAD; your fix from this past weekend got rid of the problem.  I think the solution is just to cut a new release and update the docs.

**Comment by mattmoor** [comment]
Ah, sorry I misread your comment.  You are right, thanks.
