### ISSUE TITLE
Documentation on how to have multiple binary targets in a single container

### ISSUE THREAD

**Issue by karolistamutis** [bazelbuild/rules_docker#1689]
For language specific images, such as go_image() it only accepts a single binary as source. I want the base image but to have two binaries of mine - service binary and prober binary for K8s liveliness/readiness checks, how can I package them in a single container?

How can I specify multiple binary targets? I could build the prober in the service binary and have it flag controlled but I'd like to have a separate binary.

```
go_image(
    name = "image",
    base = ":base_image",
    binary = ":service_binary",
    goarch = "amd64",
    goos = "linux",
    pure = "on",
)
```

**Comment by amalucelli** [comment]
I had the same situation, and what I did to handle this was to create a `container_layer` with the reference for the other binary that I wanted to package.

For example, let's say you have this folder structure:

```
cmd/app/BUILD.bazel
cmd/app/init/BUILD.bazel
```

In the `cmd/app/init/BUILD.bazel` you add the spec for `go_image`:

```go
go_image(
    name = "foo",
    base = "@alpine_linux_amd64//image",
    embed = [":go_default_library"],
    goarch = "amd64",
    goos = "linux",
    pure = "on",
    visibility = ["//visibility:public"],
)
```

In the `cmd/app/BUILD.bazel`, you add the `container_layer` and later package it in the `container_image`:

```go
container_layer(
    name = "init",
    tars = [
        "//cmd/app/init:foo",
    ],
    visibility = ["//visibility:public"],
)

go_image(
    name = "bar",
    base = "@alpine_linux_amd64//image",
    embed = [":go_default_library"],
    goarch = "amd64",
    goos = "linux",
    pure = "on",
    visibility = ["//visibility:public"],
)

container_image(
    name = "image",
    base = ":bar",
    layers = [
        ":init",
    ],
    symlinks = {
        "/bar": "/app/cmd/app/bar.binary",
        "/foo": "/app/cmd/app/init/foo.binary",
    },
    visibility = ["//visibility:public"],
)
```
