### ISSUE TITLE
On MacOS, container_push() appears not respecting --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64

### ISSUE THREAD

**Issue by justicezyx** [bazelbuild/rules_docker#1701]
It seems the --platform flag does not cause bazel to build the correct executable that matches the flag value.

```
$ bazel build :http_server_image.tar --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64
$ docker load -i bazel-bin/http_server_image.tar
$ docker run bazel:http_server_image
```
The above works as expected: Since this is Docker on mac, docker runs things in a VM, so the bazel builds uses --platform to build a linux executable.

Now with `container_push()` rule:
```
$ bazel run :push_http_server_image --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64
$ docker run gcr.io/http_server:zyx
standard_init_linux.go:219: exec user process caused: exec format error
```

Which I suppose failed because --platform flag does not take effect for the built executable.

The BUILD file:
```
load("@io_bazel_rules_docker//go:image.bzl", "go_image")
load("@io_bazel_rules_docker//container:container.bzl", "container_push")
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/justicezyx/everywhere
gazelle(name = "gazelle")

go_library(
    name = "go_default_library",
    srcs = ["http_server.go"],
    importpath = "github.com/justicezyx/everywhere",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "http_server",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)

go_image(
    name = "http_server_image",
    binary = ":http_server",
)

container_push(
    name = "push_http_server_image",
    image = ":http_server_image",
    registry = "localhost:5000",
    format = "Docker",
    repository = "http_server",
    tag = "{BUILD_USER}",
)
```

**Comment by mgenov** [comment]
On my side it works properly with go_image and container_push but when used with kt_jvm_image and container_push I'm getting the following message:

```
INFO: Build option --toolchain_resolution_debug has changed, discarding analysis cache.
ERROR: While resolving toolchains for target //kotlin/libs:gson_lib_deps: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
ERROR: Analysis of target '//services/infra/configuration/java/server:push' failed; build aborted: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
INFO: Elapsed time: 0.576s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 415 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 415 targets configured)
```

e.g it looks like an issue with tool-chain resolution 

Note that the image build succeeds without issues.

**Comment by mgenov** [comment]
Sounds reasonable. Added tracking issue in https://github.com/bazelbuild/rules_kotlin/issues/458

**Comment by justicezyx** [comment]
> On my side it works properly with go_image and container_push but when used with kt_jvm_image and container_push I'm getting the following message:
> 
> ```
> INFO: Build option --toolchain_resolution_debug has changed, discarding analysis cache.
> ERROR: While resolving toolchains for target //kotlin/libs:gson_lib_deps: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
> ERROR: Analysis of target '//services/infra/configuration/java/server:push' failed; build aborted: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
> INFO: Elapsed time: 0.576s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded, 415 targets configured)
> FAILED: Build did NOT complete successfully (0 packages loaded, 415 targets configured)
> ```
> 
> e.g it looks like an issue with tool-chain resolution
> 
> Note that the image build succeeds without issues.

Could you provide the configuration of your mac environment?

I am using docker machine and bazel version 3.2.0.

**Comment by mgenov** [comment]
Sure
OS: macOS Catalina
Bazel: 3.7.0-homebrew
