### ISSUE TITLE
Optionally include correct timestamps in docker images

### ISSUE THREAD

**Issue by hwright** [bazelbuild/rules_docker#172]
Using my favorite [trivial repository](https://github.com/bazelbuild/rules_docker/files/1333566/foo.tar.gz):

```
$ tar -xvzf foo.tar.gz
...
$ cd foo
$ bazel run :app
..........................................................
INFO: Found 1 target...
Target //:app up-to-date:
  bazel-bin/app-layer.tar
INFO: Elapsed time: 13.408s, Critical Path: 1.43s

INFO: Running command line: bazel-bin/app
Loaded image ID: sha256:a91e409ea874b3e21eb2591a7496fa6a81f34148a21729838e3562db50e19983
Tagging a91e409ea874b3e21eb2591a7496fa6a81f34148a21729838e3562db50e19983 as bazel:app
$  docker image list bazel:app
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
bazel               app                 a91e409ea874        47 years ago        88.8MB
$
```

The docker image creation time is shown as 47 years ago, which likely corresponds to the start of the Epoch, and a default timestamp of 0.

While using timestamps inside of containers would make them non-reproducible, it would be nice to enable the option to do so, so that users could easily determine when a container was created.  It was also help the resulting containers play nicely with timestamp-based tooling.

This would be similar to the existing support for stamping.

**Comment by mattmoor** [comment]
Yeah, you want [this](https://github.com/bazelbuild/rules_docker/issues/155)

**Comment by mattmoor** [comment]
Let's track this there.

**Comment by hwright** [comment]
Indeed I do, thanks!
