### ISSUE TITLE
container_test selects structure_test_executable for target platform, fails with cross-compilation

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_docker#1726]
When cross-compiling our binaries to run under docker (using `bazel test --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64_cgo` ), the container_test selects the target platform for structure_test_executable here:
https://github.com/bazelbuild/rules_docker/blob/master/contrib/test.bzl#L110

When running the test on a mac, this results in trying to run the linux executable which fails of course.

I *think* this tool should be configured for the execution platform instead (`cfg = "exec"`)

**Comment by jan25** [comment]
I'm facing below errors with `container_test` on my mac which looks related this issue. Would #1727 fix this?
```
ERROR: /private/var/tmp/_bazel_jan25/28a64162cd712d25eae2bdc28d7797d7/external/io_bazel_rules_docker/contrib/BUILD:52:6: Illegal ambiguous match on configurable attribute "actual" in @io_bazel_rules_docker//contrib:structure_test_executable:
@bazel_tools//src/conditions:darwin
@bazel_tools//src/conditions:darwin_x86_64
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//app/hello-world:hello-world_image_test' failed; build aborted: /private/var/tmp/_bazel_jan25/28a64162cd712d25eae2bdc28d7797d7/external/io_bazel_rules_docker/contrib/BUILD:52:6: Illegal ambiguous match on configurable attribute "actual" in @io_bazel_rules_docker//contrib:structure_test_executable:
@bazel_tools//src/conditions:darwin
@bazel_tools//src/conditions:darwin_x86_64
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: Elapsed time: 0.212s
INFO: 0 processes.
```

**Comment by alexeagle** [comment]
No that's #1674

We could really use a rules_docker release, there hasn't been one since
december...
