### ISSUE TITLE
container_test synthetic image does not inherit tags from the macro

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_docker#1729]
A container_test rule "foo_test" will generate another target "foo_test.image" but currently tags like "tags = ['requires-cgo'] are not propagated to that image. 

<img width="1077" alt="Screen Shot 2021-02-08 at 12 31 58 PM" src="https://user-images.githubusercontent.com/50580/107271567-acb93180-6a09-11eb-9c8a-51a319c4f50d.png">

**Comment by aw185176** [comment]
`"manual"` is the one that is currently biting me

**Comment by pcj** [comment]
@alexeagle ping
