### ISSUE TITLE
Container image digest doesn't match loaded image digest

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/rules_docker#1740]
The sha256 of the image loaded into Docker differs from that of `:target.digest`.

```sh
$ bazel run //:image
INFO: Analyzed target //:image (1 packages loaded, 1 target configured).
INFO: Found 1 target...
Target //:image up-to-date:
  bazel-bin/image-layer.tar
INFO: Elapsed time: 0.346s, Critical Path: 0.24s
INFO: 7 processes: 4 internal, 3 darwin-sandbox.
INFO: Build completed successfully, 7 total actions
INFO: Build completed successfully, 7 total actions
Loaded image ID: sha256:8dec145246181d45da85074c30c9438b71f0f8e4a37e2880339bf43f7c07fe94
Tagging 8dec145246181d45da85074c30c9438b71f0f8e4a37e2880339bf43f7c07fe94 as bazel:image
```

but then

```sh
$ cat bazel-bin/image.digest
sha256:afd154bd8c6b7d363aaae4cb5f42f6bdb7bfcacef7b5b4db8f6b3a3de1cdecdc%
```

## Environment

```
Bazel: 4.0.0
rules_docker: archive-e15c9ebf203b7fa708e69ff5f1cdcf427d7edf6f
OS: darwin
```

### WORKSPACE
```bazel
load("@io_bazel_rules_docker//container:container.bzl", "container_pull")

container_pull(
    name = "io_gcr_distroless_static",
    digest = "sha256:359e0c5c9a1364d82f567db01e1419dead4dfc04d33271248f9c713007d0c22e",
    registry = "gcr.io",
    repository = "distroless/static",
)
```

### BUILD.bazel
```bazel
load("@io_bazel_rules_docker//container:container.bzl", "container_image")

container_image(
    name = "image",
    base = "@io_gcr_distroless_static//image",
)
```

**Comment by jonjohnsonjr** [comment]
> `Loaded image ID: sha256:8dec145246181d45da85074c30c9438b71f0f8e4a37e2880339bf43f7c07fe94`

The Image ID and the Image Digest are separate things. The Digest is the sha256 hash of the image [manifest](https://github.com/opencontainers/image-spec/blob/master/manifest.md), whereas the Image ID is the sha256 hash of the [config file](https://github.com/opencontainers/image-spec/blob/master/config.md).

I have drawn a picture [here](https://github.com/google/go-containerregistry/tree/6928f6d356ab814273c1fc7195571b6757a29f0e/pkg/v1/remote#anatomy-of-an-image) to hopefully make this a little more clear.

**Comment by pauldraper** [comment]
Is there a way to get the Image ID (sha256 of the config file) from Bazel?

**Comment by jonjohnsonjr** [comment]
See [here](https://github.com/bazelbuild/rules_docker/blob/40d40363189166657be436714688d29aa0131d1e/container/image.bzl#L766-L768), e.g.:

```
bazel build :<image>.json.sha256
```
