### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_docker#1743]
Can someone make a new release for these rules to include the rename of the [rules_rust](https://github.com/bazelbuild/rules_rust) repo done in https://github.com/bazelbuild/rules_docker/pull/1720

**Comment by UebelAndre** [comment]
@smukherj1 do you think you have time to take a look into this?

**Comment by seh** [comment]
The fixes for #1716 (PRs #1675 and #1676) would also be welcome in a new release.

**Comment by sluongng** [comment]
In a more general sense, I think its more important to get a few active maintainers for this repo.

Looking at the list of PR, there are some interesting fews that could have made it in. Also some basic dependency upgrades for house keeping would be nice.

I guess BazelBuild folks at Google have been lack in resources for this. But perhaps having a way to bring on community maintainers to help out would be nice. That or encourage folks to unite around another fork by archiving this repo (but I think some critical GCP stuffs depending on this though)

**Comment by UebelAndre** [comment]
cc @alexeagle

**Comment by alexeagle** [comment]
@gravypod released https://github.com/bazelbuild/rules_docker/releases/tag/v0.16.0 with everything that was merged at HEAD so I assume that covers all the requests here
