### ISSUE TITLE
Generate docsite

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_docker#1751]
In rules_nodejs we have a pretty nice setup for rendering our stardoc similarly to bazel.build look-and-feel

https://bazelbuild.github.io/rules_nodejs

I think rules_docker would benefit from some sidenav and better structure of the docs rather than the big README.md we have now

**Comment by zoidbergwill** [comment]
This would be amazing. The rules_nodejs docs are great.

**Comment by zoidbergwill** [comment]
I can start a draft PR, if folks wanna start taking a look and reviewing:

![image](https://user-images.githubusercontent.com/2572493/111029405-c7156f00-83fc-11eb-956e-c38d91cb2639.png)

I tried to take a look at how the `rules_nodejs` docs are deployed to GitHub pages, but maybe we could do similar or publish them with netlify like the Kubernetes docs?

I see the previous version of rules_nodejs docs are published to docs.aspect.dev, but I don't think we need to solve previous versions of docs now.

**Comment by zoidbergwill** [comment]
I've got docs generating for the base `container_*` rules and `cc_image` rules

https://agitated-carson-dc8805.netlify.app/built-ins

https://agitated-carson-dc8805.netlify.app/cc

The stardoc rules give some cryptic errors and require splitting some files though, and I'm currently doing them in a backwards incompatible way, so I'll need to move some bits around and add aliases and things.

**Comment by zoidbergwill** [comment]
I'm making a lot of progress, but I realised it's way more complicated than I thought.

Building all the stardoc rules for each language's images requires:
- Splitting each image.bzl into repositories and image rules
- Updating a bunch of language rules we need, to make sure they're exporting the deps that stardoc needs and ideally bzl_library rules we can use
- Add bzl_library or other visibility solutions to some of the other language rules

**Comment by alexeagle** [comment]
Hey @zoidbergwill I just got back to this thread, and am also starting to work on pushing the docs with netlify. You're right that there's a long yak-shaving process first to make stardoc happy. Want to collaborate more on this? (you can ping me on bazel slack)
