### ISSUE TITLE
Spurious build failure "permission denied" on zipper

### ISSUE THREAD

**Issue by djmarcin** [bazelbuild/rules_docker#1788]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: container_layer

### Is this a regression?

Unknown

### Description

Occasionally, builds will spuriously fail with an error like this one:

<pre>
src/main/tools/linux-sandbox-pid1.cc:390: "execvp(bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/zipper/zipper_/zipper, 0x13c9df0)": Permission denied
</pre>

Immediately retrying the same bazel command results in success.

## 🔬 Minimal Reproduction

n/a

## 🔥 Exception or Error

<pre><code>
ERROR: container/BUILD:18:16: GZIP container/layer.tar.gz failed: (Exit 1): zipper failed: error executing command bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/zipper/zipper_/zipper -src bazel-out/k8-fastbuild/bin/box/layer.tar -dst ... (remaining 1 argument(s) skipped)
--
  |  
  | Use --sandbox_debug to see verbose messages from the sandbox zipper failed: error executing command bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/zipper/zipper_/zipper -src bazel-out/k8-fastbuild/bin/container/layer.tar -dst ... (remaining 1 argument(s) skipped)
  |  
  | Use --sandbox_debug to see verbose messages from the sandbox
  | src/main/tools/linux-sandbox-pid1.cc:390: "execvp(bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/zipper/zipper_/zipper, 0x13c9df0)": Permission denied
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 4.0.0
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
rules_docker-0.16.0
  </code>
</pre>

**Anything else relevant?**

**Comment by gravypod** [comment]
Is this in a CI system or something with constrained resources? Do you have any way to reproduce this with an example repository?

**Comment by djmarcin** [comment]
It does occur on our CI system which is typically under heavy load, but we have also observed it on developer machines. We don’t have a reliable repro since it typically immediately resolves when the build is retried.

What circumstance of load would cause permission denied errors? The machines have plenty of disk and ram — cpu is the typical constrained resource.

**Comment by gravypod** [comment]
@djmarcin This is a bit of a longshot but do you think you could collect a build event log from bazel and see if there's anything interesting? I'd normally ask you to post it but it will leak information that some companies might not want shared (file names & hashes, etc). 

There's two main ways to do it: 

1. https://docs.bazel.build/versions/master/build-event-protocol.html#consume-in-text-or-json-formats
2. https://docs.bazel.build/versions/master/remote-execution.html#remote-execution-services

You don't need to use the Remote Execution portion from most of those services. You can use it just as a log collector. Once have the log of a good build and a clean build it might be possible to spot a diff. My best guess is something is flakey but I'm not sure what or where the issue could be coming from. I have seen similar issues in the past though but unfortunately I no longer have access to those code bases.

**Comment by austinpray-mixpanel** [comment]
FWIW we are seeing this a bunch as well. Ubuntu 20.04, bazel 4.0.0

Seeing it on GUNZIP, GZIP, and even create_image_config and such

<details>
<summary>examples</summary>

```
(17:00:54) ERROR: /var/action/(...)/BUILD.bazel:45:21: ImageConfig (...)/image.0.config [for host] failed: (Exit 1): create_image_config failed: error executing command bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/create_image_config/create_image_config_/create_image_config -outputConfig ... (remaining 23 argument(s) skipped)
src/main/tools/process-wrapper-legacy.cc:80: "execvp(bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/create_image_config/create_image_config_/create_image_config, ...)": Permission denied
```
```
(17:00:47) ERROR: /var/action/(...)/start-layer-layer.tar.gz [for host] failed: (Exit 1): zipper failed: error executing command bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/zipper/zipper_/zipper -src bazel-out/host/bin/google-cloud/container/envoyproxy/start-layer-layer.tar -dst ... (remaining 1 argument(s) skipped)
src/main/tools/process-wrapper-legacy.cc:80: "execvp(bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/zipper/zipper_/zipper, ...)": Permission denied
```

</details>

**Comment by fmeum** [comment]
@sgowroji Could you reopen the issue?

We are also getting reports for this in the context of rules_go (https://github.com/bazelbuild/rules_go/issues/3419) with `linux-sandbox`

@larsrc-google @lberki Is this something you have seen at Google? The fact that it seems to affect multiple rulesets and both sandbox and process-wrapper execution is worrying - could there be a race in Bazel's handling of the executable bit?

**Comment by larsrc-google** [comment]
There was an issue like this a while back, but we fixed that by just setting all outputs executable. 

Does it also happen with processwrapper-sandbox?

**Comment by larsrc-google** [comment]
For flaky issues, I like to do `while blaze build <...>; do blaze clean; done` until the error occurs.

**Comment by fmeum** [comment]
https://github.com/bazelbuild/rules_docker/issues/1788#issuecomment-1072652536 seems to indicate that it did with Bazel 4.0.0, but the recent reports against rules_go are with Bazel 5.2.0 and linux-sandbox.

@larsrc-google Could you point me to the commit that was supposed to fix this?
