### ISSUE TITLE
Build container "FROM scratch"

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_docker#1800]
I am not seeing instructions on how to build a container "FROM scratch".  Scratch is not a base image, so you cannot pull it.  Any ideas?

**Comment by chrislovecnm** [comment]
@smukherj1, any ideas on how to pull this off?  We are working with submitting a container into a CI process that checks that the image is being built `FROM scratch`. We have tried building a container via `rules_docker` without defining the base.  When we submit that container to the companies CI, it fails.

**Comment by gravypod** [comment]
Hey @chrislovecnm. Here's a quick example of what you'd want to do here:

```
$ cat test/BUILD
load("@io_bazel_rules_docker//cc:image.bzl", "cc_image")
load("@io_bazel_rules_docker//container:container.bzl", "container_image")

cc_binary(
    name = "hello_world",
    srcs = ["main.cc"],
    # Produce an entirely static binary. Since this container is FROM scratch
    # it has no libc or other dynamic libraries contained inside of it. This should
    # be "fine" as long as your libc on your host has a compatible abi with whatever
    # you're running your container on.
    linkstatic = True,
    linkopts=['-static'],
)


container_image(
  name = "image",
  files = [":hello_world"],
  entrypoint = ["/hello_world"],
)
```

Assuming you have some valid cc code in `test/main.cc` you could then run the following to run your image:

```
$ bazel run //test:image
... <build log + extra stuff> ...
$ docker run bazel/test:image
hello world from host: a5eb84649f2f user:
```

Does this work for your use case?

**Comment by gravypod** [comment]
I'm going to mark this issue as closed. If the comment I left above doesn't resolve your issue @chrislovecnm please feel free to open this issue again and I can take a look.
