### ISSUE TITLE
Where does container_pull come from?

### ISSUE THREAD

**Issue by jayeye** [bazelbuild/rules_docker#1806]
https://github.com/bazelbuild/rules_docker#container_pull-1 says to put a `container_pull` rule in the `WORKSPACE`, but there is no mention on where to load it from. I have already included 

```
load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()
load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")
container_deps()
```

**Comment by symbiont-ji** [comment]
My bad... it's documented way up in the initial "include this in your workspace" text :(

This is what happens when I get too annoyed at other parts of the docs, then miss something that *was* actually documented!
