### ISSUE TITLE
Unclear/impossible to mount volumes with `bazel run` of a `container_image`

### ISSUE THREAD

**Issue by jayeye** [bazelbuild/rules_docker#1818]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: `container_image`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

Trying to figure out how to specify volumes to mount when running a `container_image` rule with `bazel run`.

Not sure if a bug or poor documentation. 

## 🔬 Minimal Reproduction

Consider the following rule:
```
container_image(
  name = "cent",
  base = "@centos7//image",
  legacy_run_behavior = False,
  volumes = ["/home/ji"],
  entrypoint = "/usr/bin/bash",
)
```

Where, of course, this exists in `WORKSPACE`:
```
container_pull(
    name = "centos7",
    registry = "index.docker.io",
    repository = "library/centos",
    digest = "sha256:e4ca2ed0202e76be184e75fb26d14bf974193579039d5573fb2348664deef76e",
)
```

## 🔥 Exception or Error

Now, if I run `bazel run :cent`, I can verify that a directory `/home/ji` exists inside the container, but it has not mounted the contents of my home directory, like `docker run -v /home/ji:/home/ji` would have done. 

Moreover, there does not seem to be a way to provide additional options in the usual way, that is with something like `bazel run :cent -- --more --options foo`. 

If this is a documentation problem, please explain how to mount volumes, and exactly how the `volumes` attribute is supposed to behave.

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>

  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by AnatoleLucet** [comment]
I think the `volumes` attribute only refers to a `VOLUME` in a Dockerfile. I seem like to mount a volume when running the container, you need to pass the `-v` flag in the `docker_run_flags` attribute:
```py
container_image(
  name = "cent",
  base = "@centos7//image",
  legacy_run_behavior = False,
  entrypoint = "/usr/bin/bash",
  docker_run_flags = "-v /home/ji:/home/ji",
)
```

Though I'm not sure how the pass a relative path to `-v` (which is what I'm trying to do on my end :smile:) since with `docker_run_flags = "-v ./:/usr/src/app"` docker returns the following error:
```
docker: Error response from daemon: create ./: "./" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

**Comment by gravypod** [comment]
@AnatoleLucet, you can do something hacky like this: 

```
container_image(
...
  docker_run_flags = "-v $BUILD_WORKSPACE_DIRECTORY:$BUILD_WORKSPACE_DIRECTORY -e BUILD_WORKSPACE_DIRECTORY=$BUILD_WORKSPACE_DIRECTORY",
)
```

I'd recommend against putting more complex build/run workflows into rules_docker like this though. In my experience it's been better to use rules_docker to build containers and use something like [skaffold](https://skaffold.dev/docs/pipeline-stages/builders/bazel/) to manage "shipping" these images.

**Comment by gravypod** [comment]
I'm closing this issue for now. If the above answer is unsatisfactory for others please feel free to reopen and tag me. I also think this should eventually lead to a discussion on adding features around a local docker-compose-like workflow because it seems the need here stemmed from nothing like that existing in rules_docker.

**Comment by hiberabyss** [comment]
> @AnatoleLucet, you can do something hacky like this:
> 
> ```
> container_image(
> ...
>   docker_run_flags = "-v $BUILD_WORKSPACE_DIRECTORY:$BUILD_WORKSPACE_DIRECTORY -e BUILD_WORKSPACE_DIRECTORY=$BUILD_WORKSPACE_DIRECTORY",
> )
> ```
> 
> I'd recommend against putting more complex build/run workflows into rules_docker like this though. In my experience it's been better to use rules_docker to build containers and use something like [skaffold](https://skaffold.dev/docs/pipeline-stages/builders/bazel/) to manage "shipping" these images.
> 
> This variable comes from [RunCommand](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommand.java;l=399;drc=b621b1b1866868a1dcb060fe7b6833df0c729761) in bazel. There is also `BUILD_WORKING_DIRECTORY` which is like the cwd.

Seems the `docker_run_flags` option could not used in `cc_image` ?
