### ISSUE TITLE
add deb packages defined in container_image to /var/lib/dpkg/status

### ISSUE THREAD

**Issue by MarkusTeufelberger** [bazelbuild/rules_docker#182]
Software like clair (https://github.com/coreos/clair/blob/master/ext/featurefmt/dpkg/dpkg.go) parses this file to look for installed Debian packages and their versions to display reported vulnerabilities.

Because the deb files are not installed using dpkg in the resulting container, this file doesn't get written and so it is not possible from the outside to analyze the container for installed packages.

**Comment by mattmoor** [comment]
I believe @r2d4 is going to do some work on this soon (is there an external issue tracking this?)

I don't think we're going to write directly to `/var/lib/dpkg/status` because it would introduce undesirable imperative `read-modify-write` chains between layers.  Our plan is to record this information into `/var/lib/dpkg/status.{shard}` that tooling like Clair (and our own scanner) can aggregate into a complete package list for scanning.

**Comment by MarkusTeufelberger** [comment]
I'm not sure if `status.{shard}` files are defined anywhere or are in actual use by any tool (Debian or not), but I understand that layering the single file together might not be a great solution either...

Maybe just an (optional?) manifest or description file that's easy to parse (JSON, YAML...) as additional build target for a container could be a solution? Lots of these scanners can also be queried manually. Then again one still would lose the benefit of being able to plop a container in there to get the result.

**Comment by mattmoor** [comment]
@MarkusTeufelberger One of my biggest asks from the Bazel folks (/cc @davidstanke @damienmg) wrt `WORKSPACE` is a way to get a manifest of versioned dependencies that can be included in archives.  Perhaps in a structured way so this can be tailored to the archive format.

I think this has applicability to just about every archive Bazel produces (JAR, WAR, PAR, Docker, ...). 
 Maybe I can get this through aspect voodoo today, but ideally every rule writer wouldn't need to do that.

**Comment by mattmoor** [comment]
[Here](https://github.com/GoogleCloudPlatform/distroless/issues/97) is the issue that is tracking this work.

**Comment by MarkusTeufelberger** [comment]
I know that this issue exists in distroless, debs handling is part of this ruleset here though, distroless only provides methods to feed deb files into docker_build (or maybe soon: container_image) rules.

**Comment by mattmoor** [comment]
To be clear, my expectation of how distroless will accomplish this is thought modifications both here and there (and possibly Bazel core).
