### ISSUE TITLE
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty caused by the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by jried31** [bazelbuild/rules_docker#183]
Possible to assist with debugging this error?

ERROR: error loading package '': Encountered error while reading extension file 'docker/docker.bzl': no such package '@io_bazel_rules_docker//docker': Error cloning repository: https://github.com/bazelbuild/rules_docker.git: cannot open git-upload-pack caused by https://github.com/bazelbuild/rules_docker.git: cannot open git-upload-pack caused by java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty caused by Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty caused by the trustAnchors parameter must be non-empty

**Comment by mattmoor** [comment]
Can you share the snippet of `WORKSPACE` that causes this?

**Comment by mattmoor** [comment]
Going to close this, feel free to reopen with some additional context.
