### ISSUE TITLE
Add NixOS compatibility through Go SDK selection

### ISSUE THREAD

**Issue by mentalblock** [bazelbuild/rules_docker#1857]
# 🚀 feature request

### Relevant Rules

N/A

### Description

With the latest version of rules_docker (0.17.0), I receive the following error on NixOS.

```
Starting local Bazel server and connecting to it...
INFO: Repository bazel_gazelle_go_repository_tools instantiated at:
  /home/bwong/git_repos_adobe/bazel-test/WORKSPACE:19:15: in <toplevel>
  /home/bwong/.cache/bazel/_bazel_bwong/9338d44fe703f03309bc0370122e9011/external/io_bazel_rules_docker/repositories/deps.bzl:33:12: in deps
  /home/bwong/.cache/bazel/_bazel_bwong/9338d44fe703f03309bc0370122e9011/external/io_bazel_rules_docker/repositories/go_repositories.bzl:35:25: in go_deps
  /home/bwong/.cache/bazel/_bazel_bwong/9338d44fe703f03309bc0370122e9011/external/bazel_gazelle/deps.bzl:72:24: in gazelle_dependencies
Repository rule go_repository_tools defined at:
  /home/bwong/.cache/bazel/_bazel_bwong/9338d44fe703f03309bc0370122e9011/external/bazel_gazelle/internal/go_repository_tools.bzl:116:38: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_tools':
   Traceback (most recent call last):
	File "/home/bwong/.cache/bazel/_bazel_bwong/9338d44fe703f03309bc0370122e9011/external/bazel_gazelle/internal/go_repository_tools.bzl", line 84, column 17, in _go_repository_tools_impl
		fail("list_repository_tools_srcs: " + result.stderr)
Error in fail: list_repository_tools_srcs: env: ‘/home/bwong/.cache/bazel/_bazel_bwong/9338d44fe703f03309bc0370122e9011/external/go_sdk/bin/go’: No such file or directory
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/bwong/.cache/bazel/_bazel_bwong/9338d44fe703f03309bc0370122e9011/external/bazel_gazelle/internal/go_repository_tools.bzl", line 84, column 17, in _go_repository_tools_impl
		fail("list_repository_tools_srcs: " + result.stderr)
Error in fail: list_repository_tools_srcs: env: ‘/home/bwong/.cache/bazel/_bazel_bwong/9338d44fe703f03309bc0370122e9011/external/go_sdk/bin/go’: No such file or directory
```

The ultimate reason why this fails is because NixOS does not have libraries which reside in expected places for the dynamically linked Go binaries installed by `rules_go`. Please see https://github.com/bazelbuild/rules_go/issues/1376 for more context. In summary, the workaround in that situation is to configure `rules_go` to use the host's Go SDK instead of trying to download an SDK on demand.

The issue is that I cannot configure which Go SDK to use with `rules_docker` because, understandably, `rules_docker` does not expose this capability when setting up the dependencies of `rules_go`. The selection of Go at https://github.com/nlopezgi/rules_docker/blob/363e12da417e6fa9dd447af5411b14489ea37ac4/repositories/go_repositories.bzl#L34 is hardcoded, but I would like to somehow indicate to the underlying `rules_go` that I want to use the host's Go SDK as described in https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go_register_toolchains.

### Describe the solution you'd like

As a potential solution, we can take the prior work of https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/79 and adapt it to this project. It provides auto-detection of NixOS and executing the appropriate `go_register_toolchains`. I am not sure if this is the optimal solution. Using the host's Go SDK when on NixOS or downloading a possibly different version of Go SDK if you are not does not account for the situation when you can leverage the Nix packager when not using NixOS. This reduces reproducibility overall.

A simpler solution would be to expose an attribute in https://github.com/nlopezgi/rules_docker/blob/363e12da417e6fa9dd447af5411b14489ea37ac4/repositories/deps.bzl#L26 that just passes through all the way to `go_register_toolchains`. This would solve the issue on NixOS because I would specify to use the host's Go SDK in the hypothetical call to `container_deps(go_sdk="host")` in the WORKSPACE file. This might be the better solution as it requires pinning the host Go SDK out of band using Nix and there is no dynamic behavior based on the detection of NixOS. It is more reproducible in that the only way to get the project working in another environment is using the Nix package manager, or any other method to pin the host Go, with Bazel.

### Describe alternatives you've considered

The only way to work around this is to run my Bazel workflow in a virtual environment using a Linux distribution where the dynamically linked Go SDK runs properly. I would rather not pursue this option due to the overhead. I also feel that Bazel and the Nix packager (and consequently NixOS) have the same goals of reproducible and hermetic builds, therefore it would be a shame if I have to compromise some of that reproducibility by using another Linux distribution because the Go SDK is distributed using dynamically linked binaries.

I have yet to try directly adding the `rules_docker` dependencies by forgoing `container_deps()` or forking the repository. These workarounds have considerable overhead if I want to track updates to upstream.

---

I am new to Bazel and would not be comfortable drafting the PR for this change, though I will be happy to do any testing or provide any more information to make `rules_docker` compatible with more Linux distributions. I look forward to any thoughts regarding this issue.

**Comment by gravypod** [comment]
@mentalblock thanks for the detailed post. Would it make sense if we exposed something like `go_deps(install_go_toolchains=False)` to allow the end user to install go packages in their WORKSPACE file? Also, would you be willing to test out the change to see if it works in your usecase? I could make a PR with this change if you're willing to test it out.

**Comment by mentalblock** [comment]
@gravypod Whatever solution we can come up with, I will be happy to test.

How many packages will I actually have to list out manually in my WORKSPACE file if this solution of `go_deps(install_go_toolchains=False)` implemented?

If it reduced it down to one or two that would be great, but I want to verify that this makes it much better than the workaround of listing out all the dependencies outright.

**Comment by ar3s3ru** [comment]
@mentalblock how did you manage to solve this, if I may ask?
Experiencing the same issue on my NixOS installation
