### ISSUE TITLE
Incorrect Python toolchain resolution

### ISSUE THREAD

**Issue by aaliddell** [bazelbuild/rules_docker#1858]
# 🐞 bug report

### Affected Rule

`py3_image`

### Is this a regression?

No

### Description

The Python toolchain specified in `toolchains/BUILD` appears to not take effect when there is another Python toolchain, even if that other toolchain does not meet the required constraints. I can't tell if this is a bug in rules_docker or Bazel's core Python rules...

This perhaps seems to be related to `exec_compatible_with` on `py_binary` not actually having any effect on the resolved toolchain. For example, if I do the following as a test, it still appears to resolve the non-docker toolchain despite it not meeting the constraints:

```starlark
py_binary(
    ...
    exec_compatible_with = ["@io_bazel_rules_docker//platforms:run_in_container"],
)
```

The resulting output files point to the python version in the non-docker toolchain and `toolchain_resolution_debug` also suggests this is the case as the host platform is not being excluded.

The above is what `rules_docker` [is doing internally](https://github.com/bazelbuild/rules_docker/blob/3494f6e2dd6ffcdc4240f11940ecf79d5c1c1f97/python3/image.bzl#L95-L101) and therefore appears to be ending up with the wrong toolchain.

## 🔬 Minimal Reproduction

See above

## 🔥 Exception or Error

Incorrect Python path from toolchain in built image.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04.5 LTS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:33:24 2021 (1611214404)
Build timestamp: 1611214404
Build timestamp as int: 1611214404
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
0.17.0
  </code>
</pre>

**Anything else relevant?**

Maybe relevant to #1247

**Comment by aaliddell** [comment]
Ok I think this was a misunderstanding of how toolchain resolution behaves in the presence of `exec_compatible_with`. I thought it was trying to exclude any local toolchains from being used by `py3_image` but it's actually trying to exclude the `rules_docker` toolchain on non-`py3_image` targets.

The local toolchain does not get excluded by that `exec_compatible_with`, since it is effectively compatible with every platform due to not providing any constraints. Whilst the `rules_docker` toolchain is exlcuded from general `py_binary` since it is not compatible with the normal host platform. Is this correct?

As a result, is there a way to exclude the local toolchain from being used in `py3_image`, besides just registering it later in WORKSPACE?

**Comment by pcj** [comment]
cc @mattem

**Comment by kwestb** [comment]
@aaliddell did you ever find a solution? I'm running into this exact same issue in my build.

**Comment by aaliddell** [comment]
> @aaliddell did you ever find a solution? I'm running into this exact same issue in my build.

I just reordered the declaration of toolchains to get it to resolve the one I want. If I remember right that means registering the custom one last, but maybe it was first. Try both and see.

**Comment by kwestb** [comment]
@aaliddell thanks for your quick response!

I figured out another solution myself: I added this stuff to my `BUILD` file:
```
constraint_value(
    name = "dont_run_in_container",
    constraint_setting = "@io_bazel_rules_docker//platforms:containerized",
)

platform(
    name = "local_config_platform_but_dont_run_in_container",
    constraint_values = [":dont_run_in_container"],
    parents = ["@local_config_platform//:host"],
)

py_runtime(
    name = "py_runtime_inside_the_container",
    interpreter_path = "/path/to/my/toolchain/in/the/container/bin/python3",
    python_version = "PY3",
)

py_runtime(
    name = "py_runtime_outside_the_container",
    interpreter = "//my/hermetic/python3",
    python_version = "PY3",
)

py_runtime_pair(
    name = "py_runtime_pair_outside_the_container",
    py3_runtime = ":py_runtime_outside_the_container",
)

py_runtime_pair(
    name = "py_runtime_pair_inside_the_container",
    py3_runtime = ":py_runtime_inside_the_container",
)

toolchain(
    name = "toolchain_for_outside_the_container",
    exec_compatible_with = [":dont_run_in_container"],
    toolchain = ":py_runtime_pair_outside_the_container",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)

toolchain(
    name = "toolchain_for_inside_the_container",
    exec_compatible_with = ["@io_bazel_rules_docker//platforms:run_in_container"],
    toolchain = ":py_runtime_pair_inside_the_container",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)
```

and then in my `WORKSPACE` file:
```
register_execution_platforms(
    "//:local_config_platform_but_dont_run_in_container",
    "@io_bazel_rules_docker//platforms:local_container_platform",
)

register_toolchains(
    "//:toolchain_for_outside_the_container",
    "//:toolchain_for_inside_the_container",
)
```

It took me hours to figure this out. I hope others find it useful for their work!
