### ISSUE TITLE
Keep package-installed files listing for Debian packages installed in a distroless image

### ISSUE THREAD

**Issue by pombredanne** [bazelbuild/rules_docker#1876]
# 🚀 feature request

### Relevant Rules
When a package is installed, only metadata are kept and the list of installed files is lost/not saved with the package metadata.

I have a concern with what happens here: https://github.com/bazelbuild/rules_docker/blob/d18033b7eb3429a55dc4a579b5c19af57ab25e5f/container/build_tar.py#L224

### Description

In a distroless container image, the as-installed .deb packages are not saved with their files/md5sums file lists in what would be in `/var/lib/dpkg/info` on a regular Debian install. As a result, it is not possible to relate an installed package in a distroless image/layer to the set of files that were installed with this package.

This data can be important for software composition analysis and its security and license compliance tracking applications.

### Describe the solution you'd like

Each installed package should include some installed file listing possibly added in some per package file in the  `status.d/` directory. This is a Debian standard in `/var/lib/dpkg/info/<package name>`

This would make distroless images more readily introspectable, otherwise there is no intrisic way to relate a package (in status.d) to the set of its installed files.

@tejal29 you committed this originally with @dlorenc ... any insight to share there?

### Describe alternatives you've considered

I cannot fathom an in-container alternative to keep a tab of each packaged-installed file. Tracking outside would mean maintaining some external database which does not seem practical.

**Comment by fedemengo** [comment]
@pombredanne I would love to help, do you already have something I start from?

**Comment by pombredanne** [comment]
@fedemengo sorry for a late reply. I do not have anything done yet, but I would likely either:
- continue using a "non-like-debian" `/var/lib/dpkg/status.d/<package name>` and add `/var/lib/dpkg/status.d/<package name>.md5sums` (originally under `/var/lib/dpkg/info/<package name>.md5sums`) and/or create a `/var/lib/dpkg/status.d/<package name>.list` file for installed files  also originally under `/var/lib/dpkg/info/<package name>.list`
- OR just keep and copy over the `/var/lib/dpkg/info/` directory as is which will contain all the original parts of the packages.

**Comment by pombredanne** [comment]
@fedemengo I do not think anything is "lost" .... but rather that in https://github.com/bazelbuild/rules_docker/blob/6ea707babdcd54514e0884278ac624fb8bda19c1/container/build_tar.py#L224
we have only one file that's extracted and that's the control file: https://github.com/bazelbuild/rules_docker/blob/6ea707babdcd54514e0884278ac624fb8bda19c1/container/build_tar.py#L41

we want the md5sums file to be extracted.

I pushed a PR here with a test: https://github.com/bazelbuild/rules_docker/pull/2065

**Comment by pombredanne** [comment]
I would really appreciate some review of https://github.com/bazelbuild/rules_docker/pull/2065 before it goes stale.
