### ISSUE TITLE
Specify required Bazel version for CI task

### ISSUE THREAD

**Issue by mai93** [bazelbuild/rules_docker#1877]
Bazel version required by certain test tasks needs to be specified in the task to be effective. If a task requires certain Bazel version, it will be skipped in Bazel@Head + Downstream tests. I think not adding `bazel: 4.0.0` to [this task](https://github.com/bazelbuild/rules_docker/blob/master/.bazelci/presubmit.yml#L7) causes the test to fail [here](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2046#77dfa088-6f26-4d6b-bae2-7606aa91be90)

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/rules_docker/commit/3fdfe0c63de0942afe977794ea632df3af435fd1#diff-c3633fb973fb6f3cf898f53da86fa77e9310338a7c2933143709d5e226f05f75 is the change that caused this breakage

/cc @alexeagle , basically when using bazel@head to test rules_docker, the `.bazelversion` file will cause an error.

@philwo Is there a way to tell the shell wrapper to ignore the `.bazelversion` file?

**Comment by philwo** [comment]
This is the code of the wrapper: https://github.com/bazelbuild/bazel/blob/master/scripts/packages/bazel.sh

I think the only way to ignore the `.bazelversion` file is to set the `USE_BAZEL_VERSION` environment variable or to delete the file.

**Comment by philwo** [comment]
But why is the shell wrapper even installed? It's only shipped if you install Bazel via `apt-get` from our repository or when using the installer script, both of which we don't do anywhere on Bazel CI. 🤔

**Comment by meteorcloudy** [comment]
@philwo Hmm... digging into the code, maybe it's the test is running Bazel inside a docker container:
- https://github.com/bazelbuild/rules_docker/blob/e1701495705a15d2fb7613f39eb01c9de6d1bd1a/WORKSPACE#L207
- https://github.com/bazelbuild/rules_docker/blob/359898dbb45cffcf7e09c2a20d331e96ae3ae543/contrib/repro_test.bzl#L60

**Comment by meteorcloudy** [comment]
In downstream pipeline, we do pass `USE_BAZEL_VERSION=/tmp/tmpqydihq2c/bazel` to the tests, but it seems to be ignored.

**Comment by alexeagle** [comment]
oh, sorry everyone, that's an unfortunate pitfall. I'll just revert that commit for now, it's not necessary for anything other than local developer reproducibility

**Comment by meteorcloudy** [comment]
Thanks, Alex!
