### ISSUE TITLE
Enforce that commit messages indicate fix vs feature vs breaking change

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_docker#1883]
This lets us make a better changelog, and also lets us determine whether the next release should be a major, minor, or patch

**Comment by dzintars** [comment]
I've seen Husky and Commitlint used quite a lot in the field to enforce commit message semantics.

**Comment by alexeagle** [comment]
yup. I don't think we want husky here (there's no need for node) but commitizen via pre-commit works pretty well
