### ISSUE TITLE
Manipulating files in layer produced by container_run_and_commit_layer

### ISSUE THREAD

**Issue by robertgates55** [bazelbuild/rules_docker#1901]
Looking for advice/prior art/hacks on how to manipulate files in the layer generated by `container_run_and_commit_layer`.

A common Dockerfile trick we used to use a lot was to use a multistage build and then eg chown & move the files being copied from a previous stage:
```
COPY --from=build_stage --chown=nginx:nginx /build/artifacts /public
```

When migrating this to bazel, I was imagining that I could use `pkg_tar` to perform this chown & remap, by loading the layer as a tar `dep`:
```
pkg_tar(
    name = "runtime_artifacts",
    strip_prefix = ".",
    deps = [ ":build_stage_layer" ],
    remap_paths = {
        "build/artifacts": "public",
    },
    owner = "1000.1000",
)
``` 
However, only `files` passed to `pkg_tar` are processed by `remap_paths` & `owner`, not the untarred contents of the deps. I also note that the files in the layer produced by `container_run_and_commit_layer` are timestamped with the actual time rather than replaced with eg 01-01-1970.

Is there anything I can do here, or should I just move the chowning & remapping logic into the `container_run_and_commit_layer` commands instead?

**Comment by ewianda** [comment]
Any pointers on how to handle this
