### ISSUE TITLE
download_pkgs should allow specifying SHA256 hashes for each package.

### ISSUE THREAD

**Issue by tferi** [bazelbuild/rules_docker#1904]
# 🚀 feature request

### Relevant Rules

`download_pkgs`

### Description

The `download_pkgs` rule doesn't allow specifying hashes for the downloaded dependencies. This allows supply channel attacks via changing the contents of the remote repository.

### Describe the solution you'd like

This could be implemented as a backwards compatible change by adding a `verified_packages` argument to the rule. If the caller passes a non-empty map<packageName, hash>, the packages identified by the map's keyset would also be fetched, and their hashes checked against the values mapped to the keys. The rule would fail if the hashes don't match.

### Describe alternatives you've considered

Installing packages and checking their hashes in code via `container_run_and_commit`. This would move dependency resolution outside Bazel, and we'd prefer Bazel to handle that end to end for us.

**Comment by Ubehebe** [comment]
This should be reopened. Every other Bazel/Starlark API for downloading things from the net that I can think of has sha256 support. Examples:

- [http_archive](https://bazel.build/rules/lib/repo/http#http_archive)
- [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external#pinning-artifacts-and-integration-with-bazels-downloader)
- [repository_ctx.download](https://bazel.build/rules/lib/repository_ctx#download)
- [compile_pip_requirements](https://github.com/bazelbuild/rules_python/blob/main/docs/pip.md#compile_pip_requirements)
- [container_pull](https://github.com/bazelbuild/rules_docker/blob/master/docs/container.md#container_pull) (from rules_docker itself)

I can probably find more.

The lack of sha256 support for download_pkgs is surprising, for exactly the reason OP describes.
