### ISSUE TITLE
Bazel build does not build image tar when building all targets (//...)

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_docker#1921]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `container_image`

### Is this a regression?

No

### Description

`bazel build //...` does not build the image `.tar` file. It must be built explicitly. 

## 🔬 Minimal Reproduction

`foo/BUILD.bazel`

```python
load("@io_bazel_rules_docker//container:container.bzl", "container_image")

container_image(
  name = "foo",
  base = "@dotnet_aspnet//image",
)
```

`$ bazel build //...`

Notice that `./bazel-bin/foo/foo.tar` is not present. 

`$ bazel build //foo/foo.tar`

Notice that `./bazel-bin/foo/foo.tar` is now present. 

## 🔥 Exception or Error

N/A

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 LTS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Build label: 4.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:11:34 2021 (1621595494)
Build timestamp: 1621595494
Build timestamp as int: 1621595494
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
http_archive(
  name = "io_bazel_rules_docker",
  sha256 = "59d5b42ac315e7eadffa944e86e90c2990110a1c8075f1cd145f487e999d22b3",
  strip_prefix = "rules_docker-0.17.0",
  urls = [ "https://github.com/bazelbuild/rules_docker/releases/download/v0.17.0/rules_docker-v0.17.0.tar.gz" ],
)
  </code>
</pre>

**Anything else relevant?**

No

**Comment by Sebelino** [comment]
I believe this is by design. It is expensive to build a `docker load` compatible `tar` bundle, and you are able to `bazel run` a `container_image` without it.

https://github.com/bazelbuild/rules_docker#using-with-docker-locally

**Comment by hxtk** [comment]
> > I believe this is by design. It is expensive to build a `docker load` compatible `tar` bundle, and you are able to `bazel run` a `container_image` without it.
> > https://github.com/bazelbuild/rules_docker#using-with-docker-locally
> 
> I see. It's quite annoying though, since I want to ensure all artefacts are built as part of CI. Now I need to maintain a list of Docker targets in the build script.

You don't actually need to maintain a list; you could run something with `bazel query` and `xargs` like `bazel query 'kind(container_image, //...) | xargs -I % bazel build %.tar`. I do something similar for `java_binary` and `[name]_deploy.jar` implicit targets, and also for running `container_push` targets.
