### ISSUE TITLE
Support official python docker container with py3_image rule.

### ISSUE THREAD

**Issue by michalk-1** [bazelbuild/rules_docker#1927]
# 🚀 feature request

### Relevant Rules

**py3_image** (perhaps also **py_image**).

### Description

I'd like to use py3_image with `docker.io/library/python:3.9-slim` from the official https://hub.docker.com/_/python.

Unfortunately, in this image the python binary is installed somewhere else than [`/usr/bin/python`](https://github.com/bazelbuild/rules_docker/blob/e5368f9c425854ddb5af31624f0a6b99a0d3f1fb/python3/image.bzl#L115). 

```
$ docker run -it --rm --entrypoint "" docker.io/library/python:3.9-slim which python
/usr/local/bin/python
```

### Steps to reproduce

`WORKSPACE`
```
load("@io_bazel_rules_docker//container:container.bzl", "container_pull")

container_pull(
    name = "python_container",
    registry = "docker.io/library",
    repository = "python",
    tag = "3.9-slim",
)
```

`BUILD`

```
load("@io_bazel_rules_docker//python3:image.bzl", "py3_image")

py3_image(
    name = "main",
    main = "main.py",
    srcs = ["main.py"],
    base =  "@python_container//image",
    deps = [],
)
```

`main.py`
```python
print("Hello world!")
```

### Proposal of the solution

We could allow the user to pass a custom entrypoint as an argument to py3_image.

**Comment by gravypod** [comment]
This is an area where we need to be careful because we could break backwards compatibility with our users. Unfortunately distroless's `gcr.io/distroless/python3-debian10` image does not have `/usr/bin/env` so we can't easily detect what path to use. For the time being we can use a hack like this to work around this:


```
load("@io_bazel_rules_docker//container:container.bzl", "container_layer", "container_image")

container_layer(
    name = "python_symlink",
    symlinks = {
      "/usr/bin/python": "/usr/local/bin/python",
      "/usr/bin/python3": "/usr/local/bin/python",
    },
)

container_image(
    name = "python",
    base = "@python_container//image",
    layers = [":python_symlink"],
    visibility = ["//visibility:public"],
)
```

This adds the expected symlinks into the image. Once we've come up with a better abstraction it should be easy to find all of the things using `//:python` in your repo and migrate away from them.

If anyone has any good ideas about how we can work through this please let me know.

**Comment by michalvi** [comment]
Hi,

Thank you for the response and a viable solution! I'll definitely use it.

What about adding `entrypoint` argument to py3_image with a default set to `/usr/bin/python`.  The default would make it backwards compatible.

Kind regards,

**Comment by esirK** [comment]
@gravypod Thanks for this solution. 
However, how can I use a custom-built image using `dockerfile_image` e.g If I want to install a system package.
As an example, my application uses `psycopg2` which requires a few prerequisites e.g ` C compiler, some development packages` which I need to install into a container so I have created the following `Dockerfile`

```
FROM python:3.10.0

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y upgrade --fix-missing\
    && apt-get install libpq-dev --no-install-recommends -y \
    && apt-get clean


RUN apt-get install gcc python-dev --no-install-recommends -y \
    && apt-get clean \
    && pip install --upgrade pip

RUN pip install psycopg2
```
Here's the content of my `BUILD`

```
py3_image(
    name="debunkbot_img",
    srcs=["main.py"],
    main="main.py",
    deps=[
        ":debunkbot",
    ],
    base=":python3.10",
)

container_image(
    name="python3.10",
    visibility=["//visibility:public"],
    base="@python3.10-base-with-pycopg2//image",
    ports = [
        "8000",
    ],
    env={
        "PYTHONUNBUFFERED": "1",
    },
    symlinks={
        "/usr/bin/python": "/usr/local/bin/python",  # To work as base for py3_image
        "/usr/bin/python3": "/usr/local/bin/python3"  # To work as base for py3_image
    },
)
```

running the `debunkbot_img` image using bazel still shows that `psycopg2` hasn't been installed even after having installed it explicitly in the `Dockerfile`

Any Ideas what I'm doing wrongly?

**Comment by ntungson** [comment]
@esirK I'm having a similar issue, have you figured out how to solve it?
