### ISSUE TITLE
How to chown a directory when running with non-root user?

### ISSUE THREAD

**Issue by nareddyt** [bazelbuild/rules_docker#1928]
I have rules similar to the following set up:

```
# Create a passwd file with a root and nonroot user and uid.
passwd_entry(
    username = "root",
    uid = 0,
    gid = 0,
    name = "root_user",
)

passwd_entry(
    username = "nonroot",
    info = "nonroot",
    uid = 1002,
    name = "nonroot_user",
)

passwd_file(
    name = "passwd",
    entries = [
        ":root_user",
        ":nonroot_user",
    ],
)

# Create a tar file containing the created passwd file
pkg_tar(
    name = "passwd_tar",
    srcs = [":passwd"],
    mode = "0o644",
    package_dir = "etc",
)

# Include it in our base image as a tar.
container_image(
    name = "passwd_image",
    base = "@go_image_base//image",
    tars = [":passwd_tar"],
    user = "nonroot",
)
```

This produces a container where all files in the filesystem are owned by the `root` user, but the user running inside the container is `nonroot`. The `nonroot` user does not have permissions to write files to the container, they can only read/execute (755).

```
$    whoami
nonroot

$    ls -al
drwxr-xr-x   1 root root      4096 Sep 10 21:46 .
drwxr-xr-x   1 root root      4096 Sep 10 21:46 ..
```

How can I run `chown` using the docker rules in this repo so that the `nonroot` user can write files?

**Comment by nareddyt** [comment]
Our workaround is to use `/tmp` directory with 777 permissions.

**Comment by gravypod** [comment]
@nareddyt, from what I can tell this is the intended behavior. Is there any reason this wouldn't make sense? If you want you can also minic more standard unix conventions by [passwd_entry](https://github.com/bazelbuild/rules_docker/blob/266a8e728fc1c1595986783571e3d38286f43cfa/testdata/BUILD#L581-L589) to create a home directory which should be owned by that user.

**Comment by nareddyt** [comment]
I was mostly concerned about giving all users `rwe` permissions, it would be safer to just make a user the owner and only give the user/group `rwe` permissions. I guess it is not a huge deal since `/tmp` already exists with the same permissions.

The home directory approach also makes sense. Closing since there is a workaround and possible solution.
