### ISSUE TITLE
Py3_image no matching toolchains for types @bazel_tools//tools/cpp:toolchain_type

### ISSUE THREAD

**Issue by GeorgeEngland** [bazelbuild/rules_docker#1935]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: py3_image

### Description
I can build a basic py_binary.
But when building the py3_image we get:

## 🔬 Minimal Reproduction

Use default RBE 16-04 config and build a py3_image

## 🔥 Exception or Error

<pre><code>

INFO: Invocation ID: a1d17661-a555-4223-a240-9dc43240e075
INFO: ToolchainResolution: Removed execution platform //configs/config:platform from available execution platforms, it is missing constraint @io_bazel_rules_docker//platforms:run_in_container
INFO: ToolchainResolution: Removed execution platform @local_config_platform//:host from available execution platforms, it is missing constraint @io_bazel_rules_docker//platforms:run_in_container
INFO: ToolchainResolution: Removed execution platform //configs/config:platform from available execution platforms, it is missing constraint @io_bazel_rules_docker//platforms:run_in_container
INFO: ToolchainResolution: Target platform //configs/config:platform: Selected execution platform //configs/config:platform,
INFO: ToolchainResolution: Removed execution platform //configs/config:platform from available execution platforms, it is missing constraint @io_bazel_rules_docker//platforms:run_in_container
INFO: ToolchainResolution: Removed execution platform @local_config_platform//:host from available execution platforms, it is missing constraint @io_bazel_rules_docker//platforms:run_in_container
INFO: ToolchainResolution: Removed execution platform //configs/config:platform from available execution platforms, it is missing constraint @io_bazel_rules_docker//platforms:run_in_container
ERROR: While resolving toolchains for target XXXX:py_image.binary: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.

</code></pre>

**Operating System:**
Ubuntu container (remote), ubuntu container local

**Comment by kriswuollett** [comment]
I've encountered the same issue while attempting to use Bazel again; however, I'm not even using a `.bazelrc` with options like `BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN` in the setup described by @GeorgeEngland. I've created a [repo that makes the issue easily reproducible with Docker](https://github.com/kriswuollett/rules_docker_issue/tree/e149e9fc47eb37d4dbaa7c1b4d5e9e4f0807425b).

Perhaps these tool versions are not compatible? Any recommendations for a version combo that currently works? Or is there something else wrong in the example repo that causes this issue?

* Ubuntu 20.04 w/ `python` and `python3` installed
* Bazelisk w/ `4.2.1` in `.bazeliskrc`
* `rules_python-0.5.0` w/ `pip_parse` for dependencies and `py3_image`
* `rules_docker-v0.21.0`

**Comment by kriswuollett** [comment]
Resolved my instance of this issue by noticing I was missing the following in my `WORKSPACE`:

```starlark
load("@io_bazel_rules_docker//python3:image.bzl", _py_image_repos = "repositories")
_py_image_repos()
```

I've updated my [example repo](https://github.com/kriswuollett/rules_docker_issue.git) to show the working example.

**Comment by esirK** [comment]
Facing the same issue on `Bazel 5.0.0`

**Comment by jensenkairos** [comment]
Had the same issue on `Bazel 5.2.0` and solve it by adding `--@io_bazel_rules_docker//transitions:enable=false` to the run command

**Comment by jmhodges** [comment]
`--@io_bazel_rules_docker//transitions:enable=false` also works for me when using a plain `container_image`, too, on an Intel Mac 12.5.1 with bazel 5.2.0.

rules_docker folks: should that be turned back off? Is there some other repo's that needs to be solved to allow that to be turned on for everyone?

**Comment by abhillman** [comment]
Related https://github.com/bazelbuild/bazel/issues/10134
