### ISSUE TITLE
rules_docker broken with Bazel@HEAD CI

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_docker#1939]
Breakage:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2211#a8703949-3bd7-4c71-bd75-d787de800fec

```

File "/var/lib/buildkite-agent/builds/bk-docker-80kl/bazel-downstream-projects/rules_docker/docker/toolchain_container/debian_pkg_tar.bzl", line 127, column 38, in _generate_deb_tar
--
  | _download_deb_pkgs.implementation(
  | File "/var/lib/buildkite-agent/builds/bk-docker-80kl/bazel-downstream-projects/rules_docker/docker/package_managers/download_pkgs.bzl", line 85, column 22, in _impl
  | packages = depset(packages or ctx.attr.packages)
  | Error in depset: parameter 'direct' must contain a list of elements, and may no longer accept a depset. The deprecated behavior may be temporarily re-enabled by setting --incompatible_disable_depset_items=false

```

Bazel instituted a change to semantics of `depset()`. This should be fixed in-place or you can temporarily use `--incompatible_disable_depset_items=false` to disable this restriction.

**Comment by mai93** [comment]
This still needs to be fixed as the project is still broken with Bazel at head: 
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2243#65c204c9-bb46-42ba-9bf2-a9d999b4b0d6

**Comment by c-parsons** [comment]
Ping. This still needs to be fixed. Going to add some assignees for visibility ( Feel free tor reassign as appropriate)
