### ISSUE TITLE
Timestamps of files in image created with container_image rule are all set to zero

### ISSUE THREAD

**Issue by lgieron** [bazelbuild/rules_docker#1941]
# 🐞 bug report

### Affected Rule

container_image

### Description

Please see example code:

```
load(
"@io_bazel_rules_docker//container:container.bzl",
"container_image"
)

container_image(
name = "image",
base = "@nginx//image",
files = ["nginx.conf"],
symlinks = {
    "/etc/nginx/nginx.conf": "/nginx.conf",
},
tars = [":build_tar"],
tags = ["catalog"])
```

The image created with this call has all timestamps set to zero (Jan 1st 1970), while the timestamps of files in the tar file (`:build_tar` target) are correct.
It looks like this call is zeroing all the timestamps. Is this a bug, or am I using `container_image` rule incorrectly?

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
   Linux
  </code>
</pre>

**Comment by zoidbergwill** [comment]
This is intentional.

https://github.com/bazelbuild/rules_docker/blob/master/container/build_tar.py#L419-L425

You can add `enable_mtime_preservation = True` to the container_layer: https://github.com/bazelbuild/rules_docker/blob/master/container/layer.bzl#L326

**Comment by hiberabyss** [comment]
@zoidbergwill How to enable this for rules like `cc_image` ?

**Comment by zoidbergwill** [comment]
@hiberabyss Doesn't look possible at the moment https://github.com/bazelbuild/rules_docker/blob/master/cc/image.bzl#L66-L103 ?

**Comment by hiberabyss** [comment]
> @hiberabyss Doesn't look possible at the moment https://github.com/bazelbuild/rules_docker/blob/master/cc/image.bzl#L66-L103 ?

@zoidbergwill Thanks for your reply! Is it possible to implement this in image.bzl?
