### ISSUE TITLE
Read mtime from volatile-status.txt

### ISSUE THREAD

**Issue by zxiang77** [bazelbuild/rules_docker#1945]
# 🚀 feature request

### Relevant Rules
`container_image` rule and the underlying `container/archive.py`.

### Description

Currently, `mtime` attribute for `container_image` can only be specified as a constant integer defined in BUILD file. but it would be helpful to have the option to get mtime from volatile-status.txt variables, e.g.: `BUILD_TIMESTAMP`

### Describe the solution you'd like
there's a few:

#### alternative 1
define mtime_str and that allows passing in volatile variables, e.g.: "{BUILD_TIMESTAMP}", and we use that for `mtime`

**alternative 2**: default `mtime` to `BUILD_TIMESTAMP` if stamp is true, or create a `file_stamp` flag, stamp files when `file_stamp` is true

### Describe alternatives you've considered

I don't have any. I want to pass the time as a variable like `bazel run --define mtime=$(date '+$s') <my target>` but it seems it's not doable with bazel? please comment if there's a way to pass mtime as a variable from shell command!

**Comment by kcking** [comment]
I would also like to see this addressed by either respecting the `--stamp` flag or some other workaround
