### ISSUE TITLE
Rules Docker no longer works with the latest commit of rules_rust

### ISSUE THREAD

**Issue by rdelfin** [bazelbuild/rules_docker#1949]
# 🐞 bug report

### Affected Rule

This issue is caused by the rules rust support.

### Is this a regression?

No, as the breakage happened in an external library, but there is a version of the other library where it still works.

### Description

bazelbuild/rules_rust#1002 removed a `rust.bzl` file that the repo wanted to remove for some time. This is a part of them modularising their project. Unfortunately, this means that they broke compatibility for any rules using this. Currently, I get the following error after upgrading:
```
ERROR: error loading package '': in /home/rdelfin/.cache/bazel/_bazel_rdelfin/f85f282bf8c8f89c0c7662b381b87b17/external/io_bazel_rules_docker/rust/image.bzl: cannot load '@rules_rust//rust:rust.bzl': no such file
```

I suspect it's a quick fix, just changing imports (and I'll be glad to do it) but I'm not sure how you all would manage versioning here. Can I just send a PR with that fix?

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Create a repo with rules rust and rules docker. In the workspace add:
```
load("@io_bazel_rules_docker//rust:image.bzl", _rust_image_repos = "repositories")
_rust_image_repos()
```
And any build that uses the docker images should fail

## 🔥 Exception or Error

<pre><code>
ERROR: error loading package '': in /home/rdelfin/.cache/bazel/_bazel_rdelfin/f85f282bf8c8f89c0c7662b381b87b17/external/io_bazel_rules_docker/rust/image.bzl: cannot load '@rules_rust//rust:rust.bzl': no such file
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel version
Bazelisk version: v1.10.1
Build label: 4.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:17:47 2021 (1630336667)
Build timestamp: 1630336667
Build timestamp as int: 1630336667
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
0.20.0
  </code>
</pre>

**Anything else relevant?**

**Comment by UebelAndre** [comment]
Continuing the thread from https://github.com/bazelbuild/rules_rust/pull/1002#issuecomment-962022203 here:

There seems to be an issue with `rules_docker` CI which blocks the PR referenced above... I'm pretty unfamiliar with `rules_docker` so will probably need help from a maintainer since according to https://github.com/bazelbuild/rules_docker/pull/1948 it seems the failures are unrelated to any changes in either PR.

**Comment by gravypod** [comment]
@rdelfin, sorry for the delay in merging the PR that would have fixed this. Thanks again @UebelAndre for sending the fix in.

**Comment by rdelfin** [comment]
No worries, appreciate you looking at it! We were able to work around it temporarily
