### ISSUE TITLE
Could `legacy_run_behavior` be documented as a attribute of `container_image`

### ISSUE THREAD

**Issue by cfife-btig** [bazelbuild/rules_docker#1959]
# 🚀 feature request

### Relevant Rules

`container_image`  

Tweak the documentation slightly

### Description

Hello, I'm relatively new to bazel and the docker_rules.

I wanted to do a `bazel run :image` where  `:image` was a `container_image` rule, but I noticed it didn't call `docker run`, unless I set `legacy_run_behavior` to false. After I realized this, it was pretty straight-forward to fix, but before that, I had to do a lot of digging in this repository before I realized this behavior even existed. I knew it was possible only because it worked for the `lang-image`s. 

`legacy_run_behavior` is not documented as an attribute of `container_image` but I feel that maybe it should be because some people may want to call `docker run` on their container image.

### Describe the solution you'd like

Document `legacy_run_behavior` under the `container image` rule documentation, or include a reference to the docker/packagemanger attributes.

### Describe alternatives you've considered

Maybe the reason this isn't documented is because it's under the packagemanager attributes. So maybe it's fine to leave as is, but it took me a long time to figure this out on my own.

**Comment by thadd3us-abcellera** [comment]
+1 to better documentation.

I just spent the last hour tracking this down by reading source code in:
```
container/layer_tools.bzl
container/image.bzl
```
