### ISSUE TITLE
Document that the "contrib" rules are not recommended

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_docker#1961]
They allow users to run build actions inside a docker container, which is both non-hermetic and very slow. This use case should almost always be handled by adding third-party software to the base image outside of Bazel.

**Comment by Toplife** [comment]
I think this is not suitable for large organizations，because it will be out of control🙈

**Comment by alexeagle** [comment]
@Toplife could you clarify? I can't tell if that's a statement in favor of this proposal or against :)
