### ISSUE TITLE
stamp variable does not expand in container_run_and_commit_layer rule

### ISSUE THREAD

**Issue by kriswuollett** [bazelbuild/rules_docker#1973]
# 🐞 bug report

### Affected Rule

The issue affects the rule: `container_run_and_commit_layer` 

### Is this a regression?

I assume it is a regression, but I did not search for the previous version in which this bug was not present.

### Description

Stamp variables like `{BUILD_USER}` are not expanded in the `env` attribute of [`container_run_and_commit_layer`](container_run_and_commit_layer).

## 🔬 Minimal Reproduction

Check out my [`rules_docker_no_stamping`](https://github.com/kriswuollett/sandbox/tree/rules_docker_no_stamping) sandbox repo branch, and then run `./test.sh`.

## 🔥 Exception or Error

The output of `./test.sh` is currently:

```
BUILD_USER={BUILD_USER}
BUILD_SCM_REVISION={BUILD_SCM_REVISION}
```

It should be reflecting the values in `bazel-out/stable-status.txt` and `bazel-out/volatile-status.txt` instead.
## 🌍  Your Environment

**Operating System:**

```
macOS 12.0.1 (Intel)
```

**Output of `bazel version`:**

```
Bazelisk version: development
Build label: 4.2.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:24:28 2021 (1630337068)
Build timestamp: 1630337068
Build timestamp as int: 1630337068
```

**Rules_docker version:**

<pre>
  <code>
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "c27ab432594e793eb864604ec0e4cfd708285218da663b805eefdd479378da93",
    strip_prefix = "rules_docker-2b35b2dd56f0be6cc6b8df957332a31435f6b3ce",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/2b35b2dd56f0be6cc6b8df957332a31435f6b3ce.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

Originally encountered issue on `Ubuntu 20.04.3` with same Bazel and rules_docker versions.

**Comment by alexeagle** [comment]
Your repro uses rules_docker at sha 2b35b2dd56f0be6cc6b8df957332a31435f6b3ce.tar.gz which includes the breaking change that only produces stamp outputs with `--stamp`
https://github.com/bazelbuild/rules_docker/commit/2b35b2dd56f0be6cc6b8df957332a31435f6b3ce explains it.

The README clearly says it should do this https://github.com/bazelbuild/rules_docker/blob/master/docker/util/README.md#container_run_and_commit_layer
but I don't see where that happens in the implementation
https://github.com/bazelbuild/rules_docker/blob/1bb136eb4661624eb8ac1e607cdf74369987b46d/docker/util/run.bzl#L300-L421

So maybe the docs were always wrong? 
On slack you said you also had this problem using 0.21.0. 
Does it repro there too?
