### ISSUE TITLE
`container_pull` doesn't respect vars from `--workspace_status_command`

### ISSUE THREAD

**Issue by charlesoconor** [bazelbuild/rules_docker#1985]
# 🐞 bug report

### Affected Rule

`container_push` not longer can expand variables passed from `--workspace_status_command bin/print-workspace-status.sh`. The script is 

```
#!/usr/bin/env bash

# This script was used by bazel as the workspace_status_command to implement
# build stamping with git information.
#
# Usage: `bin/print-workspace-status.sh`.

set -o errexit
set -o nounset
set -o pipefail

ROOT=$(dirname "${BASH_SOURCE[0]}")/..

git=(git --work-tree "${ROOT}")
GIT_COMMIT=$("${git[@]}" rev-parse "HEAD^{commit}" 2>/dev/null)
GIT_TAG=$(git describe --tag --always)

# Prefix with STABLE_ so that these values are saved to stable-status.txt
# instead of volatile-status.txt.
# Stamped rules will be retriggered by changes to stable-status.txt, but not by
# changes to volatile-status.txt.
cat <<EOF
GIT_COMMIT ${GIT_COMMIT-}
GIT_TAG ${GIT_TAG-}
EOF
```

Seems to work if the push target is only one directory down from root but breaks if nested into lower directories. 

```
container_push(
   name = "test",
    ....
    tag = "test_{GIT_TAG}",
)
```

### Is this a regression?

This worked in `v0.21.0` and previous versions. This is a regression in `v0.22.0` release. 

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Push rules need access to a repo to push to. I can create a minimal example if requested though. 

## 🔥 Exception or Error

<pre><code>
2021/12/17 12:49:18 Error pushing image to registry.hub.docker.com:test_{GIT_TAG}: error parsing "registry.hub.docker.com:test_{GIT_TAG}" as an image reference: could not parse reference: registry.hub.docker.com:test_{GIT_TAG}

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
mac but also failed in CI which is linux ubuntu 18.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.2.1-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
v0.22.0
  </code>
</pre>

**Anything else relevant?**

**Comment by scoquelin** [comment]
Same error here after moving from an old version all the way to rules_docker `v0.22.0` (btw also tried `v0.23.0`)
Sticking with `v0.21.0` which works for that use case !
Thanks @charlesoconor for reporting

**Comment by charlesoconor** [comment]
I think this is a know breaking change and we should be using `--stamed` from here https://github.com/bazelbuild/rules_docker#varying-image-names 

would probably have read the release notes more closely. https://github.com/bazelbuild/rules_docker/releases
