### ISSUE TITLE
Add retry option to container_push rule

### ISSUE THREAD

**Issue by jumbosushi** [bazelbuild/rules_docker#1989]
# 🚀 feature request

### Relevant Rules

[`container_push`](https://github.com/bazelbuild/rules_docker/blob/4c6d61c356aed293ea18c30d7dc50cfa609a3cf6/contrib/push-all.bzl#L96) in `contrib/push-all.bzl` 

### Description

It would be great if `container_push` rule supports a retry option. (this is an idea briefly explored in #673). We recently ran into a transient networking issue which was resolved by retrying manually:

```
# note: gcr info is deducted
2021/12/19 19:16:45 Unable to publish images: unable to push image gcr.io/xyz:abc: Head "https://gcr.io/v2/xyz/blobs/sha256:abc": read tcp 10.248.250.64:53422->142.250.148.82:443: read: connection reset by peer
```

### Describe the solution you'd like

- Add a new `retry` attribute to `container_push` rule like the following. 
```starlark
container_push = rule(
    attrs = {
        ...
        "retry": attr.bool(
            default = False,
            doc = "If true, retry push images on transient errors.",
        ),
    }
    ...
)
```
- Update `container/go/cmd/pusher/pusher.go` to support `--retry` boolean flag to enable retry logic

### Describe alternatives you've considered

We could add a retry logic to our `bazel run` invocations as a workaround, but we run it at various places within our CI system :/ 

---

I would be interested in working on the implementation! Let me know if the feature would be useful

**Comment by uhthomas** [comment]
This would be great. Transient network failures when pushing dozens of images using `container_bundle` is really inconvenient.
