### ISSUE TITLE
Automatically stamp well-known OCI base annotations for $lang_image rules

### ISSUE THREAD

**Issue by v3n** [bazelbuild/rules_docker#1996]
# 🚀 feature request

### Relevant Rules

All `${lang}_image` rules.

### Description

The OCI image spec [declares several well-known annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md). These annotations are useful for traceability, such as the `org.opencontainers.image.base.name ` and `org.opencontainers.image.base.digest` annotations for tracing the parent image that this image was based on.

### Describe the solution you'd like

- `container_pull` propagates digest information [via a provider](https://github.com/bazelbuild/rules_docker/blob/master/container/providers.bzl#L36) (this exists already).
- `${lang}_image` rules automatically adds the well-known labels listed above from the [PullInfo provider](https://github.com/bazelbuild/rules_docker/blob/master/container/providers.bzl#L36).

### Describe alternatives you've considered

- Custom rule–probably better to solve upstream to avoid reimplementing each lang_image rule.

**Comment by psalaberria002** [comment]
Could this be re-opened? @v3n did you have time to look into it?
