### ISSUE TITLE
Improve documentation on `container_push`

### ISSUE THREAD

**Issue by davidvandebunte** [bazelbuild/rules_docker#2003]
# 🚀 feature request

## Description

I'm relatively new to bazel (and `rules_docker`) and was recently trying to push an image using `container_push`. It was not clear to me, as an outsider, that building the `container_push` target only created a script that I would need to run manually/separately. For example, it seems the user needs to run `./bazel-bin/content/push_hugo_img` after building a target named `push_hugo_img` in the content subdirectory.

## Describe the solution you'd like

There's nothing wrong with this design; only my assumption that building the target pushed the image. I expect other outsiders may have the same assumption, though, and a comment in the documentation could help.

**Comment by SnipyJulmy** [comment]
What are you doing the push the image ? Because just running the rules push the image on a registry for me.

**Comment by supercairos** [comment]
you should use `bazel run //your-push-target`

**Comment by davidvandebunte** [comment]
Ah it's `bazel run` rather than `bazel build`! That makes sense, thanks @SnipyJulmy and @supercairos.
