### ISSUE TITLE
Propagate new values for stamping introduced in 0.22.0 to language rules

### ISSUE THREAD

**Issue by joca-bt** [bazelbuild/rules_docker#2011]
# 🚀 feature request

### Relevant Rules

All [languages rules](https://github.com/bazelbuild/rules_docker#language-rules) (`<language>_image`).

### Description

Version [0.22.0](https://github.com/bazelbuild/rules_docker/releases/tag/v0.22.0) introduced new values for stamping (`stamp:always`, `stamp:never`, and `stamp:use_stamp_flag`) for the [basic rules](https://github.com/bazelbuild/rules_docker#basic-rules) via https://github.com/bazelbuild/rules_docker/pull/1878/. However, the [language rules](https://github.com/bazelbuild/rules_docker#language-rules) were not updated and are still using the old stamping values (`True` and `False`).

For images generated via language rules, stamping for the Docker part can only be controlled via `--stamp`. For example, `java_image` is a macro that calls rules `java_binary` and `jar_app_layer`. `jar_app_layer` reuses `container_image`. Since this call to `container_image` doesn't provide any `stamp` argument the implementation is using the default value (`stamp:use_stamp_flag`).

### Describe the solution you'd like

All rules from `rules_docker` use the same values for stamping.

**Comment by joca-bt** [comment]
@alexeagle do you think this suggestion would make sense?

**Comment by alexeagle** [comment]
Yes, for sure, thank you for the description in the linked issue as well.

**Comment by joca-bt** [comment]
Dear bot, please don't close this issue.

**Comment by joca-bt** [comment]
I don't particularly care about this anymore since we are now doing it another day but I think it shouldn't be closed.
