### ISSUE TITLE
Java image .tar file is not generated in bazel-bin

### ISSUE THREAD

**Issue by juanpmarin** [bazelbuild/rules_docker#2014]
# 🐞 bug report

### Affected Rule

java_image

### Is this a regression?

Yes, it works well on v0.22.0

### Description

I have a java_image target, the label is `//src/main/java/com/example/myproject`, if I run `bazel build //src/main/java/com/example/myproject:myproject.tar` it should create a tar file in bazel-bin, which is `bazel-out/k8-fastbuild/bin` but instead, the tar is generated in the path `bazel-out/k8-fastbuild-ST-4a519fd6d3e4/bin`

This is the console output
```
INFO: Analyzed target //src/main/java/com/example/myproject:myproject.tar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //src/main/java/com/example/myproject:myproject.tar up-to-date:
  bazel-out/k8-fastbuild-ST-4a519fd6d3e4/bin/src/main/java/com/example/myproject/myproject.tar
INFO: Elapsed time: 0.084s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

## 🔬 Minimal Reproduction

Clone https://github.com/juanpmarin/bazel-java-image-bug
Run `bazel build //src/main/java/com/example/myproject:myproject.tar`

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Fedora 35
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.11.0
Build label: 5.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:08:54 2022 (1642601334)
Build timestamp: 1642601334
Build timestamp as int: 1642601334
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
0.23.0
  </code>
</pre>

**Anything else relevant?**

**Comment by fparga** [comment]
Same issue for me with nodejs images

**Comment by mashail** [comment]
We have the same issue with `go_image`

**Comment by SanjayVas** [comment]
This also affects the base `container_image` rule, so I imagine it might affect image tar generation in general.

**Comment by SanjayVas** [comment]
I suspect this is an issue with transitions, possibly introduced in https://github.com/bazelbuild/rules_docker/pull/1963

**Comment by uhthomas** [comment]
I don't believe `bazel-bin` is stable, artefacts should be located with cquery instead.

See https://github.com/GoogleContainerTools/skaffold/pull/7251 for an example.

**Comment by njlr** [comment]
For anyone stumbling on this, I was able to get a stable path by copying the output:

```starlark
load("@bazel_skylib//rules:copy_file.bzl", "copy_file")

# ...

container_image(
  name = "my_image",
  # ...
)

copy_file(
  name = "my_image_archive",
  src = ":my_image.tar",
  out = "my_image_archive.tar",
  is_executable = False,
  allow_symlink = True,
)
```
