### ISSUE TITLE
Pushing individual layers of docker images

### ISSUE THREAD

**Issue by pcmoritz** [bazelbuild/rules_docker#2025]
# 🚀 feature request

### Relevant Rules

This is about the `container_push` rule.

### Description

There is a TODO item in https://github.com/bazelbuild/rules_docker/blob/2b35b2dd56f0be6cc6b8df957332a31435f6b3ce/container/push.bzl#L41 to push by later. What would be needed to change the current implementation to do that? Is the old python based implementation still around and could be looked at for comparison?

### Describe the solution you'd like

Fast incremental pushing that only pushes the layers that have changed.

### Describe alternatives you've considered

Go through the version history and see when layers were still pushed incrementally?

**Comment by betaboon** [comment]
still relevant to me

**Comment by betaboon** [comment]
still relevant to me
