### ISSUE TITLE
container_import doesn't work with compressed tarballs

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/rules_docker#2045]
# 🐞 bug report

### Affected Rule

container_import

### Is this a regression?

No.

### Description

Contrary to the documentation, container_import doesn't work with compressed tarballs.

## 🔬 Minimal Reproduction

Use a .tar.gz for container_load.

## 🔥 Exception or Error

```txt
Failed to load tarball into OCI format: failed to read docker image tarball from ... archive/tar: invalid tar header
```

## 🌍  Your Environment

**Operating System:**

**Output of `bazel version`:**

**Rules_docker version:**

**Anything else relevant?**

**Comment by marczych-zoox** [comment]
I'm seeing the same behavior with `container_load` whose docs also indicate that it should work with a compressed tarball.

**Comment by pjjw** [comment]
piling on with a +1.

**Comment by marczych-zoox** [comment]
Can we reopen this?

**Comment by pjjw** [comment]
fwiw we worked around this by tarring the docker-generated tarball (so a tar in a tar), gzipping that, and then using http_archive to get a repository with the importable tarball.

**Comment by marczych-zoox** [comment]
Yeah, we did the same thing but I was hoping for a less hacky workaround. If nothing else, the documentation is out of date.
