### ISSUE TITLE
Mac 12.3 removed python 2.7, resulting in a regression

### ISSUE THREAD

**Issue by sbussard** [bazelbuild/rules_docker#2046]
# 🐞 bug report

### Affected Rule

rules_docker

### Is this a regression?

Yes, kind of (see below)

### Description

MacOS 12.3 removed python 2, so rules_docker doesn't work anymore.

https://www.macrumors.com/2022/01/28/apple-removing-python-2-in-macos-12-3/#:~:text=Apple%20will%20no%20longer%20bundle,security%20patches%2C%20or%20other%20changes.

## 🔬 Minimal Reproduction

WORKSPACE
```bazel
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "59536e6ae64359b716ba9c46c39183403b01eabfbd57578e84398b4829ca499a",
    strip_prefix = "rules_docker-0.22.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.22.0/rules_docker-v0.22.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load(
    "@io_bazel_rules_docker//java:image.bzl",
    _java_image_repos = "repositories",
)

_java_image_repos()
```

BUILD
```bazel
load("@io_bazel_rules_docker//java:image.bzl", "java_image")

java_image(
    name = "image",
    srcs = glob(["src/*.java"]),
    main_class = "App",
)
```

## 🔥 Exception or Error

<pre><code>
env: python: No such file or directory
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS 12.3
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.11.0
Build label: 4.2.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 2 18:28:52 2021 (1638469732)
Build timestamp: 1638469732
Build timestamp as int: 1638469732
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
0.22.0
  </code>
</pre>

**Anything else relevant?**

**Comment by sbussard** [comment]
This fixes it for me

```zsh
brew install python3
brew link python@3.9
ln -s -f /usr/local/bin/python3.9 /usr/local/bin/python
```

**Comment by gravypod** [comment]
Thanks for reporting this. I think this comes from our last python holdout `build_tar.py` which I haven't been able to re-implement in something else. I don't currently have time to fix this. If anyone is able to I'd be more than happy to review the CL. Ping me on Slack, corp chat, or via email and I'll make the review a priority.

**Comment by dennajort** [comment]
Hi there, I have the same problem, but I don't think it comes from `build_tar.py` but https://github.com/bazelbuild/rules_docker/blob/master/container/incremental_load.sh.tpl#L118 
Here it is calling `python` that doesn't exists anymore on MacOS 12.3. Replacing it with `python3` could be a quick fix.

**Comment by dennajort** [comment]
I created a very basic PR that move the usage of python to python3. @sbussard can you try if my fork on master fixes your problem ?

**Comment by dennajort** [comment]
@sbussard my PR has been merged to master, you can try with master or next release version.

**Comment by sbussard** [comment]
Thanks for adding the fix. I've already updated my machine with the workaround, and it'll be a bit of a hassle to reproduce and check it. I'll close the issue.
