### ISSUE TITLE
Parallelism issues with container_run_and_commit_layer

### ISSUE THREAD

**Issue by SanjayVas** [bazelbuild/rules_docker#2054]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: container_run_and_commit_layer

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.19.0

### Description

 There appears to be a potential parallelism issue when an image that a container_run_and_commit_layer target depends on gets dropped. The error doesn't occur when downgrading to the older version of rules_docker I was using, passing `--jobs=1` to `bazel`, or trying to build a smaller subset of targets first which builds up the cache.

## 🔬 Minimal Reproduction

At commit: https://github.com/world-federation-of-advertisers/containers/tree/b88925fa60fed7c7c72896f5ef453b6af2d775d9

1. Ensure you're not using cached results (e.g. `bazel clean`), as caching appears to affect error reproduction.
2. `bazel build ...` to build all targets.

I apologize the code sample isn't quite so minimal. I haven't figured out exactly which part of the configuration causes the problem. One hunch is that it has to do with multiple of these targets sharing a base image.

## 🔥 Exception or Error

```
bazel/BUILD.bazel:31:38: RunAndCommitLayer bazel/apt_packages-layer.tar failed: (Exit 1): apt_packages.build failed: error executing command bazel-out/k8-fastbuild/bin/bazel/apt_packages.build

Use --sandbox_debug to see verbose messages from the sandbox
Error: No such image: bazel/bazel:apt_packages
Loaded image: bazel/image:image
sha256:0ca6addabbfa9286fc7339807f455c53ffeef8809d90ad2a0b2ff014c84c58b5
810187432fdc7875fe476bc7a6131d5beed7031d0fb9162e61ab313c08d1f589
INFO: Elapsed time: 116.107s, Critical Path: 114.66s
INFO: 165 processes: 65 internal, 100 linux-sandbox.
FAILED: Build did NOT complete successfully
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
gLinux Rodete (based on Debian Bookworm)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: gbazelisk_2022.03.27_RC00
Build label: 5.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:08:54 2022 (1642601334)
Build timestamp: 1642601334
Build timestamp as int: 1642601334
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
0.23.0
  </code>
</pre>

**Anything else relevant?**

**Comment by ns-ggeorgiev** [comment]
I observed the same
