### ISSUE TITLE
Got permission denied while trying to connect to the Docker daemon socket using container_run_and_commit

### ISSUE THREAD

**Issue by nev888** [bazelbuild/rules_docker#2085]
# 🐞 bug report

### Affected Rule
container_run_and_commit

### Is this a regression?
No.

### Description

I have a dev container and inside this dev container I'm trying to build the main image but the rules fails with permission denied.:

## 🔬 Minimal Reproduction

The dev container is started like:
<code><pre>
docker run --init -i --rm --network host --user root:root --workdir=/repo  -v /var/run/docker.sock:/var/run/docker.sock --volume /repo:/mnt/repo DEV-IMAGE:dirty

Then starting the bazel docker rule:
bazel build bbb

load("@io_bazel_rules_docker//docker/util:run.bzl", "container_run_and_commit")
container_run_and_commit(
  name = "bbb",
  commands = ["touch /xyz"],
  image = "@adc_base//image",
)
</code></pre>
## 🔥 Exception or Error

<code><pre>
ERROR: /build/ims-adc/bbb/BUILD:5:25: Action bbb/bbb_commit.tar failed: (Exit 1): bbb.build failed: error executing command bazel-out/k8-fastbuild/bin/bbb/bbb.build

Use --sandbox_debug to see verbose messages from the sandbox
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/load?quiet=1": dial unix /var/run/docker.sock: connect: permission denied
Target //bbb:bbb failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 40.023s, Critical Path: 1.30s
INFO: 6 processes: 4 internal, 2 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
ubuntu 20.04

Docker version 20.10.12
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.10.1
Build label: 5.1.1
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
"3.51.0-8"
  </code>
</pre>

**Comment by chinmaya-n** [comment]
I'm having the exact same issue as well.

**Comment by wiwa** [comment]
Got this issue as well.
