### ISSUE TITLE
py_binaries aren't executable inside py_image

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_docker#209]
The executable for a `py_binary` starts with this line (from [the template](https://github.com/bazelbuild/bazel/blob/6163d43bada9d6876025200907c8177a371dbe9a/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L1)):

`#!/usr/bin/env python`

However, `env` is not installed inside distroless/python2.7, so you get a `not found` error when you try to execute the script (eg, if it is a dependency of the script that you're running inside the container.

I can't think of a clean solution for this. Installing `env` is not very "minimal", and patching the stubs or installing a fake `env` would be hacky.

### Workaround

Create a new base image based on the debug image, with a link so that `env` is available in `/usr/bin`.

```
container_image(
    name = "base",
    base = "@py_debug_image_base//image",
    symlinks = {"/usr/bin/env": "/busybox/env"},
)
```

**Comment by mattmoor** [comment]
@dlorenc @r2d4 Any thoughts?

**Comment by duggelz** [comment]
It will eventually be possible to specify a `py_runtime` target with the right path, but I'm not sure if all the implementation of that is ready.

Short-term, I used to have a "python_path" flag to the compiler that was removed in favor of parsing Bazel's stub file.  We could add that flag back in, so that you'd have something like:

```
py_binary(
    ...
    python_path = "/path/inside/docker",
)
```

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.

**Comment by drigz** [comment]
I don't have the privileges to reopen, but this is still an issue.

Repro:

```
cat > WORKSPACE << EOF
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_bazel_rules_docker",
    commit = "7672a86f175f961902f074185d91c51ea2f7e2a7",
    remote = "https://github.com/bazelbuild/rules_docker.git",
)

load(
    "@io_bazel_rules_docker//python:image.bzl",
    _py_image_repos = "repositories",
)

_py_image_repos()
EOF
cat > BUILD.bazel << EOF
load("@io_bazel_rules_docker//python:image.bzl", "py_image")
load("@io_bazel_rules_docker//container:image.bzl", "container_image")

py_image(
    name = "main",
    srcs = ["main.py"],
    main = "main.py",
)

container_image(
    name = "main_wrapped",
    base = ":main",
    entrypoint = ["/app/main.binary"],
)
EOF
bazel run :main_wrapped
```

gives the error:

```
standard_init_linux.go:190: exec user process caused "no such file or directory"
```

Changing the entrypoint is just an easy way to repro: the issue arose for me when trying to execute a `py_binary` as a subprocess within an container.
