### ISSUE TITLE
Release rules_docker on tag to the repo

### ISSUE THREAD

**Issue by gravypod** [bazelbuild/rules_docker#2102]
Right now releases are done manually be me from a script in google3 which has been deleted at head. This script zips the repo, generates a description, and uploads it to github. I would love if this process was automated outside of google3.

Ideal workflow:

1. We make a release branch `git checkout -b release-0.29.0`
2. We push the release branch `git push -u origin release-0.29.0`
3. Git automatically creates a release for this branch called `0.29.0.zip` with all of the PRs that have been merged included in it.

**Comment by kriscfoster** [comment]
I may have a chance to do this later this week if it hasn't been done by someone else before then. I believe it will be related to https://github.com/bazelbuild/rules_docker/blob/master/.github/workflows/add_binaries_to_release.yml.

**Comment by kriscfoster** [comment]
Hi @gravypod, PR listed above. I actually made the experience the following:

- go to whatever branch you want to release from e.g. `master`
- `git tag -a v0.25.0 -m ""`
- `git push origin v0.25.0`
- [a release is created](https://github.com/kriscfoster/rules_docker/releases/tag/v0.25.0)

[Here's a demo.](https://drive.google.com/file/d/1uBiV_xlxUf4FaXDxYNwzSt8AjHGmg8Xq/view?usp=sharing)

**Comment by uhthomas** [comment]
Fixed by https://github.com/bazelbuild/rules_docker/pull/2106
