### ISSUE TITLE
Add zst compression handling for deb archives to container rules

### ISSUE THREAD

**Issue by y0psolo** [bazelbuild/rules_docker#2104]
# 🚀 feature request

### Relevant Rules

Add zst decompression capabilies to "build_tar.py" inside container rules (/container/build_tar.py)

### Description

Ubuntu Jammy comes with deb files where data.tar archive is compressed with zstd. As the build_tar.py archive only support gz and xz compression we may need to add zst compression handling without breaking current xz ang gz compression.

### Describe the solution you'd like

Add a function relying on zstd binary tro decompress files with .zst suffix when encountered inside a deb archive. Add the correct trigger for .zst suffix and add a config parameter for specifying zstd binary path.
Modify the docker toolchain to take into account the zstd binary as configuration with auto discovery through a which command.

### Describe alternatives you've considered

None so far but any suggestions is welcome

**Comment by y0psolo** [comment]
I already have some code modifcation done there https://github.com/y0psolo/rules_docker/blob/master/container/build_tar.py. If you are ok i can create a pull request for that need.

**Comment by EdSchouten** [comment]
Hey @y0psolo, could you submit these changes as a PR? Thanks!

**Comment by y0psolo** [comment]
@EdSchouten sorry for the delay, i submitted a PR.
