### ISSUE TITLE
`container_push` doesn't respect `cred_helpers` attribute within docker toolchains

### ISSUE THREAD

**Issue by dyatlov** [bazelbuild/rules_docker#2109]
`container_pull` accepts `cred_helpers` and allows to use native login helper binaries but it's not implemented for `container_push` which makes it impossible to push images to a private repo.

**Comment by loeffel-io** [comment]
+1 (!)

**Comment by titanous** [comment]
I implemented this in #2115.

**Comment by loeffel-io** [comment]
🎉

**Comment by titanous** [comment]
Bump.
