### ISSUE TITLE
should `//contrib:test.bzl` be moved to `//container:test.bzl`?

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_docker#2112]
# 🚀 feature request

### Description

I've been looking for a rule which allows me to build an image and run it as a test with some unique arguments per test. I think `//contrib:test.bzl%container_test` might get me what I want but am confused why this functionality isn't something front and center in the `//container` package. Would it be reasonable to move this rule and begin to make that functionality more visible to users? What's the purpose of the `//contrib` package?

**Comment by UebelAndre** [comment]
This is still desired

**Comment by alexeagle** [comment]
I am moving this rule to the https://github.com/GoogleContainerTools/container-structure-test repo.
