### ISSUE TITLE
Latest relesae (v0.25.0) is not compatible with latest rules_go (v0.35.0)

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_docker#2157]
# 🐞 bug report

### Description

Attempting to use [rules_go v0.35.0](https://github.com/bazelbuild/rules_go/releases/tag/v0.35.0) with [rules_docker v0.25.0](https://github.com/bazelbuild/rules_docker/releases/tag/v0.25.0) leads to the following error
```
ERROR: /Users/Code/BUILD.bazel:33:19: every rule of type container_push_ implicitly depends upon the target '@io_bazel_rules_docker//container/go/cmd/pusher:pusher', but this target could not be found because of: error loading package '@io_bazel_rules_docker//container/go/cmd/pusher': at /private/var/tmp/_bazel_user/5f6cb807741f123860937f76a6878615/external/bazel_gazelle/def.bzl:34:5: at /private/var/tmp/_bazel_user/5f6cb807741f123860937f76a6878615/external/bazel_gazelle/internal/gazelle_binary.bzl:22:5: Label '@io_bazel_rules_go//go/private:rules/aspect.bzl' is invalid because '@io_bazel_rules_go//go/private/rules' is a subpackage; perhaps you meant to put the colon here: '@io_bazel_rules_go//go/private/rules:aspect.bzl'?
```

I attempted to fix this here by updating the pins but that lead to a few additional issues that a maintainer would probably be best qualified to look at: https://github.com/bazelbuild/rules_docker/pull/2155

**Comment by dmivankov** [comment]
Seems to be working with rules_go 0.37.0?

**Comment by alexeagle** [comment]
thanks @dmivankov I'll take that to mean this is no longer an issue.
