### ISSUE TITLE
Add rules_docker to the bzlmod registry

### ISSUE THREAD

**Issue by chris-codaio** [bazelbuild/rules_docker#2165]
# 🚀 feature request

### Description

Add rules_docker to the bzlmod registry, the new external dependency system for Bazel.

https://bazel.build/build/bzlmod

https://github.com/bazelbuild/bazel-central-registry

**Comment by alexeagle** [comment]
FWIW I'm publishing rules_oci to bzlmod right now in https://github.com/bazel-contrib/rules_oci/pull/91

rules_docker doesn't have any active maintainers so I think this is unlikely to happen.

**Comment by alexeagle** [comment]
https://registry.bazel.build/modules/rules_oci is up. If you need any migration docs I can provide them :)

**Comment by alexeagle** [comment]
Dupe of #2116
