### ISSUE TITLE
Documentation for container_test

### ISSUE THREAD

**Issue by BeyondEvil** [bazelbuild/rules_docker#2179]
Is container_test documented somewhere?

What is supposed to go into a configuration yaml-file?

**Comment by alexeagle** [comment]
The configuration file is specified at https://github.com/GoogleContainerTools/container-structure-test

rules_docker ought to document this...

**Comment by alexeagle** [comment]
I am moving the rule to the  https://github.com/GoogleContainerTools/container-structure-test repo.
