### ISSUE TITLE
testdata/BUILD warning: target 'passwd' is both a rule and a file

### ISSUE THREAD

**Issue by Capstan** [bazelbuild/rules_docker#218]
`WARNING: /…/rules_docker/testdata/BUILD:408:1: target 'passwd' is both a rule and a file; please choose another name for the rule.`

**Comment by Capstan** [comment]
Repros with `bazel build //testdata:cc_image`

**Comment by mattmoor** [comment]
@tejal29 I think we can fix this by simply referencing the output differently, can you TAL at this?

@dlorenc FYI

**Comment by ash2k** [comment]
I think this has been fixed in https://github.com/bazelbuild/rules_docker/pull/306.

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
