### ISSUE TITLE
Support for cosign as part of container_push

### ISSUE THREAD

**Issue by rajatvig** [bazelbuild/rules_docker#2190]
# 🚀 feature request

### Relevant Rules

container_push

### Description

Support [cosign](https://github.com/sigstore/cosign) as part of the container_push rule to sign docker images?

### Describe alternatives you've considered

NA.

**Comment by thesayyn** [comment]
rules_oci, an alternative to rules_docker, supports this feature. https://github.com/bazel-contrib/rules_oci/blob/main/example/sign/BUILD.bazel
