### ISSUE TITLE
nodejs toolchain resolution fails on M1 with rules_nodejs >= 5.6.0

### ISSUE THREAD

**Issue by mattsoulanille** [bazelbuild/rules_docker#2197]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `container_deps()` WORKSPACE rule.

### Is this a regression?

I don't think so. I tried some earlier versions, including 0.20.0 (with repo mapping `@nodejs` to `@nodejs_host`), but the error persisted. My guess is this was caused by a change `rules_nodejs` made that `rules_docker` may need to adapt to. However, the breakage is between minor versions of `rules_nodejs`, so this may be a regression on their side. I'm happy to create an issue there if necessary, and I'll see if I can find the cause by looking at the difference between `5.5.4` and `5.6.0`.

### Description

When using `rules_nodejs >= 5.6.0` on an Apple Silicon mac with `rules_docker`, running `container_deps()` in the WORKSPACE file to set up `rules_docker`'s deps results in the `@rules_nodejs//nodejs:toolchain_type` toolchain not being resolved by rules like `nodejs_binary`.

## 🔬 Minimal Reproduction

https://github.com/mattsoulanille/docker_rules_nodejs_issue
## 🔥 Exception or Error

<pre><code>
% bazel run :index_bin --toolchain_resolution_debug='nodejs' --define=VERBOSE_LOGS=1
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @nodejs_linux_amd64//:node_toolchain; mismatching values: linux, x86_64
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: execution platform @local_config_platform//:host: Rejected toolchain @nodejs_linux_amd64//:node_toolchain; mismatching values: linux, x86_64
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @nodejs_linux_arm64//:node_toolchain; mismatching values: linux, arm64
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: execution platform @local_config_platform//:host: Rejected toolchain @nodejs_linux_arm64//:node_toolchain; mismatching values: linux, arm64
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @nodejs_linux_s390x//:node_toolchain; mismatching values: linux, s390x
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: execution platform @local_config_platform//:host: Rejected toolchain @nodejs_linux_s390x//:node_toolchain; mismatching values: linux, s390x
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @nodejs_linux_ppc64le//:node_toolchain; mismatching values: linux, ppc
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: execution platform @local_config_platform//:host: Rejected toolchain @nodejs_linux_ppc64le//:node_toolchain; mismatching values: linux, ppc
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @nodejs_darwin_amd64//:node_toolchain; mismatching values: x86_64
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: execution platform @local_config_platform//:host: Rejected toolchain @nodejs_darwin_amd64//:node_toolchain; mismatching values: x86_64
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @nodejs_darwin_arm64//:node_toolchain; mismatching values: arm64
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: execution platform @local_config_platform//:host: Rejected toolchain @nodejs_darwin_arm64//:node_toolchain; mismatching values: arm64
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @nodejs_windows_amd64//:node_toolchain; mismatching values: windows, x86_64
INFO: ToolchainResolution:     Type @rules_nodejs//nodejs:toolchain_type: execution platform @local_config_platform//:host: Rejected toolchain @nodejs_windows_amd64//:node_toolchain; mismatching values: windows, x86_64
INFO: ToolchainResolution:   Type @rules_nodejs//nodejs:toolchain_type: target platform @local_config_platform//:host: No toolchains found.
ERROR: /Users/matthew/Projects/docker_rules_nodejs_issue/BUILD.bazel:3:14: While resolving toolchains for target //:index_bin: no matching toolchains found for types @rules_nodejs//nodejs:toolchain_type
ERROR: Analysis of target '//:index_bin' failed; build aborted: 
INFO: Elapsed time: 0.272s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (38 packages loaded, 259 targets configured)
FAILED: Build did NOT complete successfully (38 packages loaded, 259 targets configured)
</code></pre>

## 🌍  Your Environment

**Operating System:** 
<pre>
  <code>
MacOS 12.5 Apple Silicon
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 5.4.0
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
0.25.0
  </code>
</pre>

**Anything else relevant?**

**Comment by mattsoulanille** [comment]
[This might be a relevant change](https://github.com/bazelbuild/rules_nodejs/compare/5.5.4...5.6.0#diff-6dd22794844f3d36110ff13790b7264985ad1d19b16ed4742e749c7bde067914R54) in rules_nodejs 5.5.4 -> 5.6.0.

**Comment by mattsoulanille** [comment]
I've confirmed that this is the cause. I overrode the `rules_nodejs` core repo locally and changed this line back to `@platforms//cpu:aarch64`.

**Comment by mattsoulanille** [comment]
I checked this on arm linux as well, since the change also renames the linux cpu, and I get the same error.

```
    "linux_arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
-           "@platforms//cpu:aarch64",
+           "@platforms//cpu:arm64",
        ],
    ),
    ```

**Comment by mattsoulanille** [comment]
This appears to be an issue with `rules_go 0.24.2`. Pinning `rules_go` to [0.33.0](https://github.com/bazelbuild/rules_go/releases/tag/v0.33.0) in my WORKSPACE file and using `rules_docker` at `48ad6d6df43d1e4b9feeec961995aef01dd72080` before running `container_deps()` seems to remove the error, although I haven't tested creating any containers yet.

['Fixed' branch](https://github.com/mattsoulanille/docker_rules_nodejs_issue/tree/workaround)

**Comment by mattsoulanille** [comment]
I also had to pin `gazelle` to `0.28.0` to get `container_push` working.

**Comment by uhthomas** [comment]
So the real fix here is to update rules_go and gazelle in rules_docker?
