### ISSUE TITLE
Document fast local development story with ibazel

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_docker#221]
Discussed in-person: `ibazel run` (https://github.com/bazelbuild/bazel-watcher) is a nice watch mode for Bazel to keep runfiles up-to-date. I'd like to use this for local development, so that when a source file changes, the right images are published and live.

It's possible that some sort of re-hosting on minikube would be useful, but if remote deployment is fast that would satisfy this issue too.

**Comment by pcj** [comment]
Closing due to age/inactivity.
