### ISSUE TITLE
upcoming release timeline?

### ISSUE THREAD

**Issue by yc185050** [bazelbuild/rules_docker#2213]
Looking for this fix https://github.com/bazelbuild/rules_docker/commit/64827560cbbe9359294b9a14e8ac417224f6fdd2 to be included in the next release.
Is there a planned date for upcoming release?

**Comment by uhthomas** [comment]
Thanks, we can cut a release soon. It may be better to wait for bzlmod support first though.

https://github.com/bazelbuild/rules_docker/pull/2201
