### ISSUE TITLE
Generated API Documentation Link broken

### ISSUE THREAD

**Issue by notnarb** [bazelbuild/rules_docker#2224]
https://github.com/bazelbuild/rules_docker/blob/fc729d85f284225cfc0b8c6d1d838f4b3e037749/README.md?plain=1#L7-L8

> Generated API documentation is in the docs folder, or you can browse it online at
<https://docs.aspect.dev/rules_docker>

![image](https://user-images.githubusercontent.com/1731591/222026401-9244c35b-3b14-4c02-bd34-0bf58e74fd83.png)

Looks like the site is no longer hosting rules_docker docs? 

@alexeagle  FYI

**Comment by alexeagle** [comment]
err yeah thanks, it's at https://docs-legacy.aspect.dev/rules_docker

I'll think I'll remove from the README.

**Comment by alexeagle** [comment]
Removed the link.
