### ISSUE TITLE
java_image does not include compile-time deps in the classpath

### ISSUE THREAD

**Issue by kevingessner** [bazelbuild/rules_docker#224]
I have a `java_binary` rule that looks like this, which I tried converting to `java_image`:

```bzl
java_binary(
    name = "my_app",
    main_class = "com.foo.App",
    runtime_deps = [
        "//apps/my_app/src/main/scala/com/foo",
    ],
)
```

Where `//apps/my_app/src/main/scala/com/foo` is a scala_library with many `deps`.  Currently, we deploy the `my_app_deploy.jar` from the `java_binary`, which includes the `scala_library` and all of its transitive dependencies.

However, `java_image` does not include the transitive `deps` in the image.  It only includes the `scala_library` target itself, but none of its compile-time dependencies.  It should include the same transitive deps as `java_binary`.

I think it could be fixed by changing this line to `f.java.transitive_runtime_deps + f.java. transitive_deps`, but I haven't tested it: https://github.com/bazelbuild/rules_docker/blob/d5f7eb48234a2d03b757b930092c56ceda94fca2/java/image.bzl#L98

**Comment by mattmoor** [comment]
That sounds like an interesting nuance between Java and Scala, I had not tried mixing these before.

My schedule has been chaos this week thanks to Bazelcon, but I have tried to block some time tomorrow to take a look (and at least try to reproduce for a unit test, if not fix).

Thanks for reaching out, and it was great meeting you at Bazelcon. :)

**Comment by kevingessner** [comment]
Thanks, Matt.  Apologies for not including this earlier:  I'm using Bazel 0.7.0, rules_docker at 87dd8bb5793b0f5fc0e5e3f951f1202a1f0752cc, and rules_scala at 388a2585f45dff804d006b0e81e1b1a1c60578bc.

**Comment by promiseofcake** [comment]
@kevingessner, is this isolated to containers? I am facing similar behavior with transitive dependencies when a `scala_binary` depends on`java_library` targets (which export deps) illustrated here: https://github.com/promiseofcake/pubref-java-proto-scala/pull/1

**Comment by mattmoor** [comment]
This feels like content that came up during Bazelcon.  Something about a sandwich :)

@damienmg @dslomov FYI  (Anyone have Ittai's GitHub handle?)

**Comment by kevingessner** [comment]
@johnynek @ittaiz ^

FWIW by scala_binary's deps are a combination of scala_librarys and java_librarys; none of them are included in the image.

**Comment by mattmoor** [comment]
(just to confirm that I am seeing what you see)

I added a `Library.scala` variant of `Library.java` and changed `//testdata:java_image` to use the `Library.scala` version, which when I `bazel run testdata:java_image` gives:
```shell
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Joiner                                             
        at examples.Library$.SayHello(Library.scala:22)                                                                              
        at examples.Library.SayHello(Library.scala)                                                                                  
        at examples.images.Binary.main(Binary.java:21)                                                                               
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Joiner                                                           
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)                                                                
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)                                                                     
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)                                                             
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)                                                                     
        ... 3 more                                                                                                                   
ERROR: Non-zero return code '1' from command: Process exited with status 1 
```

**Comment by mattmoor** [comment]
I opened a PR that I think exhibits the issue here, so that we can reason about the code and problem together: https://github.com/bazelbuild/rules_docker/pull/226

Please correct me if this isn't the issue you're seeing.

**Comment by kevingessner** [comment]
Yep @mattmoor, that looks like a good test case to reproduce the problem.  Thanks for putting it together.  Inspecting the image with e.g. `docker run --rm --entrypoint="sh" bazel/testdata:java_sandwich_image -c "ls -R /app"` shows the guava jar is not present in the class path.

**Comment by mattmoor** [comment]
Ping @damienmg @dslomov 

I'm going to take a look at things in the failing example with @duggelz's [wonderful tool](https://github.com/google/subpar/blob/master/debug.bzl#L15) to see what I can find.

**Comment by mattmoor** [comment]
This change seems to do the trick for me:
```shell
$ git diff
diff --git a/java/image.bzl b/java/image.bzl
index 0de09bc..bdb21d5 100644
--- a/java/image.bzl
+++ b/java/image.bzl
@@ -96,6 +96,8 @@ load(
 def java_files(f):
   if hasattr(f, "java"):  # java_library, java_import
     return f.java.transitive_runtime_deps
+  if hasattr(f, "scala"):  # scala_library
+    return f.scala.transitive_runtime_jars
   if hasattr(f, "files"):  # a jar file
     return f.files
   return []
```

I have pushed this to the `scala-sandwich` branch of my fork.  @kevingessner can you confirm whether this fixes things for you?

**Comment by mattmoor** [comment]
On a brighter note, this was all that stood between `scala_image` and fancier layering, so I'm going to push that change to the branch as well :)
