### ISSUE TITLE
need to rerun docker login multiple times during the day

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/rules_docker#225]
when I execute `bazel run <target to container_image rule>` I often get this error:
```
containerregistry.client.v2_2.docker_http_.BadStateException: Bad status during token exchange: 401
{"errors":[{"code":"DENIED","message":"Unable to access the repository; please check that you have permission to access it."}]}
```
and then I have to run
```
docker login -u oauth2accesstoken -p "$(gcloud auth application-default print-access-token)" https://eu.gcr.io
```
Shouldn't the docker rules refresh the tocken on their own?

**Comment by mattmoor** [comment]
Ah, you should definite switch to the credential helper ([docs](https://github.com/bazelbuild/rules_docker#authorization)).  I did and never looked back :)

**Comment by ensonic** [comment]
"""
ERROR: (gcloud.components.install) 
The docker-credential-gcr component(s) is unavailable through the packaging system 
you are currently using. Please consider using a separate installation 
of the Cloud SDK created through the default mechanism described at: 

https://cloud.google.com/sdk/ 
"""

**Comment by mattmoor** [comment]
Hmm, yeah that's something weird `gcloud` does when installed a particular way.

In this case, I believe it's just downloading a Go binary which you can get from the releases page [here](https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases).

@KingEmet FYI

**Comment by KingEmet** [comment]
Ack, have an internal bug for making it work with package managers.

**Comment by mattmoor** [comment]
Aside from gcloud distribution issues, I think this is resolved.  If not please reopen.
