### ISSUE TITLE
Python 3 `py_image` support

### ISSUE THREAD

**Issue by hwright** [bazelbuild/rules_docker#229]
The base image used for `py_image` uses Python 2.7:
https://github.com/bazelbuild/rules_docker/blob/master/python/image.bzl#L43

It would be nice to have a python 3 `py_image` rule available as well, rather than having to construct the rule manually using lower-level constructs.  I realize the base images are grabbed from https://github.com/GoogleCloudPlatform/distroless, and it doesn't yet look like they have a python 3 image available, so there's probably a bit of work involved here.

The relevant Python 3 bug for distroless is here: GoogleCloudPlatform/distroless/issues/111

**Comment by mattmoor** [comment]
/cc @duggelz @dlorenc @r2d4 FYI

Yeah, having a distroless Python 3 base is not strictly a pre-requisite, but would be nice for consistency with the other images.

Having not messed with Python versions too much in Bazel, is there an appropriate kwarg to `py_image` we could key base image selection off of?

**Comment by hwright** [comment]
@mattmoor I'd almost be tempted to call it `py3_image` rather than `py_image` with some special attributes.  There's enough of a language difference that it might make sense to treat it as its own beast.

As for the Bazel support: python 3 support is all over the map, and I'm not sure what the overall plan is there.  I don't know that we want to wait for it to get sorted out before moving forward here.
