### ISSUE TITLE
docker daemon repository rule

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_docker#241]
Hi,
We have a need for running docker daemon in our tests.
The simple use-case is running a docker image of embedded mysql in a service's end-to-end test. 
For this purpose we need to have docker daemon as a dependency in the WORKSPACE file and to link that (as `@data` maybe) to the relevant test target.
Would you be interested in getting a contribution for such a repository rule?
Do you think it should be a repository rule or a toolchain? We of course need to download different binaries according to the different platforms. A toolchain might be a better choice but I'm not sure it's not an overkill. The alternative is to have a few `if`s in the repository rule.
cc @katre since toolchains for his thoughts :)

**Comment by katre** [comment]
This definitely sounds like a case for toolchains. My hope is that using toolchains is easy to set up and not so complicated that people defer the work, so I'd definitely like your thoughts. There are, unfortunately, several sets of rules and build functions to be called, but most of it should be one-time-per-platform setup and not too time-consuming.

Another thing to consider is that, internally at Google, we typically don't use bazel for long-running integration tests that start up several server processes and connect them together. These tend to run for longer than anyone wants the bazel lock to be held, so we have a variety of (sadly, not open-sourced) services that manage these tests out of band. Are these tests things that developers will actually be running from the command-ling with bazel frequently enough to make setting them up worth it, or should they be handled via a different custom-purpose setup?

**Comment by ittaiz** [comment]
Yes definitely. Very often running this suite of tests takes a minute or so so people run it from IntelliJ (which uses Bazel command line). This suite can start a few (3-4 typically) embedded / docker based server and interact with them.

@matmoor- would you be interested in such a toolchain?

@katre- any place which we can look at for "inspiration"?

**Comment by katre** [comment]
@ittaiz Here's the commit where I updated rules_rust to use toolchains: https://github.com/bazelbuild/rules_rust/commit/7b1ba1f2a89006fbe358e97011cb1c1516435806

The important features are:

1. In toolchain.bzl, it defines the new `rust_toolchain` rule, which takes in the required tools and generates a `ToolchainInfo` provider. This file also has some helper functions that take the `ToolchainInfo` provider and build rustc commandlines.
2. In rust.bzl, all rust rules that need a toolchain access it from `ctx.toolchains`.
3. In repositories.bzl, new toolchains are added by first defining them using `rust_toolchain`, and then configuring them with `toolchain` (which associates the toolchain definition with the type, and the execution and target constraints).
4 Finally, also in repositories.bzl, the WORKSPACE function register_toolchains is called to let Bazel know these toolchains are available for use.

The docs are live at https://docs.bazel.build/versions/master/toolchains.html, please please please let me know if they are unclear so I can improve them.

**Comment by ittaiz** [comment]
Thanks. I'll try to see who can take it from other side while I wait for a
reply from Matt

**Comment by ittaiz** [comment]
@mattmoor ping

**Comment by mattmoor** [comment]
Sorry for the delay, digging out from the Holiday state-side.

@dlorenc @nkubala own `container_test`, some modes of which require the daemon.

@nkubala @dlorenc It sounds like @ittaiz would be a great person to engage with to make sure the `container_test` stuff suits their needs.  It sounds a little to me like he wants the pod-like capabilities from the marketplace `functional_test` extensions.

Can you guys work together to land on mutually agreeable requirements?  It sounds like you both have experience here, and I'd like to ensure that we build towards a common foundation (if not solution) for this problem space.

**Comment by ittaiz** [comment]
Thanks! I'll take the opportunity to loop in @barlevalon who'll work on this next week

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
