### ISSUE TITLE
go_image() doesn't respect visibility attr

### ISSUE THREAD

**Issue by damonkohler** [bazelbuild/rules_docker#242]
e.g. go_image(..., visibility = ["//visibility:public"]) will not have the desired effect. However, if you specify the package default visibility, that does work. This can be seen using bazel query --output=proto //target which will print the final visibility after preprocessing.

**Comment by mattmoor** [comment]
Can you try updating the version of the rules that you are using?  I believe this [was fixed](https://github.com/bazelbuild/rules_docker/blob/master/go/image.bzl#L88-L90).

Please re-open if this reproduces at HEAD.
