### ISSUE TITLE
rules_docker and rules_go (go_image) no longer compatible

### ISSUE THREAD

**Issue by kevindrosendahl** [bazelbuild/rules_docker#262]
(Originally reported in rules_go: https://github.com/bazelbuild/rules_go/issues/1112, there is some information about the probable root cause in a reply there)

I've updated rules_go to 0.8.0 as well as bazel to 0.8.0, and I am no longer able to create valid go_images using rules_docker. It appears as if the name of the binary produced is no longer compatible with the name rules_docker is expecting:

```
$ bazel run //:container
INFO: Analysed target //:container (0 packages loaded).
INFO: Found 1 target...
Target //:container up-to-date:
  bazel-bin/container-layer.tar
INFO: Elapsed time: 1.374s, Critical Path: 0.02s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/container
Loaded image ID: sha256:77289d428a7769d045f4c36b58fe1783c615cc1591596a5a0cdf900381464cd5
Tagging 77289d428a7769d045f4c36b58fe1783c615cc1591596a5a0cdf900381464cd5 as bazel:container
container_linux.go:265: starting container process caused "exec: \"/app//container.binary\": stat /app//container.binary: no such file or directory"
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/app//container.binary\": stat /app//container.binary: no such file or directory".

$ docker inspect bazel:container --format '{{.Config.Entrypoint}}'
[/app//container.binary]

$ docker run -it --entrypoint sh bazel:container
/app # ls -l /app//container.binary
lrwxrwxrwx    1 root     0               58 Jan  1  1970 /app//container.binary -> /app//container.binary.runfiles/__main__//container.binary
/app # ls -l /app//container.binary.runfiles/__main__//
total 4
drwxr-xr-x    2 root     0             4096 Jan  1  1970 linux_amd64_stripped
```

Below is a minimal reproducible example:

`WORKSPACE`:
```
http_archive(
     name = "io_bazel_rules_go",
     url = "https://github.com/bazelbuild/rules_go/releases/download/0.8.0/rules_go-0.8.0.tar.gz",
     sha256 = "8eaf2e62811169d9cf511209153effcb132826cea708b2f75d4dd5f9e57ea2aa",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "cce1de49c54b145a9d9542685660f72d8fa593a7",
)
load("@io_bazel_rules_docker//go:image.bzl", _go_image_repos = "repositories")
_go_image_repos()
```

`BUILD`:

```
load("@io_bazel_rules_go//go:def.bzl", "go_prefix")
go_prefix("example")

load("@io_bazel_rules_docker//go:image.bzl", "go_image")
go_image(
    name = "container",
    base = "@go_debug_image_base//image",
    importpath = "example/cmd",
    library = "//cmd:go_default_library",
    visibility = ["//visibility:public"],
)
```

`cmd/main.go`:
```
package main

import "fmt"

func main() {
        fmt.Println("hello world")
}
```

`cmd/BUILD`:
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "example/cmd",
    visibility = ["//visibility:public"],
)

go_binary(
    name = "cmd",
    embed = [":go_default_library"],
    importpath = "example/cmd",
    visibility = ["//visibility:public"],
)
```

**Comment by margic** [comment]
go_rules adds a target cpu to the part to the path linux_amd64_pure_stripped in the case of k8.

I used a go_image like this
`
go_image(
    name = "service1-image",
    binary = ":service1",
)
`

referring to an exiting go_binary() service1

That would create the binary in the image however rules_docker doesn't use that in the base lang/image.bzl

in lang/image.bzl 
I added the literal  "linux_amd64_pure_stripped" to be added to the link to the binary

` symlinks += {
    # Create a symlink from our entrypoint to where it will actually be put
    # under runfiles.
    _binary_name(ctx): "/".join([_reference_dir(ctx), ctx.label.package, "linux_amd64_pure_stripped",
                                 ctx.attr.binary.label.name]),
    # Create a directory symlink from <workspace>/external to the runfiles
    # root, since they may be accessed via either path.
    _external_dir(ctx): _runfiles_dir(ctx),
  }`

And this worked. This is clearly not an answer but it did work. So I figured I'd share to show where abouts the issue is. I'm going to dig around to see it there is actually a more compatible way to do this with the rest of the docker rules. But I'm sure someone will beat me to it.

**Comment by ah-edg** [comment]
I think replacing double slashes with single slashes would suffice - at least in this case. The binary is at the right location and has the right name, cleaning up the result of _binary_name results would suffice.
But the right way would apparently involve `ctx.files` or `ctx.file` (as mentioned by the rules_go maintainer in the linked issue).
