### ISSUE TITLE
container_push not pushing image, does not fail either

### ISSUE THREAD

**Issue by tagarwal** [bazelbuild/rules_docker#265]
load("@io_bazel_rules_docker//java:image.bzl", "java_image")
load("@io_bazel_rules_docker//docker:docker.bzl", "container_push")

java_image(
    name = "httpserver",
    srcs = ["src/main/java/com/example/httpserver/myHttpServer.java"],
    main_class = "com.example.httpserver.myHttpServer",
    deps = ["//ProjectRunner:greeter"]
)

container_push(
    name = "publish",
    format = "Docker",
    registry = "wcr.io",
    repository = "aura/tagarwal/samplehttpserver",
    tag="tagarwal",
    image=":httpserver"
)

`bazel build :publish`
INFO: Found 1 target...
Target //httpserver:publish up-to-date:
  bazel-bin/httpserver/publish
INFO: Elapsed time: 4.036s, Critical Path: 2.51s

But looking at wcr.io/aura/tagarwal/samplehttpserver:tagarwal the image is not there
The java.log file in output_directory also does not indicate any errors.
What might be the problem over here

I am using
`git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    tag = "v0.3.0",
)`

**Comment by mattmoor** [comment]
`bazel run` will do what you want.  We don't publish on `bazel build` because it isn't hermetic.

**Comment by mattmoor** [comment]
(Feel free to reopen if things still don't work)
