### ISSUE TITLE
Allow setting the container cmd in the X_image rule

### ISSUE THREAD

**Issue by tanner-bruce** [bazelbuild/rules_docker#268]
I don't think this really fits in with the model however it would be nice to be able to set the `cmd` right in the X_image rule.

**Comment by mattmoor** [comment]
You can get the same effect by doing something like:
```python
lang_image(
   name = "foo",
   ...
)

container_image(
   name = "bar",
   base = ":foo",
   cmd = [...],
)
```

This is somewhat verbose, but you can also define a macro that does this, to get exactly what you want.  An example of this pattern with other rules can be found [here](https://github.com/bazelbuild/rules_docker/blob/master/contrib/with-tag.bzl).

**Comment by tanner-bruce** [comment]
Thanks for that link, @mattmoor !

p.s great presentation/demo on rules_k8s, really appreciate the work you are doing.

**Comment by mattmoor** [comment]
Glad you like it all!

If you have any feedback / questions / whatever please don't hesitate to open an issue here/elsewhere.
