### ISSUE TITLE
Cred Helper docs are broken

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_docker#275]
Looks like gcloud stopped distributing `docker-credential-gcr`, see [here](https://github.com/bazelbuild/rules_docker#authorization)

**Comment by evanj** [comment]
I think this is not true: #278 was my mistake: `docker-credential-gcr` does work, and is installable via an extra component. It is `gcloud docker --authorize-only`, which is built-in without an additional component install, that does not work with `rules_docker`. I filed a bug against gcloud to attempt to get them to write the new format config file: https://issuetracker.google.com/issues/71533637

I'd suggest closing this issue.

**Comment by mattmoor** [comment]
Sorry, the body of the issue is incorrect.

We reproduced the issue motivating this yesterday, and it was actually that if you install `gcloud` via `apt-get` then you cannot use `gcloud components install`.  This is exacerbated by the fact that `docker-credential-gcloud` (which is bundled by default, and hopes to replace `docker-credential-gcr`) isn't compatible with these rules.

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
