### ISSUE TITLE
container_push does not easily work with gcloud authorization

### ISSUE THREAD

**Issue by evanj** [bazelbuild/rules_docker#278]
It would be nice if there was a simple way to get `container_push` targets to work with Google Cloud Container registry. Maybe one of:

1. There was documentation showing how to use `container_push` with GCP Container Registry.
2. `container_push` could read the authorization info that `gcloud docker --authorize-only` writes, which I don't think it can.
3. The error message was more friendly when it failed.

I *think* the root cause of my issue is that `container_push` does not support the `~/.dockercfg` file that `gcloud docker--authorize-only` writes. Unfortunately, `docker` does read this file, so manually pushing images using `docker push` works. I think this is the root cause: https://github.com/google/containerregistry/blob/master/client/docker_creds_.py#L226

The error message was very unhelpful: "Unable to access the repository". It seems that the pusher is trying to use the anonymous credentials. Perhaps it should print a warning if it gets an "unauthorized" error, but did not find any credentials?

(This is likely ALSO an issue for `google/containerregistry`; I'll file an issue there once I figure out more specifically exactly what the issue *is*)

**Comment by mattmoor** [comment]
See [here](https://github.com/bazelbuild/rules_docker#authorization) ([but I think gcloud recently broke us](https://github.com/bazelbuild/rules_docker/issues/275)).

We will probably never support `.dockercfg`, it is quite ancient.  If `gcloud docker` is writing it, it probably means you are either using an ancient Docker client, or you haven't used `docker login` to any other registry in some time.  If you only use GCR, it should be safe to delete `.dockercfg`, and it should start writing `~/.docker/config.json`.

The error messaging could be much better, so I'll leave this open for that.

**Comment by dekkagaijin** [comment]
@mattmoor `gcloud docker` writes to `~/.dockercfg` when no config is present, for backwards compatibility. 
Try this:
```
echo "{}" > ~/.docker/config.json
gcloud docker -a
```

**Comment by mattmoor** [comment]
Right, since that's the only thing we can do that all versions kinda-sorta support. :-/

**Comment by mattmoor** [comment]
Hmm, if the rules_docker documentation is actually broken, then so are the [official GCR docs](https://cloud.google.com/container-registry/docs/advanced-authentication#docker_credential_helper), which have the same two lines.

**Comment by evanj** [comment]
@dekkagaijin : Your workaround does the trick! That convinces `gcloud docker --authorize-only` to write `~/.docker/config.json` instead!

Sorry, this appears to be partly a failure on my part to read the directions. I guess I didn't see the "Authorization" section of the documentation, sorry. I saw `gcloud docker --authorize-only`, and it worked to run `docker push gcr.io/...` so I assumed that would be sufficient. `docker-credential-gcr` writes `~/.docker/config.json` by default, so it also works.

Maybe this is a gcloud bug instead: Why are there two different ways to authorize docker? I'll file an issue with them. At least one of them seems like it should be marked deprecated?

Closing this because this is definitely some user error on my part, sorry. Thanks for responding so quickly! (And making useful rules: I'm hoping this will simplify our build/deploy story for Kubernetes)

**Comment by evanj** [comment]
For completeness, I filed https://issuetracker.google.com/issues/71533637

If I'm feeling ambitious I may remove the TODO from containerregistry, and add some debug logging that says something like "cannot load docker credentials falling back to anonymous" which would have tipped me off when I ran the tool directly with extra logging.

**Comment by dekkagaijin** [comment]
> Maybe this is a gcloud bug instead: Why are there two different ways to authorize docker?
 
\>3, actually, and I ask myself that every day
