### ISSUE TITLE
files from the data attribute are missing in the final java_image

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/rules_docker#284]
BUILD
```
java_image(
    name = "service",
    srcs = [ "Service.java" ],
    main_class = "com.example.Server",
    jvm_flags = ["-Djava.util.logging.config.file=/app/logger.properties"],
    data = ["logger.properties"],
    deps = [ ... ]
)
```
``` shell
bazel build -c dbg //src/java:service.tar
docker load -i bazel-bin/src/java/service.tar
docker run -ti --rm --entrypoint=sh bazel/src/java/service
/ # find . -name "logger.properties"
/ # 
```
What are my options here to get the data files into the image? I've also tries to shove them in as a layer  through the layers attr, but that for whatever (undocumented) reason is not supporting a filegroup.

**Comment by mattmoor** [comment]
I believe there should be a `service-layer.tar` output from building that target.  When you `tar tvf` it do you see `logger.properties`?

As a workaround, you can do:
```shell
java_image(
  name = "foo",
  ...
)

container_image(
  name = "bar",
  base = ":foo",
  directory = "/app",
  files = ["logger.properties"]
```

... but if it's not in there it's a bug.

**Comment by ensonic** [comment]
Good point. I was looking at each layer in service.tar. Using the layer is easier and yes it is not there.
```shell
> tar tvf bazel-bin/src/java/service-layer.tar | grep logger
```

**Comment by jonjohnsonjr** [comment]
Possibly just a typo? You have an extra p in "propperties".

**Comment by ensonic** [comment]
> Possibly just a typo? You have an extra p in "propperties".
Then bazel should have error'ed with a file-not-found, right? I'll double check tomporrow, but I probably mistyped it when I made the example.

**Comment by mattmoor** [comment]
I'd give ~80% odds that [this](https://github.com/bazelbuild/rules_docker/blob/master/java/image.bzl#L98-L100) logic isn't consuming all of the attributes it needs to from the Java common provider.

@ittaiz @iirina What are the best docs for the Java common provider (bonus points if you can spot the bug!).  thanks in advance.

**Comment by mattmoor** [comment]
I poked at this a little bit by adding `data = [":foo"],` to `testdata:java_image`, and couldn't find anything that looked right on the java provider.

Looking at `list(f.default_runfiles.files)` I get `foo` (first entry), but also an avalanche of JRE deps:
```shell
DEBUG: /home/mattmoor/.cache/bazel/_bazel_mattmoor/5c340bb9d399314dffbfbc3c347e19fb/external/subpar/debug.bzl:42:5: 
f.default_runfiles.files[list]: [<source file testdata/foo>, <source file external/com_google_guava_guava/jar/guava-18.0.jar>, <generated file testdata/libjava_image_library.jar>, <source file extern
al/local_jdk/bin/ControlPanel>, <source file external/local_jdk/bin/appletviewer>, <source file external/local_jdk/bin/extcheck>, <source file external/local_jdk/bin/idlj>, <source file external/loca
l_jdk/bin/jar>, <source file external/local_jdk/bin/jarsigner>, <source file external/local_jdk/bin/java>, <source file external/local_jdk/bin/java-rmi.cgi>, <source file external/local_jdk/bin/javac
>, <source file external/local_jdk/bin/javadoc>, <source file external/local_jdk/bin/javafxpackager>, <source file external/local_jdk/bin/javah>, <source file external/local_jdk/bin/javap>, <source f
ile external/local_jdk/bin/javapackager>, <source file external/local_jdk/bin/javaws>, <source file external/local_jdk/bin/jcmd>, <source file external/local_jdk/bin/jconsole>, ...
# This goes on for a while :)
```

**Comment by ittaiz** [comment]
Can you use resources?
Data doesn't get packaged in the jar so java provider doesn't know about it

**Comment by ensonic** [comment]
Hmm, according to
https://docs.bazel.build/versions/master/be/java.html#java_binary.resources
those files will be part of the jar. This is about the java logging setup. In the BUILD file I have a
```
jvm_flags = ["-Djava.util.logging.config.file=/path/to/logger.properties
```
I've tried to specify all flags via -D, but could not make this work.

**Comment by ittaiz** [comment]
I see.
Matt,
The answer is that "data" and runfiles in general currently isn't something
JavaInfo supports.
Maybe that's a mistake or maybe there needs to be a sibling JavaBinaryInfo.

**Comment by ensonic** [comment]
Maybe the extra layer is a good pattern since it give more control over where to put the files. When using data, one would probably need to build a path relative to runfiles to reference the file.
So one way to fix it could be to document that:
1.) data is not supported
2.) one can use the layered container_image to add the files.
WDYT?

**Comment by nlopezgi** [comment]
I think this was recently fixed. if its still an issue please reopen.
