### ISSUE TITLE
Need a way to expose a port when running java_image

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/rules_docker#296]
I have a binary which listens to port. When I run its docker image via java_image, the port isn't exposed. How can I expose it?

**Comment by mattmoor** [comment]
I think my bias these days is that all of the `lang_image` rules should simply use [these](https://github.com/bazelbuild/rules_docker/blob/master/java/image.bzl#L329-L331) flags, not just `war_image`.

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
