### ISSUE TITLE
building containers for go is broken

### ISSUE THREAD

**Issue by tkellen** [bazelbuild/rules_docker#305]
Hi,

I'm just getting started with bazel and I'm hitting an issue building a very simple go container.

I have prepared a minimal reproduction here:
https://github.com/tkellen/bazel-test

...I would expect `bazel run container` to work but it does not. Have I missed something obvious?

I'm going to dig in now and see if I can fix the problem myself but I wanted to post this as a sanity check before I go down a rabbit hole I don't need to :)

Thanks in advance if you can help!

**Comment by mattmoor** [comment]
You want `binary = ":helloworld"` not `embed`

**Comment by tkellen** [comment]
Thanks @mattmoor! I tested that (and just pushed a commit updating the test repo) but I am seeing the same behavior.

**Comment by mattmoor** [comment]
Hmm, can you include the output when you run this?

One other thing to try would be to use `pure = "on"` on your `go_binary` target.

**Comment by tkellen** [comment]
Yup!
```
~/sources/go/src/github.com/tkellen/bazel-test master*
❯ bazel run container
INFO: Analysed target //:container (30 packages loaded).
INFO: Found 1 target...
Target //:container up-to-date:
  bazel-bin/container-layer.tar
INFO: Elapsed time: 44.962s, Critical Path: 5.04s
INFO: Build completed successfully, 11 total actions

INFO: Running command line: bazel-bin/container
Loaded image ID: sha256:404677e3f13437d7a3b6cc7a6fdb583ff9b77a5245c2f661aba249f2228776a7
Tagging 404677e3f13437d7a3b6cc7a6fdb583ff9b77a5245c2f661aba249f2228776a7 as bazel:container
standard_init_linux.go:195: exec user process caused "exec format error"
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

...trying the pure setting now.

**Comment by tkellen** [comment]
I think this may be related to #1112 but I'm really not sure.

**Comment by mattmoor** [comment]
Yeah, I think `pure = "on"` is the right workaround for that.  We've been seeing Go starting to link `libstdc++` without pure go enabled, so we need to switch to the `cc` base image for `go`.

**Comment by tkellen** [comment]
Hmmm. No dice. Same output.

**Comment by mattmoor** [comment]
Can you push what you tried?

**Comment by tkellen** [comment]
Done.

**Comment by mattmoor** [comment]
FYI this needs Bazel 0.10 to work, there was a bug in 0.9 :(

**Comment by tkellen** [comment]
Sorry, I should have shared that from the get go (my OS/Bazel version)
```
~/sources/go/src/github.com/tkellen/rules_docker master*
❯ bazel version
Build label: 0.10.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Nov 9 05:23:23 +50056 (1517474669003)
Build timestamp: 1517474669003
Build timestamp as int: 1517474669003

~/sources/go/src/github.com/tkellen/rules_docker master*
❯ uname -a
Darwin Tylers-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by mattmoor** [comment]
Does that flag fix things?

**Comment by tkellen** [comment]
Cross compiling worked. I assumed the build was running in a container with the right architecture. That's obviously wrong. Can I specify that somewhere in my BUILD file so this flag isn't needed?

**Comment by tkellen** [comment]
Apologies, I know we're veering into stackoverflow territory. I'm looking that up for myself now. Thanks for the rapid responses!

**Comment by mattmoor** [comment]
You can put a `.bazelrc` in the root of this repo and it'll get respected.  I believe there may also be a way of specifying this on the `go_binary` rule, but I'm not 100% sure.

**Comment by tkellen** [comment]
Thanks @mattmoor!

**Comment by tkellen** [comment]
Apologies, but, one further question here. Shouldn't go_image automatically build for the correct architecture for the base image being used?

**Comment by tkellen** [comment]
I was able to resolve this by setting `goos = "linux"` on `go_binary`, but that prevents me from building the binary directly on OSX. Would you accept a PR that passes the `goos` value from `go_image` through to `go_binary` ?

**Comment by tkellen** [comment]
For future readers, I was able to resolve this thusly:
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@io_bazel_rules_docker//go:image.bzl", "go_image")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/tkellen/bazel-test",
)

go_binary(
    name = "helloworld",
    pure = "on",
    embed = [":go_default_library"],
)

go_image(
    name = "container",
    pure = "on",
    goos = "linux",
    embed = [":go_default_library"]
)
```

It's a bummer I can't use the `go_binary` directly with some overrides, but this will do for now.

**Comment by mattmoor** [comment]
Sorry, just catching up after some meetings.  Does this work?

```python
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@io_bazel_rules_docker//go:image.bzl", "go_image")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/tkellen/bazel-test",
)

go_binary(
    name = "helloworld",
    pure = "on",
    goos = "linux",
    embed = [":go_default_library"],
)

go_image(
    name = "container",
    binary = ":helloworld",
)
```
