### ISSUE TITLE
container_push failing with exit code 0

### ISSUE THREAD

**Issue by acehko** [bazelbuild/rules_docker#314]
I have a `BUILD.bazel` file like this:
```python
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_bundle")
load("@io_bazel_rules_docker//contrib:push-all.bzl", "docker_push")

docker_bundle(
    name = "all_images",
    images = {
        "eu.gcr.io/my-project/my-image": "//my/image:some_image",
    },
)

docker_push(
    name = "push_all",
    bundle = ":all_images",
)
```

When I run `bazel run //some/path:push_all` I get the following output:
```bash
INFO: Analysed target //some/path:push_all (0 packages loaded).
INFO: Found 1 target...
Target //some/path:push_all up-to-date:
  bazel-bin/some/path/push_all
INFO: Elapsed time: 0.426s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/some/path/push_all
F0208 12:19:52.635199    4906 fast_pusher_.py:156] Error publishing eu.gcr.io/my-project/my-image: Bad status during token exchange: 401
{"errors":[{"code":"DENIED","message":"Unable to access the repository, please check that you have permission to access it."}]}
```
The exit code is `0`.

**Comment by acehko** [comment]
I am using the latest commit:
```python
git_repository(
    name = "io_bazel_rules_docker",
    commit = "898b3b964cebb1b709c8529a3c449bf45700cc33",
    remote = "https://github.com/bazelbuild/rules_docker.git",
)
```

**Comment by mattmoor** [comment]
That's interesting.  Does this happen when you use the single-image form of `docker_push`?

An exit code of zero on an error is certainly a bug.

I'm guessing the reason for the authentication problem is that you haven't [set up](https://github.com/bazelbuild/rules_docker#authentication) the GCR credential helper.


@dekkagaijin @jonjohnsonjr Either of you want to TAL at this?

**Comment by acehko** [comment]
Yes, the behavior is the same with `docker_push`.

Yes, the reason for the error is that it's not set up. I have deleted the `~/.docker/config.json` file to reproduce the issue.

**Comment by mattmoor** [comment]
Ok, thanks for letting us know, that is definitely not WAI.

**Comment by dekkagaijin** [comment]
Looks like we're logging errors, but otherwise exiting normally: https://github.com/google/containerregistry/blob/master/tools/fast_pusher_.py#L156

Should be an easy fix...

**Comment by mattmoor** [comment]
TIL Python's `logging.fatal` isn't fatal.  This is my bad, thanks for the quick fix @dekkagaijin
