### ISSUE TITLE
pushing images fail with: manifest tag did not match URI: None

### ISSUE THREAD

**Issue by mouadino** [bazelbuild/rules_docker#316]
## System information:

bazel: 0.10.0
docker rules: Latest commit (898b3b964cebb1b709c8529a3c449bf45700cc33)

## Issue:

I have the following rules:

```
container_push(
   name = "push_image",
   image = ":image",
   format = "Docker",
   registry = "<private-registry-host-name>",
   repository = "services/hq_api",
   tag = "{MY_SERVICE_REVISION}",
   stamp = True,
   tags = tags,
)

docker_build(
    name = "image",
    base = "//docker:go_production",
    cmd = ["..."],
    data_path = ".",
    env = {
       ....
    },
    files = [
        ...
    ],
    repository = "<private-registry-host-name>",
    stamp = True,
    tags = tags,
)
```

Now when I try to run `bazel run //<path>:push_image`, this later fails with `manifest tag did not match URI: None`.

Trying to use `docker tag ...` and `docker push ...` works fine, any help is appreciated.

**Comment by mattmoor** [comment]
That looks like [this](https://github.com/docker/distribution/blob/master/registry/api/v2/errors.go#L47).

There are only a handful of places that this can happen.  Are you sure `{MY_SERVICE_REVISION}` is defined and resolving properly?  Does it work if you replace a fixed value?

**Comment by mouadino** [comment]
Yes, I played with it a bit, I put a fix tag, I changed the repository to different values, I even set the tag to "image" (name of the rule that generates the image, hence also the name of the tag of the built image) without success.

**Comment by mouadino** [comment]
Seems like the issue above is due to the docker registry, after installing one locally and pushing to it things works, currently I am checking what is exactly wrong.

**Comment by mouadino** [comment]
Confirmed the issue was because we were using an older https://github.com/docker/distribution and after bisecting over the different versions, I can confirm that `container_push` rule only **works with distribution version 2.3.0 and up**.

**Comment by mouadino** [comment]
Not sure whether this is worth documentation change, but will close for now since I know what's the issue is.

**Comment by mattmoor** [comment]
Yes, the rules only support v2.2 (aka "schema 2") pushes (or OCI, which is similar), which it looks like [launched](https://github.com/docker/distribution/releases/tag/v2.3.0) in 2.3.

It might be worth documenting, but v2.2 is old enough that it's pretty ubiquitous now.
