### ISSUE TITLE
Correct way to build image_tar

### ISSUE THREAD

**Issue by codesuki** [bazelbuild/rules_docker#327]
I had to add the below alias to the build file at `cmd/feature/BUILD.bazel`
```
go_image(
    name = "feature_image",
    binary = ":feature",
)

# needed to make bazel build //cmd/feature:... build the docker image which has rule //cmd/feature:feature.tar
# it seems it is not built because nothing depends on it.
alias(
    name = "feature_image_tar",
    actual = ":feature_image.tar",
)
```

Is there a more proper way to build `image_tar`?

**Comment by mattmoor** [comment]
The image is built, but it isn't linked into a `docker save` tarball unless one is explicitly requested because that form isn't needed by most other rules (incl. `container_push` and `k8s_object`)

We've set things up to avoid creating the tarball unless requested because it can be fairly expensive to create if the image is large.

**Comment by codesuki** [comment]
Thanks. That makes sense and is what I thought. Right now I am using bazel to build the tars and concourse to upload them. Are you guys doing everything, including uploading with bazel? 
Anyway, then the alias rule seems to be a good solution for us.

**Comment by mattmoor** [comment]
More or less, yes.

What I've started to bias towards for developing stuff for K8s (using `rules_k8s`) is having:
 * `k8s_object` per component, for fast development via `bazel run :component.replace`
 * `k8s_objects` for logical groupings, and in particular `:everything`

`:everything` is interesting for a few reasons:
1. It makes getting started and cleanup easy (`bazel run :everything.{create,delete}`)
1. It makes creating a release yaml pretty easy: `bazel run :everything > release.yaml`.  Then folks can simple `kubectl create -f release.yaml`.

There's some nuance that comes into play when you start using stamping to juggle different environments, but you can do fairly powerful things with these simple rules.  There a demo [here](https://www.youtube.com/watch?v=RS1aiQqgUTA) from Bazelcon 2017.

LMK if I can help with any of this stuff.

**Comment by codesuki** [comment]
Thanks for the helpful advise! I will have a look at the demo.
Right now we are building our images with bazel and then separately upload them with concourse-docker-resource. This step could be done with bazel now. 
Next we deploy using helm charts, for easier configuration and rollback etc.
This step seems harder to do with bazel. But it would be great if we could build the helm charts itself with bazel. Should be possible. 
I am unsure how well helm would be replaced with `rules_k8s`, but to deploy developer environments, per branch or something, `rules_k8s` seems useful.
The `release.yaml` you are talking about seems similar to a helm release, just without the configurability. (We have value files per environment that get applied together.)
I am not sure if what we are do is very good but we are trying to improve the process every time we find something better. If something seems weird to you, please let me know. :)

**Comment by mattmoor** [comment]
> This step seems harder to do with bazel. But it would be great if we could build the helm charts itself with bazel. Should be possible.

I spent a little while digging into helm in the earlier days of `rules_k8s` prototyping.  The wall I hit is that there isn't really a good way to roundtrip templat-ized helm configs.  They are basically unstructured Go templates until they've been evaluated, at which point they *may* be yaml (or json?).  So Helm templates are fairly hostile to tool writers, unless you want them expanded.

This is one of the sentiments that comes through in Brian Grant's Declarative Application Management document.

I believe Helm should move in the direction of a K8s Custom Resource Definition (or CRD), which is itself valid yaml (Helm's Tiller => a CRD Controller).  This would limit the kinds of things you could do via templating, but enable tooling to operate over and reason about charts pre-instantiation.

FWIW, I believe you could use Helm with `rules_k8s` today if you restrict the templating you allow to well-formed yaml.  e.g. don't predicate large swaths of structure, but restrict to value-substitutions.  I'm happy to try and help, if you wanna be a guinea pig :)

**Comment by mattmoor** [comment]
I just saw this, so it seems Helm may be headed this way :)
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-apps/nHk_Z-zb_fg/RSEBTf5jCwAJ

**Comment by codesuki** [comment]
Thanks for going into details and offering help! I will check out the resources, watching the video now.

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
