### ISSUE TITLE
container_image: expose file_map

### ISSUE THREAD

**Issue by zllak** [bazelbuild/rules_docker#328]
__Proposal__:
- Expose the `file_map` attribute to the `container_image` rule

__Problem__:
I need to put files in the tarball but I need to specify different directories (ie one file in `/dir`, other files in `/dir2`)
Maybe I missed something.
I have seen that you can specify the data directory but I have files that needs to file in different directories.

**Comment by mattmoor** [comment]
Are you simply thinking that we'd expose this like:
```python
container_image(
    name = "foo",
    file_map = {
      '/dir1/bar': ':bar',
      '/dir2/baz': ':baz',
    },
)
```

I could definitely live with that, if we document clearly which attributes it works with and ignores (e.g. `directory`, `data_prefix`).

**Comment by zllak** [comment]
Yes @mattmoor that was the idea.
That way we can easily map different files to different paths.
Awesome !

**Comment by nerd2** [comment]
+1, it is very verbose having to specify a layer for each directory when you have a tree of deps

**Comment by Capstan** [comment]
I ran into this in the monorepo; still seems like a good idea.

**Comment by gravypod** [comment]
I think we should loop in some discussion from the bazel team on this issue. Ideally we could provide some way to do this generically across all of Bazel. Right now I know there is a lot of usage of [Fileset](https://bazel.build/support.html#unstable) which the Bazel team is attempting to deprecate. I need to look into what the best replacement of this would be.
