### ISSUE TITLE
Make container images a dependencies of another rule

### ISSUE THREAD

**Issue by mouadino** [bazelbuild/rules_docker#331]
Hey,

I have create a rule in the following format:

```
my_test_rule = rule(
    _impl,
    executable = True,
    test = True,
    attrs = {
        "srcs": attr.label_list(
            allow_files = True,
            mandatory = True,
        ),
        "deps": attr.label_list(
            allow_files = True,
            providers = [],
        ),
    },
)
```

where I want to have the `image.tar` being build when a given test is run but something like this doesn't seem to do it:

```
my_test_rule(
    name = "test",
    srcs = ["..."],
    deps = ["//services/mine:image.tar"]
)
```

FWIW calling `bazel build //services/mine:image.tar` does create the tar ball.

Anyone know what I am missing?

**Comment by mattmoor** [comment]
@mouadino Take a look in `testdata/BUILD` we do a bunch of this, but it's a `data = [...]` dependency, vs. `deps = [...]`.  I'd guess for `deps = [...]` it depends a lot on how the rule itself decomposes into actions.

**Comment by mouadino** [comment]
Sorry but forgot to update, it worked thanks for the hint by looking at more examples I figured out.
