### ISSUE TITLE
correct way of dealing with cc_image system shared object libraries

### ISSUE THREAD

**Issue by an-kumar** [bazelbuild/rules_docker#338]
My binary depends on some system libraries that don't seem to be in the docker base used by cc_image. in particular, libgfortran.so.3 is missing.

What is the correct way of dealing with system libraries that are shared object files? Compile them from scratch in bazel? Or is there a way of adding to the cc_image docker base with commands to add the necessary libraries (e.g via the deb attributes)?

**Comment by mattmoor** [comment]
The `lang_image` rules take `base = ":..."` kwarg, so you can base it on `ubuntu:latest` or whatever, if you pull it yourself in `WORKSPACE`.

**Comment by an-kumar** [comment]
Great, sounds good — out of curiosity what does the current base image contain? Would it be in some way inadvisable to switch it (I.e it has been chosen carefully and deliberately)?

**Comment by mattmoor** [comment]
They use the `distroless` base images by default (see github.com/googlecloudplatform/distroless), which are super stripped down.  You can try to extend them with libraries you need, but it can be non-trivial.

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.

**Comment by hustclf** [comment]
My go binary also depends on some private shared library, which is stored in `_solib_k8` after `bazel build`.

Is it possible to copy these .so files to image automatically instead of changing base image?
