### ISSUE TITLE
if --name is not provided to pusher, pusher should inspect repositories in tar

### ISSUE THREAD

**Issue by mikedanese** [bazelbuild/rules_docker#34]
opening issue here since issues aren't enabled in https://github.com/google/containerregistry

**Comment by mattmoor** [comment]
This is tricky, since there may be `N` names in the tarball.  Would you expect it to push every name it finds?

**Comment by mikedanese** [comment]
Yes, I would expect it to push all tags present in the repositories blob.

**Comment by mattmoor** [comment]
I opened a bug internally to track this so that it's in the same place as other issues, you should be CC'd.
