### ISSUE TITLE
Removing the subpar dependency

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_docker#352]
hello since I am on red hat 7 the subpar package doesn't work. I am trying to edit my fork of the docker rules to remove this dependency.

How can I implement container pull and push using something output by py_binary?

**Comment by nlopezgi** [comment]
Hi @jeb2239 ,
sorry for the super long delay responding to this issue. Our current plans are to migrate to go-containerregistry (https://github.com/bazelbuild/rules_docker/issues/580) which iiuc should fix your problem. Closing, but please let me know if you want to keep this issue open for any reason.
