### ISSUE TITLE
nodejs_image does not preserve data filepaths

### ISSUE THREAD

**Issue by an-kumar** [bazelbuild/rules_docker#355]
In nodejs_binary, you can pass in data that will be accessible to the binary at runtime. 

When replaced with nodejs_image, these files are not available when executed. If you manually cd into the workspace directory under the runfiles and run the .binary file via sh ../../{binary_file}, it will work as expected.

Does this have to do with the symlinks in app_layer?

**Comment by phedoreanu** [comment]
Yep, getting the same behaviour when replacing a working `nodejs_binary` with `nodejs_image`:
```
“/app/test/docker_image.binary.runfiles/dm/external/nodejs/bin/node: line 3: /private/var/tmp/_bazel_test/c0afc54142141aeaf49127d556990309/external/nodejs/node/bin/node: No such file or directory”
```

Any ideas how to fix it? Or a workaround?

**Comment by nlopezgi** [comment]
It's possible that the workdir is not being set correctly for the nodejs_image rules (or generally for all x_image rules). Please see my comment in https://github.com/bazelbuild/rules_docker/pull/365 on June 18th. It would be great if you could test the fix I suggested in that PR for your failure use case. If it does also work for you, then we can be sure that the workdir fix is right for all x_image rules.

**Comment by ohedin** [comment]
@phedoreanu I have the same issue. nodejs_binary works well but nodejs_image gives me the same error message.

@nlopezgi I have tested the 3 last commits of #365 -> this problem is not resolved

**Comment by nlopezgi** [comment]
@ohedin #365 does not currently resolve the problem, I suggested in #365 a possible solution (fixing the workdir). It would be great if you (or anyone else in these threads) could try that solution I suggest (though I understand it takes a bit of effort to set up). Once I have some confirmation from one of these issues that changing the workdir fixes the problems we can work on a fix.

**Comment by Globegitter** [comment]
@ohedin Can you try and see if #452 fixes your issue?
