### ISSUE TITLE
Installing 32 bit compatability libraries in a container fails

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/rules_docker#357]
I'm trying to build a 64 bit container with 32 bit compatibility libraries.  These are, for example, lib32gcc1.  I'm doing this by adding them to the debs option of container_image.

The post install script of the package runs ldconfig to update /etc/ld.so.cache.  This adds /usr/lib32/ to the search path.

rules_docker doesn't run the post install scripts because they could be non-reproducible.  This prevents 32 bit binaries from running in the container without hand modifications.  I'm not seeing any other ways to do this.  How can I regenerate /etc/ld.so.cache?

**Comment by nlopezgi** [comment]
Hi @AustinSchuh ,
sorry for the super long delay responding to this issue, you can try using download_pkgs and install_pkgs rules (https://github.com/GoogleContainerTools/base-images-docker/tree/master/package_managers) which will run the post install scripts. but note package installation is indeed non deterministic, and there is no generalizable approach to avoid this issue - we have some hacks around this for specific packages in our rules in bazel-toolchains repo that rely on download_pkgs and install_pkgs (https://github.com/bazelbuild/bazel-toolchains/blob/master/rules/container/docker_toolchains.bzl#L326). Closing as there is no real fix on this repo that can be done to get debs to be installed properly. Please let me know if you want me to reopen for any reason.
