### ISSUE TITLE
PY3 Image build failed.

### ISSUE THREAD

**Issue by gravitywp** [bazelbuild/rules_docker#360]
![image](https://user-images.githubusercontent.com/8477504/37822784-72546ae4-2ec2-11e8-976c-1d9480ac1330.png)

My Build File:
![image](https://user-images.githubusercontent.com/8477504/37822816-90ff2da8-2ec2-11e8-9e3c-1ce04bebd721.png)

**Comment by mattmoor** [comment]
What does your `WORKSPACE` look like?

**Comment by mattmoor** [comment]
In particular, do you have something like [this](https://github.com/bazelbuild/rules_docker/blob/master/WORKSPACE#L53-L58)?

**Comment by gravitywp** [comment]
Yes, I have already included those codes in WORKSPACE.
![image](https://user-images.githubusercontent.com/8477504/37885833-fe4df24e-30e9-11e8-8b19-c20e2a313d48.png)

**Comment by nlopezgi** [comment]
Hi @gravitywp ,
is this still an issue? Let me know if so (ideally with an update on state of issue) to reopen.
