### ISSUE TITLE
install uwsgi and start service in py_image

### ISSUE THREAD

**Issue by jschenxiaoyu** [bazelbuild/rules_docker#366]
I have a problem when using `uwsgi` in my python project.

When using `py_image` I cannot install `uwsgi` by running `pip install uwsgi` and then start the server via `uwsgi xxx` command.

So how can I start `uwsgi` service using `rules_docker`?

**Comment by nlopezgi** [comment]
This use case (installing a pip package and then starting server with a command installed by the package) should be supported in the general case. I wonder if all the dependencies required for uwsgi are indeed present in the py_image or not. How is this failing for you? Is it failing when trying to install the package or when starting the server with the command?

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
