### ISSUE TITLE
Consider adding a file map in addition to current files list

### ISSUE THREAD

**Issue by calder** [bazelbuild/rules_docker#368]
AFAICT, creating directory structure within a container currently requires tedious composition of `pkg_tar` targets. If there's a better way, please enlighten me! :-)

If not, something like this would be useful:

```python
container_image(
    file_map = {
        "/usr/bin/foo": "//some/package:foo.par",
        "/usr/local/bin/bar": "//another/package:bar.stripped",
    }
    ...
)
```

**Comment by nlopezgi** [comment]
using pkg_tar is the supported way to achive the behavior you need (as you point out). What exactly about doing this with pkg_tar do you find tedious (maybe its relevant feedback for the pkg_tar owners to improve their rules)?
