### ISSUE TITLE
Creating empty, mode 0777 /tmp directory

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_docker#37]
Looking in the docs it appears that it would be possible to make a file in a directory called "/tmp" but I can't figure out how to make a /tmp dir with mode 0777. Is that possible?

**Comment by mattmoor** [comment]
@damienmg knows the most about file attributes.

**Comment by damienmg** [comment]
Unfortunately we have a way to set the attribute for file but not for directory. I think directory get automatically created in 0777 | mode where mode is the mode of the file we actually add.

**Comment by achew22** [comment]
How do applications that expect the availability of a /tmp directory make this work on your setups? Is there a way to make docker mount a new tmpfs on /tmp or something like that?

**Comment by f0** [comment]
https://github.com/GoogleCloudPlatform/distroless/issues/75

any news here?

**Comment by mattmoor** [comment]
@damienmg If I add `mode="777"` to our `with_tmp` layer [here](https://github.com/GoogleCloudPlatform/distroless/blob/master/base/BUILD#L22) it still doesn't enable write on the directories:
```shell
$ tar tvf bazel-bin/base/with_tmp-layer.tar 
drwxr-xr-x 0/0               0 1970-01-01 00:00 ./
drwxr-xr-x 0/0               0 1970-01-01 00:00 ./tmp/
-rwxrwxrwx 0/0               0 1970-01-01 00:00 ./tmp/empty
```

**Comment by f0** [comment]
@mattmoor  if i understand the code correctly , setting the mode  (or creation ) of a directory is not implemented atm.
(thats why the empty file is needed)

**Comment by mattmoor** [comment]
Indeed, which is why I assigned this to @damienmg who owns `pkg_tar` :)

**Comment by muhammadharis** [comment]
Any update on this?

**Comment by nlopezgi** [comment]
None, I don't think this issue should be in this repo, or maybe I'm misunderstanding the problem, but this seems like something that should be solved in  pkg_tar rule?

**Comment by muhammadharis** [comment]
It would be great if there could be a feature such that if we specified
```
container_layer(
    name = "tmp",
    directory = "/tmp",
    mode = "0777"
)

```
it creates a /tmp directory on the image with the correct permissions.

**Comment by nlopezgi** [comment]
Thanks @muhammadharis ,
we would welcome contributions to implement your feature, we have no plans on working on this atm.

**Comment by muhammadharis** [comment]
@nlopezgi thank you for your reply. After looking through source code, it seems the feature is already implemented by specifying `empty_dirs = ["/tmp"]`, just hasn't been documented.
