### ISSUE TITLE
How to make image that includes python artifacts depended on grpcio on macOS

### ISSUE THREAD

**Issue by ynqa** [bazelbuild/rules_docker#370]
I built docker image that includes python artifacts depended on grpcio (probably, the case that uses cython libraries runs into this issue) on macOS.
But it is difficult to build simply by `py_image`, because making container image after `py_binrary` that resolves the dependencies and optimizes cython building for macOS. So the library don’t work well for importing in other distributions.

Therefore I just prepared Dockerfile for base image (btw, why could it get base image by `container_pull` from remote repos only?). But I don’t think the best way. The codes are here: https://github.com/ynqa/bazel_docker_py_grpcio

Do you know better any solutions?

**Comment by nlopezgi** [comment]
I dont quite understand the issue you are running into, could you clarify if the answer I left in #372 also covers your first question. 
wrt your second question (why container_pull has to be in WORKSPACE) its because rules that do non-hermetic operation (like pulling a container from some repo) should only be implemented as workspace repository rules (i.e., its Bazel best practice as doing it otherwise might break incremental / correct builds).

**Comment by ynqa** [comment]
> you could try to run your build from inside a docker container
The main problem is resolved by your answer in #372.

**Comment by ynqa** [comment]
@nlopezgi As second question, your answer means that injecting other source (such as Dockerfile on local) for bazel building goes against the non-hermetic operations, don't you?
But I think that it's useful to enable to do that operations.

**Comment by nlopezgi** [comment]
Yes, typically using Dockerfiles as part of the build process inherently goes against hermetic principles of Bazel. How would you envision enabling this in rules_docker, and what is it exactly that you want to do with the Dockerfile? We can help you find alternatives to what you are trying to do in the Dockerfile. If its something that cannot be done w/o a Dockerfile, we will want to know to think of ways to overcome current limitations in the future.

**Comment by ynqa** [comment]
Of course, it can do anything without Dockerfile. But, it's helpful if no base images which you want or if you want to use customized images on the remote repo.

**Comment by ynqa** [comment]
@nlopezgi Of course, it can do anything without Dockerfile. But, it's helpful if no base images which you want or if you want to use customized images on the remote repo.
