### ISSUE TITLE
feature request: `$(location)` substitution for container_image symlinks

### ISSUE THREAD

**Issue by kevingessner** [bazelbuild/rules_docker#375]
Given an image target such as:

```
container_image(
 name = "foo",
 directory = "/app",
 files = ["app.bin"],
 symlinks = {"/usr/bin/app": "$(location app.bin)"},
)
```

As of 4d8ec6570a5313fb0128e2354f2bc4323685282a, the symlink in the image at `/usr/bin/app` will be broken as it will point to literally the invalid path `$(location app.baz)`.  It would be awesome if that macro was correctly resolved at build time to `/app/app.bin` (e.g. the `directory` + the file's name).

**Comment by nlopezgi** [comment]
Is there any interest in pursuing this feature? If so let me know to reopen.

**Comment by skyl** [comment]
I like this idea. I tried to use it but found this issue. I have a workaround though too, I think.
