### ISSUE TITLE
http in addition to https

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_docker#376]
These rules don't support http for communicating with a docker registry only https. This makes using it behind a fire wall very difficult because there is the expectation that requesting via http is safe and docker registry are therefore run over http. Also since I don't manage where the company uses http over https this makes using these rules to pull from an internal docker registry impossible.

```
[Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by jonjohnsonjr** [comment]
The library that `rules_docker` uses for communicating with registries just stupidly tries to guess which domains should use http [here](https://github.com/google/containerregistry/blob/657fcea7f1206de849058517bd0a0b5bdc92d325/client/v2_2/docker_http_.py#L415).

See #220 - I think we do need some escape hatch here, like docker's [`"insecure-registries"`](https://docs.docker.com/registry/insecure/) flag.

**Comment by jeb2239** [comment]
So these rules download the puller.par and pusher.par from Google storage while also downloading the version provided their git hub repo. This makes integrating these rules very difficult. Because we need changes in two places.

**Comment by jeb2239** [comment]
Is there a reason why this behavior can't be supported?

**Comment by jonjohnsonjr** [comment]
Nope! I'd be happy to implement a fix for this upstream if you have a reasonable proposal.

**Comment by jeb2239** [comment]
So it seems like this code uses two versions of subpar a precompiled one which is downloaded as a zip file and one which is downloaded from github. Is there a reason why you can't just use the github version of subpar?

**Comment by jeb2239** [comment]
https://github.com/bazelbuild/rules_docker/blob/4d8ec6570a5313fb0128e2354f2bc4323685282a/container/container.bzl#L37

**Comment by nlopezgi** [comment]
sorry for the super late response. The reason this needs to be pulled twice is because the bazel mechanism to resolve deps for starlark rules (e.g. container_push) and workspace repo rules (e.g. container_pull) are separate and work in different ways. In particular dependency management for workspace repo rules is a hack, no matter what you do. Apologies for the problems. 
That said, is this still an issue? please reopen if so.

**Comment by asford** [comment]
rule_docker has been updated to use go-containerregistry, which has different (but still hardcoded) behavior when inferring http vrs https targets for registries:

https://github.com/google/go-containerregistry/blob/d187a716b559771a3768caa9c4dba796cb4650b3/pkg/name/registry.go#L74-L95

This will still cause issues where `localhost:5000` registries must use HTTP, and non-local must use HTTPS.
