### ISSUE TITLE
How to pass docker run flags using container image

### ISSUE THREAD

**Issue by srellik** [bazelbuild/rules_docker#377]
I want to start the container

`docker run -p 80:3000 <IMAGE>`

**Comment by erain** [comment]
I don't think we have a rules for `docker run`, and the rules in this repo are mainly for producing / fetching docker images (without docker daemon).

**Comment by mattmoor** [comment]
We don't support `RUN` as in Dockerfile. :)

If you `bazel run :foo` it will load the `container_image` into the Docker daemon, and then you can `docker run` it.  You can make it load and run things with `legacy_run_behavior = False` (the default for `lang_image`).
