### ISSUE TITLE
data for a go_image doesn't get into the image

### ISSUE THREAD

**Issue by raliste** [bazelbuild/rules_docker#378]
For instance

```
go_image(
    name = "gru_docker",
    srcs = [
        "main.go",
    ],
    goarch = "amd64",
    goos = "linux",
    pure = "on",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_golang_glog//:go_default_library",
        "//gru:gru",
    ],
    data = [
        "//static:static"
    ]
)
```

The same but using the `go_binary` rules does get `static` into the runfiles, but changing to `go_image` doesn't get them into the runfiles.

**Comment by PranavSathy** [comment]
Has anyone found a workaround for this, I will be relying on this functionality to successfully deploy my application.

**Comment by raliste** [comment]
@PranavSathy it turns out data does get into the image, under a `.runfiles` directory.  See the data attribute at https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go_binary. The prefix should match your binary's name, for instance:

```
go_image(
  name = "foo"
  ...
)
```

runfiles should be `foo.runfiles`. It's also helpful to use filepath.Join and getting your binary's base path:

```
base, err := filepath.Abs(filepath.Dir(os.Args[0]))
if err != nil {
	return nil, err
}

filepath.Join(base, runfiles, pathToYourArtifact)
```

**Comment by PranavSathy** [comment]
@raliste Thanks! I actually managed to come to this conclusion just before as well; but this is surely helpful for anyone in the future.

Just FYI; you can also utilize `binary` in your `go_image` rule and then the runfiles path will be prefixed according to your `go_binary` rule rather than your `go_image`, so that running locally vs. running in Docker will be identical and require 0 code change.

**Comment by nlopezgi** [comment]
It's possible that the workdir is not being set correctly for the go_image rules (or generally for all x_image rules). Please see my comment in #365 on June 18th (also see https://github.com/bazelbuild/rules_docker/issues/355). It would be great if you could test the fix I suggested in that PR for your failure use case. If it does also work for you, then we can be sure that the workdir fix is right for all x_image rules.
--
