### ISSUE TITLE
How to reset to the default `null` entrypoint?

### ISSUE THREAD

**Issue by kevingessner** [bazelbuild/rules_docker#379]
When building a `container_image` on top of a base that already defines an entrypoint, how can I reset the new image to have docker's default `null` (i.e. empty) entrypoint?  I tried setting `entrypoint = []` and `entrypoint = None`, which both result in the base's entrypoint being preserved.  Is there a value that will reset to the default, or one that behaves like it?

**Comment by mattmoor** [comment]
Does `entrypoint = None` work?

**Comment by kevingessner** [comment]
No, it doesn't: that seems to be equivalent to not adding the `entrypoint` attribute at all, which inherits the entrypoint from base.

I'm looking to do what would be `ENTRYPOINT []` in a Dockerfile (per https://stackoverflow.com/questions/40122152/how-to-remove-entrypoint-from-parent-image-on-dockerfile).  I believe that `None`, `[]`, etc don't work in `container_image` because they are all falsy in Python and so end up being ignored as "unset" but the image builder; they aren't special-cased like that value is in a Dockerfile.

**Comment by mattmoor** [comment]
> that seems to be equivalent to not adding the entrypoint attribute at all

@kevingessner good point. :)

I think the appropriate fix here would be to make `entrypoint = []` do what you want (despite its "falsy" nature) by explicitly checking for `None`.

WDYT?

**Comment by kevingessner** [comment]
That sounds right to me.

**Comment by siddharthab** [comment]
Can we also do this for `cmd` please?

Most base images have `cmd` defined and the `app_layer` rule sets the `entrypoint`. Docker behavior is to unset the `cmd` of any parent image if `entrypoint` is (re)defined ([source](https://github.com/moby/moby/issues/19611)). But this does not happen in `container_image`, and we end up with unwanted arguments to the entrypoint command when running the image.

At least being able to manually reset `cmd` would be sweet.

**Comment by xingao267** [comment]
Created https://github.com/bazelbuild/rules_docker/pull/471 to set cmd or entrypoint to null if the value is None, [] or ""

**Comment by xingao267** [comment]
https://github.com/bazelbuild/rules_docker/pull/471 is merged. Now setting entrypoint or cmd in container_image to one of {None, [] or ""} will make entrypoint or cmd "null" in the final image config. I'm closing this issue. But feel free to reopen this if you encounter any issue.
