### ISSUE TITLE
Alpine: Can't RUN `apk add ca-certificates`

### ISSUE THREAD

**Issue by apelisse** [bazelbuild/rules_docker#38]
I'm trying to convert my `Dockerfile` to bazel. Here is the `Dockerfile`:
```
FROM alpine:3.5
RUN apk add --no-cache ca-certificates && update-ca-certificates
COPY my-binary /
ENTRYPOINT ["/my-binary"]
```

`my-binary` connects to some **HTTPS** websites.

Right now I have:
```
# in WORKSPACE
docker_pull(
   name = "alpine",
   registry = "index.docker.io",
   repository = "library/alpine",
   tag = "3.5",
)

# in BUILD
docker_build(
    name = "my-binary-docker",
    base = "@alpine//image:image.tar",
    files = [":my-binary"],
)
```

I'm not sure how to replace the `RUN` part of the file.

**Comment by mattmoor** [comment]
`RUN` requires Docker, and for a wide variety of reasons `docker_build` doesn't support it.

However, if you are putting a mostly-static binary into a container, consider replacing Alpine with a [distroless](github.com/googlecloudplatform/distroless) image.  Our base should have ca-certs.

@dlorenc FYI

**Comment by yutongz** [comment]
Distroless works great!

**Comment by SleepyBrett** [comment]
What if I want to add my own, internal, trust root to a distroless container.
