### ISSUE TITLE
Reliance on Published google/containerregistry artifacts

### ISSUE THREAD

**Issue by promiseofcake** [bazelbuild/rules_docker#384]
Why do we rely on published artifacts from [google/containerregistry](https://github.com/google/containerregistry) as opposed to their public Bazel targets? 

https://github.com/bazelbuild/rules_docker/blob/4d8ec6570a5313fb0128e2354f2bc4323685282a/container/push.bzl#L108-L113
vs
https://github.com/bazelbuild/rules_docker/blob/4d8ec6570a5313fb0128e2354f2bc4323685282a/container/pull.bzl#L88-L92

Since we require the repository to be available to access `@containerregistry//:containerregistry`, we already have all of the deps we'd need in order to build them.

https://github.com/bazelbuild/rules_docker/blob/553d5506bb7325185950f91533b967da8f5bc536/container/BUILD#L45-L54

I had trouble making that change so I am wondering if there is some external context I am missing.

Here is am attempted change and the corresponding error:

```python
container_pull = repository_rule(
    attrs = {
        "registry": attr.string(mandatory = True),
        "repository": attr.string(mandatory = True),
        "digest": attr.string(),
        "tag": attr.string(default = "latest"),
        "_puller": attr.label(
            executable = True,
            default = Label("@containerregistry//:puller"),
            cfg = "host",
            allow_files = True,
        ),
    },
    implementation = _impl,
)
```

```bash
DEBUG: /Users/lucas/Workspace/repos/rules_docker/cc/image.bzl:71:5: cc_image does not benefit from layers=[], got: [":cc_image_library"]
ERROR: /Users/lucas/Workspace/repos/rules_docker/testdata/BUILD:151:1: no such package '@pause_tar//image': Traceback (most recent call last):
	File "/Users/lucas/Workspace/repos/rules_docker/container/load.bzl", line 43
		repository_ctx.execute([_python(repository_ctx), reposi...)])
	File "/Users/lucas/Workspace/repos/rules_docker/container/load.bzl", line 45, in repository_ctx.execute
		repository_ctx.path(repository_ctx.attr._importer)
Not a regular file: /private/var/tmp/_bazel_lucas/da98986e638dd5ad0d4d5776e97dea2d/external/containerregistry/importer and referenced by '//testdata:docker_tarball_base'
ERROR: Analysis of target '//testdata:docker_tarball_base' failed; build aborted: no such package '@pause_tar//image': Traceback (most recent call last):
	File "/Users/lucas/Workspace/repos/rules_docker/container/load.bzl", line 43
		repository_ctx.execute([_python(repository_ctx), reposi...)])
	File "/Users/lucas/Workspace/repos/rules_docker/container/load.bzl", line 45, in repository_ctx.execute
		repository_ctx.path(repository_ctx.attr._importer)
Not a regular file: /private/var/tmp/_bazel_lucas/da98986e638dd5ad0d4d5776e97dea2d/external/containerregistry/importer
```

**Comment by jonjohnsonjr** [comment]
IIRC this is related to transitive workspace dependencies.

Some breadcrumbs:
https://github.com/bazelbuild/rules_docker/pull/171#commitcomment-26435390
https://github.com/bazelbuild/rules_python/issues/35

**Comment by promiseofcake** [comment]
@jonjohnsonjr, thanks for the reply. In this case we are manually including all of the transitive dependencies of google/containerregistry, as pointed out in that comment, and I can build public targets from that repo and execute them in the `bazelbuild/rules_docker` workspace without issue: 

```
$ bazel run @containerregistry//:puller -- --directory . --name index.docker.io/library/openjdk:8
INFO: Analysed target @containerregistry//:puller (0 packages loaded).
INFO: Found 1 target...
Target @containerregistry//:puller up-to-date:
  bazel-bin/external/containerregistry/puller
INFO: Elapsed time: 0.161s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/external/containerregistry/puller --directory . --name index.docker.io/library/openjdk:8
[...pulling...]
```

So is there something specific to the runtime for that `py_binary` target that isn't working whereas they do work for the other targets (importer, pusher, etc..)?

**Comment by mattmoor** [comment]
@promiseofcake tl;dr This is a limitation of `WORKSPACE` in Bazel.

`WORKSPACE` cannot depend on `py_binary` tool dependencies, only executable files.  So we rely on `.par` files we publish for the tools that must execute during `WORKSPACE` (e.g. for `container_pull` and `container_load` IIRC).  For tools that only execute in the `BUILD` phase, we simply rely on their `py_binary` target.
