### ISSUE TITLE
Expose layer_providers as an argument to image implementation

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/rules_docker#385]
It will be really nice if the layers override in the implementation for image took `LayerInfo` provider objects instead of targets. That way, we can dynamically construct a variable number of `LayerInfo` providers in Skylark based on providers in the deps. Right now, we are restricted to the information available in BUILD files to determine the number of layers.

https://github.com/bazelbuild/rules_docker/blob/452878d665648ada0aaf816931611fdd9c683a97/container/image.bzl#L217

**Comment by nlopezgi** [comment]
Hi @siddharthab 
sorry for the extra long response time. I think it should be feasible to use providers instead of the targets. I'd be happy to review any PRs you want to send for this.
