### ISSUE TITLE
How to create war image with unpacked classes and resources

### ISSUE THREAD

**Issue by auke-** [bazelbuild/rules_docker#387]
I'm trying to create a Docker image for our Java web applications with Bazel and i'm aiming for more or less identical images from our current Maven build. The basics are simple using the war_image rule, but i'm struggling to get the classes which are compiled from the war_image rule in /WEB-INF/classes instead of in a jar file (named libwar_image.library.jar) in /WEB-INF/lib.

For example with the following rule:
```python
load("@io_bazel_rules_docker//java:image.bzl", "war_image")

war_image(
    name = "war_image",
    srcs = ["Servlet.java"],
    deps = [
        "@javax_servlet_api//jar:jar",
    ],
    layers = [
        ":java_image_library",
    ],
)
```
I want the following result:
```
/WEB-INF/classes/Servlet.java
/WEB-INF/lib/java_image_library.jar
```

Furthermore I want to add static files (such as configuration files) to the WEB-INF directory, while keeping their original directory structure (e.g. /WEB-INF/conf/app/my-config.xml).

I would imagine that this could be implemented in a Skylark rule, but I can use some help with that. Can someone point me in the right direction?

**Comment by nlopezgi** [comment]
I dont think the use case you need is trivially supported with war_image (or via extending it / using it in another skylark rule). To see if I understand correctly, the war_image rule is currently producing an image that has some files in a jar file in /WEB-INF/lib, but you want this files to not be in a jar file, but instead to be expanded under some other location? If that is correct, then you could try to declare the files that you need in the image simply in a files attribute or create a tar with the structure that you need (using https://docs.bazel.build/versions/master/be/pkg.html) and use the tars attribute. Let me know if that is not the case so I can understand better and try to help you figure out a path forward.

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
