### ISSUE TITLE
TLSV1_ALERT_PROTOCOL_VERSION

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_docker#395]
We are running the [helm chart for docker_registry](https://github.com/kubernetes/charts/tree/master/stable/docker-registry) with SSL configured, and I'm able to push and pull from it using the docker command line, but I receive this error when trying to use container_pull via Bazel:

```
 Pull command failed: F0427 22:33:32.078401   81016 __main__.py:107] Error pulling and saving image registry3.office.yext.com/yext/play:1: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)
```

Looking online, it seems that this might rely on some particular version of SSL support installed for Python. Is that correct? Do you have any particular advice for getting this to work?

Thank you!
Rob

**Comment by robfig** [comment]
My laptop's system python is linked to (OpenSSL 1.0.2o  27 Mar 2018) running El Capitan and reports the above error. My workstation, with python linked to (LibreSSL 2.2.7) running High Sierra executes the pull successfully. 

Investigating how to fix my laptop without upgrading..

**Comment by robfig** [comment]
Sorry, my previous comment was incorrect. I updated it just now.

**Comment by nlopezgi** [comment]
Can you try setting the value of the env variable "BAZEL_PYTHON" and see if that works (https://github.com/bazelbuild/rules_docker/blob/master/container/pull.bzl)?

**Comment by robfig** [comment]
This ended up being due to the list of ciphers supported by the docker registry only including elliptic curve ciphers. Adding older ciphers to that list made it work as expected.
