### ISSUE TITLE
Overriding Default Image Name

### ISSUE THREAD

**Issue by bzimmerman** [bazelbuild/rules_docker#408]
[Varying image names](https://github.com/bazelbuild/rules_docker#varying-image-names) explains how to override the default image tag, but there doesn't appear to be a way to override the default image name that Bazel generates. Names for tagged and pushed images for deeply nested targets can wind up being very long.

**Comment by erain** [comment]
Why this is the case for pushing? 

So you have a container image:

```
container_image(
   name = "foo", 
  ...
)
```

And you can always push this image with container_push rule by referencing the container image target directly:

```
container_push(
   name = "push_foo",
   image = ":foo",
   format = "Docker",
   registry = "gcr.io",
   repository = "my-project/my-image",
   tag = "dev",
)
```

**Comment by bzimmerman** [comment]
Ah, @erain, you're right. `container_push` results in exactly the name one would expect. `container_image` can still be long for a deeply nested BUILD file.
