### ISSUE TITLE
container_layer(): any way to strip prefixes of tars?

### ISSUE THREAD

**Issue by EdSchouten** [bazelbuild/rules_docker#422]
I'm using Bazel to create a container image of MediaWiki with a couple of extensions included. My goal was to add something like this to `WORKSPACE`:

```python
http_file(
    name = "mediawiki_extensions_auth_remoteuser",
    sha256 = "ce90204bf99361e16cd0721d32b2fe9341db8534417f3f988758a2499b78a471",
    url = "https://github.com/wikimedia/mediawiki-extensions-Auth_remoteuser/archive/REL1_30.tar.gz",
)

http_file(
    ...
```

And then add this to `BUILD`:

```python
container_layer(
    name = "mediawiki_extensions_auth_remoteuser",
    directory = "/var/www/html/extensions/Auth_remoteuser",
    tars = ["@mediawiki_extensions_auth_remoteuser//:file"],
)

container_layer(
    ...
)

container_image(
    name = "mediawiki_container",
    base = "@mediawiki_base//image",
    layers = [
        ":mediawiki_extensions_auth_remoteuser",
        ":mediawiki_extensions_...",
    ],
)
```

As in, take the base image and place some extra directories under `/var/www/html/extensions`, containing the contents of some tarballs.

Now the issue is that those tarballs contain directory prefixes like `mediawiki-extensions-Auth_remoteuser-REL1_30`, whereas MediaWiki expects that this thing is called `Auth_remoteuser`. Initially I tried to solve that by extracting them under their original names and adding `symlinks = {...}`. Even though the symlinks that are created are valid, MediaWiki doesn't want to follow them; likely due to web server security policies. My second idea was to use `container_layer()`'s `data_path` to strip off the prefix. Unfortunately, this only seems to apply to `files`; not `tars`.

Eventually I 'solved' this by adding the following to my `WORKSPACE` instead:

```python
new_http_archive(
    name = "mediawiki_extensions_auth_remoteuser",
    build_file_content = """
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "file",
    srcs = glob(["mediawiki-extensions-Auth_remoteuser-REL1_30/**"]),
    strip_prefix = "mediawiki-extensions-Auth_remoteuser-REL1_30",
    visibility = ["//visibility:public"],
)
""",
    sha256 = "ce90204bf99361e16cd0721d32b2fe9341db8534417f3f988758a2499b78a471",
    url = "https://github.com/wikimedia/mediawiki-extensions-Auth_remoteuser/archive/REL1_30.tar.gz",
)
```

As in, instead of using `http_file()`, I'm using `new_http_archive()` and `pkg_tar()` to create a secondary tarball that has the prefix removed.

My question is, should we consider adding something that makes this a bit less painful to deal with? Maybe let `container_layer()`'s `data_path` also apply to tarballs?

**Comment by nlopezgi** [comment]
I think the solution you came up with in the end is the correct one. I wonder how we could create better documentation (i.e., is it something that should be documented in this repo, or is this something that belongs in the pkg_tar documentation) about how to handle this type of use case, as it is quite common, and it sounds like you had a bit of a hard time getting to the right solution. Any advice (or if you want to contribute some docs) is welcome!
