### ISSUE TITLE
Unauthorized when pulling distroless from gcr.io

### ISSUE THREAD

**Issue by jmendiara** [bazelbuild/rules_docker#424]
At f8208d54bb68b495c23ba8b3a544ba19001b7bab (now master) 
i got a `401` error pullig from gcr.io for a distroless image when pushing an image via `container_push`

```
ERROR: BUILD:66:1: no such package '@java_image_base//image': Pull command failed: 
F0607 18:41:44.582945   94424 __main__.py:125] Error pulling and saving image 
gcr.io/distroless/java@sha256:bd4cbe432f91f69a673bad2bc7b000bb1bf29b86442677b0726d4ef694c8754e:
Bad status during token exchange: 401
{"errors":[{"code":"UNAUTHORIZED","message":"Not Authorized."}]}
```

The `BUILD` is 
```
scala_image(
  name = "image",
  main_class = "play.core.server.ProdServerStart",
  deps = [
    ":lib",
  ],
)

container_push(
  name = "publish",
  format = "Docker",
  image = ":image",
  registry = "whatever",
  repository = "whatever",
  tag = "{BUILD_USER}",

  # Trigger stamping.
  stamp = True,
)
```

Any hints?

**Comment by jonjohnsonjr** [comment]
It's a typo. `grc.io` != `gcr.io`

**Comment by jmendiara** [comment]
Yeah,  I made a fat-fingers transcription error, but the error was copy pasted correctly 😄 
Edited the PR description

**Comment by jonjohnsonjr** [comment]
That is indeed very strange, since those images are public. Is it possible that you have bad (expired?) credentials in `~/.docker/config.json`? It might help to see the content of that file (with any sensitive credentials redacted).

**Comment by jmendiara** [comment]
Yeah, the image is here, native `docker pull` pulls it

The  `~/.docker/config.json` was correct and did not have any reference to `gcr.io`, but after deleting it and  login again via `az acr login` (Azure Container Registry Helper) and `bazel clean --expunge` I dont get the error ` ¯\_(ツ)_/¯ `

Thanks @jonjohnsonjr for pointing me out!
