### ISSUE TITLE
Update to containerregistry v0.0.27

### ISSUE THREAD

**Issue by jmendiara** [bazelbuild/rules_docker#425]
https://github.com/google/containerregistry/releases/tag/v0.0.27 was released some months ago and solves pushing images to Azure Container Registry errors like this one I'm having

```
F0608 00:18:08.044440   99064 fast_pusher_.py:162] Error publishing any.azurecr.io/foo/bar:0.0.0
Malformed JSON response: {"access_token":"eyJhbGciOiJSUzI1NiI...KgQ5mmXsZIy31R0cPJ7_Y5g"}
```

I read somewhere that is easier to make this silly changes internal->external, but let me know if you want a PR for this

Related https://github.com/bazelbuild/rules_k8s/issues/128
Related https://github.com/google/containerregistry/pull/77

**Comment by jonjohnsonjr** [comment]
I think `bazelbuild/rules_docker` will happily accept PRs -- it's just `google/containerregistry` that is hard to do external -> internal contributions.

@erain correct me if I'm wrong!
