### ISSUE TITLE
Working directory is different between py_binary and py_image

### ISSUE THREAD

**Issue by marczych** [bazelbuild/rules_docker#451]
I have a `py_binary` with some `data` files that are referenced with a relative path in code e.g. `//example:binary` references `example/binary/foo`.

I was surprised to find out that a comparable `py_image` failed to find the file. It turned out that `example/binary/foo` was indeed in the image (at `/app/example/binary.runfiles/example/binary/foo`) but the working directory was `/app` when doing `bazel run //example:binary_image`.

Shouldn't something set the working directory to `/app/example/binary.runfiles` before handing control over to the real binary?

**Comment by nlopezgi** [comment]
Hi, yes I think you are correct and the runfiles directory is not being set properly (this is likely happening not only for py_image, but also for all lang _images). There have been a couple of other issues (https://github.com/bazelbuild/rules_docker/issues/355) and notably https://github.com/bazelbuild/rules_docker/pull/365. I think all issues could be resolved with setting the runfiles directory properly in image.bzl. It would be awesome if you could test the fix I suggest in my comment on https://github.com/bazelbuild/rules_docker/pull/365 on June 18, to see if that fixes your issue and send a PR with the fix.

**Comment by marczych** [comment]
Thank you for the response!

I'm seeing the code using `workdir` but I can't quite make out your proposal to fix it. I'm willing to test it out a patch if you have one!

**Comment by nlopezgi** [comment]
please try out now that fix is merged and let me know if this is still problematic.

**Comment by marczych** [comment]
Works like a charm! Thank you!
