### ISSUE TITLE
container_test isn't compatible with rules_go 0.13.0

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_docker#455]
rules_go 0.13.0 removes go_prefix ([release note](https://github.com/bazelbuild/rules_go/releases/tag/0.13.0)), which was used by container-structure-test's [BUILD.bazel](https://github.com/GoogleContainerTools/container-structure-test/blob/e9fd330291f325343a65d3ffee2b62f86e98ae7b/BUILD.bazel#L66). This can't easily be worked around by updating container-structure-test, as the Bazel build has been removed ([issue](https://github.com/GoogleContainerTools/container-structure-test/issues/150)).

@nkubala, the original author of `container_test` and @xingao267, who has maintained it recently.

**Comment by xingao267** [comment]
I think there are few alternatives here.

1. use new_git_repository rules, with a custom BUILD file with a go_binary target to generate the container_structure_test binary. This one I'm not sure exactly how hard would be, but it's kind of having one giant aggregated BUILD file with all/most content previously in container-structure-test's BUILD files?

2. Checkout container_structure_test's release binary file and directly invoke that in the container_test rule.

3. Still checkout the container_structure_test's repo, use [container_run_and_extract](https://github.com/GoogleContainerTools/base-images-docker/blob/master/util/run.bzl#L121) to compile the binary in a container and then use for test. This is not very promising as it potentially adds "docker" as a dependency of rules_docker.

@nkubala, wdyt?

**Comment by xingao267** [comment]
Have a PR for option 2. @nkubala we need to cut another release to include the fix for yaml config validation and tar image not properly prepared issues so container_image can depend on that.

**Comment by nkubala** [comment]
I think option 2 is probably the best bet here. Definitely don't want to depend on docker in rules_docker so option 3 is out, and while you could use gazelle to autogenerate BUILD files for option 1, I'm not sure we should do that since container-structure-test is no longer using bazel.

@xingao267 I'll try and get a release out this afternoon.

**Comment by xingao267** [comment]
@drigz Reopened. Sorry for the confusion. There is another PR on the way.

**Comment by xingao267** [comment]
https://github.com/bazelbuild/rules_docker/pull/461 is in. Please reopen if you experience any issue.
