### ISSUE TITLE
exec format error when running nodejs_image

### ISSUE THREAD

**Issue by bugzpodder** [bazelbuild/rules_docker#458]
Repo steps:
1) clone repo
2) cd testdata
3) bazel run nodejs_image
4) Get error: /app/testdata/nodejs_image.binary: line 153: /app/testdata/nodejs_image.binary.runfiles/io_bazel_rules_docker/external/nodejs/node/bin/node: cannot execute binary file: Exec format error

**Comment by bugzpodder** [comment]
looks like from https://github.com/bazelbuild/rules_docker/issues/434 I should be building from linux machine instead of mac?

**Comment by bugzpodder** [comment]
built in linux and it worked fine, please close if its expected.

**Comment by bugzpodder** [comment]
I was able to trick bazel into using the right nodejs binary: replacing the darwin one with the linux_amd entry
node_repositories = {
    "8.10.0-darwin_amd64": ("node-v8.10.0-darwin-x64.tar.gz", "node-v8.10.0-darwin-x64", "7d77bd35bc781f02ba7383779da30bd529f21849b86f14d87e097497671b0271"),
    "8.10.0-linux_amd64": ("node-v8.10.0-linux-x64.tar.xz", "node-v8.10.0-linux-x64", "92220638d661a43bd0fee2bf478cb283ead6524f231aabccf14c549ebc2bc338"),
    "8.10.0-windows_amd64": ("node-v8.10.0-win-x64.zip", "node-v8.10.0-win-x64", "936ada36cb6f09a5565571e15eb8006e45c5a513529c19e21d070acf0e50321b"),
  },

**Comment by nlopezgi** [comment]
Yes, this is expected, these rules cannot be run from a mac.

**Comment by mikberg** [comment]
@nlopezgi Following the trick above, and with some slight edits, I made workspace rule to download the Node binary for Linux, then made a copy of `nodejs/image.bzl` which accepts the `node` kwarg which is passed on to `nodejs_binary`. The end result is that I can pass `node = "@nodejs_linux//:node",` as a kwarg to `nodejs_image`, where `@nodejs_linux` is the linux binary.

The images (built from MacOS) work perfectly – at least, I haven't found any issues.

Is this too much of a hack to go into this repo? Would there be corner-cases where this approach would break down?

Assuming this approach actually works, it's a very minor fix.

**Comment by Globegitter** [comment]
@mikberg That would be a great workaround until proper cross-platform support has been built in. The only issues I can think of is if you are depending on native/compiled modules but I think for a lot of applications is easy enough to avoid these that it imo is worth the fix.

**Comment by Globegitter** [comment]
@mikberg thinking about it we might even be able to control this via some flags through `rules_nodejs` directly. I will investigate this option

**Comment by nlopezgi** [comment]
yes, this definitely is something that should be upstream in rules nodejs.
This issue is problematic not only for rules_docker but also for remote execution. rules_go had  a similar problem (https://github.com/bazelbuild/rules_go/issues/1760) that has been already resolved

**Comment by Globegitter** [comment]
Thanks for the pointers @nlopezgi
