### ISSUE TITLE
bazel run for java_image fails: no such attribute 'ports' in 'java_binary' rule

### ISSUE THREAD

**Issue by igorgatis** [bazelbuild/rules_docker#464]
My java app needs to expose a few ports, here is what I wrote:
```
java_image(
    name = "foo-image",
    main_class = "com.foo.Main",
    ports = ["50051"],
    runtime_deps = [
        ":foo",
    ],
)
```
It fails because `ports` gets passed to a `native.java_binary`.

**Comment by nlopezgi** [comment]
ports are not supported in lang_image rules. You can compose java_image with container_image to achieve what you need (see example for go_image in https://github.com/bazelbuild/rules_docker/issues/309)
