### ISSUE TITLE
Expand jvm_flags in java_image

### ISSUE THREAD

**Issue by mjduijn** [bazelbuild/rules_docker#468]
The native Java binary rule accepts jvm_flags with a location like so:
```
java_binary(
    name = "my_rule",
    data = [
        ":log4j.properties",
    ],
    jvm_flags = [
        "-Dlog4j.configuration=file:$(location :log4j.properties)",
    ],
    main_class = "com.example.Main",
    runtime_deps = [":my_app"],
)
```
It would be great to have the same for java_image.

**Comment by nlopezgi** [comment]
Expanding these flags would be great indeed. We recently received a PR doing something similar for args: https://github.com/bazelbuild/rules_docker/pull/452. It would be awesome if you could send a PR to do this.
