### ISSUE TITLE
Run update_deps.sh regularly to pick up distroless security and bug fixes

### ISSUE THREAD

**Issue by evanj** [bazelbuild/rules_docker#477]
It seems that the Python base distroless images that are referenced by these rules have not been [updated since 2018-01-24](https://github.com/bazelbuild/rules_docker/blob/master/python/python.bzl#L21). As a result, this is missing some of the upstream fixes (in my case, I was assuming the SSL fix I made would be here now, and I could remove my hacks). The upstream distroless project should hopefully be updating on some regular cadence to get Debian security updates. It would be nice if this project similarly updated on some regular cadence to ensure it picks up those updates as well.

If it would be useful, I'm happy to run `update_deps.sh` myself right now and submit a PR to update this now, but it would be nice if a project maintainer could try to do this say once a month or once a quarter or something.

**Comment by nlopezgi** [comment]
hi @evanj it would be awesome if you could send a PR to update this! Otherwise I'll try to get to it next week. Thanks for notifying us of the issue.

**Comment by nlopezgi** [comment]
Actually, taking care of this now as I had some spare cycles today.

**Comment by nlopezgi** [comment]
https://github.com/bazelbuild/rules_docker/pull/480

**Comment by evanj** [comment]
Awesome thanks!
