### ISSUE TITLE
@py_debug_image_base has a busybox that cannot cope with large files

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/rules_docker#479]
The busybox binary
```
BusyBox v1.27.1 (2017-07-18 19:24:44 CEST) multi-call binary.
```
has several commands failing list this, when I exec into the containers:
```
> ls
ls: can't open '.': Value too large for defined data type
```
This seems to be the case when it has not been built with large file support.

**Comment by nlopezgi** [comment]
Could you please provide some instructions to repro the issue you are having?
Alternatively, the base images for py_image are defined here: https://github.com/bazelbuild/rules_docker/blob/master/python/python.bzl. Could you try to update the sha's there to use the latest ones defined in http://gcr.io/distroless/python2.7 and let me know if that fixes your issue?

**Comment by nlopezgi** [comment]
https://github.com/bazelbuild/rules_docker/pull/480

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
