### ISSUE TITLE
v0.5.0 doesn't work due to updated bazel RC

### ISSUE THREAD

**Issue by bjchambers** [bazelbuild/rules_docker#500]
When using rules_docker v0.5.0, the following error is reported:

ERROR: /root/.cache/bazel/_bazel_root/fedbe18efb44ce20c9a2f91ac34da5e7/external/io_bazel_rules_docker/container/BUILD:67:1: no such package '@bazel_source//tools/build_defs/pkg': java.io.IOException: Error downloading [https://releases.bazel.build/0.17.0/rc1/bazel-0.17.0rc1-dist.zip] to /root/.cache/bazel/_bazel_root/fedbe18efb44ce20c9a2f91ac34da5e7/external/bazel_source/bazel-0.17.0rc1-dist.zip: Checksum was 46dfffac884ccd51fcb493dd86463cb8c21be949fdb17634ca37805fd544beae but wanted a9afd2b16a21085bd6c0a70a23acce30b105a8af3a7b3c92a4b83bea6b623fd8 and referenced by '@io_bazel_rules_docker//container:build_tar'

It looks like (possibly) the checksum of bazel-0.17.0rc1 has changed.

This also seems to be mentioned in bazelbuild, but if the RC has been updated (instead of creating a new RC) it seems like something that needs to be fixed here.

https://github.com/bazelbuild/bazel/issues/5964

**Comment by xingao267** [comment]
bazel 0.17.0rc1 is indeed replaced. See https://groups.google.com/forum/#!msg/bazel-discuss/1116GHzkNm0/AYWnvEK_AAAJ for why it's replaced instead of cutting new 0.17.0rc2.

**Comment by bjchambers** [comment]
As a note to anyone that hits this, an easy work around is to import bazel_source yourself. The rules_docker will then skip importing it. I added the following to my WORKSPACE to get things working:

```
# Import bazel_source ourselves, to work around checksum issues 
# https://github.com/bazelbuild/rules_docker/issues/500
http_archive(
    name = "bazel_source",
    sha256 = "46dfffac884ccd51fcb493dd86463cb8c21be949fdb17634ca37805fd544beae",
    urls = [("https://releases.bazel.build/0.17.0/rc1/bazel-0.17.0rc1-dist.zip")],
)
```

**Comment by nlopezgi** [comment]
thanks for providing a suggested fix, I just released 0.5.1 with the fix to pick the right 0.17.0rc. Please also note that once 0.17.0 is officially out we will be able to remove this dependency altogether.

**Comment by zaneclaes** [comment]
@nlopezgi I stumbled on this thread because the default install in `README` results in this error. This is because the md still references `0.5.0`.

**Comment by nlopezgi** [comment]
thanks for pointing this out, fixing.
