### ISSUE TITLE
Separate workspace functions from BUILD rules

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/rules_docker#503]
(1) Logically, they are separate, and there is no point for WORKSPACE to be loading build rules or BUILD to be loading workspace rules/functions.

(2) Real work consequence https://github.com/andyscott/rules_scala_annex no longer loads the test workspace when upgrading to Bazel 0.14.0+.

`@rules_scala_annex` has a emulation mode where it can be a drop in replacement `@io_bazel_rules_scala`.

It breaks somewhere for a reason I can't figure out

```
create remote repository `@rules_scala_annex`

create local repository as @io_bazel_rules_scala (this will delegate to @rules_scala_annex)

create remote repository as @io_bazel_rules_docker

load @io_bazel_rules_docker//scala:image.bzl (for repositories function)
    load @io_bazel_rules_scala//scala:scala.bzl # unnecessary
        load @rules_scala_annex//rules/rules_scala.bzl
           ... BREAKS somewhere
```

However, if I separate `@io_bazel_rules_docker//scala:image.bzl` into WORKSPACE-related and BUILD -related skylark files, everything from `# unnecessary` on doesn't happen. I can dig into what changed between Bazel 0.13 and 0.14, but I figure this is a good change anyway.

**Comment by nlopezgi** [comment]
Hi @pauldraper 
I'm not sure I understand 100% your issue, so sorry if I'm off.
Is the issue that you want to override how @io_bazel_rules_scala is loaded when in your repo you add a dep to @rules_docker? If that is the case, then I think it should be possible to do this by moving the load declaration of io_bazel_rules_scala from here https://github.com/nlopezgi/rules_docker/blob/master/WORKSPACE#L107, to somewhere in here: https://github.com/nlopezgi/rules_docker/blob/master/container/container.bzl#L63. That way, if you were to declare an override for @io_bazel_rules_scala (in your workspace file, and pointing that to your @rules_scala_annex), the repositories function would not attempt to pull it again. All you would need to do then is make sure the load for @rules_docker is below the load for @io_bazel_rules_scala in your workspace file.

If you want to send a PR to move the load of io_bazel_rules_scala to container.bzl that would be awesome!

(If this is not what you meant please let me know with a bit more clarifications so I can try to understand)
Thanks!

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
