### ISSUE TITLE
gzip missing on Windows

### ISSUE THREAD

**Issue by enriched** [bazelbuild/rules_docker#507]
If the user has not installed gzip on windows then building containers will fail because the `@gzip//:gzip` target does not exist.

**Comment by nlopezgi** [comment]
Thanks for noting this issue. Do you have any suggestions as to how we could improve this experience (i.e., gzip is a requirement of these rules, but perhaps the error messaging is not clear atm about this)?

**Comment by enriched** [comment]
I think that a required dependencies section in the setup would make sense. I think there are a couple of rules like this that end up using a local binary (I think that rules_k8s uses a local kubectl binary), which seems like a reasonable requirement as long as it's documented.

A `choco install gzip` fixes the issue for windows users.

**Comment by nlopezgi** [comment]
thanks for the advice, we also maintain rules_k8s. Will update docs to include dependencies soon (we're working on improving some of these deps which will make things better, and will do doc cleanup as part of this). Will keep issue open for now to remind myself once we get to do doc updates. Thanks again

**Comment by enriched** [comment]
Thanks for the update and for all of the great work on these rules! The ability to build docker containers without the docker daemon is awesome. And the control that it gives you to reuse the layers and only rebuild the ones that have changed is also amazing.
