### ISSUE TITLE
docker_bundle always up-to-date (nothing to build)

### ISSUE THREAD

**Issue by jimmidyson** [bazelbuild/rules_docker#51]
Playing around trying to see how this can be used for a general go project. Building the binary via `go_binary` and image via `docker_build` works, but `docker_bundle` always says it's up-to-date, when no binary bundle (tarball I'm expecting is being produced.

Output is:

```bash
$ bazel build :docker

INFO: Found 1 target...
Target //:docker up-to-date (nothing to build)
INFO: Elapsed time: 0.837s, Critical Path: 0.64s
```

Here's my BUILD file:

```
go_binary(
    name = "dummy-web",
    library = ":go_default_library",
)

docker_build(
    name = "docker-internal",
    base = "@distroless_base//image:image.tar",
    entrypoint = ["/dummy-web"],
    files = [":dummy-web"],
    visibility = ["//visibility:private"],
)

docker_bundle(
    name = "docker",
    images = {
        "dummy/web:latest": ":docker-internal",
    },
    stamp = True,
)
```

I assume i'm doing something wrong but not sure what (I'm a bazel n00b I'm afraid).

**Comment by mattmoor** [comment]
If you have a sample repo I can clone and build, I can take a look.

What happens if you `bazel build :docker.tar`?

**Comment by jimmidyson** [comment]
Aha that works great. But I have no idea why... I was expecting `bazel build :docker` to work - is that just my misunderstanding or an issue with docker_bundle?

**Comment by mattmoor** [comment]
So `.tar` makes it link the full tarball, which can be expensive, so we avoid it for intermediate steps (think: n^2 expensive).  You can also load the resulting image without linking via `bazel run :docker`.

This is an optimization @damienmg implemented years ago now.

Also FWIW `docker_push` should work with either form.

**Comment by jimmidyson** [comment]
OK that's brilliant thanks for the info!
