### ISSUE TITLE
Common attribute: tags=["manual"] doesn't work. Rule is always ran with //...

### ISSUE THREAD

**Issue by btbuxton** [bazelbuild/rules_docker#523]
I would like to run container_image and container_push as manual rules and not part of the //... build. In the common attributes page of bazel: https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes. It states that tags are a common attribute to control the build. 

Would it be possible to add this to the container_* rules? Or is there a work around to have container_* rules not run with the generic //... build?

**Comment by cgbystrom** [comment]
I've been having the same issue. At least the `scala_image` rule do not pass common attributes such as tags down to `jar_app_layer` for the layers.

See: https://github.com/bazelbuild/rules_docker/blob/f5ed963f7411f07efd6b0bd8667fe89d6a05077b/scala/image.bzl#L63

Seems to work for me if patching that to pass `tags` as well.

**Comment by nlopezgi** [comment]
@cgbystrom thanks for noting! It would be great if you could send a PR adding the passing of these common attributes for the scala_image rule (iiuc, should be simple PRs)! As I mentioned above, I only tested the container_image rule with tag and seemed to work for me. Unfortunately, testing things like this systematically (i.e., creating unit tests) is not at all easy for Skylark rules (if not to say impossible for details such as whether tags are working well). Happy to review any PRs you or @btbuxton want to send to fix any of these issues! I think there might be several places that need these tags to be passed, but all of these should be simple PRs hopefully.

**Comment by nlopezgi** [comment]
Leaving issue open as we should try to fix this on a case by case basis.

**Comment by mhines99** [comment]
I am having the same issue with container_image not honoring tags

**Comment by nlopezgi** [comment]
As mentioned above (https://github.com/bazelbuild/rules_docker/issues/523#issuecomment-423657124) we are aware some targets do not respect tags. We would be happy to receive a PR to fix. You can also see https://github.com/bazelbuild/bazel/issues/8462
and try to use --incompatible_allow_tags_propagation.

Closing this issue as the recommended fix, atm, is to use --incompatible_allow_tags_propagation (or wait for a bazel version that has that on by default).
