### ISSUE TITLE
Java images don't get build-data.properties

### ISSUE THREAD

**Issue by deadmoose** [bazelbuild/rules_docker#524]
Building the `foo_deploy.jar` fat-jar target for a `java_binary` includes a file `build-data.properties` with some of the content from `volatile-status.txt` and `stable-status.txt`. (In particular, the value of --embed_label)

Since the java_image rule includes `foo.jar` and its dependencies rather than building the fat jar, it doesn't get that & my end binary is blissfully ignorant of its build details.

Grepping through Bazel itself, it looks like `build-data.properties` is pretty internal to building the `_deploy.jar`, so I can't even explicitly throw that into my `deps` or `runtimedeps`. :/

In the meantime, I guess I can make my own rule to generate that properties file, stuff it in a lib, and depend on that, but ideally `java_image` should do that for me.

Alternately this might be more of an upstream bug for Bazel to get stamped build details into the core `java_binary` target instead of only its deploy jar.

**Comment by xingao267** [comment]
Hey @deadmoose, thanks for reporting. Yea, from my understanding, when you add `_deploy` between the target and .jar when building a `java_binary` target, Bazel builds a standalone jar with some additional files. We'll evaluate options and post here for comments/feedback soon. At the meantime, if you have some ideas, feel free to comment as well. If you would like to send a PR, that will be awesome! Thanks!

**Comment by nlopezgi** [comment]
Hi @deadmoose ,
It seems to me that if the `build-data.properties` is internal and is not being exposed as `deps` or `runtimedeps` there is very little we can do in `java_image` to fix this (short of replicating the code bazel has to create this file ourselves in `java_image`, which is a non starter as it will increase the maintenance burden of the rules and will break whenever Bazel upstream wants to change the implementation details of how `build-data.properties` is created. I recommend you create an issue in Bazel upstream to have that file exposed in a way that can be consumed by `java_image`. Will keep this open as a feature request pending on the upstream issue to be resolved.
