### ISSUE TITLE
Any way to add RUN command to set up docker account using root?

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_docker#529]
FROM dev-docker:5000/katz/rhel7
COPY bin/kinit.sh /apps/kinit.sh
RUN echo "sh /apps/kinit.sh &" >> /apps/startup.sh
RUN useradd -r -u 50148 -d /apps asgdevmgr
RUN chown asgdevmgr /apps
USER asgdevmgr

There doesn't seem to be any way to use RUN commands in the bazel docker rules.

**Comment by nlopezgi** [comment]
RUN is not currently supported as it requires the docker deamon and produces non-deterministic outputs.
