### ISSUE TITLE
Update Authentication section

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_docker#532]
https://github.com/bazelbuild/rules_docker#authentication currently suggests installing docker-credential-gcr, however the docker-credential-gcr docs prefer users do `gcloud auth configure-docker`. https://github.com/GoogleCloudPlatform/docker-credential-gcr#introduction Can we the docks for this?

**Comment by smukherj1** [comment]
Hello Erick,
 The command text  "gcloud auth configure-docker" in
https://github.com/GoogleCloudPlatform/docker-credential-gcr#introduction links to https://cloud.google.com/sdk/gcloud/reference/auth/configure-docker which is the docs for gcloud auth configure-docker. Were you looking for anything in addition to the docs at https://cloud.google.com/sdk/gcloud/reference/auth/configure-docker ?

**Comment by fejta** [comment]
Yes, the rules_docker authentication docs tell me to run the deprecated:

```
$ gcloud components install docker-credential-gcr
$ docker-credential-gcr configure-docker
```

Rather than the modern `gcloud auth configure-docker`

**Comment by xingao267** [comment]
Yea. Let's update the doc to instruct the users to use `gcloud` and point to https://cloud.google.com/sdk/gcloud/reference/auth/configure-docker, and only use `docker-credential-gcr` if they don't want to or unable to install `gcloud`.

(sorry about mis-changing the title...:P)
