### ISSUE TITLE
[optimization] make container_bundle rule to work parallel

### ISSUE THREAD

**Issue by excavador** [bazelbuild/rules_docker#536]
It would be great to make container_bundle works parallel.

Motation is simple: performance.
In our integration tests we load images to local docker & run local stand on every test run.

If you have 5 images and every image spect about 2-3 seconds, we have a lag to start about 10-15 seconds.

With parallel load it would be just few seconds

**Comment by xingao267** [comment]
Thanks again Oleg, it was nice meeting you in the BazelCon. We will look into this.

**Comment by nlopezgi** [comment]
Thanks for creating this issue. Adding this functionality would be fine as long as the maintenance burden is not to high and its properly tested. If you want to submit a PR I'll be happy to review. Thanks again.
