### ISSUE TITLE
[feature request] container_push for multiple images

### ISSUE THREAD

**Issue by excavador** [bazelbuild/rules_docker#537]
With local docker we have two options:
- load single image by `bazel run //local/of/image`
- load bundle of images by `container_bundle`

Would be great to receive "bundle" version of push.
We have something similar in contrib/push-all.bzl, but it has numerous of issues:
- no way to specify repositories/registries for individual images
- no way to specify tag for individual images
- uses old `struct` instead of providers.

In addition to bundle version of push, would be also to have parallel solution. (see also #536)

Single `docker push registry/repository:tag` works on our images (~100 Mb) just 2 seconds
Actual `container_push`on same version works about 15 seconds.

If you push 5-6 images sequentially, it would be one and half minutes.
In parallel version it would be same 15 seconds.

And, of course, would be great to see optimizations to actual container push

**Comment by nlopezgi** [comment]
Thanks for creating this issue. Adding this functionality would be fine as long as the maintenance burden is not to high and its properly tested. If you want to submit a PR I'll be happy to review. Thanks again.
