### ISSUE TITLE
Docker Run w/o Docker

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_docker#541]
@nlopezgi mentioned at dockercon that `docker run` without docker would be very nice to have with this rule set.

**Comment by Globegitter** [comment]
That sounds pretty great, how would that be possible?

**Comment by nlopezgi** [comment]
we are planning on exploring things like gvisor (https://github.com/google/gvisor)

**Comment by Globegitter** [comment]
That seems very interesting, looking forward to seeing progress on this.
