### ISSUE TITLE
Setting jvm_flags in a java_image at runtime

### ISSUE THREAD

**Issue by michaelschiff** [bazelbuild/rules_docker#548]
The `java_image` rule has a parameter `jvm_flags` that allows the user to set desired flags at compile time, however there does not seem to be a way to set these arguments at runtime.  In `image.bzl` the java container entrypoint is defined as:
```
  entrypoint = [
      '/usr/bin/java',
      '-cp',
      # Support optionally passing the classpath as a file.
      '@' + classpath_path if ctx.attr._classpath_as_file else classpath,
   ] + ctx.attr.jvm_flags + [ctx.attr.main_class]
```

Setting these flags at runtime is desirable so that a single image could be built, and JVM parameters could be tweaked depending on where this image is deployed. For example, Continuous Integration environment vs. Production environment - ideally you would test _exactly_ the same image you are going to run, but this is not possible if they require different jvm flags and if jvm flags are only settable at compile time.

The `java_binary` rule allows the user to set jvm_flags at runtime, as this parameter is exposed in the script that actually calls the compiled jar.

One possible route to achieve this would be to expose an environment variable that would be part of the container entry point.  If I am correct that there is no way to do this, and if this seems like a reasonable approach I would be happy to submit a PR implementing this change.

**Comment by michaelschiff** [comment]
Thanks for getting back to me @nlopezgi - I think you understand my intent correctly: allow a user to set JVM flags at image runtime.  

Looking through the diff you linked to the Docker env value is set in the call to the underlying container implementation:
```
    return _container.image.implementation(
        ctx,
        # We use all absolute paths.
        directory = "/",
        env = {
            "JAVA_RUNFILES": "/app",
        },
        file_map = file_map,
        entrypoint = entrypoint,
    )
```
 I assume if I were do something similar e.g. adding a `JAVA_OPTS` variable, that the value of this variable could be expanded in the container entry point.

However, the approach in the diff you linked to still appears to be a compile time strategy in that the map of these values is passed into the call to `container.image.implementation`.  My goal is to put some variable into the entrypoint whose value would not be decided until the container is executed. Maybe I am misunderstanding something now - but if expanding a variable in the entrypoint requires that it be present in the env map at container build time, I don't think this actually solves the problem.

**Comment by nlopezgi** [comment]
anything else needed for this issue or does #563 fix it. Let me know if anything else is needed to reopen.

**Comment by michaelschiff** [comment]
#563 addresses all of my main issues.  We can keep ongoing discussion/work in #574
