### ISSUE TITLE
container_push ignores BAZEL_PYTHON environment variable

### ISSUE THREAD

**Issue by lvt-mm** [bazelbuild/rules_docker#556]
Environment setup
-----------------------

This bug happens when `python` defaults to `python3` and `BAZEL_PYTHON` is set to `python2`, that is, when things are like this:

    $ python -c "import sys; print(sys.version[0])"
    3
    $ echo $BAZEL_PYTHON
    python2
    $ python2 -c "import sys; print(sys.version[0])"
    2

The bug
----------

In these circumstances, `container_push` fails with a `SyntaxError`:

	Traceback (most recent call last):
	  File ".../publish_test.runfiles/containerregistry/tools/fast_pusher_.py", line 29, in <module>
		from containerregistry.client import docker_creds
	  File ".../publish_test.runfiles/containerregistry/client/init.py", line 23, in <module>
		from containerregistry.client import docker_creds_
	  File ".../publish_test.runfiles/containerregistry/client/docker_creds_.py", line 31, in <module>
		import httplib2
	  File ".../publish_test.runfiles/httplib2/init.py", line 988
		raise socket.error, msg
                              ^
	SyntaxError: invalid syntax

What goes wrong?
-----------------------

This seems to happen because `container_push` somehow ignores the `BAZEL_PYTHON` setting: it obviously uses `python3` to execute the `fast_pusher_.py` file. This goes badly when it tries to execute code written with python 2 only syntax.

Contrast with `container_pull`, which works as expected under these circumstances.

SSCCE
---------

Here's the contents of a BUILD file that triggers the bug under the above conditions, but you need to replace `<your-repo-here>` and possibly `index.docker.io` with values for where you have push access.

    load("@io_bazel_rules_docker//container:container.bzl", "container_push")
    load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")
    load("@io_bazel_rules_docker//container:layer.bzl", "container_layer")
    load("@io_bazel_rules_docker//container:image.bzl", "container_image")
    
    # Tests that pushing images work.
    
    package(default_visibility = ["//visibility:public"])
    
    pkg_tar(
        name = "test_tar",
        strip_prefix = ".",
        # Just a file that we know exists. Tested and works.
        srcs = ["BUILD"],
        mode = "0755",
    )
    
    container_layer(
        name = "test_files",
        directory = "/opt/",
        tars = ["test_tar"],
    )
    
    container_image(
        name = "container",
        layers = ["test_files"],
        visibility = ["//visibility:public"],
    )
    
    container_push(
        name = "publish_test",
        image = "container",
        format = "Docker",
        registry = "index.docker.io",
        repository = "<your-repo-here>",
    )

Finally, this is the `@io_bazel_rules_docker` entry from the WORKSPACE:

    http_archive(
        name = "io_bazel_rules_docker",
        sha256 = "29d109605e0d6f9c892584f07275b8c9260803bf0c6fcb7de2623b2bedc910bd",
        strip_prefix = "rules_docker-0.5.1",
        urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.5.1.tar.gz"],
    )

Trigger bug with `bazel run //build/path:publish_test`.

**Comment by nlopezgi** [comment]
Hi,
Thanks for creating this issue. Please see the comment here https://github.com/bazelbuild/rules_docker/blob/master/python/BUILD#L18 for current advice to set the python path. We are aware we currently do not support all bazel python related flags, if you need this specific flag supported, we'll be happy to review any PRs you send to add support for it. Thanks again!

**Comment by Globegitter** [comment]
@lvt-mm seperately from the fact that it should respect the `BAZEL_PYTHON` version there is also https://github.com/google/containerregistry/pull/109 which should make the whole code py2 & 3 compatible and remove the need for any of these workarounds :)
