### ISSUE TITLE
Add possibility to install RPM's under the container

### ISSUE THREAD

**Issue by cynepco3hahue** [bazelbuild/rules_docker#564]
Currently, I have the possibility to deploy Debian packages, but no support for RPM's.

**Comment by nlopezgi** [comment]
Hi @cynepco3hahue ,
thanks for opening this issue, sorry for the late response, and thanks for noticing its a duplicate. 
While the response in the duplicate issue is still valid, there is lots of work happening in the bazel/python area that might make this feasible in the future. Please keep track of bazel-sig-python@googlegroups.com  and feel free to reopen once proper pip support is in the pipeline so we can talk about this again.

**Comment by cynepco3hahue** [comment]
@nlopezgi Thanks for information will follow google group.
