### ISSUE TITLE
container_image pull failed due to ModuleNotFoundError: No module named 'urlparse'

### ISSUE THREAD

**Issue by sevki** [bazelbuild/rules_docker#571]
container pull is failing, is there a way these rules can fetch their own dependencies?

```
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sevki/.cache/bazel/_bazel_sevki/8418c246714b9c1ed2e6af9cd105006f/external/puller/file/puller.par/__main__.py", line 30, in <module>
  File "/home/sevki/.cache/bazel/_bazel_sevki/8418c246714b9c1ed2e6af9cd105006f/external/puller/file/puller.par/containerregistry/client/__init__.py", line 19, in <module>
  File "/home/sevki/.cache/bazel/_bazel_sevki/8418c246714b9c1ed2e6af9cd105006f/external/puller/file/puller.par/containerregistry/client/docker_name_.py", line 21, in <module>
ModuleNotFoundError: No module named 'urlparse'
```
this is fixed by BAZEL_PYTHON envinroment variable, but I think the docker rules should either get rid of the python dependencies or bring it's own python.

**Comment by nlopezgi** [comment]
Hi @sevki ,
Currently working with python in Bazel has several limitations. However, there is lots of work currently happening in Bazel team to improve how python is specified which will make use cases like these better (please follow https://groups.google.com/forum/#!forum/bazel-sig-python). We have plans to improve these rules once some of these changes land. For now, you will need to work with setting the env variable (but please note the solution you suggest, to make it easy for rules to bring their own python, is one that not likely to happen for quite some time). 
Thanks for your understanding.

Keeping this issue open to return to it once Bazel upstream changes for python land.

**Comment by smukherj1** [comment]
I think the problem here might be something slightly different. urlparse is a python standard library module and shouldn't need to be pulled. From the urlparse python2 docs (https://docs.python.org/2/library/urlparse.html) I see:-
The urlparse module is renamed to urllib.parse in Python 3

The stack trace above suggests container_pull is being run using python3. I think in addition to better python support in bazel as @nlopezgi  suggested, containerregistry might need to be updated to import the right module depending on whether it's running in python2 or python3

**Comment by sevki** [comment]
@smukherj1 exactly right. I was trying to use the `container_pull` rule which I don't think should not have a dependency on python 2,3

**Comment by smukherj1** [comment]
> @smukherj1 exactly right. I was trying to use the `container_pull` rule which I don't think should not have a dependency on python 2,3

@sevki didn't fully get that. Did you mean container_pull should **not** depend on python?

**Comment by sevki** [comment]
yes.

**Comment by nlopezgi** [comment]
@sevki thanks for your suggestion; the containerregistry library we currently use depends on python.

**Comment by nlopezgi** [comment]
the containerregistry library we use does not provide such modes (https://github.com/google/containerregistry/blob/master/tools/docker_pusher_.py). You can modify the code in $(bazel info output_base)/external/containerregistry/tools/docker_pusher_.py to printf debug through your issue

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
