### ISSUE TITLE
document what happens with docker_build targets when run by bazel build vs run

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_docker#58]
The old docs at https://bazel.build/versions/master/docs/be/docker.html, I believe, mentioned what would happen when a docker_build target was run with `bazel build` vs `bazel run`. I don't see that in the README here, but maybe I missed it?

It'd be nice to have a thing to hand to newbies about these targets.

**Comment by mattmoor** [comment]
That is definitely a good point, I'll use this to track.  thanks!

**Comment by jmhodges** [comment]
Thanks!
