### ISSUE TITLE
deb file extracted relative to workdir

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_docker#582]
We where just trying to install the deb whois package (https://packages.debian.org/stretch/whois) in a `container_image` and noticed that when also  setting `workdir=/path` that the whois binary was extracted to `/path/usr/bin/whois` rather than the expected `/usr/bin/whois`

It seems like the extraction is taking the `workdir` into account which seems a bit surprising. Was that done on purpose or is it a bug?

**Comment by nlopezgi** [comment]
sounds like a bug to me,  can't imagine why anyone would expect that behaviot. I think we have few tests that use the deb feature, so it might have drifted. If you could send a PR to fix (+add tests) that would be awesome!

**Comment by Globegitter** [comment]
Yeah I was trying to have a quick glance at the code, is the `build_tar.py` as well as `https://github.com/bazelbuild/rules_docker/blob/master/container/layer.bzl` the place where the extraction is happening?

**Comment by nlopezgi** [comment]
@Globegitter could you provide repro instructions, or can we close?

**Comment by Globegitter** [comment]
@nlopezgi sorry we did workaround that issue and I have not had time to look at this yet, I will try and add a repro case within the next week.
