### ISSUE TITLE
rules_gwt compatibility

### ISSUE THREAD

**Issue by factuno-db** [bazelbuild/rules_docker#583]
Is there any interest in making rules_docker compatible with rules_gwt (https://github.com/bazelbuild/rules_gwt)?

As of now, war_image does not work with gwt_application.

If there is any interest, I would be willing to give it a try!

**Comment by nlopezgi** [comment]
Hi @factuno-db ,
We don't know of any other customers currently requesting this use case. My one concern is that maintenance of the xx_image rules is complex enough as it is atm (e.g., subtle changes to how xx_binary rules work can impact or even break the corresponding xx_image rule) so I do not want to expand on the maintenance burden. But I'm also not too familiar with how rules_gwt work or what your expectation is. 

Please note war_image is currently a very simple rule that creates the container overlaying a java_library as an exploded WAR, so it can only work (as it is intended) if what you are using as input is a java_library. If changing this to support gwt_application means that we will be having code that directly calls rules provided in rules_gwt, then this is something we cannot take in this repo as the maintenance burden is something we are not prepared to take on.

**Comment by factuno-db** [comment]
Alright!
