### ISSUE TITLE
container_test broken when using container-structure-test 1.6

### ISSUE THREAD

**Issue by Monnoroch** [bazelbuild/rules_docker#600]
I tried to override the container-structure-test dependency from 1.4 to 1.6 and got this error:

```
Error: error creating driver: processing tar image reference: mkdir /tmp/root.cachebazel_bazel_rootdce6ed4f9b6b93214722cd6fa27af714execrootastrabazel-outk8-fastbuildbinsomeveryveryveryveryveryveryveryveryveryveryverylongname_test.runfilessomeveryveryveryveryveryveryveryveryveryveryverylongname.tar@sha256:27157e6b7e4373f939de9c51191487f9cbf80e6e7f132445fa5a2d605c3e39fb691144971: file name too long
```

1.5 is working though. I realize that strictly speaking 1.6 is "not supported" but the upgrade will happen at some point and this issue will have to be fixed.

See related discussion in https://github.com/GoogleContainerTools/container-structure-test/issues/183.

**Comment by Monnoroch** [comment]
A very long file name is not needed. I just update the container-structure-test dependency to 1.6 and call `bazel test //...` on my repo. I'll try to come up with a minimal example tomorrow, but it's Bazel (or, rather Bazel and the rules) who generates file names. Please take a look at the related issue in container-structure-test repo.

**Comment by Monnoroch** [comment]
The release is fine, it works perfectly as a standalone software. It's `bazel test //...` who generates long names.

**Comment by Monnoroch** [comment]
Here is a more detailed file name generated:

```
/tmp/homemonnoroch.cachebazel_bazel_monnoroch0a678f6ad8dbaaba9053e7774197befbsandboxlinux-sandbox3execroot${workspace_name}bazel-outk8-fastbuildbin${package_path}${container_test_target_name}.runfiles${workspace_name}${package_path}${container_image_target_name}.tar@sha256:3c0db08cdeed96c0d85bd3b6b10dab11f8281fdff96ef9fda7f93d20aa89afa3308596592: file name too long
```

My `${package_path}` is 32 characters long, my workspace name is 5 characters long, my target names are at most 10 characters long. There's nothing unreasonable here, though I notice that the package name is used twice and that there's the image digest which is super long by itself.

Overall I would just say that the probability of getting a long file name is super high right now. `short_path` [here](https://github.com/bazelbuild/rules_docker/blob/5eb0728594013d746959c4bd21aa4b0c3e3848d8/contrib/test.bzl#L31) is not short at all.

This is all I know so far, I'm not a huge expert on hacking Bazel just yet, but the `container_test` rule seems super simple and it looks like it's the long `short_path` is at fault here.

**Comment by nlopezgi** [comment]
Sorry but that does not answer my question. contaniner_test is not part of this repo, and Bazel defines how file names are created (https://github.com/bazelbuild/bazel). So I honestly do not see any action that can be taken on this repo to fix this issue. I want to point this out as posting this issue here will likely not get you to a resolution.
