### ISSUE TITLE
How to configure nodejs entrypoint

### ISSUE THREAD

**Issue by milesmatthias** [bazelbuild/rules_docker#607]
My goal is to get my NodeJS image to run `history-server` with a parameter of the path of where my assets are, so history-server can serve them.

Here's my config:

```
nodejs_image(
    name = "nodejs_image",
    entry_point = "workspace/external/npm/node_modules/history-server/modules/cli.js",
    templated_args = ["workspace/js-client/src"],
...
```

But when I build my image and inspect it, I'm seeing this section:

```
 "Cmd": [
                "/bin/sh",
                "-c",
                "/bin/bash"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/app/js-client/src/nodejs_image.binary.runfiles/workspace",
            "Entrypoint": [
                "/app/js-client/src/nodejs_image.binary"
            ],
```

and when I run this image in docker, I'm getting an error like this:

```
→ docker run 72c120c3ea03
history-server using config in /bin/bash
Invalid config file: /bin/bash
```

which makes me think the image is running `/app/js-client/src/nodejs_image.binary -c /bin/bash`, which is an error since `-c` is the flag for history server's config file.

I'm reading the docs as saying that I can set an entry_point and templated_args to have the container run `node {entry_point} {templated_args}`, but that isn't my experience.

Did I misread the docs?

**Comment by nlopezgi** [comment]
the entry_point in nodejs_image is not the same as the entrypoint in the produced container. nodejs_image takes in attrs defined in rules_nodejs (see readme in https://github.com/bazelbuild/rules_nodejs and https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node.bzl#L160). 

- Can you try creating first a working `nodejs_binary` target and then just replace '`nodejs_binary`' for '`nodejs_image`'. 

- Can you publish the remainder of the `nodejs_image` target that you are declaring? I have no idea where the command you show in the image inspect details is coming from, but that's definitely wrong. I suspect you are somehow overriding the cmd in the container which would break the container produced by the `nodejs_image` target

**Comment by chrislovecnm** [comment]
@nlopezgi let me email you

**Comment by nlopezgi** [comment]
cause was : https://github.com/bazelbuild/rules_docker/issues/618 which has been now fixed. Please let me know if you have any other issues

**Comment by milesmatthias** [comment]
Thanks @nlopezgi. Email sent about other issues.
