### ISSUE TITLE
Fix Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_docker#621]
I'd like to be able to build rules_docker with `--all_incompatible_changes`:
  `bazel test --all_incompatible_changes //...`

It may not be possible to fix every issue now due to transitive dependencies, but we should try to fix the issues from this repository.

**Comment by laurentlb** [comment]
We'll be blocked on https://github.com/bazelbuild/rules_d/issues/17

rules_d doesn't seem maintained. Is it an option to drop support for D?

**Comment by laurentlb** [comment]
From the latest CI run (https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/28#149a8ab2-0bec-4e3f-b55d-126548216440), migration is needed for the following flags:
  * --incompatible_depset_is_not_iterable
  * --incompatible_depset_union

Depset documentation is here: https://docs.bazel.build/versions/master/skylark/depsets.html
Let me know if you need help

**Comment by xingao267** [comment]
looking

**Comment by xingao267** [comment]
Seems rules_docker is all green in latest run. https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/40#_
