### ISSUE TITLE
Inconsistent args handling between lang images

### ISSUE THREAD

**Issue by clintharrison** [bazelbuild/rules_docker#637]
This is a bit of a follow-up to #374 and #586, as I'm one of the users who was depending on command line args being passed to the binary 🙂

The issue is a result of inconsistency in `args` handling between different image types: `java_image` appends them directly to the entrypoint, but for other language images (node, python) they are set in `Cmd` -- this means bazel passing them during `bazel run` doesn't duplicate them, just overrides the image Cmd with the same arguments.

It'd be a breaking change to move the Java args from the entrypoint to cmd, but I think the consistency (and ability to pass args at all in the `bazel run` case) means we should consider it.

**Comment by nlopezgi** [comment]
hi @clintharrison,
apologies for the issue. Keeping the xx_image rules working for all use cases has proven challenging for us. What do you think about starting with adding some tests that highlight what currently happens vs what you are proposing for java_image (+bonus points for adding some tests python/node) - (probably will need to be part of e2e tests as they need to do bazel run...). As long as we document well (and test well so we dont regress) breaking changes like the one you propose should be fine.

**Comment by clintharrison** [comment]
cool, totally understandable -- lots of competing priorities  🙂 i think we can extend the existing container structure tests to check the image metadata instead of adding more to the e2e ones -- I'll try to get something up by the end of the week.
thanks for the quick response, really appreciated!
