### ISSUE TITLE
default repository for docker_build

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_docker#64]
It'd be nice to have a way to change the default `repository` for my `docker_build` somewhere in WORKSPACE or a top-level BUILD.bazel or similar. I always forget to change it to my private gcr.io docker repo unless I copy and paste the `docker_build` from elsewhere.

**Comment by mattmoor** [comment]
@damienmg Any guidance here?  Is there a way we could make this configurable in the `WORKSPACE`?  e.g. `docker_repositories(default_registry="gcr.io", default_repository="foo")`

Honestly, we internally default to `gcr.io` for registry, but I was trying to avoid that bias when I externalized the rules :)

**Comment by damienmg** [comment]
We could create a bzl file that contains those information generated from a remote repository rule and load it from docker_build.
