### ISSUE TITLE
Build smaller Go images when pure is true

### ISSUE THREAD

**Issue by ah-edg** [bazelbuild/rules_docker#649]
The default go base image should be `gcr.io/distroless/static` instead of `gcr.io/distroless/base` when pure is True.
It would be nice if rules_docker supported that by default.

See https://github.com/GoogleContainerTools/distroless/tree/master/base (which you probably already know very well).

**UPDATE** rereading this, it sounds incredibly condescending. I definitely didn't mean it that way. I'm very grateful for the work you do and I'd just like this to avoid setting different base images myself.

**Comment by nlopezgi** [comment]
hi @ah-edg,
Thanks for your comment. Most of the feature work for xx_image rules is based on community contributions atm.
I'd be happy to review a PR updating use of the default go image to use `gcr.io/distroless/static` instead of `gcr.io/distroless/base` when pure is True!

**Comment by nrvnrvn** [comment]
I ended up with this for a while.

In `WORKSPACE`:

```python
load("@io_bazel_rules_docker//container:container.bzl", "container_pull")

container_pull(
     name = "go_image_base_static",
     registry = "gcr.io",
     repository = "distroless/static",
     digest = "sha256:9b60270ec0991bc4f14bda475e8cae75594d8197d0ae58576ace84694aa75d7a",
 )
```

Sample `BUILD` file:

```python
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")
load("@io_bazel_rules_docker//go:image.bzl", "go_image")

# gazelle:prefix lol
gazelle(name = "gazelle")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "lol",
    visibility = ["//visibility:private"],
)

go_image(
    name = "lol",
    embed = [":go_default_library"],
    goos = "linux",  # sits here because of https://github.com/bazelbuild/rules_go/issues/2089
    base = "@go_image_base_static//image",
    visibility = ["//visibility:public"],
)
```

@ah-edg @nlopezgi if you still think it is useful to implicitly switch between `static` and `base` based on the _pure_-ness of the go binary let me know I will dig into it a bit deeper and come up with a PR.

BTW do you know what's the correct way of checking the pureness when `static`/`pure` flags are not set explicitly?

**Comment by nlopezgi** [comment]
thanks for sending the PR, to respond explicitly to your question: I do not know how to check the pureness if flags are not set explicitly
