### ISSUE TITLE
java_image - passing main arguments

### ISSUE THREAD

**Issue by adibrastegarnia** [bazelbuild/rules_docker#660]
Hello, 

I created an image using java_image but I would like to pass arguments to my main function (i.e. String args[]). How can I do that when I use "bazel run name_of_image" command? 

Thanks

**Comment by alex1545** [comment]
Hello @adibrastegarnia,

You can do that in the exact same way as you would in your `java_binary` target. The `java_image` target also allows you to specify `args`, which is the attribute you are looking for. For example, your `java_image` target would like something like:
```
java_image(
    name = "my_java_image",
    ...,
    args = ["arg1", "arg2"],
)
```
You can find out answers to similar questions in the main doc of this repo [here](https://github.com/bazelbuild/rules_docker#language-rules). More specifically, take a look at the [signature](https://docs.bazel.build/versions/master/be/java.html#java_binary) of `java_image`/`java_binary`.

**Comment by adibrastegarnia** [comment]
@alex1545 

I know about the signature but It is still not clear for me. args in java image specify the values or attributes? I am looking for a way to pass arguments when I run the image using bazel run.  
I found out it can be done like this: 
bazel run //your:rule -- arg1 arg2 ... argN

Do I still need to specify them in the args when I create the image?

**Comment by adibrastegarnia** [comment]
@alex1545 
It looks like it is not possible to change args during runtime. I was trying to run the same image but with different parameters . Is that possible?

**Comment by alex1545** [comment]
@adibrastegarnia, I'm sorry for your confusion.

The `args` attribute in a `java_image` target specify the parameters that are passed to your java binary. So in my example above, specifying `args = ["arg1", "arg2"]` in the target is similar to running the java command like so:
`$ java your_binary arg1 arg2`

Unfortunately, the option to pass those parameters via
`$ bazel run //path:java_image_target -- arg1 arg2`
is currently unsupported. The option that you discovered to pass those parameters to
`$ bazel run //path:java_binary_target`
only works for a `java_binary` target. So to run the same `java_image` target with different parameters, you would have to change your target definition to update the `args` attribute.

But if the functionality to pass the java parameters via
`$ bazel run //path:java_image_target -- arg1 arg2`
is very important for you, then you could contribute to implement that and we will lead you through the process as much as possible. However, implementing this change will be complicated.

**Comment by adibrastegarnia** [comment]
@alex1545 
Thanks for your response.  As you said the workaround for that is to define a new target with different parameters. It is not really important for me at this moment but that weakness does not allow to use the same image with different parameters.  I will let know if I decide to contribute in the project. Thanks for your offer.
