### ISSUE TITLE
container_image() cmd not working

### ISSUE THREAD

**Issue by dimitri88** [bazelbuild/rules_docker#668]
Hi,

I have a java_image and container_image set up like the following 
 
java_image(
    name = "java_server",
    base = ":java_base",
    main_class = "org.xxx.server",
    runtime_deps = [
        ":server_deps",
    ],
)
container_image(
    name = "java_base",
    base = "@java_image_base//image",
    directory = "/app",
    cmd = ["./app/xxx/run.sh"]
)

When I run `bazel run :java_server`, it seems like `cmd=['./app/xxx/run.sh']` is not being applied. Even if I use a random string on cmd, there is no error or warning. 
Am I using container_image wrong? Please help! 

Thanks!

**Comment by nlopezgi** [comment]
the java_image target adds an entrypoint that will mess up with the command (i.e., the command ends up being appended to the entrypoint iirc). You can probably try to do the opposite of what you have now (have the base be the java_image target and the container_image that sets the cmd use the java_image as base, and also set its entrypoint to empty string to override the value in the base java_image).
