### ISSUE TITLE
Support make variables in env field

### ISSUE THREAD

**Issue by syml** [bazelbuild/rules_docker#670]
I would like to specify some env vars at build time. Make variables are not currently supported in the env field.

**Comment by nlopezgi** [comment]
Hi @syml ,
Thanks for opening this issue.
Supporting make variables for the env field in container_image (and other related rules) should not be hard. We currently support this for, e.g., tags in the images attr of container_bundle (doc: https://github.com/bazelbuild/rules_docker#container_bundle-1 / impl of make variable substitution:
https://github.com/bazelbuild/rules_docker/blob/master/container/bundle.bzl#L46). It should be fairly straightforward to add code in image.bzl that does make variable substitution somewhere around here: https://github.com/bazelbuild/rules_docker/blob/master/container/image.bzl#L304 + adding tests somewhere around here: https://github.com/bazelbuild/rules_docker/blob/master/tests/docker/BUILD#L206. If you're willing to volunteer a PR I'd be happy to review it and guide you through any issues you have.
