### ISSUE TITLE
container_push targets are not robust to transient issues

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_docker#673]
Would you accept a PR for me to add retries here?

We're seeing flakiness when trying to push a lot of images concurrently:

https://testgrid.k8s.io/sig-testing-prow#push-prow

**Comment by nlopezgi** [comment]
hi @fetja,
do you have ideas about why the push is flaky (e.g. is it connection issues?) I think adding retries with proper exponential backoff and limits would be fine. But likely those changes will have to go to in  https://github.com/google/containerregistry. Let mr know if you want to pursue this to guide you how to send changes to that repo (the SoT for their code is in google3)

**Comment by fejta** [comment]
Click on any red cell in the testgrid link I gave above (https://testgrid.k8s.io/sig-testing-prow#push-prow&width=20) 

Most common is:

```console

/root/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/prow/release-push: line 116: wait: pid 17196 is not a child of this shell
```

**Comment by ixdy** [comment]
The particular failure @fejta linked
```
.../release-push: line 116: wait: pid 17196 is not a child of this shell
```

appears to be described by https://github.com/moby/moby/issues/36864#issuecomment-383824768 - basically, it is an issue in bash 4.3 when run in environments where the user process limit (`ulimit -u`) is set to `unlimited`, such as inside a docker container. Upgrading to bash 4.4 seems to resolve the issue.

https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1590001 offers a test script which replicates the problem easily under docker when using bash 4.3; I was not able to reproduce when using bash 4.4 under docker.

**Comment by ixdy** [comment]
and that failure is manifesting in the `contrib/push-all.sh.tpl` script:

https://github.com/bazelbuild/rules_docker/blob/7f61e98d7df54be9b2e0e4d46ec6ddf7f1b3ac0d/contrib/push-all.sh.tpl#L39-L44
