### ISSUE TITLE
Sort files in (tar) layers for reproducibility

### ISSUE THREAD

**Issue by chanseokoh** [bazelbuild/rules_docker#675]
Distroless wants to achieve "reproducibility" (https://github.com/GoogleContainerTools/distroless/issues/274). Seems like the list of entries in the (tar) layers generated by `container_image` should be sorted by name so that they are always in the same order no matter where the image is built.

However, to be perfect, I think you still need to preserve the order of "addition" for files with the same name (if this is applicable); tar allows having an infinite number of files with the same name. I'm not sure how `container_image` constructs a tar, but if it is not replacing a previous entry in a tar, sorting might end up bringing later entry before an earlier entry, I suppose. Or maybe it would be simpler without this minor issue if `container_image` just replaces an earlier entry so that a tar layer never has entries with the same name.

**Comment by nlopezgi** [comment]
Hi @chanseokoh, thanks for opening this issue. 
It makes sense to have entries in tar layers be ordered by name. Want to volunteer a PR to sort + add a test?
Overall the best thing to do if we want to achieve full reproducibility (and we also want to have it for the containers we produce) is to start by adding some tests that expose some of the use cases that you highlight (i.e., how are files ordered, and if repeated which one is picked). We can then move from there to decide if there are any other fixes that we need to implement. If you also want to volunteer to add tests to https://github.com/bazelbuild/rules_docker/blob/master/tests/docker/BUILD that would be super awesome?
