### ISSUE TITLE
Avoid having to specify the registry for container rules

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/rules_docker#683]
Even with this change, the registry where images should be pushed to need to be specified all over the place.

What about adding support for an environment variable? The generated run script can use the value from the rule as a default, have the env-var override it and fail with an error if none of them sets a registry. This won't affect build time, this only affects `bazel run //src/docker/foo.push`.

This would need changes here:
https://github.com/bazelbuild/rules_docker/blob/master/container/push.bzl#L102
to output the registry into a variable and here:
https://github.com/bazelbuild/rules_docker/blob/master/container/push-tag.sh.tpl
to check the variable + the env-var and do the error checking.

WDYT?

**Comment by ensonic** [comment]
Thanks for the quick reply! I'd like to avoid rebuilding because the envvar will not affect the build output.
After all this is bazel run, not build. If one wants to do:
```
CONTAINER_REGISTRY="eu.gcr.io/project" bazel run ...
CONTAINER_REGISTRY="gcr.io/project" bazel run ...
```
to push the images to 2 different registries, that's cool, right? This is important for us to avoid having to decouple project specific setting from the checked in code. Right now we tell people to generate a config.bzl from which we load the variable.

**Comment by nlopezgi** [comment]
With the make variable expansion alternative I propose you should be able to push to the two different registries in just the same way.
As you mention, there will be some rebuild time between the two runs, but it should be very very low as only the push targets would get rebuilt. 
I think while your proposal might yield better performance, the one I propose fits better with how other things are being done currently on these rules. Would it be a feasible path forward to first try out the make variable substitution alternative and if the performance of rebuilding is not cutting it for you we can think of performance improvements?

**Comment by ensonic** [comment]
I agree having the --define is a nice way forward. To be honest my concern is not so much performance, more strict separation of build and deploy settings.

**Comment by ensonic** [comment]
Please reopen. Not fixed.
