### ISSUE TITLE
Can you explain the magic of @docker_config?

### ISSUE THREAD

**Issue by shettich** [bazelbuild/rules_docker#689]
I'm getting build errors (that I did not get the last time I messed with this in Sept) about no package @docker_config//

I sort of thing this name is auto-generated when it sets up the toolchain, and that fails with no error if you don't have docker?  Is that right?

I'm trying to build minimal images without invoking docker, so I don't want (or need) docker installed.  Is that no longer an option?

**Comment by nlopezgi** [comment]
Hi @shettich ,
sorry to hear you are having issues.
Building images without needing access to the docker binary is still fully supported.
docker_config contain toolchain targets that allow the rules to properly access the docker binary (if it exists).
You are probably missing in your workspace a declaration like:
```
load("@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
    docker_toolchain_configure="toolchain_configure"
)
docker_toolchain_configure(
  name = "docker_config",
)
```
Please let me know if you are missing this in your WORKSPACE and adding it fixes the issue or if it still persists could you point me to some repro instructions?

**Comment by shettich** [comment]
Ah!  I thought that was optional.  Thanks.

**Comment by nlopezgi** [comment]
Thanks, the optional bit is the client_config, will clarify in the docs. Thanks for the feedback. Closing but please let me know if you run into other issues to re-open.
