### ISSUE TITLE
In ubuntu18.04, ERROR: ...no such package '@java_base//image': Pull command failed

### ISSUE THREAD

**Issue by Jiangyuna** [bazelbuild/rules_docker#705]
Environment:
ubuntu18.04  ; bazel-0.18.0 ;docker- 18.09.3

Problem description:
The Bazel and Docker are installed. When I input “bazel run //docker:layers_calculator”，I am getting an error

`ERROR: /home/jiangyuna/compass/docker/BUILD:3:1: no such package '@java_base//image': Pull command failed: E0304 04:30:07.223462   11514 retry_.py:106] Retrying after exception .
E0304 04:30:50.248965   11514 retry_.py:106] Retrying after exception .
F0304 04:31:34.271480   11514 __main__.py:127] Error pulling and saving image gcr.io/distroless/java@sha256:bb1c9179c2263733f235291998cb849d52fb730743125420cf4f97a362d6a6dd: 
 (/usr/bin/python /home/jiangyuna/.cache/bazel/_bazel_jiangyuna/fd9c9618bbf2a9b4eb3f232928ab16be/external/puller/file/downloaded --directory /home/jiangyuna/.cache/bazel/_bazel_jiangyuna/fd9c9618bbf2a9b4eb3f232928ab16be/external/java_base/image --name gcr.io/distroless/java@sha256:bb1c9179c2263733f235291998cb849d52fb730743125420cf4f97a362d6a6dd) and referenced by '//docker:layers_calculator'
ERROR: Analysis of target '//docker:layers_calculator' failed; build aborted: no such package '@java_base//image': Pull command failed: E0304 04:30:07.223462   11514 retry_.py:106] Retrying after exception .
E0304 04:30:50.248965   11514 retry_.py:106] Retrying after exception .
F0304 04:31:34.271480   11514 __main__.py:127] Error pulling and saving image gcr.io/distroless/java@sha256:bb1c9179c2263733f235291998cb849d52fb730743125420cf4f97a362d6a6dd: 
 (/usr/bin/python /home/jiangyuna/.cache/bazel/_bazel_jiangyuna/fd9c9618bbf2a9b4eb3f232928ab16be/external/puller/file/downloaded --directory /home/jiangyuna/.cache/bazel/_bazel_jiangyuna/fd9c9618bbf2a9b4eb3f232928ab16be/external/java_base/image --name gcr.io/distroless/java@sha256:bb1c9179c2263733f235291998cb849d52fb730743125420cf4f97a362d6a6dd)
INFO: Elapsed time: 129.411s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
`

**Comment by nlopezgi** [comment]
can you provide some repro instructions (i.e. what version of these rules are you pinnned to)? Also  you should try with a more recent version of Bazel (0.22 or 0.23). 0.18.0 is from some months ago and we only test with recent versions

**Comment by Jiangyuna** [comment]
I want to construct a Tangle based on the website of https://www.iotachina.com/private_tangle.html.
When I  install the LayerCalculator docker image via: bazel run //docker:layers_calculator, the error occurs. I have changed the version of Bazel, but there exist the same errors.

**Comment by Jiangyuna** [comment]
> can you provide some repro instructions (i.e. what version of these rules are you pinnned to)? Also you should try with a more recent version of Bazel (0.22 or 0.23). 0.18.0 is from some months ago and we only test with recent versions
I want to construct a Tangle based on the website of https://www.iotachina.com/private_tangle.html.
When I install the LayerCalculator docker image via: bazel run //docker:layers_calculator, the error occurs. I have changed the version of Bazel, but there exist the same errors.

**Comment by nlopezgi** [comment]
still need more details to be able to help you out. Can you paste here the contents of your WORKSPACE file (you should check the rules_docker import is at version 0.7.0 or close to that) , and possibly link to the code if it's on GitHub? the link you point to above seems to be in Chinese and I can't read it, and I'm not familiar with Tangle or the LayerCalculator

**Comment by Jiangyuna** [comment]
Sorry, I am not familiar with the Github.
 I just tell you what I have done on ubuntu18.04

Step1:Install Bazel
`sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
wget https://github.com/bazelbuild/bazel/releases/download/0.23.0/bazel-0.23.0-installer-linux-x86_64.sh
chmod +x bazel-0.23.0-installer-linux-x86_64.sh
./bazel-0.23.0-installer-linux-x86_64.sh --user`

Step2: Install Docker
`sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
sudo apt update
sudo apt install docker-ce`

Step3: Install jq
`sudo add-apt-repository universe
sudo apt install jq`

Step4: Clone the "compass" from Github
`git clone https://github.com/iotaledger/compass.git
cd compass`

Step5:Install the LayerCalculator docker image
`bazel run //docker:layers_calculator`

Then the error occurs.

Thanks for your help.

**Comment by nlopezgi** [comment]
I'll try to repro the environment too see why it's failing. on quick inspection, you're missing the auth setup (https://github.com/bazelbuild/rules_docker/blob/master/README.md#authentication). Try doing that and let me know if it still fails.

**Comment by Jiangyuna** [comment]
I have finished the auth setup, but the error still exist.

**Comment by Jiangyuna** [comment]
I have finished the auth setup, but it still fails.

**Comment by nweinthal** [comment]
Having the same issue:

BUILD:23:1: no such package '@java_image_base//image': Pull command failed

Still double checking all my settings

**Comment by nweinthal** [comment]
At least in my case it seemed to be an underlying issue with the system python being python 3 but something needed by puller being python2 only.  Maybe the action item here is that the "no such package" error message here is actually misleading and seems to be a catchall for underlying exceptions?

**Comment by nlopezgi** [comment]
thanks for debugging! 
these rules do need a python2 installed and if it's not in the path the location must be passed explicitly (see https://github.com/bazelbuild/rules_docker/blob/master/python/BUILD). Lets keep this issue open for now to improve error messaging.

**Comment by smukherj1** [comment]
I tried running the bazel run //docker:layers_calculator command in a container built using the original instructions (Dockerfile attached)
[Dockerfile.tar.gz](https://github.com/bazelbuild/rules_docker/files/2953752/Dockerfile.tar.gz)

but I get a different error
```
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Option.process(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(Unknown Source)
        at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Caused by: java.nio.file.NoSuchFileException: external/local_jdk
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.isSameFile(Unknown Source)
        at java.base/java.nio.file.Files.isSameFile(Unknown Source)
        ... 15 more
Target //docker:layers_calculator failed to build
```

However, @java_base//image built successfully which means the image was pulled successfully. Also, the java_base image is gcr.io/distroless/java which is a public image and shouldn't need authentication setup. I tried doing a docker pull on this image without any authentication setup in my container and it worked. So authentication isn't the issue here.

**Comment by nlopezgi** [comment]
@smukherj1, i think as @nweinthal mentioned this issue is likely related to not finding python 2 but instead pyhton 3 on the path. What we likely need to do is add a verification in container_pull that checks the python found on path is indeed py2 or otherwise fail with a nice message.

**Comment by nlopezgi** [comment]
(closed by mistake, reopened)

**Comment by xiaocaipi** [comment]
I also have this problem ,which error below:
ERROR: Analysis of target '//docker:layers_calculator' failed; build aborted: no such package '@java_base//image': Pull command failed: F0401 15:39:02.580904   25691 __main__.py:127] Error pulling and saving image gcr.io/distroless/java@sha256:bb1c9179c2263733f235291998cb849d52fb730743125420cf4f97a362d6a6dd: hostname 'gcr.io' doesn't match either of '*

**Comment by SidZhangCN** [comment]
The same problem.
My error:
ERROR: Analysis of target '//docker:layers_calculator' failed; build aborted: no such package '@java_base//image': Pull command failed: F0404 16:18:37.846494    3673 __main__.py:127] Error pulling and saving image gcr.io/distroless/java@sha256:bb1c9179c2263733f235291998cb849d52fb730743125420cf4f97a362d6a6dd: Unable to find the server at gcr.io
 (/usr/bin/python /home/zxd/.cache/bazel/_bazel_zxd/821a953e25ca85474d872e5286daafe4/external/puller/file/downloaded --directory /home/zxd/.cache/bazel/_bazel_zxd/821a953e25ca85474d872e5286daafe4/external/java_base/image --name gcr.io/distroless/java@sha256:bb1c9179c2263733f235291998cb849d52fb730743125420cf4f97a362d6a6dd)

**Comment by sanjayzzzhong** [comment]
@Jiangyuna @surlyengineer @xiaocaipi @nlopezgi @smukherj1 
Try this:
`cd compass` and modify the file named `WORKSPACE`
```shell
container_pull(
    name = "java_base",
    digest =
        "sha256:bb1c9179c2263733f235291998cb849d52fb730743125420cf4f97a362d6a6dd",
    registry = "gcr.io",
    repository = "distroless/java",
)
```
to 
```shell
 container_pull(
     name = "java_base",
     registry = "index.docker.io",
     repository = "anjia0532/distroless.java",
     tag = "latest"
  )
```
That says we use the repository in dockerhub instead of google cloud.
The related link of this image is https://hub.docker.com/r/anjia0532/distroless.java/tags/ 
What's more, the explanation of changes can be referenced by this link [the gramma of container_pull](https://github.com/bazelbuild/rules_docker#container_pull)
Hope it works! :smile_cat:
