### ISSUE TITLE
Wrong image digest pulled for google-containers/debian-iptables

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_docker#714]
With the latest HEAD, I get strange behavior when pulling debian-iptables:

WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_bazel_rules_docker",
    commit = "b167423d6bcc0ee69e021432d8fc4ab7305b6649",
    remote = "https://github.com/bazelbuild/rules_docker",
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "iptables_base",
    digest = "sha256:cd81b1a8f40149b5061735927d2a2cf4b90fc27a52fc4cc66889b373368b6ef6",
    registry = "gcr.io",
    repository = "google-containers/debian-iptables",
)
```

Note the SHA256 for iptables_base: cd81b1...

```
> bazel build @iptables_base//image:all
DEBUG: Rule 'io_bazel_rules_docker' modified arguments {"shallow_since": "1551974828 -0500"}
DEBUG: Rule 'iptables_base' modified arguments {"digest": "sha256:d4ff8136b9037694a3165a7fff6a91e7fc828741b8ea1eda226d4d9ea5d23abb"}
INFO: Analysed target @iptables_base//image:image (26 packages loaded, 247 targets configured).
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to '/tmp/explain.log'
Target @iptables_base//image:image up-to-date:
  bazel-bin/external/iptables_base/image/image.tar
INFO: Elapsed time: 6.570s, Critical Path: 1.64s
INFO: 9 processes: 9 linux-sandbox.
> cat bazel-*/../../external/iptables_base/image/image.digest       
sha256:d4ff8136b9037694a3165a7fff6a91e7fc828741b8ea1eda226d4d9ea5d23abb
```

For some reason, it has pulled a different image than desired, as seen in `DEBUG: Rule 'iptables_base' modified arguments {"digest": "sha256:d4ff81...` and the content of `image.digest`.

**Comment by nlopezgi** [comment]
does this repro with a file_test similar to the one we added in https://github.com/bazelbuild/rules_docker/commit/b167423d6bcc0ee69e021432d8fc4ab7305b6649.
is this working with 0.7.0 or another commit before head?

**Comment by drigz** [comment]
> is this working with 0.7.0 or another commit before head?

Fails with 0.7.0.

> does this repro with a file_test similar to the one we added in b167423.

Yes:

```
INFO: From Testing //tests/docker:iptables_base_digest_test:
==================== Test output for //tests/docker:iptables_base_digest_test:
--- tests/docker/iptables_base_digest_test.dat  2019-03-08 08:06:43.753621310 +0000
+++ ../google_containers_debian_iptables/image/digest   2019-03-08 08:03:32.525809896 +0000
@@ -1 +1 @@
-sha256:cd81b1a8f40149b5061735927d2a2cf4b90fc27a52fc4cc66889b373368b6ef6
\ No newline at end of file
+sha256:d4ff8136b9037694a3165a7fff6a91e7fc828741b8ea1eda226d4d9ea5d23abb
\ No newline at end of file
================================================================================
```

[rules_docker-714-repro.patch.txt](https://github.com/bazelbuild/rules_docker/files/2944884/rules_docker-714-repro.patch.txt)

**Comment by nlopezgi** [comment]
thanks for the additional info. will debug and let you know what we find.

**Comment by drigz** [comment]
@nlopezgi Any update on this? Pulling an older version of a base image could have severe security implications, and the debug output that points to the problem is unlikely to be noticed.

**Comment by alex1545** [comment]
I was able to reproduce this issue.
In rules_docker we use [containerregistry](https://github.com/google/containerregistry) for the actual interaction with a Docker registry. After some investigation, it looks that it's the [fast_puller_.py](https://github.com/google/containerregistry/blob/master/tools/fast_puller_.py) that is pulling the wrong image. I will now look further into that to see where the failure comes from.

**Comment by alex1545** [comment]
@drigz, the image you are pinning to with `sha256:cd81b1a8f40149b5061735927d2a2cf4b90fc27a52fc4cc66889b373368b6ef6` is a special type of image that acts as a collection of pointers to actual Docker images. When pulling that image, you get an image from the `manifests` list that matches your platform.

See google/containerregistry#145 for the original reply in [containerregistry](https://github.com/google/containerregistry).

To avoid the behavior you described, you should pin directly to `sha256:d4ff8136b9037694a3165a7fff6a91e7fc828741b8ea1eda226d4d9ea5d23abb`.

**Comment by drigz** [comment]
@alex1545 Thanks for the investigation and explanation! Do you think it would make sense for `container_pull` to warn or error out when it points at a manifest list, since it doesn't have the information to pull an image in a hermetic fashion?

**Comment by alex1545** [comment]
IMO, `container_pull` should definitely not error out when it points at a manifest list. The ability to point at the manifest list which determines the container to pull based on platform seems like handy feature and may be useful to others. So producing an error for such images will simply block from using this "auto-resolution" feature.

As for providing a warning for such images, I think the DEBUG message
```
DEBUG: Rule 'iptables_base' modified arguments {"digest": "sha256:d4ff8136b9037694a3165a7fff6a91e7fc828741b8ea1eda226d4d9ea5d23abb"}
```
is good enough. After all, the user of `container_pull` should be aware of the image type being described in the target. 

Maybe I misunderstood your point about pulling an image in a hermetic way, but in either case (whether you pin to manifest list or manifest) `container_pull` performs a non-hermetic operation by pulling any image from outside (the internet).

**Comment by drigz** [comment]
> Maybe I misunderstood your point about pulling an image in a hermetic way, but in either case (whether you pin to manifest list or manifest) container_pull performs a non-hermetic operation by pulling any image from outside (the internet).

My concern was based on a mistake assumption: I thought `fast_puller_.py` would pull the image that matches the platform on which it runs, so even if you specify `digest`, the result would depend on the host platform. However, it defaults to linux/amd64 ([source](https://github.com/google/containerregistry/blob/5b4a2cd1adeb4cc04cd30b89490f8748f407665e/client/v2_2/docker_image_list_.py#L156)), so the result doesn't depend on the host platform.

However, one concern remains: container_pull doesn't verify that the image pulled matches the digest provided by the user. This differs from the `http_archive` rule, which fails if the digest doesn't match the archive it downloads. This was very surprising to me, although given what I know now, the severity is low. At worst, a bug in fast_puller or the container registry (or arguably, a malicious container registry) could lead to the build using the wrong image without the user noticing.

**Comment by drigz** [comment]
Thanks! Hope it doesn't break too many people...

**Comment by alex1545** [comment]
Maybe it will even help some people discover that they had pins pointing at a manifest list.

**Comment by Globegitter** [comment]
I am just running into this issue and it would be nice to have a mention in the readme (or even better in the error message) on how to get the correct sha. I though running `docker inspect --format='{{index .RepoDigests}}' image:tag` would give me the correct sha but that does not seem to be the case.

**Comment by drigz** [comment]
Does the error message say something like `"Expected {}, but pulled image with {}.`? If you copy the second SHA, you should get the previous behavior back.

**Comment by Globegitter** [comment]
`docker manifest inspect nginx:1.15.9-alpine` did indeed do the trick.
