### ISSUE TITLE
Cannot run image locally on macOS: command not found.

### ISSUE THREAD

**Issue by dgarzon** [bazelbuild/rules_docker#736]
Hi,

When running images on `macOS 10.14.3`, I am getting `line 202: : command not found`. This worked for me on High Sierra, but after updating it broke. After debugging, I see that the `DOCKER` variable is not being set, and thus the script fails to run any command against Docker. Interestingly, on line 34 I see the following `DOCKER=""`, and then nothing sets it back to an executable binary. 

Steps to reproduce:
1. Launch and wait for `docker`
2. `bazel run //project:image`
3. `line 202: : command not found`

Has anyone ran into a similar issue? I made sure I have `docker`, `tar` and `tee` in my `PATH`, so the binaries are available, but the script is not picking the `docker` one. 

Thanks in advanced!

**Comment by nlopezgi** [comment]
depending on which version of bazel you are using, you might need to pass an extra flag for Bazel to pick up tools in the path (--action_env=PATH). You can also explicitly set the path of docker (example:
https://github.com/bazelbuild/rules_docker/blob/master/WORKSPACE#L22)

**Comment by robfig** [comment]
I'm running into this same issue on MacOS Mojave 10.14.3, trying to "bazel run" targets that work on my High Sierra machine. 

I have Docker for Mac installed via their download page and it's accessible:
```
$ which docker 
/usr/local/bin/docker
```

I tried specifying action_env 

```
bazel run --action_env=PATH ...
bazel run --action_env=PATH=/bin:/usr/bin/:/usr/local/bin ...
```
and explicitly configuring docker_toolchain
```
load(
    "@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
    docker_toolchain_configure = "toolchain_configure",
)

docker_toolchain_configure(
    name = "docker_config",
    docker_path = "/usr/local/bin/docker",
)
```

... but neither made a difference. 

```
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Analysed target //cmd/server:image (2 packages loaded, 6882 targets configured).
INFO: Found 1 target...
Target //cmd/server:image up-to-date:
  bazel-bin/cmd/server/image-layer.tar
INFO: Elapsed time: 2.683s, Critical Path: 1.35s
INFO: 6 processes: 6 darwin-sandbox.
INFO: Build completed successfully, 9 total actions
INFO: Build completed successfully, 9 total actions
/private/var/tmp/.../image: line 202: : command not found
```

I see the same thing, of DOCKER="" never being overridden in the generated script.

**Comment by nlopezgi** [comment]
please note the `docker_config` target must be placed in your WORKSPACE before the call to `container_repositories`, otherwise [this](https://github.com/bazelbuild/rules_docker/blob/master/repositories/repositories.bzl#L219) declaration might take precedence.
If that does not solve the issue for you, can you run a build with `--toolchain_resolution_debug` and paste the output here to see what else might have gone wrong?

**Comment by robfig** [comment]
Ah, moving it ahead of `container_repositories` was the trick. Thank you!

**Comment by nlopezgi** [comment]
thanks for reporting back that fixed it!
