### ISSUE TITLE
py_image does not run if locally-built base image is specified

### ISSUE THREAD

**Issue by emempi** [bazelbuild/rules_docker#739]
Note: There might be a correlation with #728, but reporting separately, since this manifests using python rules.

I'm trying to use bazel run to execute my py_image target. If I don't specify the base (or use the default `@py_image_base//image`), the image runs fine. However, if specify a custom-built base image, even the dummy version like

```
container_image(
    name = "python_dummy_image",
    base = "@py_image_base//image",
)
```

won't run. Then the docker container is built correctly, but bazel won't launch it. I tried `docker run <image id>`, and it ran without any problems.

**Comment by emempi** [comment]
I was able to work around this by changing `container/image.bzl`(https://github.com/bazelbuild/rules_docker/blob/db6d42869d376a7cd4f3260bc26d20d695cebc0d/container/image.bzl#L480) -- I flipped the default value of `legacy_run_behavior` to `False`, as indicated by the TODO note one line above.

**Comment by jschaf** [comment]
I can repro for `go_image`:

```
git clone https://github.com/jschaf/bazel-docker-runnable.git
cd bazel-docker-runnable

# Outputs 'Hello, world!' from container running
bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 :server_image_runnable

# No output, container is not run.
bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 :server_image_not_runnable

# Outputs 'Hello, world!' from container
bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 :server_image_workaround
```

The workaround that worked was setting `legacy_run_behavior` on the container_image **not** the go_image:

```
container_image(
    name = "go_base_image_workaround",
    base = GO_DEFAULT_BASE,
    ports = ["8181"],
    legacy_run_behavior = False,
)

go_image(
    name = "server_image_workaround",
    binary = ":server",
    base = ":go_base_image_workaround",
)
```

**Comment by xingao267** [comment]
I think this is intended behavior. You can set `legacy_run_behavior` attr to `False` in the `container_image` target if you are sure the entrypoint or cmd is correctly set for the `container_image` target. But I don't think we are ready to default `legacy_run_behavior` for `container_image` to `False`. For other `lang_image`s, e.g. `go_image`, `python_image`, this attr is default to `True` because the rule makes the entrypoint and cmd is set correctly and can be safely run with in a single `bazel run` command.

**Comment by xingao267** [comment]
See also https://github.com/bazelbuild/rules_docker/pull/584 which attempted to flip the default value of `legacy_run_behavior` for container_image to True.

**Comment by jschaf** [comment]
What does `legacy_run_behavior` mean?  My mental model is:

`legacy_run_behavior` | `bazel run` behavior
-----------|-----------
True | The docker container is not run.
False | The docker container is run.
 
> You can set legacy_run_behavior attr to False in the container_image if you are sure the entrypoint or cmd is correctly set for the container_image target. [...] For other lang_images, e.g. go_image, python_image, this attr is default to True because the rules make sure the entrypoint and cmd is set correctly and can be safely run with in a single bazel run command.

In the following example, I'm using `go_image` with a custom `base`. Why do I have to specify `legacy_run_behavior = False` in the base image?  If `go_image` guarantees `cmd` is set correctly, then it should be safe to set to False, right?

```
container_image(
    name = "go_base_image_workaround",
    base = GO_DEFAULT_BASE,
    ports = ["8181"],
    legacy_run_behavior = False,
)

go_image(
    name = "server_image_workaround",
    binary = ":server",
    base = ":go_base_image_workaround",
)
```

> For other lang_images, e.g. go_image, python_image, this attr is default to True

Which attr is set to True? `legacy_run_behavior`?  I thought it needed to be False to get it to run with `bazel run`?

**Comment by xingao267** [comment]
"Why do I have to specify legacy_run_behavior = False in the base image? If go_image guarantees cmd is set correctly, then it should be safe to set to False, right?"

Yes. You shouldn't need to specify `legacy_run_behavior` to False in the base image. I just fixed that in https://github.com/bazelbuild/rules_docker/pull/769. Can you try it?

"Which attr is set to True? legacy_run_behavior? I thought it needed to be False to get it to run with bazel run?"
Sorry. That was a mistake. I meant it's default to `False`.

**Comment by jschaf** [comment]
>  I just fixed that in #769. Can you try it?

Thanks! Verified that it works.

From #769 docs:

> `docker_run_flags`: Only used when `legacy_run_behavior` is set to `False`.

Might be worth a mention that `legacy_run_behavior` is set to False with using $LANG_image rules.

**Comment by xingao267** [comment]
Sent https://github.com/bazelbuild/rules_docker/pull/773 to add more doc for lang_image rules.

**Comment by xingao267** [comment]
#773 addresses the documentation comments.
