### ISSUE TITLE
Please update the version of httplib2

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_docker#754]
httplib2 0.11.3 is not capable of picking of system-wide CA bundle changes, which in practice will cause SSL verification failures if the registry is presenting a cert signed by an unsupported CA (including custom ones).

Before #580 is implemented, we should consider updating httplib2 to at least 0.12.0 to load CA bundle in a smarter way (see https://github.com/httplib2/httplib2/issues/2#issuecomment-451422731).

**Comment by alex1545** [comment]
Hi @ashi009 and thank you for bringing this up.
You can go ahead and send a PR to update [this target](https://github.com/bazelbuild/rules_docker/blob/57b687825ace86e3de364b9afb8a66f736c2bd2f/repositories/repositories.bzl#L102) and I will be happy to review it.
