### ISSUE TITLE
container_pull incompatible with quay.io

### ISSUE THREAD

**Issue by dicarlo2** [bazelbuild/rules_docker#765]
Every image that we use from quay.io appears to be failing due to https://github.com/bazelbuild/rules_docker/pull/734. Switching the digest to the one output by the error message doesn't help. Here are some example images and digests to try:

```
container_pull(
    name = "kube-state-metrics",
    registry = "quay.io",
    repository = "coreos/kube-state-metrics",
    # 01/14
    # digest = "sha256:955b57c68705a57290f6e34b00e40ee7ec33e0138d39bf0b8759f7a2f709e70b",
    tag = "v1.5.0",
)

container_pull(
    name = "prometheus",
    registry = "quay.io",
    repository = "prometheus/prometheus",
    # 02/01
    # digest = "sha256:1da427c5ffd5f365c975da80c262c791a3946739f1c2e26afec9a40fa00e0bbf",
    tag = "v2.7.2",
)

container_pull(
    name = "alertmanager",
    registry = "quay.io",
    repository = "prometheus/alertmanager",
    # 02/01
    # digest = "sha256:ebac08af1fbe49fa0dd52939762481a3660e17839d2098fd5ecf292060279219",
    tag = "v0.16.1",
)
```

The commented out `digest` is the one that's reported by the error message.

`docker manifest` also doesn't seem to help, e.g.:

```
$ docker manifest inspect quay.io/coreos/kube-state-metrics:v1.5.0
unsupported manifest media type and no default available: application/vnd.docker.distribution.manifest.v1+prettyjws
```

**Comment by dicarlo2** [comment]
rules_docker configuration:

```
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "ce53700205ed4312970641b94d8bbf3c92e4bab8216ef0ce575cfc4d2eedba7c",
    strip_prefix = "rules_docker-4ccc5359b620dc2669845cc1782429956298969b",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/4ccc5359b620dc2669845cc1782429956298969b.tar.gz"],
)
```

**Comment by xingao267** [comment]
@alex1545 will take a look.

**Comment by xingao267** [comment]
Also from what I heard, quay.io is still using Image V2 schema 1 which is legacy image registry format, and they are migrating to Image V2 Schema 2.

**Comment by alex1545** [comment]
Hi @dicarlo2, your issue is indeed coming from quay.io still using manifest v2 schema 1 format for some of its repositories. Check [this issue](https://github.com/google/containerregistry/issues/148) that I opened for more details.

That being said, your only solution for now is to pull by a tag in your `container_pull` targets and not to expect the image sha256 match anything.

**Comment by dicarlo2** [comment]
@alex1545 I see, thanks for looking into it!
