### ISSUE TITLE
Expose ports on MacOS manually because --network=host isn't supported

### ISSUE THREAD

**Issue by jschaf** [bazelbuild/rules_docker#768]
Docker for MacOS doesn't support `--network=host`: https://docs.docker.com/network/host/

What do you think about emulating this feature by binding ports using the `--publish` flag instead?

    docker run --publish 8080:8080

One way to implement is similar to #312, with a check for MacOS.

**Comment by xingao267** [comment]
Hi @jschaf, I'm not an expect in network. From a quick Google search. --publish should work but it's just mapping port 8080 between the host and container while --network=host maps all the ports? Will you be able to get around it by just manually specifying the --publish <xxxx>:<xxxx> for the ports you want to bind using the `docker_run_flags` in `container_image`?

**Comment by jschaf** [comment]
> Will you be able to get around it by just manually specifying the --publish : for the ports you want to bind using the docker_run_flags in container_image?

Yes, that works for me.

The problem is that the behavior of `$LANG_image` varies dramatically between Linux and MacOS.  Within Google, it's probably not a huge deal since everyone develops gLinux.  On a Mac, using docker rules is much more involved.

On a MacOS:

`bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 :server_image_macos`

```
container_image(
    name = "go_base_image_macos",
    base = GO_DEFAULT_BASE,
    ports = ["8181"],
    legacy_run_behavior = False,
    docker_run_flags = "-i --publish=8181:8181
)

# Also, must 
go_image(
    name = "server_image_macos",
    binary = ":server",
    base = ":go_base_image_macos",
)
```

Whereas, with Linux, you have the much simpler:

`bazel run :server_image_linux`

```
go_image(
    name = "server_image_linux",
    binary = ":server",
)
```

**Comment by jschaf** [comment]
> --network=host maps all the ports

Since bazel knows the ports at build time, it can emulate exposing all the ports by including them in the `--publish` flag.

**Comment by xingao267** [comment]
Yea. I think at this moment, we have to get around it by having a separate container_image target + go_image + adding all ports to --publish in the container_image target. The container_image target is kind of unavoidable because we need to specify the list of ports there as MacOS doesn't support --network=host.
