### ISSUE TITLE
docker_repositories() fails if user's workspace already contains "subpar"

### ISSUE THREAD

**Issue by dmitry-xnor** [bazelbuild/rules_docker#77]
We use `subpar` for packaging Python. When trying to introduce Docker support using WORKSPACE file (following the example in README.md), I get the following:

```
	File "/home/dmitryb/.cache/bazel/_bazel_dmitryb/8e618220280fa417619d9462a0a41d8d/external/io_bazel_rules_docker/docker/docker.bzl", line 128, in docker_repositories
		native.git_repository(name = "subpar", remote = "https:/...", ...")
Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'subpar').
ERROR: Error evaluating WORKSPACE file.
ERROR: error loading package 'external': Package 'external' contains errors.
```
Seems like you're loading `subpar` as a part of docker_repositories(), and it's conflicting with the existing `subpar` target we already have.

Maybe namespacing it in some way (e.g. `rules_docker_subpar`) could prevent this?

**Comment by promiseofcake** [comment]
Related: https://github.com/bazelbuild/rules_docker/issues/55

**Comment by mattmoor** [comment]
Yeah I think #55 is what we want, I just haven't had a moment to do it amidst some improvements I've been working on.  If the workaround in #55 doesn't work for you, then I'll try to TAL at it sooner than later.
