### ISSUE TITLE
Ability to add healthcheck

### ISSUE THREAD

**Issue by dgarzon** [bazelbuild/rules_docker#770]
Hi, is there a way to add a healthcheck to a `container_image` or any of the language rules?

**Comment by xingao267** [comment]
HI @dgarzon what kind of health check would you like?

**Comment by dgarzon** [comment]
Hi @xingao267, we are running a web-server on a `scala_image` and we would like to check that hitting an endpoint yields `20X` when `curl`'d. Any ideas? Thanks in advanced!

**Comment by xingao267** [comment]
Sorry, I'm not sure I understand it. Could you expand a little more?

**Comment by dgarzon** [comment]
I would like to do this: https://docs.docker.com/engine/reference/builder/#healthcheck, it is a deterministic operation, so it should be totally compatible with Bazel.

**Comment by alex1545** [comment]
Hi @dgarzon, in order for us to determine whether or not we will be able to add a healthcheck to any of the image rules, we need to know how the healthcheck is being set once the image is built from a Dockerfile with a `HEALTHCHECK` instruction. I.e., does it add/modify any files in any of the image layres? Or maybe it sets any special fields in the manifest.json file?
Are you able to help answer this question or maybe explore this if needed?

**Comment by dgarzon** [comment]
Hi @alex1545 , after looking at https://github.com/docker/docker-ce/blob/8a582e89b407639018e067123eb17f61dbfd10ee/components/engine/daemon/health_test.go, I believe `HEALTHCHECK` only adds an entry to the `manifest.json` file with certain fields. Does this help?

**Comment by alex1545** [comment]
Hi @dgarzon, this is definitely useful information, but certainly not enough. Can you investigate further with more details?
If `HEALTHCHECK` only adds an entry to the `manifest.json` file, then can you find out the exact entry being added and its format? Can you verify that modifying the `manifest.json` is all that's needed and possibly share an example of a `manifest.json` file with and without the healthcheck entry that can be used with the same image?

**Comment by dgarzon** [comment]
@alex1545 I did some more research. Adding a `HEALTHCHECK` to a `Dockerfile`, does not add any entry to the `manifest.json`, and rather it adds to `config.json`. Here are some examples:

1. User defines `HEALTHCHECK NONE`:
```
{
    ...
    "config": {
        ...
        "Healthcheck": {
            "Test": [
                "NONE"
            ]
        }
    }
}
```

2. User defines `HEALTHCHECK CMD curl --fail http://localhost:5000 || exit 1`:
```
{
    ...
    "config": {
        ...
        "Healthcheck": {
            "Test": [
                "CMD-SHELL",
                "curl --fail http://localhost:5000/ || exit 1"
            ]
        }
    }
}
```

3. User defines `HEALTHCHECK --interval=30s --timeout=30s --start-period=1s --retries=3 CMD curl --fail http://localhost:5000/ || exit 1`:
```
{
    ...
    "config": {
        ...
        "Healthcheck": {
            "Test": [
                "CMD-SHELL",
                "curl --fail http://localhost:5000/ || exit 1"
            ],
            "Interval": 30000000000,
            "Timeout": 30000000000,
            "StartPeriod": 1000000000,
            "Retries": 3
        }
    }
}
```

From my research, I think I would need to modify https://github.com/bazelbuild/rules_docker/blob/master/container/image.bzl to add a new arg for `healthcheck`, like this:

```
healthcheck = {
    test = "NONE" || "curl --fail http://localhost:5000/ || exit 1",
    interval: 30s
    timeout: 30s
    retries: 3
    start_period: 1s
}
``` 

And then, modify https://github.com/bazelbuild/rules_docker/blob/master/container/create_image_config.py to take the healthcheck dictionary as input and do the right modifications to append it to the `config.json` for the base image.

Does this make sense to you? If so I can work on this over the weekend no problem!

**Comment by alex1545** [comment]
Hi @dgarzon 
I'm sorry for this very delayed reply. I definitely missed this after coming back from vacation.
Thank you for the additional research and the details you provided. And yes, that makes sense. Are you still interested in contributing to implement this feature?

**Comment by dgarzon** [comment]
Hi @alex1545 , no worries! I would still like to implement this feature. I will work on it over the weekend and should have a PR by then. Thank you for going over my proposal  👍
