### ISSUE TITLE
FR: Support aliasing the resulting image in docker_build

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_docker#8]
This is a fork of the discussion in https://github.com/bazelbuild/bazel/issues/616 that is intended to capture the desire for a `docker_build` kwarg for tagging the resulting image.

**Comment by mattmoor** [comment]
@linuxerwant @damienmg FYI

**Comment by mattmoor** [comment]
@linuxerwang To unblock yourself consider defining:
```
docker.bzl:

load("//tools/build_defs/docker:docker.bzl", docker_build_ = "docker_build", "docker_bundle")

def docker_build(name=None, tag=None, **kwargs):
    docker_build_(name=name + '-internal', **kwargs)
    docker_bundle(name=name, images={
      tag: ':' + name + '-internal'
    })
```
... and importing that instead of the standard `docker.bzl`.  We do this internally to augment the `docker_build` functionality in certain ways.

**Comment by linuxerwang** [comment]
Thanks, @mattmoor. I verified that the following target works well with the above workaround:

docker_build(
    name = "storm",
    # image_name = "storm/storm",
    tag = "storm/storm",
    # ...
)

**Comment by mattmoor** [comment]
You should now be able to switch to loading `docker_build` from: `@io_bazel_rules_docker//docker/contrib:with-tag.bzl`
