### ISSUE TITLE
Tide and GitHub merge requirements don't match

### ISSUE THREAD

**Issue by michelle192837** [bazelbuild/rules_docker#852]
Hi! Noticed that Tide is continually failing to merge PR 851 (https://github.com/bazelbuild/rules_docker/pull/851), as seen on Tide history (https://prow.k8s.io/tide-history?repo=bazelbuild%2Frules_docker):

failed merging [851]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? 3 of 3 required status checks are expected.]

Someone should update the GitHub settings for the repo to match Tide requirements, after which it should be fine to remove the hold label from the PR and let it merge.

**Comment by nlopezgi** [comment]
We are no longer using Tide. Closing.
