### ISSUE TITLE
Bad mktemp syntax on Mac OS

### ISSUE THREAD

**Issue by ohler** [bazelbuild/rules_docker#86]
On Mac OS X, running a docker_build rule with `bazel run` gives me
```
mktemp: option requires an argument -- t
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
```

I'm guessing this comes from https://github.com/bazelbuild/rules_docker/blob/48a438c543a44f2cedc4087422a3e9ea3fd7c333/docker/incremental_load.sh.tpl#L42-L43 .

What was the "review feedback" in 3042c969b61051e7b1bca16f2d240528d469b14f ?  https://linux.die.net/man/1/mktemp suggests that `-t` is deprecated.

**Comment by cwoodcock** [comment]
Just raised a PR with a fix for this... https://github.com/bazelbuild/rules_docker/pull/87

Not sure if it's the desired approach by the maintainers but IWFM.

**Comment by mattmoor** [comment]
Hmm, @damienmg gave the feedback, so perhaps it was my bug incorporating it.

thanks for the PR.

**Comment by damienmg** [comment]
The -t requires an argument, sorry I should have been clearer in my review.
-t is required for earlier version of macOS.

**Comment by mattmoor** [comment]
I believe this has been fixed.
