### ISSUE TITLE
The GitHub merge requirements do not match the Tide configuration for this repo.

### ISSUE THREAD

**Issue by cjwagner** [bazelbuild/rules_docker#862]
PR #859 cannot be merged because the GitHub settings do not match the tide configuration. When Tide tries to merge this PR it gets an error from GitHub "3 of 3 required status checks are expected." 
The Tide history shows that Tide is stuck trying to merge this PR in a loop which wastes API tokens and prevents other PRs in the repo from being merged. https://prow.k8s.io/tide-history?repo=bazelbuild%2Frules_docker&branch=master
I'm not sure what GitHub setting is making this PR unmergeable since I can't see the settings myself and it looks like all 3 required status checks are present, but something must be inconsistent between the Tide config and GitHub merge requirement settings. Please align these requirements so that Tide doesn't try to merge unmergeable PRs.

**Comment by nlopezgi** [comment]
@smukherj1 fyi

**Comment by smukherj1** [comment]
@nlopezgi @cjwagner Tide is unable to merge this because we have the branch protection setting that requires the pull request source branch to be up to date for it to be mergeable. This is a known issue but this pull request is an example where we accidentally got a pull request in a state where this issue happens but we didn't realize it because we got no indication from prow/tide that it is stuck in this loop.

We are working on a pull request automation utility and I think we can add a feature to that utility that looks for pull requests that are approved but have an out of date source branch. If so, it can automatically add "hold" to those pull requests so that tide doesn't get into the infinite loop. Once the pull request is updated by merging the latest changes from master, this utility can come in and remove the "hold" label.

**Comment by cjwagner** [comment]
Whoops, I meant to comment on this issue not the PR.

See number 5 here: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/maintainers.md#best-practices

Repos that are managed by Tide should not require that pull request branches are up to date. Tide provides the exact same testing guarantees in a more intelligent way so that PR authors are not required to update their PR branches when the base branch is updated. This is achieved by tracking the base branch commit SHA that presubmit tests are run against and rerunning tests if the base branch commit SHA changes.

**Comment by smukherj1** [comment]
Regarding

> but Tide already provides this guarantee through a more sophisticated mechanism that does not force PR authors to rebase their PR whenever another PR merges first

from point 5 [here](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/maintainers.md#best-practices), this mechanism only comes into play when the CI used to run the tests is prow. Our repo uses other CI systems like buildkite, travis and Google Cloud Build to run presubmit checks on our PRs. However, tide/prow is unable to ensure the tests pass at HEAD on these systems prior to merging.

**Comment by cjwagner** [comment]
> Our repo uses other CI systems like buildkite, travis and Google Cloud Build to run presubmit checks on our PRs. 

Ah, I didn't notice that, good point. Switching to using ProwJobs might be worth considering. That would allow PRs to merge consecutively without requiring PR authors to rebase their PRs.

**Comment by cjwagner** [comment]
This repo is still causing Tide errors and wasting our API ratelimit. Please address this as soon as possible.
https://prow.k8s.io/tide-history?repo=bazelbuild%2Frules_docker

**Comment by nlopezgi** [comment]
@cjwagner apologies, for some reason the PRs mentioned above did not get a CLA check approved (even though the author did have a CLA). Is there any way we can tell if any of our PRs are in the stuck state so we can put the /hold label ourselves and avoid causing troubles for you?

**Comment by cjwagner** [comment]
You can check https://prow.k8s.io/tide-history?repo=bazelbuild%2Frules_docker, but we don't have a way to send you alerts for this.
Tide was not designed to work with the GitHub setting that requires PRs to be strict fast forwards, because it can provide the same guarantee without requiring users to rebase their PRs if all test jobs are ProwJobs.

@smukherj1 mentioned a utility that would manage a merge blocking label that would apply to PRs that are not strict fast forwards (not up to date). That's one way to address this. Alternatively, disable the GitHub feature and either convert all jobs to ProwJobs or accept that non-Prow jobs may not be tested against the latest base branch commit.

**Comment by smukherj1** [comment]
@cjwagner I have a pending cl that adds the ability to detect and mark PRs with out of date base branches with the "hold/do-not-merge" label. I'm hoping to get that in by the end of this week and this should be handled automatically.

**Comment by cjwagner** [comment]
Cool. FYI the label is `do-not-merge/hold` and since that is managed by the `/hold` command it might be better to use a new label like `do-not-merge/out-of-date` or something like that. The label can be anything as long as we add it to the list of labels the block merge: https://github.com/kubernetes/test-infra/blob/9869938fbfdbf5b258a52a145a306a8d8eab591e/prow/config.yaml#L417-L422
