### ISSUE TITLE
container_test does not produce useful output on failure

### ISSUE THREAD

**Issue by briandealwis** [bazelbuild/rules_docker#863]
The `container_test` rule defaults to `verbose = False`:
https://github.com/bazelbuild/rules_docker/blob/41af08c30bf9719dc9946e11cdf4d117c6056da0/contrib/test.bzl#L104-L107

which means that `container-structure-test` is run with the `--quiet` flag:
https://github.com/bazelbuild/rules_docker/blob/41af08c30bf9719dc9946e11cdf4d117c6056da0/contrib/test.bzl#L52-L53

which means that a failing test's output has no detail:
```
$ bazel test //... --verbose_failures --sandbox_debug --cpu=darwin
[...]
FAIL: //examples/nonroot:check_user_test (see /private/var/tmp/_bazel_bsd/6fd0d1827c5b8b84c4601a789fdb920b/execroot/distroless/bazel-out/darwin-fastbuild/testlogs/examples/nonroot/check_user_test/test.log)
INFO: From Testing //examples/nonroot:check_user_test:
==================== Test output for //examples/nonroot:check_user_test:
+ examples/nonroot/check_user_test.image --norun
Loaded image ID: sha256:c9c520f1efc254bab68495c7a51ba76a7c8353dbec7828a6b8e4938c3ddc0269
Tagging c9c520f1efc254bab68495c7a51ba76a7c8353dbec7828a6b8e4938c3ddc0269 as examplesnonrootcheck_user_image:intermediate
+ ../structure_test_darwin/file/downloaded version
v1.8.0
+ ../structure_test_darwin/file/downloaded test --driver docker --image examplesnonrootcheck_user_image:intermediate --quiet --config examples/nonroot/testdata/user.yaml
time="2019-05-29T15:08:40Z" level=fatal msg=FAIL
================================================================================
```

which is somewhat less than optimal.  To be honest, this value would be better wired to `container-structure-test`'s `--verbosity` flag:
```
  -v, --verbosity string   Log level (debug, info, warn, error, fatal, panic) (default "warning")
```

cc: @nkubala @dprotaso

**Comment by smukherj1** [comment]
Hi @briandealwis,
Thanks for opening this issue. I wouldn't change the semantics of the existing `verbosity` attribute on `container_test` to avoid breaking current users of this attribute. I would suggest adding an optional `log_level` string attribute that would specify `debug`, `info`, `warn`, etc that can be given to the `container-structure-test` binary when verbosity is specified as `true`.

Would this help your use case? If so, please feel free to open a pull request contributing this change.
