### ISSUE TITLE
docker_build does not work well with py_binary

### ISSUE THREAD

**Issue by azymnis** [bazelbuild/rules_docker#91]
Say I have a python rule:

```
py_binary(
    name = 'main',
    ...
)
```

And I make a docker build rule that looks like this:

```
docker_build(
    files = ['//path/to/bin:main'],
    ...
)
```

If I do a `bazel run` for this rule and then inspect the contents of the image, i see that the `main` executable has been copied over but not the directory `main.runfiles` or the manifest `main.runfile_manifest`. Without these files the python executable will not work. Am I doing something wrong?

**Comment by mattmoor** [comment]
@azymnis you want to look into `par_binary` for now (see github.com/google/subpar), which bundles everything together into a portable archive.  Let me know if an example would be helpful.

(slightly longer version)
Basically today there is zero intelligence in the hand-off from `foo_binary` to `docker_build` it is literally a file transfer, so it works best with statically linked archives (like PAR, or Java "deploy jars").  Most rules have these as it's what we use internally to place binaries into our internal container format.

FWIW, I'm exploring some better options here, but nothing I'd call "ready" yet.

If you are interested you can watch [this](https://github.com/bazelbuild/rules_docker/issues/81) issue, and I'll try to surface more content there.

**Comment by azymnis** [comment]
@mattmoor thanks for the explanation. I tried adding a par_binary rule that looks like this:

```
par_binary(
    name = "main",
    srcs = [MAIN_PROG],
    deps = [":lib"]
)
```

But when I run:

```
bazel build //src/python/package:main
```

I don't get a par file under `bazel-bin/src/python/package`. Looks like it just builds what py_binary would. Am I missing something?

Also: seems like docker_rules are already pulling in subpar so if I add an explicit import of subpar in `WORKSPACE` I get an error

**Comment by azymnis** [comment]
@mattmoor ah never mind, i need to run:

```
bazel build //src/python/package:main.par
```

instead... Subtle but important difference...

**Comment by mattmoor** [comment]
Yeah, the link can get expensive, so it doesn't spit out the `.par` unless you ask for it.  Glad you seem to have found it quickly!

**Comment by azymnis** [comment]
Incidentally, might make sense to explain this issue (i.e. that docker_build only really works with targets that output a single monolithic artifact) at the top readme.

Thanks for the help.
