### ISSUE TITLE
rules docker does not work when using experimental_remote_download_outputs toplevel/minimal

### ISSUE THREAD

**Issue by phb** [bazelbuild/rules_docker#921]
To me it looks like an issue with rules_docker declaring it's runfiles, but it could also be a bug in experimental_remote_download_outputs.

Repro here: https://github.com/phb/bazel_minimal_missingrunfiles, see https://github.com/phb/bazel_minimal_missingrunfiles/blob/master/EXAMPLE_OUTPUT for output when I run it locally with a cache.

Also reported in https://github.com/bazelbuild/bazel/issues/6862.

**Comment by nlopezgi** [comment]
Hi @phb 
Thanks for opening this issue.
experimental_remote_download_outputs is a new feature (very experimental) that has not been tested before with rules_docker. We'd be happy to help you work out through issues that you find by accepting and reviewing any PRs you can contribute for this purpose!

**Comment by phb** [comment]
I feel fairly confident this is an issue with experimental_remote_download_outputs. I've confirmed that the runfiles provided the rules_docker is correct.
