### ISSUE TITLE
docker_run_flags impossible to override with subsequent container_image targets

### ISSUE THREAD

**Issue by clintharrison** [bazelbuild/rules_docker#923]
In #505, the behavior of `container_image` was changed to prefer a base image's `docker_run_flags` over the top-most `container_image`.

This seems backwards to me, as it's now impossible to override this value, and we end up duplicating our `container_image` definitions with the same `layers` attributes (and any others we want to set) just so we can change the `docker_run_flags` on them.

I think it makes sense to prefer the `docker_run_flags` of the base _only_ in the case where the current `container_image` is relying on the default value.

Are there folks relying on the current behavior? I would expect not, but maybe there's a deeper reason here I'm not understanding.

**Comment by xingao267** [comment]
I think the original reason for #505 is to inherit the `docker_run_flags` from `container_image` to `lang_image`s as we cannot set the in `lang_image`s. Yea, I agree it "makes sense to prefer the `docker_run_flags` of the base only in the case where the current `container_image` is relying on the default value." We'll see what we can do there. Also if you are willing to send a PR, we would also love to review as well.
