### ISSUE TITLE
new_container_push: Error reading from xxx-layer.tar: file manifest.json not found in tar

### ISSUE THREAD

**Issue by factuno-db** [bazelbuild/rules_docker#927]
Using new_container_push (introduced yesterday with commit 5647f4f7a6b7c247e788675963e2e03a6e7156e1) results in

`2019/06/25 18:28:14 Running the Image Pusher to push images to a Docker Registry...
2019/06/25 18:28:14 Error reading from bazel-out/k8-fastbuild/bin/[...]/web_image-layer.tar: open bazel-out/k8-fastbuild/bin/[...]/web_image-layer.tar: no such file or directory
`

The file actually exists.

**Comment by nlopezgi** [comment]
fyi @smukherj1

**Comment by factuno-db** [comment]
Commit ac23af6914f0d9fc4dd6b853f6d016ba3a08006a results in:

2019/06/26 20:07:12 Running the Image Pusher to push images to a Docker Registry...
2019/06/26 20:07:12 Error reading from /[...]/1597cabd3fc5ac127946332b9db4062c/execroot/__main__/bazel-out/k8-fastbuild/bin/[...]/web_image_push.runfiles/__main__/[...]/web_image-layer.tar: file manifest.json not found in tar

**Comment by xiaohegong** [comment]
Hi @factuno-db, thank you for reporting the issue.  The `new_container_push` supports pushing tarballs of the `docker save` and our old `container_pull` formats. In addition, we also support pushing image indices in [OCI layout](https://github.com/opencontainers/image-spec/blob/master/image-layout.md#oci-image-layout-specification). Do you mind letting us know how you got your tarball?

**Comment by factuno-db** [comment]
hi @xiaohegong, via `go_image`.

**Comment by factuno-db** [comment]
If I'm seeing this correctly, the old push.bzl calls `get_from_target` from layer_tools.bzl, which calls `_extract_layers`. `_extract_layers` defines the manifest file and calls extract_config.py which generates it.

**Comment by xiaohegong** [comment]
Thank you for pointing this out. We are still in the process of implementing `new_container_push`, so some of the features are not fully supported yet. We will let you know when it is ready. 

As a temporary workaround, you can `docker save` the loaded `go_image` and push that tarball. Hope that helps.

**Comment by factuno-db** [comment]
Alright, so I am closing this issue as new_container_push is WIP. Thanks a lot!

**Comment by smukherj1** [comment]
rules_docker v0.10.0 includes the fix for this issue. Please let us know if that's not the case.
