### ISSUE TITLE
Bazel CI is reporting things broken

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_docker#95]

**Comment by damienmg** [comment]
Links?

**Comment by mattmoor** [comment]
The badge on the main page shows this, but here's one of the failing builds: http://ci.bazel.io/job/rules_docker/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/150/console

**Comment by damienmg** [comment]
That's because bazel head is broken, the sheriff is responsible to fix it.
I'll roll out after 0.5.3 release (next week) the new pipeline which will
remove those failure from the badge.

**Comment by damienmg** [comment]
Ok that was actually a reimaging of the slaves that broke it, should be
fixed now.
