### ISSUE TITLE
new_pull() doesn't work on MacOs

### ISSUE THREAD

**Issue by mskonovalov** [bazelbuild/rules_docker#950]
Hi,

it seems only linux distro of go_puller is loaded. Is it intentional? Where can I find macos binary?
Thanks

**Comment by xingao267** [comment]
Hi @mskonovalov, thanks for your feedback. the go_puller and new_container_pull are still under development, and we are currently not supporting and releasing macos binary yet.

**Comment by mskonovalov** [comment]
:(

**Comment by nlopezgi** [comment]
We are now publishing macOs versions of go_puller. Could you give it a try again and report if you see any issues? Thanks!

**Comment by nlopezgi** [comment]
Closing for now, please reopen if you experience any issues with the new go_puller on mac.
