### ISSUE TITLE
Specify docker image labels using java_image rule

### ISSUE THREAD

**Issue by neakor** [bazelbuild/rules_docker#976]
I'd like to store metadata into my docker image via the `java_image` rule. This doesn't seem to exist as an option. Please advise.

**Comment by neakor** [comment]
it looks like we can just add a new parameter to the `java_image` rule and pass it through to the `container.image.implementation` call. Is this right? If so, I can put up a PR.

**Comment by nlopezgi** [comment]
please see the note here: https://github.com/bazelbuild/rules_docker/blob/master/README.md#overview-1

If you need to add a custom env or symlink to a lang_image, you must use container_image targets for this purpose. Specifically, you can use as base for your lang_image target a container_image target that adds e.g., custom env or symlink.

let me know if for some reason this will not work for metadata. otherwise we can close

**Comment by neakor** [comment]
This might be a stupid question, but how should I specify the base image?
```
load("@io_bazel_rules_docker//java:image.bzl", "java_image")
load("@io_bazel_rules_docker//container:image.bzl", "container_image")

container_image(
    name = "test_image_base",
    base = "@java_base//:8",
)

java_image(
    name = "test_image",
    base = ":test_image_base",
    srcs = glob(["**/*.java"]),
    deps = [],
    main_class = "com.test.Main",
    visibility = ["//visibility:public"],
)
```

My `WORKSPACE` has
```
load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)
container_pull(
  name = "java_base",
  registry = "gcr.io",
  repository = "distroless/java",
  # 'tag' is also supported, but digest is encouraged for reproducibility.
  digest = "sha256:a5aa2ef3d3902be516f53503ada27e85bb7dbed1546ab919c73f607ccf28a50d",
)
```

When I ran `bazel build`, I got an error `no such target '@java_base//:8': target '8' not declared in package`

**Comment by neakor** [comment]
NVM that was stupid haha. Instead of using the tag `8`, which is already specified in `WORKSPACE` `container_pull`, I just need to use `base = "@java_base//image"`. I'll continue trying the `labels` field and report back.

Much appreciated!

**Comment by neakor** [comment]
This works great! Thank you again!
