### ISSUE TITLE
A test is failing on the CI

### ISSUE THREAD

**Issue by vladmos** [bazelbuild/rules_docker#978]
`//tests/container:new_distroless_base_test_index_json` is failing on the CI (although there were no recent commits and both are tested with Bazel 0.28.0):

  * Green on 11.07: https://buildkite.com/bazel/rules-docker-docker/builds/2229#21630ef4-299b-4176-b4a2-95a0248336d3
  * Red on 12.07: https://buildkite.com/bazel/rules-docker-docker/builds/2234#ba69057a-fe45-45b6-b1bd-ea676fd4ecd9

[Error message](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/5b252d1c-e516-4284-881e-63df5993f89c/tests/container/new_distroless_base_test_index_json/attempt_1.log): 

    -         "digest": "sha256:edc3643ddf96d75032a55e240900b68b335186f1e5fea0a95af3b4cc96020b77"
    +         "digest": "sha256:e37cf3289c1332c5123cbf419a1657c8dad0811f2f8572433b668e13747718f8"

**Comment by xingao267** [comment]
I'm looking into this.
