### ISSUE TITLE
Must migrate rule.output to OutputGroupInfo

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/rules_docker#987]
Just checked bazel 28 with the flag `--incompatible_no_rule_outputs_param` and failed on `rules_docker` 

```
ERROR: /private/var/tmp/_bazel_ors/e1cd358f405ae1d1a5186e8a38e284f5/external/io_bazel_rules_docker/container/bundle.bzl:86:21: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
```

I might try to solve and contribute but I wanted to have an open issue about it here:

See details here:
https://github.com/bazelbuild/bazel/issues/7977

**Comment by Monnoroch** [comment]
This is not fixed in `push.bzl`.
