### ISSUE TITLE
dpkg_list should auto-generate with dependencies from one package

### ISSUE THREAD

**Issue by bajacondor** [bazelbuild/rules_docker#998]
Rather than create a dpkg_list with individual dependencies, the user should be able to specify one debian package from the repository, and the rule should examine the package for dependencies and add them to to the list.

I am happy to start this work in a PR, if one of the maintainers would give me a little direction for this contribution

Thank you!

**Comment by nlopezgi** [comment]
Have you seen the new download_pkgs and install_pkgs rules?
https://github.com/bazelbuild/rules_docker/blob/master/docker/package_managers/README.md
These do resolve dependencies. Passing packages to container_image via debs directly is deprecated.

**Comment by bajacondor** [comment]
Thanks for your response!  Not great news for me, since one of the reasons we use Bazel rules_docker is to avoid the security risk of running a docker daemon in a shared build environment.  Is the `debs` argument also going to be depreciated from `container_layer()` as well?  I spent some time today writing a rule to that will wrap `dpkg_src()` -- which is part of distroless -- to find dependent packages from a short list.  I'd like to know how best to contribute this work?

**Comment by nlopezgi** [comment]
hi @bajacondor, so are you referring specifically to improving the rules [here](https://github.com/GoogleContainerTools/distroless/tree/master/package_manager). I guess it might make sense to propose a PR in that repo and see what they think. I dont think adding that rule here in rules_docker repo is a good idea as it would create a dependency to distroless that we would have to test for and maintain.

**Comment by bajacondor** [comment]
Thanks again, @nlopezgi.  I am working on a PR for the distroless repo.  Can you give me a little rundown on how to best debug/test a target used by rules_docker?
I've forked distroless, and in the workspace of my project, I changed the @distroless git_repository() to a local_repository.  That works fine.  The trouble comes, because in dpkg.bzl they specify the Label() of the executable for the rules dpkg_list() and dpkg_src() as a downloaded par  (encapsulated python bin).  I am trying to change that so that I can add my code to dpkg_parser.py (the src of the par_binary)  But now the rule can't seem to find the local par.  I get 
>Not a regular file: /private/var/tmp/_bazel.../a256311e92234013bb6c7cb2b2b6cad9/external/distroless/package_manager/dpkg_parser.par

Any advice would be appreciated!

**Comment by nlopezgi** [comment]
You probably need to create a new par_binary and publish it somewhere (i.e., your own GCS bucket) and change the pointer in the repo rule from the existing par binary to the one you are publishing. Sorry for the delay getting back. Closing this issue for now as this belongs more in the distroless repo. Let me know if you want to keep this issue open for some reason.
